<?php
define("_BBB","BBB Conferences");
define("_BBB_SYSTEMLINK1", "BBB system link1");
define("_BBB_SYSTEMLINK2", "BBB system link2");
define("_BBB_LESSONLINK", "Lesson BBB");
define("_BBB_MODULE", "BBB Conference Module");
define("_BBB_MAIN","Main page");
define("_BBB_MANAGEMENT","Manage Conferences");
define("_BBB_SUCCESFULLYINSERTEDBBBENTRY", "Conference was succesfully updated");
define("_BBB_PROBLEMINSERTINGBBBENTRY", "Conference could not be created");
define("_BBB_INSERTBBB", "Insert conference");
define("_BBB_GOTOBBBPAGE", "Go to conference page");
define("_BBB_BBBPAGE", "Conference");
define("_BBB_NAME", "Conference name");
define("_BBB_DATE", "Date");
define("_BBB_NOBBBFOUND", "There are no conference entries");
define("_BBB_QUESTIONS", "Questions");
define("_BBB_ANSWERS", "Answers");
define("_BBB_BBBLIST", "BBB conference list");
define("_BBB_ADDBBB", "Add conference");
define("_BBB_EDITBBB", "Edit conference");
define("_BBB_DELETEBBB", "Delete conference");
define("_BBB_CHANGEBBBORDER", "Change conference order");
define("_BBB_SUCCESFULLYDELETEDBBBENTRY", "Succesfully deleted conference");
define("_BBB_SUCCESFULLYUPDATEDBBBENTRY", "Succesfully updated conference");
define("_BBB_PROBLEMUPDATINGBBBENTRY", "The conference could not be updated");
define("_BBBTHEFIELDNAMEISMANDATORY","The conference meeting room name is mandatory");
define("_BBBNOMEETINGSCHEDULED","No conferences have been scheduled");
define("_BBB_STATUS","Conference status");
define("_BBBSTARTED","Started");
define("_BBBFINISHED","Finished");
define("_BBBNOTSTARTED","Not started");
define("_BBBSTARTMEETING", "Start conference");
define("_BBB_TIME","Time of conference");
define("_BBBJOINMEETING","Join conference");
define("_BBBAREYOUSUREYOUWANTTODELETEEVENT","Are you sure you want to cancel this conference?");
define("_BBB_BBBMEETING", "Conference");
define("_BBB_SCHEDULEMEETING", "Conference schedule");
define("_BBB_MEETINGATTENDANTS", "Conference attendants");
define("_BBB_BBBMEETINGDATA", "BBB conference information");
define("_BBB_BBBSERVER", "BBB Conference Server configuration");
define("_BBB_BBBSERVERNAME", "Server host");
define("_BBB_BBBSERVERVERSION", "Server Version 0.7+");
define("_BBB_SECURITYSALT","Security salt");
define("_BBB_SUCCESFULLYCHANGEDSERVER", "Server host has been successfully updated");
define("_BBB_NOBBBSERVERDEFINED", "No BBB conferences server has been defined");
define("_BBBDURATION","Duration");
define("_BBBUSELOBBYROOM","Use lobby waiting room");
define("_BBBAUDIOONLY","Audio only");
define("_BBBAUDIOVIDEO","Audio and video");
define("_BBBMAXPARTICIPANTS","Maximum number of participants");
define("_BBBMAXMICS","Maximum number of microphones");
define("_BBBPRESENTERAV","Type of conference");
define("_BBB_NOTIFYUSERSVIAEMAIL", "Send notification email to participants");
define("_BBB_MEETING", "eFront Conference Notification");
define("_BBB_DEAR","Dear");
define("_BBB_YOUHAVEBEENINVITEDBYPROFESSOR","You have been invited by professor");
define("_BBB_TOATTENDACONFERENCE","to attend the eFront conference");
define("_BBB_FORLESSON","for lesson");
define("_BBB_SCHEDULEDFOR","scheduled for");
define("_BBB_SINCERELY","Sincerely");
define("_BBBYOUCANJOINTHEMEETINGDIRECTLYBYCLICKINGTHEFOLLOWINGLINKAFTERITSTARTS", "After the meeting starts, you may join it by clicking the appropriate link in efront");
define("_BBB_EMAILSENTSUCCESFFULLY", "emails sent successfully");
define("_BBBMEETINGHASFINISHED","The conference you have selected has finished");
define("_BBB_AREYOUSUREYOUWANTTOSTARTTHECONFERENCE", "Are you sure you want to start the conference? (After this action, viewers will be allowed to join the meeting until its expiration time)");
define("_BBB_RESETDEFAULTSERVER","Reset default server");
define("_BBB_IN","In");
define("_BBB_NOW","Now!");
?>
