<?php
define("_FLASHCARDS_FLASHCARDS","Flashcards");
define("_FLASHCARDS_NAME","Name");
define("_FLASHCARDS_CARDS","Cards");
define("_FLASHCARDS_PUBLISHED","Published");
define("_FLASHCARDS_OPERATIONS","Functions");
define("_FLASHCARDS_DECKS","Decks");
define("_FLASHCARDS_ANSWER","Answer");
define("_FLASHCARDS_USECARD","Use card");
define("_FLASHCARDS_OPTIONS","Options");
define("_FLASHCARDS_ACTIVE","Active");
define("_FLASHCARDS_SHOWANSWERFIRST","Show answser first");
define("_FLASHCARDS_SHUFFLECARDS","Shuffle cards");
define("_FLASHCARDS_DISPLAYMASTERY","Display mastery on card");
define("_FLASHCARDS_WRONGREDUCES","Wrong reduces success count");
define("_FLASHCARDS_SHOWSUCCESSCOUNT","Show success count on card");
define("_FLASHCARDS_SHOWEXPLANATION","Show explanation on card");
define("_FLASHCARDS_MASTERY","Mastery");
define("_FLASHCARDS_EXPLAIN","Explain this card");
define("_FLASHCARDS_RETURNCARD","Return to card");
define("_FLASHCARDS_FALSE","Got it wrong");
define("_FLASHCARDS_RIGHT","Got it right");
define("_FLASHCARD_NUMBEROFSUCCESSFORMASTERY","Number of success for mastery");
define("_FLASHCARDS_COMPLTETEDDECK","Completed deck");
define("_FLASHCARDS_SUCCESSFULLY","Options were successfully saved");
define("_FLASHCARDS_TIMES","times");
define("_FLASHCARDS_TIME","time");
define("_FLASHCARDS_RESTARTDECK","Restart deck");
define("_FLASHCARDS_RESTARTALL","Restart all decks");
define("_FLASHCARDS_SUCCESSFULLYCOMPLETEDDECK","You have completed this deck. In order to do it again, you have to restart it first");
define("_FLASHCARDS_RESTART","Restart");
define("_FLASHCARDS_FLIP","FLIP");
define("_FLASHCARDS_PROGRESSRESETAREYOUSURE","This action will reset progress data. Are you sure?");
define("_FLASHCARDS_CARDSINDECK", "cards in deck");
define("_FLASHCARDS_MASTERYOFDECK", "Mastery of deck");
?>