<?php
define("_CROSSWORD_CROSSWORD","Σταυρόλεξο");
define("_CROSSWORD_NAME","'Ονομα");
define("_CROSSWORD_LISTS","Λέξεις");
define("_CROSSWORD_CLUES","Στοιχεία");
define("_CROSSWORD_CLUE","Στοιχείο");
define("_CROSSWORD_CLUES_ANSWER","Στοιχεία και απαντήσεις");
define("_CROSSWORD_PUBLISHED","Δημοσιευμένο");
define("_CROSSWORD_OPERATIONS","Λειτουργίες");
define("_CROSSWORD_WORDS","Λέξεις");
define("_CROSSWORD_ANSWER","Απάντηση");
define("_CROSSWORD_SCORE","Σκόρ");
define("_CROSSWORD_USELIST","Χρήση λέξης");
define("_CROSSWORD_OPTIONS","Επιλογές");
define("_CROSSWORD_ACTIVE","Ενεργό");
define("_CROSSWORD_SHOWANSWERFIRST","Αποκάλυψη απάντησης");
define("_CROSSWORD_SAVEPDF","Αποθήκευση ως pdf");
define("_CROSSWORD_NUMBEROFWORDS","Μέγιστο πλήθος λέξεων");
define("_CROSSWORD_SUCCESSFULLY","Οι επιλογές αποθηκευτηκαν επιτυχώς");
define("_CROSSWORD_GAME_SUCCESSFULLY","Το σταυρόλεξο ολοκληρωθηκε με επιτυχία");
define("_CROSSWORD_TIMES","φορές");
define("_CROSSWORD_TIME","Χρόνος");
define("_CROSSWORD_ACROSS","Οριζόντια");
define("_CROSSWORD_DOWN","Κάθετα");
define("_CROSSWORD_GAMESTARTED","Το παιχνίδι ξεκίνησε");
define("_CROSSWORD_CHECK","Έλεγχος");
define("_CROSSWORD_CHECKDISABLED","Απενεργοποιημένος έλεγχος");
define("_CROSSWORD_CHECKALL","Έλεγχος όλων");
define("_CROSSWORD_CHECKED","Ελέγχθηκε");
define("_CROSSWORD_MATCHED","επιτυχής");
define("_CROSSWORD_REVEAL","Εμφάνιση");
define("_CROSSWORD_REVEALED","Εμφανίστηκε");
define("_CROSSWORD_ACROSSFIRSTLETTER","Ο");
define("_CROSSWORD_DOWNFIRSTLETTER","Κ");
define("_CROSSWORD_NOCOMPLETEWORDSFOUND","Δεν βρέθηκαν ολόκληρες λέξεις");
define("_CROSSWORD_HAVENOTSUFFICIENTPOINTS","Δεν έχετε βρει επαρκή σημεία");
define("_CROSSWORD_THEWORD","Η λέξη");
define("_CROSSWORD_ISINCOMPLETE","είναι ανολοκλήρωτη");
define("_CROSSWORD_DIDNOTMATCH","δεν ταιριάζει");
define("_CROSSWORD_UNABLEGENERATECROSSWORD","Λυπούμαστε, δεν ήταν δυνατή η δημιουργία σταυρόλεξου από τις λέξεις");
?>
