<?php

$_TEXTME_UNINSTALL_QUERIES = array();

$_TEXTME_UNINSTALL_QUERIES[] = 'DROP TABLE IF EXISTS `module_textme_phonebook`';

$_TEXTME_UNINSTALL_QUERIES[] = 'DROP TABLE IF EXISTS `module_textme_lessons_settings`';

$_TEXTME_UNINSTALL_QUERIES[] = 'DROP TABLE IF EXISTS `module_textme_messages`';

$_TEXTME_UNINSTALL_QUERIES[] = 'DROP TABLE IF EXISTS `module_textme_subscribers`';

$_TEXTME_UNINSTALL_QUERIES[] = 'DROP TABLE IF EXISTS `module_textme_groups`';

$_TEXTME_UNINSTALL_QUERIES[] = 'DROP TABLE IF EXISTS `module_textme_recipients`';

$_TEXTME_UNINSTALL_QUERIES[] = 'DROP TABLE IF EXISTS `module_textme_group_has_recipients`';

$_TEXTME_UNINSTALL_QUERIES[] = 'DROP TABLE IF EXISTS `module_textme_gateways`';

?>
