<?php
if (is_file($GLOBALS['path']."language/custom-japanese.php.inc")) {
include($GLOBALS['path']."language/custom-japanese.php.inc");
}
define("_HEADERLANGUAGEHTMLTAG","ja");//en
define("_CURRENTLANGUAGESYMBOL","ja");//en
define("_HEADERLANGUAGETAG","japanese");//english
define("_CHARSET","x-euc");//ISO-8859-1
define("_LANGUAGE","言語");//Language
define("_PASSWORD","パスワード");//Password
define("_SUBMIT","提出する");//Submit
define("_REGISTER","登録");//Register
define("_CONTACT","お問い合わせ先");//Contact us
define("_FROM","〜から");//From
define("_SENDSUCCESS","あなたのメッセージが送信されました。お問い合わせいただきありがとうございます！");//Your message was sent successfully. Thank you for contacting us!
define("_SENDFAILURE","は、問題が出てくるから。もう一度やり直してください。");//A problem has come up. Please try again.
define("_LOGIN","ログイン");//Login
define("_NAME","名前");//Name
define("_SURNAME","名字");//Surname
define("_ADDRESS","住所");//Address
define("_POSTCODE","郵便番号");//Post code
define("_CITY","町");//City
define("_HOMEPHONE","電話番号");//Phone number
define("_EMAILADDRESS","電子メールアドレス");//Email address
define("_COMMENTS","コメント");//Comments
define("_TIME","時間");//Time
define("_BACK","←戻る");//&larr;&nbsp;Back
define("_CONFIGURATIONVARIABLES","システム構成");//System configuration
define("_CHANGESITELOGO","サイトのロゴを変更");//Change site logo
define("_ONLYONELANGUAGE","1つのみがサポートさ（デフォルト）の言語");//Support only one (the default) Language
define("_YES","はい");//Yes
define("_NO","いいえ");//No
define("_UPDATELESSONS","更新プログラムのレッスン");//Update lessons
define("_ADMINEMAIL","管理者に電子メール");//Administrator email
define("_LESSONSDELETED","ここでの教訓が削除さ");//The lesson was deleted
define("_SHOWFOOTER","詳細フッター");//Show footer
define("_DEFAULTLANGUAGE","デフォルトの言語");//Default language
define("_DIGITALLIBRARY","デジタルファイルライブラリ");//Digital file library
define("_BACKUP","バックアップシステム");//Backup system
define("_RESTORE","システムの復元");//Restore system
define("_FREE","このレッスンは無料のすべての");//This lesson is free for all
define("_SUCCESSREGISTER","あなたが登録正常に");//You have registered successfully
define("_LESSONSREGISTRATION","レッスンユーザ登録");//Lesson registration
define("_YOUREMAIL","あなたのe -メール");//Your e-mail 
define("_MESSAGESUBJECT","メッセージの件名");//Message subject
define("_PASSWORDLEAVEBLANK","パスワード（空白を離れる現行どおり）");//Password (blank to leave unchanged)
define("_PERSONALDATACHANGESUCCESS","お客様の個人情報が変更されました");//Your personal info has been successfully altered
define("_REGISTRATIONDATE","ユーザ登録日付");//Registration date
define("_SAVECHANGES","変更を保存");//Save changes
define("_PERSONALDATA","個人情報");//Personal info
define("_LESSONOPTIONS","レッスンオプション");//Lesson options
define("_PERSONALOPTIONS","道具");//Tools
define("_QUESTIONWEIGHT","質問の重量（ 1-10 ）");//Question weight (1-10)
define("_WEIGHT","重量");//Weight
define("_NONEWLESSONREGISTRATIONS","新しいレッスンユーザ登録");//No new lesson registration
define("_LESSONS","レッスン");//Lessons
define("_RECREATESEARCHTABLE","再検索テーブル");//Recreate search table
define("_LESSONSREGISTRATIONS","レッスン登録");//Lesson registrations
define("_TOOLS","道具");//Tools
define("_ONLINEUSERS","上行のユーザー");//On line users
define("_DATE","日付");//Date
define("_STUDENT","学生");//Student
define("_LINE","ライン");//Line
define("_SOMEPROBLEMEMERGED","いくつかの問題が発生しました。");//Some problem has occured
define("_CORRECTION","正しいこと");//Correct it
define("_LESSONNAME","レッスン名");//Lesson name
define("_DIRECTION","カテゴリー");//Categories
define("_DIRECTIONNAME","カテゴリ名");//Category name
define("_NEWLESSON","新しいレッスン");//New lesson
define("_NEWDIRECTION","新しいカテゴリ");//New category
define("_EMAILSENDAT","電子メールを送信しました。");//Email was sent to 
define("_CHOOSELESSON","選択授業");//Choose lesson
define("_SUBJECT","主題");//Subject
define("_RECIPIENTSSELECTION","受信者の選択");//Recipients selection
define("_EMAILBODY","電子メールの本文");//E-mail body
define("_SENDEMAIL","電子メールを送る");//Send E-mail
define("_EXIT","出口");//Exit
define("_MORE","よりたくさんの");//more
define("_DELETE","削除する");//Delete
define("_MESSAGES","メッセージ");// Messages
define("_THEORY","理論");//Theory
define("_PROJECTS","プロジェクト");//Projects
define("_TESTS","テスト");//Tests
define("_PREVIOUS","&lt;前");//&lt; Previous
define("_NEXT","次へ&gt;");//Next &gt;
define("_CANNOTACCESSTHISUNIT","このユニットを参照することはできませんので：");//You cannot see this unit because:
define("_SENDPERSONALMESSAGE","個人的なメッセージを送る");//Send personal message
define("_SEND","送る");//Send
define("_STATISTICS","報告書");//Reports
define("_OPTIONS","オプション");//Options
define("_THEFIELD","フィールド");//The field
define("_WELCOMETO","へようこそ");//Welcome to the
define("_LESSONANNOUNCEMENT","発表は、レッスン");//Announcement for the lesson
define("_COLOR","カラー");//Color
define("_HOUR","時間");//hour
define("_HOURS","営業時間");//hours
define("_MINUTE","分");//minute
define("_MINUTES","分");//minutes
define("_SECONDS","秒");//seconds
define("_LASTLOGIN","最終更新ログ-さ");//Last log-in
define("_MEAN","平均の");//Average
define("_LOGINAT","ログインには");//Log-in at
define("_TESTHADAT","テスト完了");//Test completed at
define("_HASMAXIMUMDURATION","それが最大の期間");//It had maximum duration
define("_YOURSCOREIS","お客様によるスコアは、");//Your score is
define("_FINALSCOREWILLBEFROM","最終スコアされるから");//Final score will be from
define("_ANDYOUDIDITIN","とすることが完了");//and you completed it in
define("_TO","〜へ");//to
define("_DEPENDSONQUESTIONS","あなたの答えをオープンに応じて質問に答える。");//depending on your answers on open-answer questions.
define("_EXAMPLEANSWER","回答例");//Example answer
define("_SCORE","スコア");//Score
define("_THISQUESTIONCORRECTEDPROFESSOR","この問題が修正されることを教授します。");//This question will be corrected by the professor
define("_RIGHTANSWER","正しい答え");//Correct answer
define("_TESTSHOULDCOMPLETEIN","このテストを完了する必要があります。");//This test must be completed in
define("_TIMELEFT","残り時間");//Time remaining
define("_YOUCANNOTLOGINAS","ユーザーが存在する場合は、ログイン名：");//No user exists with login name:
define("_WRONGPASSWORDTRYAGAIN","あなたは間違ったパスワードを入力します。もう一度やり直してください。");//You gave a wrong password. Please try again.
define("_NOTACTIVATEDACCOUNTTRYAGAINLATER","活性化されていないお客様のアカウントはまだありません。お試しください。");//Your account has not been activated yet. Please try again later.
define("_YOUHAVEBEENEXCLUDEDBYPROFESSOR","あなたが除外された教授");//You are excluded by professor
define("_MUSTFIRSTREADUNIT","最初の読み取りユニットする必要があります。");//You must first read unit
define("_MUSTFIRSTTAKEATLEAST","第一に、少なくともする必要があります。");//You must first take at least
define("_YOURTIMEISUP","お時間がアップ");//Your time is up
define("_ATTEST","をテストする");//at test
define("_WANTTOREDOTEST","このテストをやり直すしたい");//I want to redo this test
define("_PERCENT","％");//Percent
define("_CANNOTREDOTEST","このテストすることはできません。やり直し！");//You cannot redo this test!
define("_LESSON","レッスン");//Lesson
define("_ALL","すべてのコンテンツ");//All content
define("_GOTOFORUM","フォーラムに行く");//Go to forum
define("_SENDMESSAGEATFORUM","ポストメッセージが表示さ");//Post message
define("_SENDMESSAGE","送信メッセージの送信");//Send message
define("_ANNOUNCEMENTS","アナウンス");//Announcements
define("_MESSAGESATFORUM","フォーラムのメッセージ");//Forum messages
define("_PERSONALMESSAGES","個人的なメッセージ");//Personal messages
define("_SOLVEDTESTS","解決のテスト");//Solved tests
define("_ATFORUM","また、フォーラム");//At forum
define("_PRINTERFRIENDLY","印刷ユニット");//Print unit
define("_PRINTERFRIENDLYALLCONTENT","のすべてのコンテンツを印刷する");//Print all the content
define("_ADDCOMMENT","コメントの追加");//Add comment
define("_LESSONSELECT","選択授業");//Select lesson
define("_CURRENTCONTENT","現在のコンテンツ");//Current content
define("_COMMENTDELETED","のコメントは削除されて");//The comment has been deleted
define("_COMMENTADD","コメントの追加");//Add comment
define("_ADDYOURCOMMENT","コメントを追加する");//Add your comment
define("_SUCCESFULLYADDEDCOMMENT","正常にコメントが追加されました。");//The comment was added successfully
define("_SUCCESFULLYUPDATEDCOMMENT","コメントが更新されました");//The comment was updated successfully
define("_SUCCESFULLYDELETEDFILEWINDOWCLOSE5SECONDS","そのファイルが削除されました。このウィンドウが自動的に閉じるに5秒後にします。");//The file was deleted. This window will automatically close in 5 seconds.
define("_SUCCESFULLYDELETEDFOLDERWINDOWCLOSE5SECONDS","そのフォルダが削除されました。このウィンドウが自動的に閉じるに5秒後にします。");//The folder was deleted. This window will automatically close in 5 seconds.
define("_NOTSUCCESFULLYDELETEDFOLDERWINDOWCLOSE5SECONDS","そのフォルダを削除できませんでした。それを含めることはできません任意のファイルまたはフォルダをすべて削除されます。このウィンドウが自動的に閉じるに5秒後にします。");//The folder was not deleted. It must not contain any files or folders to be deleted. This window will automatically close in 5 seconds.
define("_SUCCESFULLYCREATEDFOLDERWINDOWCLOSE5SECONDS","そのフォルダが作成されました。このウィンドウが自動的に閉じるに5秒後にします。");//The folder was created. This window will automatically close in 5 seconds.
define("_FOLDERNAME","フォルダ名");//Folder name
define("_CREATE","作成");//Create
define("_LESSONNOTSET","ここでの教訓が未設定します。");//The lesson was not set.
define("_COPYNAMESFROMLEFTTORIGHTTOSAVEIMAGES","名前をコピーするには、左側の右の列は、イメージファイルを保存するために、お客様のドキュメントです。");//Copy names from the left to the right column, in order to save the image files in your document.
define("_THEFILE","ファイル");//The file
define("_MUSTBESMALLERTHAN","より小さくする必要があります。");//must be smaller than
define("_KILOBYTES","バイトです。");//Kbytes.
define("_HASBEENSEND","が送信されます。");//was sent.
define("_SENDFILE","ファイルを送る");//Send file
define("_CLOSEWINDOW","このウィンドウを閉じる");//Close window
define("_UPDATE","更新する");//Update
define("_SUCCESFULLYDELETEDANNOUNCEMENTWINDOWCLOSE5SECONDS","の発表が削除さ正常に");//The announcement was deleted successfully
define("_ANNOUNCEMENTADD","追加発表");//Add announcement
define("_ANNOUNCEMENTTITLE","発表タイトル");//Announcement title
define("_ANNOUNCEMENTBODY","発表体");//Announcement body
define("_SUCCESFULLYADDEDANNOUNCEMENTWINDOWCLOSE5SECONDS","成功の発表が追加されました。");//The announcement was added successfully
define("_SUCCESFULLYUPDATEDANNOUNCEMENTWINDOWCLOSE5SECONDS","の発表が更新されました");//The announcement was updated successfully
define("_ENDDATEMUSTBEBEFORESTARTDATE","終了日が開始日後にしなければならない。");//End date must be after start date.
define("_SAVE","保存する");//Save
define("_SUCCESFULLYUPDATEDQUESTION","という質問が更新さ正常に");//The question was updated successfully
define("_SUCCESFULLYADDEDQUESTION","この問題は正常に追加されました");//The question was added successfully
define("_QUESTIONTEXT","質問本文");//Question text
define("_SAVEQUESTION","割引率の質問");//Save question
define("_UNIT","単位");//Unit
define("_QUESTIONTYPE","質問のタイプ");//Type
define("_DIFFICULTY","難易度");//Difficulty
define("_RATEMUSTBEBETWEEN0100","範囲は0から100の間によるスコア必要があります。");//The score must range between 0 and 100
define("_ALLOFTHEM","すべてのユーザー");//All users
define("_VALIDFOR","有効です。");//Valid for
define("_TOBEEXCLUDEDFROMUNIT","単位から除外される");//to be excluded from the unit
define("_THEUNIT","の単位");//the unit
define("_TESTNAME","テスト名");//Test name
define("_UNITPARENT","親ユニット");//Parent unit
define("_SAVETEST","割引率試験");//Save test
define("_SUCCESFULLYADDEDRATE","米国の回収率は正常に挿入さ");//The rate was inserted successfully
define("_STUDENTANSWER","学生の回答");//Student answer
define("_SEARCHTABLERECREATED","の検索テーブルが再現");//The search table was recreated
define("_SAVETHE","保存して");//Save the
define("_OFTHELESSONATYOURCOMPUTER","お使いのコンピュータのレッスンをします。");//of the lesson at your computer.
define("_ATYOURCOMPUTER","お使いのコンピュータにします。");//at your computer.
define("_DATAFILE","データファイル");//Data file
define("_NOTGIVEFILENAME","ファイル名を供給していない");//You did not supply a file name
define("_LESSONDATAFILE","レッスンデータファイル");//Lesson data file
define("_INSERTDATA","データのインポート");//Import data
define("_OFLESSON","は、レッスン");//Of the lesson
define("_CATEGORY","カテゴリ");//Category
define("_SEARCH","探す");//Search
define("_DESCRIPTION","説明書");//Description
define("_TYPE","種類");//Type
define("_POSITION","位置");//Position
define("_LESSONCONTENT","レッスン内容");//Lesson content
define("_TITLE","タイトル");//Title
define("_TEXT","本文");//Text
define("_NORESULTSFOUNDINFORUM","フォーラムのない結果が見つかりました");//No results found in forum
define("_SEARCHRESULTSINLESSONS","検索結果が表示さレッスン");//Search results in lessons
define("_SEARCHRESULTSINFORUM","検索結果が表示さフォーラム");//Search results in forum
define("_SEARCHRESULTSINUSERS","ユーザーの検索結果が表示さ");//Search results in users
define("_NOSEARCHRESULTSFOUND","中に、検索結果が見つかりました");//No results found during the search
define("_PRINTIT","印刷すること！");//Print it!
define("_LANGUAGEADMINISTRATION","言語設定");//Set languages
define("_INTERMEDIATESELLER","中間のセールスマン");//Intermediate salesman
define("_PROFESSOR","教授");//Professor
define("_ADMINSTRATOR","管理者");//Administrator
define("_CONTROLCENTER","管制センター");//Control center
define("_EXAMPLES","例");//Examples
define("_FORUM","フォーラム");//Forum
define("_NOCONTENT","単位なしのコンテンツ");//Unit without content
define("_INACTIVE","非アクティブなユニット");//Inactive unit
define("_CONTENTMANAGEMENT","内容");//Content
define("_SCHEDULING","スケジューリング");//Scheduling
define("_OFDEVELOPMENT","開発");//development
define("_MULTIPLECHOICEONESELECTION","複数の選択肢が、 1つの正しい答え");//Multiple choices, single correct answer
define("_MULTIPLECHOICEMULTIPLESELECTIONS","複数の選択肢が、複数の正しい答え");//Multiple choices, multiple correct answers
define("_OFMATCH","マッチング");//matching
define("_OFEMPTYSPACES","記入してブランク");//Fill in the blanks
define("_LOW","低い");//Low
define("_MEDIUM","培地");//Medium
define("_HIGH","高い");//High
define("_PERIODSPERSTUDENT","期間の学生一人当たり");//Periods per student
define("_NETMEETINGSUPPORT","NetMeetingをサポート");//Netmeeting support
define("_IFSTUDENTHASNOTSEEN","学生ていない場合に見られる");//If student has not seen
define("_IFSTUDENTHASNOTPASSED","学生の場合に合格していません。");//If student has not passed
define("_STUDENTALLWAYS","学生allways");//Student allways
define("_ACCESSRULES","レッスンのルール");//Lesson rules
define("_EMAILS","電子メール");//Emails
define("_CHAT","チャット");//Chat
define("_OFJANUARY","1月");//January
define("_OFFEBRUARY","年2月");//February
define("_OFMARCH","3月");//March
define("_OFAPRIL","4月");//April
define("_OFMAY","〜かもしれない");//May
define("_OFJUNE","年6月");//June
define("_OFJULY","7月");//July
define("_OFAUGUST","8月");//August
define("_OFSEPTEMBER","9月");//September
define("_OFOCTOBER","10月");//October
define("_OFNOVEMBER","11月");//November
define("_OFDECEMBER","12月");//December
define("_ADDLANGUAGE","追加言語");//Add language
define("_CURRENTLANGUAGES","現在の言語");//Current languages
define("_CHANGE","変化");//Change
define("_RETURN","リターン");//Return
define("_UPDATESUCCESFULLYMADE","この更新プログラムが正常に完了した");//The update was completed successfully
define("_LESSONMATERIAL","レッスン材料");//Lesson material
define("_NOQUESTIONSSETFORTHISUNIT","定義されて質問はありません。");//There are no questions defined
define("_ADDQUESTION","追加の質問");//Add question
define("_PREVIEW","プレビュー");//Preview
define("_NOTESTSSETFORTHISUNIT","のテストが見つかりました");//No tests found
define("_ADDTEST","追加テスト");//Add test
define("_UNITANDSUBUNITSTESTS","ユニットとサブユニットテスト");//Unit and subunits tests
define("_NORESULTSFOUND","該当する検索結果が見つかりました！");//No results found!
define("_PAGES","ページ");//pages
define("_UPLOADFILESANDIMAGES","ファイルのアップロードや画像");//Upload files and images
define("_COPYFROMANOTHERLESSON","別の教訓からコピー");//Copy from another lesson
define("_UNITNAME","ユニット名");//Unit name
define("_CONTENTTYPE","コンテンツタイプ");//Content type
define("_CONTENT","内容");//Content
define("_UPDATEUNIT","更新プログラムの単位");//Update unit
define("_CREATESUBUNIT","サブユニットを作成");//Create subunit
define("_CREATETEST","作成テスト");//Create test
define("_ADDPERIOD","カート期間");//Add period
define("_LESSONPERIODS","レッスン期間");//Lesson periods
define("_COPY","コピー");//Copy
define("_EXCLUDECONSTRAINT","除外制約");//Exclusion constraint
define("_EXCLUSIONUNIT","除外単位");//Exclusion unit
define("_FUNCTIONS","機能");//Functions
define("_THETEST","テスト");//the test
define("_WITHSCOREATLEAST","少なくともレート");//with rate at least
define("_NOQUESTIONSTOCORRECTFORTHISLESSON","この教訓を修正する質問はありません。");//No questions to correct for this lesson.
define("_QUESTIONSTOCORRECT","質問を修正する");//Questions to correct
define("_DELETESELECTED","選択した項目を削除");//Delete selected
define("_REDOABLE","テストの繰り返し");//Test repetitions
define("_PROFESSORS","教授");//Professors
define("_CANNOTOPENFOLDER","そのフォルダを開くことはできません。");//The folder can&#039;t be opened
define("_CREATEFOLDER","フォルダを作成");//Create folder
define("_OPENFOLDER","開いているフォルダ");//Open folder
define("_CUT","切る");//Cut
define("_PASTE","貼り付け");//Paste
define("_UNDO","元に戻す");//Undo
define("_REDO","やり直し");//Redo
define("_FIND","見つける");//Find
define("_INSERTHYPERLINK","ハイパーリンクの挿入");//Insert hyperlink
define("_INSERTIMAGE","画像を挿入");//Insert image
define("_NORMAL","通常");//Normal
define("_DEFAULT","債務不履行");//Default
define("_BOLD","大胆な");//Bold
define("_ITALIC","イタリック体");//Italics
define("_UNDERLINED","下線");//Underlined
define("_FONTCOLOR","フォントの色");//Font color
define("_DIMENSIONS","外形寸法");//Dimensions
define("_CANCEL","キャンセル");//Cancel
define("_OR","または");//or
define("_LEFT","左");//Left
define("_RIGHT","右");//Right
define("_UP","上へ");//Up
define("_MIDDLE","真ん中");//Middle
define("_DOWN","下に");//Down
define("_FILE","ファイル");//File
define("_SELECTTHEONEYOUWANTASLINK","として1つを選択してハイパーリンクを挿入したい");//Select the one you want inserted as hyperlink
define("_SELECTTHEONEYOUWANTAS","1つを選択して挿入さしたい");//Select the one you want inserted as
define("_SMALLCAPSHYPERLINK","ハイパーリンク");//hyperlink
define("_ADD","追加する");//Add
define("_NOTE","注：");//Note
define("_SELECTLESSON","選択授業");//Choose lesson
define("_STUDENTS","学生");//Students
define("_ADMINISTRATORS","管理者");//Administrators
define("_LESSONSTATISTICS","レッスン報告書");//Lesson reports
define("_FILES","ファイル");//Files
define("_TOTALSIZE","合計サイズ");//Total size
define("_NEWMESSAGE","新しいメッセージが表示さ");//New message
define("_PARTICIPATION","参加");//Participation
define("_AVERAGE","人の注意を引かない");//unremarkable
define("_ACTIVE","アクティブ");//Active
define("_PASSWORDLOST","パスワードをお忘れですか？");//Forgot your password?
define("_ANEMAILHASBEENSENT","電子メールにと指示が送信されます。");//An email with instructions was sent to you.
define("_PASSWORDRECOVERY","あなたのパスワードを回復");//Recover your password
define("_THENEWPASSWORDIS","新しいパスワードは：");//Your new password is: 
define("_EMAILWITHPASSWORDSENT","電子メールでお客様の新しいパスワードが送信されます。");//An email with your new password was sent to you.
define("_LINEARCONTENT","コンテンツの注文");//Content order
define("_ONEBYONE","詳細な質問を1つずつ");//Show questions one by one
define("_NEXTQUESTION","次の質問");//Next question
define("_IDONOTWANTTODOTHETEST","気が変わったんだ。ごミーバック");//I changed my mind. Please take me back
define("_YOUHAVE","あなたは");//You have
define("_SENDFILEASANSWER","ファイルをアップロードするとの回答");//Upload a file as an answer
define("_FILEUPLOADED","ファイルのアップロード");//File uploaded
define("_PREVIOUSQUESTION","前の質問");//Previous question
define("_RESTARTLESSON","レッスンの初期化");//Lesson initialization
define("_RESTARTLESSONCOMPLETED","ここでの教訓に初期化され");//The lesson has been initialized
define("_UPLOADFILE","ファイルをアップロード");//Upload file
define("_PROBLEMUPLOADINGFILE","ファイルのアップロード中に問題がありました。");//There was a problem while uploading file
define("_SHOW","見せる");//Show
define("_URL","のURL");//URL
define("_TARGET","目標物");//Target
define("_NONE","何もない");//None
define("_OTHER","その他の");//Other
define("_TEXTTOP","texttop");//Texttop
define("_ABSMIDDLE","absmiddle");//Absmiddle
define("_ABSBOTTOM","absbottom");//Absbottom
define("_BASELINE","ベースライン");//Baseline
define("_CELLSPACING","セルの間隔");//Cell spacing
define("_CELLPADDING","細胞パディング");//Cell padding
define("_EM","日");//Em
define("_WIDTH","幅");//Width
define("_ALIGN","整列");//Align
define("_BORDER","国境");//Border
define("_BOTTOM","底");//Bottom
define("_CSS","CSSの");//CSS
define("_CAPTION","キャプション");//Caption
define("_CENTER","センター");//Center
define("_CHAR","文字");//Char
define("_HEIGHT","高さ");//Height
define("_JUSTIFY","正当化");//Justify
define("_MARGIN","マージン");//Margin
define("_PADDING","パディング");//Padding
define("_RULES","ルール");//Rules
define("_SUMMARY","概要");//Summary
define("_TEXTALIGN","テキストの整列");//Text align
define("_TOP","頂上");//Top
define("_ENTER","ログイン");//Login
define("_HASBEENLOGGEDOUT","アウトは記録されて");//has been logged out
define("_LOGOUT","ログアウト");//Log out
define("_EACHFILESIZEMUSTBESMALLERTHAN","各ファイルをより小さくする必要があります。");//Each file must be smaller than
define("_DONE","完了した");//Done
define("_UPLOADTHESCORMFILEINZIPFORMAT","SCORMをzip形式のファイルをアップロード");//Upload SCORM file in ZIP format
define("_SCORMEXPORT","輸出のレッスンをSCORMを");//Export lesson to SCORM
define("_SCORMIMPORT","SCORMをインポートするコンテンツ");//Import SCORM content
define("_FORUMPOSTS","フォーラムのメッセージ");//Forum messages
define("_TOTAL","合計");//Total
define("_ALLLESSONS","すべてのレッスン");//All lessons
define("_STUDENTSOFLESSON","学生のレッスン");//Students of lesson
define("_REVIEWSCORMDATA","日SCORMをデータ");//Review SCORM data
define("_IMPORTOFUNIT","インポートの単位");//Import of unit
define("_SELECTFILE","ファイルを選択する");//Select a file
define("_THESYSTEMSUGGESTSTHEFILES","ファイルシステムを示唆して");//The systems suggests the files
define("_CHECKIFITISASINGLESCO","空の場合は、 1つのSCOグループ");//Check if it is a single SCO
define("_CHOOSESTUDENT","選択する学生");//Select a student
define("_NOSCORMDATAFOUNDFORTHISSTUDENT","この学生のSCORMをデータが見つかりません");//No SCORM data found for this student
define("_ENTRY","エントリ");//Entry
define("_TOTALTIME","合計時間");//Total time
define("_MINSCORE","最小スコア");//Minimum score
define("_MAXSCORE","最大スコア");//Maximum score
define("_FINALSCORE","最終スコア");//Final score
define("_TOCAPITAL","〜へ");//To
define("_NOTEPUBLICROOMSARESTOREDANDACCESSED","注記：会話を記録して、公共の客室はすべてのユーザーに利用できるように作ら");//Note: Conversations in public rooms are recorded and made available to all users
define("_PRIVATEROOM","プライベートルーム");//Private room
define("_ENTEREDROOM","が部屋に入って");//entered the room
define("_LEFTTHEROOM","左の朝食");//left the room
define("_WRONGROOMID","間違って部屋番号");//Wrong room id
define("_EXITCHAT","出口のチャット");//Exit chat
define("_ADJUSTTOPAGE","ページに適応する");//Adjust to page
define("_CREATEPUBLICROOM","公共のルームを作成");//Create public room
define("_CREATEPRIVATEROOM","プライベートルームを作成");//Create private room
define("_OPENROOMS","オープンルーム");//Open rooms
define("_NEWPUBLICROOM","新しいパブリックルーム");//New public room
define("_NEWPRIVATEROOM","新しいプライベートルーム");//New private room
define("_SHOWPASTCOVERSATIONS","詳細過去のスレッド");//Show past conversations
define("_PUBLICROOMS","公共の部屋");//Public rooms
define("_PRIVATEROOMS","プライベートルーム");//Private rooms
define("_PARTICIPANTS","参加者");//participants
define("_NOROOMSFOUND","の部屋が見つかりました");//No rooms found
define("_DEACTIVATE","非アクティブ");//Deactivate
define("_ACTIVATE","アクティブ");//Activate
define("_SYSTEMMESSAGE","システムメッセージが表示さ");//System message
define("_ROOMALREADYEXISTS","お部屋にこの名前が既に存在する");//A room with this name already exists
define("_ROOMNAME","ルーム名");//Room name
define("_ACTIVENEUTRAL","アクティブ");//Active
define("_SHOWCONVERSATIONSFORROOM","詳細スレッドをルーム");//Show conversations for the room
define("_NOMESSAGESFOUNDFORTHISINTERVAL","この部屋の会話が見つかりました、指定した間隔で");//No conversations found in this room for the specified interval
define("_MESSAGE","メッセージが表示さ");//Message
define("_FILESIZE","ファイルサイズ");//File size
define("_ILLEGALFILENAME","違法なファイル名");//Illegal file name
define("_IRREVERSIBLEACTIONAREYOUSURE","この操作は取り返しのつかない！してもよろしいですか？");//This operation is irreversible! Are you sure?
define("_FILENAME","ファイル名");//File name
define("_SUCCESFULLYDELETEDFILE","正常に削除されたファイル");//Successfully deleted file
define("_TAKEBACKUP","バックアップ！");//Backup!
define("_SUCCESFULLYBACKEDUP","バックアップを正常に完了");//Backup successfully completed
define("_NONEXISTINGMAIL","この電子メールに属していない場合、任意のユーザ");//This email/login does not belong to any user
define("_PORT","サーバーのポート");//Server port
define("_DATABASE","データベース名");//Database name
define("_ACTIVATELDAP","LDAPサポートを有効に");//Activate LDAP support
define("_LDAPSERVER","LDAPサーバー");//LDAP server
define("_LDAPBINDDN","LDAPバインドのDN");//LDAP bind DN
define("_LDAPPASSWORD","LDAPバインドパスワード");//LDAP bind password
define("_SUPPORTONLYLDAP","LDAPのユーザ登録のみがサポートさ");//Support only LDAP registration
define("_LOGINATTRIBUTE","ログイン名属性");//Login name attribute
define("_LDAPCOMMONNAME","フルname属性");//Full name attribute
define("_LDAPADDRESS","アドレス属性");//Address attribute
define("_LDAPLOCALITY","都市属性");//City attribute
define("_LDAPTELEPHONENUMBER","電話番号の属性");//Phone number attribute
define("_LDAPMAIL","電子メールの属性");//Email attribute
define("_LDAPLANGUAGE","言語属性");//Language attribute
define("_CHECKSETTINGS","空の設定");//Check settings
define("_LDAPPORT","LDAPサーバーポート");//LDAP server port
define("_USESSL","SSL接続を使用する");//Use SSL connection
define("_CANNOTCONNECTLDAPSERVER","このシステムに接続するにはLDAPサーバーができませんでした。");//The system was unable to connect to LDAP server
define("_CANNOTBINDLDAPSERVER","このシステムをLDAPサーバーをバインドすることができませんでした。");//The system was unable to bind to LDAP server
define("_LDAPCONFIGURATION","LDAP設定");//LDAP configuration
define("_LDAPBASEDN","LDAPのベースDN");//LDAP Base DN
define("_YOUHAVEALREADYCORRECTEDTHISQUESTION","この問題を既に修正");//You have already corrected this question
define("_SHOWALL","すべて表示");//Show all
define("_TOTALLOGINS","トータルシステムログイン");//Total system logins
define("_ALLOWEDIPS","可型IPS");//Allowed IPs
define("_COMMASEPARATEDLISTASTERISKEXAMPLE","カンマ区切りのリストです。アスタリスク*が可能です。例： 192.168.0 .* 、 192.168.1.1 、 192.168.1.100");//Comma separated list. The asterisk * is allowed. Example: 192.168.0.*, 192.168.1.1, 192.168.1.100
define("_DISALLOWEDIPS","許可されない型IPS");//Disallowed IPs
define("_ALLOWEDEXTENSIONS","可ファイルの拡張子");//Allowed file extensions
define("_DISALLOWEDEXTENSIONS","許可されないファイルの拡張子");//Disallowed file extensions
define("_COMMASEPARATEDLISTASTERISKEXTENSIONEXAMPLE","カンマ区切りのリストです。例：デザイン、 EXEを実行し、 CGIの");//Comma separated list. Example: php, js, exe, cgi
define("_DENIALTAKESPRECEDENCE","拒否の前に許可します。両方のフィールドは空白のままの場合、入力し、すべてが可");//Denial precedes permission. If both fields are left blank, then everything is allowed
define("_EFRONT","efront");//eFront
define("_CONTACTUS","お問い合わせ先");//Contact us
define("_EFRONTLOGIN","にログインしてefront");//Login to eFront
define("_LDAPPROTOCOLVERSION","LDAPプロトコルバージョン");//LDAP Protocol Version
define("_GOTOINBOX","受信トレイに行く");//Go to inbox
define("_RECENTCOMMENTS","最新コメント");//Last comments
define("_CONTROLPANEL","[コントロールパネル]");//Control panel
define("_YOUCANNOTCREATETHISFOLDER","このようなフォルダを作成することはできません。");//You cannot create such a folder
define("_INVALIDID","無効な番号");//Invalid id
define("_UNPRIVILEGEDATTEMPT","お持ちでない方はこのアクションを実行する権限");//You do not have the priviledges to perform this action
define("_INVALIDLOGIN","無効なログイン名");//Invalid login name
define("_DOWNLOADLANGUAGEFILE","言語ファイルをダウンロード");//Download language file
define("_SOMEPROBLEMOCCURED","いくつかの問題が発生した");//Some problem occured
define("_ALTERNATIVELYCOPYANDPASTEBROWSER","また、リンクをコピーして貼り付けることがありますそれをお使いのブラウザのアドレスフィールド");//Alternatively, you may copy the link and paste it in your browser&#039;s address field
define("_YOUCANNOTACCESSTHISFOLDER","する必要はありませんこのフォルダのアクセスを");//You do not have access to this folder
define("_YOUCANNOTDELETETHISFILE","このファイルを削除することはできません。");//You cannot delete this file
define("_TRIEDTODELETE","ファイルを削除しようと");//Tried to delete file
define("_ACTION","アクション");//Action
define("_NOTES","ノート");//Notes
define("_SENDFILES","ファイルを送信");//Send files
define("_YOUCANNOTUPLOADFILESWITHTHISEXTENSION","ファイルをアップロードすることはできませんこの拡張モジュール");//You cannot upload files with this extension
define("_YOUMAYONLYUPLOADFILESWITHEXTENSION","拡張子だけでファイルをアップロードする場合があります。");//You may only upload files with extension
define("_COULDNOTCREATEFOLDER","フォルダを作成できませんでした。フォルダ名を確認してくださいとは、既に存在するフォルダが存在しない");//Could not create folder. Please check the folder name and that the folder does not already exist
define("_REGISTERANEWACCOUNT","新しいユーザーアカウント");//New user account
define("_REC","録画");//rec
define("_SUCESSFULLYCONNECTEDTOLDAPSERVER","LDAPサーバーに接続して正常に");//Successfully connected to LDAP server
define("_DIRECTIONDELETED","カテゴリ削除");//Category deleted
define("_NOANNOUNCEMENTSPOSTED","このレッスンのアナウンスを掲載");//No announcements posted for this lesson
define("_NONEWFORUMMESSAGES","このレッスンについてのフォーラムのメッセージ");//No forum messages regarding this lesson
define("_NONEWPERSONALMESSAGES","いいえ新しい個人のメッセージが受信トレイ");//No new personal messages in your inbox
define("_NONEWCOMMENTS","新規コメント");//No new comments
define("_NOMATERIALINTHISLESSON","その教訓は現在、空");//The lesson is currently empty
define("_NOSOLVEDTESTSFOUND","いいえ解決テスト");//No solved tests
define("_NORELATEDPOSTSFOUND","このユニットの記事に関連しています。");//No posts relevant to this unit.
define("_SUCCESSFULLYCREATEDLESSON","ここでの教訓が正常に作成さ");//The lesson was created successfully
define("_SORRYNEEDIFRAME","申し訳ありませんが、サポートする必要があります。 iframeのチャットを使用して");//Sorry, you need iframe support to use the Chat
define("_TOPICSUBJECT","トピックの件名");//Topic subject
define("_SEARCHRESULTS","検索結果");//Search results
define("_NORESULTSFOUNDINPERSONALMESSAGES","個人的なメッセージを発見さ結果はありません");//No results found in personal messages
define("_SEARCHRESULTSINPERSONALMESSAGES","検索結果が表示さ個人的なメッセージ");//Search results in personal messages
define("_SEARCHRESULTSINCOURSES","検索結果が表示さコース");//Search results in courses
define("_MESSAGEFOLDER","メッセージが表示さフォルダ");//Message folder
define("_EMAIL","電子メール");//e-mail
define("_RESETPASSWORD","パスワードのリセット");//Reset password
define("_JOINED","メンバー登録");//Joined
define("_MOREINFO","さらに詳しい情報");//More info
define("_AVERAGESCORE","平均スコア");//Average score
define("_CHATMESSAGES","チャットメッセージ");//Chat messages
define("_MONTHLOGINS","先月のログイン");//Logins last month
define("_WEEKLOGINS","最終更新週間以内にログイン");//Logins last week
define("_MEANDURATION","セッションの期間を意味");//Mean session duration
define("_MONTHMEANDURATION","先月のセッションの期間を意味");//Mean session duration last month
define("_WEEKMEANDURATION","セッションの期間を意味最終週");//Mean session duration last week
define("_MONTH","月日");//Month
define("_WEEK","週間以内に");//Week
define("_PRICE","価格");//Price
define("_DURATION","セッションの期間");//Session duration
define("_MAINTENANCE","メンテナンス");//Maintenance
define("_FORUMLASTMESSAGE","最後のメッセージが表示されるフォーラム");//Last message in forum
define("_MESSAGESFOLDERS","個人的なメッセージをフォルダに");//Personal messages folders
define("_FOLDERS","フォルダ");//Folders
define("_CHATLASTMESSAGE","最終更新チャットメッセージが表示される");//Last message in chat
define("_INFO","情報");//Information
define("_LASTPOST","最終投稿");//Last post
define("_TOTALQUESTIONS","合計の質問");//Total questions
define("_DEVELOPMENT","開発");//Development
define("_MULTIPLEONE","複数の選択肢-1つの正しい答え");//Multiple choices - Single correct answer
define("_MULTIPLEMANY","複数の選択肢-多くの正しい答え");//Multiple choices - Many correct answers
define("_MATCH","試合");//Match
define("_EMPTYSPACES","スペース");//Empty spaces
define("_LOWDIFFICULTY","難度は低い");//Low difficulty
define("_MEDIUMDIFFICULTY","中間の難易度");//Medium difficulty
define("_HIGHDIFFICULTY","高難度");//High difficulty
define("_CATEGORIES","カテゴリー");//Categories
define("_OVERALL","全体的な");//Overall
define("_BACKTOTOP","このページのトップへ");//Back to top
define("_STATISTICSFORLESSON","レッスンのレポートを作成");//Reports for lesson
define("_GENERALLESSONINFO","一般的なレッスン情報");//General lesson information
define("_LESSONPARTICIPATIONINFO","レッスン参加情報");//Lesson participation information
define("_LESSONCONTENTINFO","レッスンコンテンツ情報");//Lesson content information
define("_TESTINFO","テスト情報");//Test information
define("_QUESTIONINFO","質問情報");//Question information
define("_VIEWTEST","対象試験");//View test
define("_SYSTEMSTATISTICS","システム報告書");//System reports
define("_ORDER","順番");//Order
define("_TEST","試験");//Test
define("_TOPICSUCCESFULLYCREATED","が正常に作成されるトピックを参照し");//The topic was created successfully
define("_SUCCESFULLYPOSTEDMESSAGE","あなたのメッセージが投稿さ正常に");//Your message was posted successfully
define("_SUCCESFULLYUPDATEDTOPIC","が更新されるトピックを参照し正常に");//The topic was updated successfully
define("_SUCCESFULLYUPDATEDMESSAGE","あなたのメッセージが更新されました");//Your message was updated successfully
define("_INVISIBLE","目に見えない");//Invisible
define("_LOCKED","ロック");//Locked
define("_PUBLIC","公共");//Public
define("_PREVIEWMESSAGE","プレビューメッセージが表示さ");//Preview message
define("_BODY","体");//Body
define("_ATTACHMENT","添付ファイル");//Attachment
define("_RECENTMESSAGESATFORUM","最後のメッセージをフォーラム");//Last messages at Forum
define("_RECENTUNREADPERSONALMESSAGES","最近の個人的なメッセージを未読");//Recent unread personal messages
define("_NOCONTENTAVAILABLE","いいえユニットは、次のコンテンツタイプ現在入手可能な");//No units of this content-type currently available
define("_THEREWASAPROBLEMDELETETINGFILEWINDOWCLOSE5SECONDS","ファイルの削除中に問題が発生します。このウィンドウは5秒後に自動的に閉じる");//A problem occured during the file deletion. This window will close automatically in 5 seconds
define("_TRIEDTOCREATEFOLDER","しようとフォルダを作成する：");//Tried to create folder:
define("_COULDNOTCREATEFOLDERWINDOWCLOSE5SECONDS","そのフォルダを作成できませんでした。このウィンドウは5秒後に自動的に閉じる");//The folder could not be created. This window will close automatically in 5 seconds
define("_INVALIDNAME","無効な名前");//Invalid name
define("_THISFOLDERCONTAINS","このフォルダに");//This folder contains
define("_TOPICS","トピック");//Topics
define("_FILEDOESNOTEXIST","ファイルが存在しません");//File does not exist
define("_ADDLINK","追加リンク");//Add link
define("_CONTENTUNITS","コンテンツ単位");//Content units
define("_MAINPAGE","メインページ");//Main page
define("_PLEASEGIVEYOURLOGINOREMAIL","お客様のログインまたは電子メールにお譲りください。");//Please give your login or email
define("_LESSONSETTINGS","投与");//Administration
define("_ADMINISTRATOR","管理者");//Administrator
define("_PROGRESS","進捗状況");//Progress
define("_IMAGEFILE","画像ファイル");//Image file
define("_SETAVATAR","セットアバター");//Set avatar
define("_CURRENTAVATAR","現在のアバター");//Current avatar
define("_DELETECURRENTAVATAR","現在のアバターを削除");//Delete current avatar
define("_ONLYIMAGEFILESAREVALID","画像ファイルのみが有効です。イメージファイルを選択してください。");//Only image files are valid. Please select an image file.
define("_VIEWLIST","リストを表示");//View list
define("_SUCCESFULLYSETAVATAR","新しいアバターが正常に設定");//New avatar is successfully set
define("_TOPICDELETEDSUCCESSFULLY","トピックを削除しました");//Topic deleted successfully
define("_MESSAGEDELETEDSUCCESSFULLY","メッセージを削除しました");//Message deleted successfully
define("_POSTS","投稿");//Posts
define("_BY","〜によって");//by
define("_NEWCATEGORY","新しいカテゴリ");//New category
define("_FORUMCONFIGURATIONPANEL","フォーラムの構成パネル");//Forum configuration panel
define("_VIEWS","再生回数");//Views
define("_STICKY","付箋");//Sticky
define("_NOTOPICSFOUND","トピックはありませんが見つかりました");//No topics found
define("_NEWTOPIC","新しいトピック");//New topic
define("_POSTEDBY","投稿者");//Posted by
define("_ON","〜の上に");//on
define("_INREPLYTO","に返信して");//in reply to
define("_REPLYWITHQUOTE","返信に引用符");//Reply with quote
define("_QUOTE","引用する");//quote
define("_REPLY","返答する");//Reply
define("_AREYOUSUREYOUWNATTODELETEMESSAGE","してもよろしいですをまとめて削除するメッセージが表示さ");//Are you sure you want to delete message
define("_EDIT","編集");//Edit
define("_STATUS","地位");//Status
define("_NOMESSAGESFOUND","のメッセージが見つかりました");//No messages found
define("_GOTOCHATROOMSLIST","チャットルームのリストに行く");//Go to chat rooms list
define("_ROOM","部屋");//Room
define("_INVITE","招待");//Invite
define("_INVITESYOUCLICKLINK","すると、チャットセッションに招待しています。以下のリンクをクリックしてチャットルームがあります。");//invites you to a chat session. Click the link below to be taken to the chat room.
define("_GOTOCHATROOM","チャットルームに行く");//Go to chat room
define("_CHATINVITATION","チャットの招待状");//Chat invitation
define("_NEWCONTENT","新しいコンテンツ");//New content
define("_NONEWCONTENT","新しいコンテンツない");//No new content
define("_TEMPLATE","テンプレート");//Template
define("_APPLY","適用する");//Apply
define("_PRIVATECONVERSATIONWITH","民間との会話を");//Private conversation with
define("_TORESPOND","に対応する...");//to respond...
define("_TOAPRIVATECONVERSATION","個人的な会話をする");//to a private conversation
define("_INVITESYOUTOPRIVATECONVERSATION","個人的な会話をしては、招待");//is inviting you to a private conversation
define("_DOYOU","ように");//Do you
define("_QUESTIONMARK","ですか？");//?
define("_CONVERSATIONINVITATIONACCEPTED","会話の招待状が受理");//The conversation invitation was accepted
define("_CONVERSATIONINVITATIONDENIED","会話の招待状が拒否されました");//The conversation invitation was denied
define("_YOUACCEPT","受入");//accept
define("_YOUDENY","拒否する");//deny
define("_THEMAILCOULDNOTBESENDTRYLATER","電子メールを送信できませんでした。後ほどお試しくださいまたはシステム管理者に連絡して");//The email could not be send. Please try again later or contact the system administrator
define("_AUTOMATEDEMAILSENTFROM","自動送信メールから送信された住所：");//Automated email sent from address:
define("_CLIKCINGONTHELINKWILLCONFIRM","下のリンクをクリックしては、お客様の電子メールアドレスを確認して新しいパスワードが有効なので、広告が表示されます。");//Clicking on the link will confirm that your email address is valid so a new password can be sent to you.
define("_FORFURTHERCONTACTADMINAT","をより詳細な情報については、場合があります。お問い合わせは、システム管理者は、");//For further information, you may contact the system administrator, at
define("_KINDREGARDSEFRONT","敬具、 efrontシステム");//Kind regards, eFront system
define("_THISISANAUTOMATEDEMAILSENTFROM","これは、自動送信メールから送信された");//This is an automated email sent from
define("_BECAUSEYOUASKEDTORECOVERPASSWORD","要請を回復するためにあなたのパスワードを入力します。");//because you asked to recover your password.
define("_PLEASECLICKTHECONFIRMATIONLINKBELOW","確認用のリンクをクリックしてください：");//Please click the confirmation link below:
define("_WITHTHENEWPASSWORD","efrontアカウントを新しいパスワードを入力します。");//with your new eFront account password.
define("_REGISTRATIONEMAIL","ユーザ登録電子メール");//Registration email
define("_CURRENCYSYMBOL","€");//&euro;
define("_ELEARNINGPLATFORM","eラーニングプラットフォーム");//eLearning platform
define("_ACCOUNTACTIVATEDWITHPERSONALINFORMATION","お客様のアカウントが正常に作成さは、次の個人情報：");//Your account was successfully created with the following personal information:
define("_YOUHAVEAPPLIEDFORTHELESSONS","に出席する必要が適用される次のレッスン：");//You have applied to attend the following lessons:
define("_YOUMAYSTARTUSINGFREEIMMEDIATELYBUTNOTNONFREE","レッスンを開始することがありますは無料ですぐに出席します。お客様が選択した場合に含まれてレッスンされていない自由は、管理者が選択する前に使用して適用する必要があります。します。");//You may start attending lessons that are free immediately. If your selection includes lessons that are not free, the administrator must apply your selection before using them.
define("_YOUMAYALTERPERSONALINFORMATIONFROMSETTINGS","のすべての個人情報を提出するだけでなく、レッスン選択して、いつでも設定が変更される場合お客様の個人設定のページをご覧ください。");//All the personal info you have submitted, as well as your lessons selection, may be altered at any time from your personal settings page.
define("_YOUMAYLOGINIMMEDIATELY","場合があります。ログイン名とスタート]ボタンを使用して、システムを直ちに");//You may login and start using the system immediately
define("_YOUMAYLOGINWHENADMINACTIVATESYOU","場合があります。次第スタート]ボタンを使用して、システム管理者として、お客様のアカウントを活性化");//You may start using the system as soon as the administrator activates your account
define("_EMAILSENTFROM","電子メールから送信された");//Email sent from
define("_STUDENTSOFLESSONSMALL","学生のレッスン");//students of lesson
define("_DIRECTIONDEACTIVATED","カテゴリ無効");//Category deactivated
define("_DIRECTIONACTIVATED","カテゴリ活性化");//Category activated
define("_LESSONUPDATED","レッスンを更新済み");//Lesson updated
define("_LESSONDEACTIVATED","レッスンを無効に");//Lesson deactivated
define("_LESSONACTIVATED","レッスンを活性化");//Lesson activated
define("_VIEWALL","カテゴリーのすべての");//View all
define("_FILESANDSUBFOLDERS","ファイルやサブフォルダ");//files and subfolders
define("_ATTACHMENTS","添付ファイル");//Attachments
define("_PROBLEMQUERYINGDATABASE","問題のデータベース検索を実行する");//Problem querying database
define("_FIRSTNAME","名前");//First name
define("_LASTNAME","姓");//Last name
define("_LESSONSTATUS","レッスンの状態");//Lesson status
define("_SPACEUSAGE","宇宙利用方法");//Space usage
define("_NEWFOLDER","新しいフォルダ");//New folder
define("_VIEWFOLDERSTATISTICS","対象のフォルダの統計情報");//View folder statistics
define("_VIEWMESSAGE","対象メッセージが表示さ");//View message
define("_OFTOTAL","の合計");//of total
define("_KBYTESUSED","バイト使用される");//Kbytes used
define("_MARK","マーク");//Mark
define("_WITHSELECTED","を選択");//With selected
define("_MARKASREAD","既読");//Mark&nbsp;as&nbsp;read
define("_MARKASUNREAD","未読にする");//Mark&nbsp;as&nbsp;unread
define("_MOVETOFOLDER","フォルダに移動する");//Move to folder
define("_MOVE","動く");//Move
define("_PERSONALMESSAGE","個人的なメッセージが表示さ");//Personal message
define("_FROM2","投稿者：");//From:
define("_TO2","：");//To:
define("_SUBJECT2","件名：");//Subject:
define("_BECAUSEYOURMESSAGEBOXISFULL","ため、お客様のメッセージボックスがいっぱいに");//because your message box is full
define("_YOURMESSAGETO","お客様のメッセージを");//Your message to
define("_COULDNOTBEDELIVERED","配信できませんでした。");//could not be delivered
define("_BECAUSEHISMESSAGEBOXISFULL","彼のメッセージボックスがいっぱいに");//because his message box is full
define("_THEMESSAGE","メッセージが表示さ");//Message
define("_MESSAGEWASSENT","メッセージの送信");//Message was sent 
define("_INVALIDFOLDERNAME","無効なフォルダ名");//Invalid folder name
define("_SORRYYOUCANNOTCREATEANYMOREFOLDERS","申し訳ありませんしかし、他のフォルダを作成することはできません。");//Sorry but you cannot create any other folders
define("_FOLDERWITHSAMENAMEALREADYEXISTS","と同じ名前のフォルダが既に存在する");//A folder with the same name already exists
define("_FOLDERCREATED","フォルダの作成");//Folder created
define("_FOLDERUPDATED","フォルダの更新済み");//Folder updated
define("_FOLDERDELETED","フォルダの削除");//Folder deleted
define("_NEWFOLDERNAME","新しいフォルダ名");//New folder name
define("_THISFOLDERDOESNOTEXIT","このフォルダが存在しません");//This folder does not exist
define("_MODIFY","変更");//Modify
define("_FOLDER","フォルダ");//Folder
define("_SIZE","寸法");//Size
define("_YOUMUSTSPECIFYANACTION","のアクションを指定する必要があります。");//You must specify an action
define("_ALLOWHTMLFPM","htmlでフォーラムや個人的なメッセージを許可する");//Allow HTML in Forum and Personal messages
define("_ACTIVATEPOLLS","有効に投票");//Activate polls
define("_ALLOWATTACHMENTSINF","フォーラムで添付ファイルを許可する");//Allow attachments in forum
define("_PMQUOTA","個人的なメッセージクォータ");//Personal messages quota
define("_PMATTACHMENTSQUOTA","個人的なメッセージの添付ファイルを割当");//Personal messages attachments quota
define("_YOUMUSTSELECTMESSAGESTODELETE","メッセージを削除するを選択する必要があります。");//You must select messages to delete
define("_YOUMUSTSELECTMESSAGESTOMOVE","メッセージを移動するを選択する必要があります。");//You must select messages to move
define("_YOUMUSTSELECTMESSAGESTOMARK","マークのメッセージを選択する必要があります。");//You must select messages to mark
define("_SUCCESSFULLYDELETEDMESSAGES","メッセージが正常に削除さ");//Messages were successfully deleted
define("_AREYOUSURETODELETEFOLDER","してもよろしいしたいフォルダを削除する");//Are you sure you want to delete folder
define("_ANDALLCONTENTS","とそのすべてのコンポーネントのですか？");//and all its components?
define("_APPROACHINGMESSAGEQUOTA","あなたがあなたのメッセージが表示さクォータが近づいています。");//You are approaching your message quota.
define("_DELETEOLDMESSAGES","古いメッセージを削除して容量を節約する。");//Please delete any old messages to save space.
define("_MESSAGEBOXSIZECRITICAL","あなたのメッセージボックスのサイズが非常に重要です。");//Your messages box size is critical.
define("_ERASEMESSAGESNOTRECEIVENEW","すべてのメッセージを消去をお持ちでない場合、あなたは新しいものを受信することはできません。");//If you don&#039;t erase any messages, you will not be able to receive new ones.
define("_NOMESSAGESINFOLDER","このフォルダ内のメッセージ");//No messages in this folder
define("_AREYOUSURETODELETEMESSAGE","を削除してもよろしいですこのメッセージが表示したいですか？");//Are you sure you want to delete this message?
define("_TRIEDACCESSMESSAGEMALFORMEDID","不正な番号にアクセスしようとしたメッセージを");//Tried to access messages with malformed id
define("_THISMESSAGEDOESNOTEXIST","このメッセージは存在しません");//This message does not exist
define("_RETURNFOLDERSLIST","フォルダのリストに戻ります");//Return to folders list
define("_TOFORUM","〜へ");//To
define("_RE","再");//Re
define("_INCOMING","着信");//Incoming
define("_SENT","送った");//Sent
define("_DRAFTS","下書き");//Drafts
define("_CALENDAR","カレンダー");//Calendar
define("_JANUARY","1月");//January
define("_FEBRUARY","年2月");//February
define("_MARCH","3月");//March
define("_APRIL","4月");//April
define("_MAY","〜かもしれない");//May
define("_JUNE","年6月");//June
define("_JULY","7月");//July
define("_AUGUST","8月");//August
define("_SEPTEMBER","9月");//September
define("_OCTOBER","10月");//October
define("_NOVEMBER","11月");//November
define("_DECEMBER","12月");//December
define("_MON","メートル");//M
define("_TUE","トン");//T
define("_WED","ワット");//W
define("_THU","トン");//T
define("_FRI","f");//F
define("_SAT","秒");//S
define("_SUN","秒");//S
define("_VALUE","値");//Value
define("_PERSONALDATACHANGESUCCESSADMIN","ユーザーの個人情報が変更されました");//User&#039;s personal info have been successfully altered
define("_CONTINUE","続行");//Continue
define("_WEB","個人ページ");//Personal page
define("_DATA","データ");//Data
define("_USERNAMEERROR","表示名を入力してください！");//Please enter the a display name!
define("_CVERROR","いくつかの情報をご記入下さい！");//Please fill in some information about you!
define("_NUM","ティッカー番号");//Ticker number
define("_SCORM","SCORMを");//SCORM
define("_MYSETTINGS","私の設定");//my Settings
define("_MYLESSONS","私のレッスン");//my Lessons
define("_MYOPTIONS","マイオプション");//my Options
define("_YOUHAVENOBOOKMARKS","ブックマークはありません");//You have no bookmarks
define("_ADDCONTENT","コンテンツを追加");//Add content
define("_NEWMESSAGES","新しいメッセージ");//New messages
define("_DOYOUWANTTOADDTHISPAGETOYOURBOOKMARKS","を追加する場合はこのページをブックマークですか？");//Do you want to add this page to your bookmarks?
define("_BOOKMARKS","ブックマーク");//Bookmarks
define("_SHOWBOOKMARKS","詳細ブックマーク");//Show bookmarks
define("_ADDTHISPAGETOYOURBOOKMARKS","このページをブックマークに追加して");//Add this page to your bookmarks
define("_YOUCANDOTEST","はテストすることができます。");//You can do test
define("_TIMESMORE","倍以上");//times more
define("_FIELDNAME","フィールド名");//Field name
define("_FIELDDESCRIPTION","フィールド説明");//Field description
define("_DBTYPE","データベースの種類");//Database type
define("_ADDFIELD","追加フィールド");//Add field
define("_TREESAVEDSUCCESSFULLY","カテゴリ保存succefully");//Tree saved succefully
define("_ERROROCCURED","中にエラーが発生します。もう一度やり直してください。");//An error occured. Please try again.
define("_EXPORTSTATS","輸出報告書：");//Export reports:
define("_MATHTYPEHELP1","数学の表現を挿入することができます。 、エディタを使用して、特別なコードをtranlates数学でASCII数学の記法を表現します。 efrontこの特別なコードエディタが組み込まれています。そのため、ユーザーは、数学の種類を簡単に追加します。することができますから、このコードの詳細については次の表には、 <a target=\"_blank\" href=\"http://www1.chapman.edu/~jipsen/mathml/asciimath.html\">このページ</a>から");//You can insert math expressions in the editor by using a special code which tranlates an ASCII math notation to mathematic expressions. eFront has built into editor this special code. So users can easily add math types. You can learn about this code from the table below or from <a target=\"_blank\" href=\"http://www1.chapman.edu/~jipsen/mathml/asciimath.html\">this page</a>
define("_MATHTYPEHELP2","<p> `することは避けるべきですシンボルを使用する特殊文字を表すためのエンコーディングします。問題が発生した場合を使用する場合には、エスケープ文字を使用する前に、例えば\\ ` </p>");//<p>You should  avoid to use symbol \` because it represents a special character for the encoding. In case you want to use it, use escape character \ before it, e.g. \\\`</p>
define("_PERCENTCORRECT","％正しい");//percent correct
define("_GLOSSARY","用語集");//Glossary
define("_ADDDEFINITION","カートで定義されて");//Add definition
define("_SUCCESFULLYADDEDDEFINITION","成功の定義が追加されました。");//The definition was added successfully
define("_DEFINITION","で定義されて");//Definition
define("_NODEFINITIONSFOUNDFORTHISLESSON","このレッスンの定義は見つかりませんでした。");//No definitions found for this lesson
define("_CHOOSEWHATTOEXPORT","輸出するものを選択し（離れコンテンツ）");//Choose what to export (apart from content)
define("_CREATED","作成");//Created
define("_CANCELTEST","キャンセルのテスト");//Cancel test
define("_DELETEEXISTINGDATAFROM","既存のデータを削除投稿者：");//Delete existing data from:
define("_CLOSE","閉じる");//Close
define("_SHOWHIDE","表示/非表示");//Show/Hide
define("_EFRONTLOGO","efrontロゴ");//eFront logo
define("_READ","読む");//Read
define("_UNREAD","未読");//Unread
define("_SUCCESFULLYADDEDROOM","正常に追加されましたルーム");//Succesfully added room
define("_AND","および");//and
define("_TRUEFALSE","真/偽");//True/False
define("_DROPDOWN","リストからお選び下さい");//Select from list
define("_TRUE","真");//True
define("_FALSE","偽");//False
define("_QUESTIONNUMBER","質問番号");//Question number
define("_QUESTIONTITLE","質問タイトル");//Question title
define("_NUMBEROFOPTIONS","いくつかのオプション");//Number of options
define("_YOUHAVELOGGEDOUTBECAUSEYOURSESSIONHASTIMEDOUT","あなたがログに記録するため、お客様のセッションがタイムアウト");//You have logged out because your session has timed out
define("_ORSELECTONEFROMLIST","またはリストから1つ選択して");//Or select one from list
define("_EXPLANATION","説明");//Explanation
define("_QUESTION","質問");//Question
define("_CHANGESTYLE","変更のテーマ");//Change theme
define("_PREDEFINED","定義済みの");//Predefined
define("_SELECTNEWSTYLE","新しいテーマを選択");//Select new theme
define("_SETSTYLE","設定テーマ");//Set theme
define("_NOPREVIEWIMAGEFOUND","プレビューイメージが見つかりませんでした");//Preview image not found
define("_EDITOR_BOLD_DESC","太字（ Ctrl + Bキー）");//Bold (Ctrl+B)
define("_EDITOR_ITALIC_DESC","イタリック体（ Ctrl + Iキー）");//Italic (Ctrl+I)
define("_EDITOR_UNDERLINE_DESC","下線（ Ctrlを押しながら+ u 』 ）");//Underline (Ctrl+U)
define("_EDITOR_STRIKETROUGH_DESC","取り消し線");//Strikethrough
define("_EDITOR_JUSTIFYLEFT_DESC","左寄せ");//Align left
define("_EDITOR_JUSTIFYCENTER_DESC","中央揃え");//Align center
define("_EDITOR_JUSTIFYRIGHT_DESC","右寄せ");//Align right
define("_EDITOR_JUSTIFYFULL_DESC","両端揃え");//Align full
define("_EDITOR_BULLIST_DESC","箇条書きで表示");//Unordered list
define("_EDITOR_NUMLIST_DESC","注文リスト");//Ordered list
define("_EDITOR_OUTDENT_DESC","outdent");//Outdent
define("_EDITOR_INDENT_DESC","インデント");//Indent
define("_EDITOR_UNDO_DESC","元に戻す（ Ctrlを押しながら+ Z ）さ");//Undo (Ctrl+Z)
define("_EDITOR_REDO_DESC","やり直し（ Ctrlを押しながら+ y ）");//Redo (Ctrl+Y)
define("_EDITOR_LINK_DESC","挿入/ [編集]リンクを");//Insert/edit link
define("_EDITOR_UNLINK_DESC","解除");//Unlink
define("_EDITOR_IMAGE_DESC","挿入/編集イメージ");//Insert/edit image
define("_EDITOR_CLEANUP_DESC","厄介なコードのクリーンアップ");//Cleanup messy code
define("_EDITOR_FOCUS_ALERT","集中しなければならないのインスタンスをエディタを使用する前に、このコマンドを実行します。");//A editor instance must be focused before using this command.
define("_EDITOR_EDIT_CONFIRM","を使用したい場合は、このtextareaをWYSIWYGのモードですか？");//Do you want to use the WYSIWYG mode for this textarea?
define("_EDITOR_INSERT_LINK_TITLE","挿入/ [編集]リンクを");//Insert/edit link
define("_EDITOR_INSERT","挿入");//Insert
define("_EDITOR_UPDATE","更新する");//Update
define("_EDITOR_CANCEL","キャンセル");//Cancel
define("_EDITOR_INSERT_LINK_URL","リンク先URL");//Link URL
define("_EDITOR_INSERT_LINK_TARGET","目標物");//Target
define("_EDITOR_INSERT_LINK_TARGET_SAME","同じウィンドウでリンクを開く");//Open link in the same window
define("_EDITOR_INSERT_LINK_TARGET_BLANK","新しいウィンドウでリンクを開く");//Open link in a new window
define("_EDITOR_INSERT_IMAGE_TITLE","挿入/編集イメージ");//Insert/edit image
define("_EDITOR_INSERT_IMAGE_SRC","画像のURL");//Image URL
define("_EDITOR_INSERT_IMAGE_ALT","イメージ説明書");//Image description
define("_EDITOR_HELP_DESC","ヘルプ");//Help
define("_EDITOR_BOLD_IMG","bold.gif");//bold.gif
define("_EDITOR_ITALIC_IMG","italic.gif");//italic.gif
define("_EDITOR_UNDERLINE_IMG","underline.gif");//underline.gif
define("_EDITOR_CLIPBOARD_MSG","コピー/カット/貼り付けではない利用可能なMozillaやFirefoxを起動します。関連情報を参照するようにこの問題を解決したいですか？");//Copy/Cut/Paste is not available in Mozilla and Firefox.Do you want more information about this issue?
define("_EDITOR_POPUP_BLOCKED","申し訳ありませんが、しかし、私たちのことに気付いているお客様のポップアップブロッカーは無効になって、ウィンドウを提供するアプリケーションの機能を提供します。ポップアップブロックを無効にする必要があります。このサイトをフルに活用するために、このツールを使用します。");//Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.
define("_EDITOR_JAVA_TITLE","挿入/編集ジャワ");//Insert / edit Java
define("_EDITOR_JAVA_DESC","挿入/編集ジャワ");//Insert / edit Java
define("_EDITOR_JAVA_FILE","ジャワ-ファイル（ 。クラス）");//Java-File (.class)
define("_EDITOR_JAVA_SIZE","寸法");//Size
define("_EDITOR_JAVA_LIST","javaファイル");//Java files
define("_EDITOR_JAVA_PROPS","Javaのプロパティ");//Java properties
define("_EDITOR_JAVA_GENERAL","全般");//General
define("_EDITOR_JAVA_CODEBASE","コード");//Codebase
define("_EDITOR_ADVHR_INSERT_ADVHR_DESC","horizontaleルール");//Horizontale rule
define("_EDITOR_ADVHR_INSERT_ADVHR_WIDTH","幅");//Width
define("_EDITOR_ADVHR_INSERT_ADVHR_SIZE","高さ");//Height
define("_EDITOR_ADVHR_INSERT_ADVHR_NOSHADE","の影");//No shadow
define("_EDITOR_ADVIMAGE_TAB_GENERAL","全般");//General
define("_EDITOR_ADVIMAGE_TAB_APPEARANCE","外観");//Appearance
define("_EDITOR_ADVIMAGE_TAB_ADVANCED","高度な");//Advanced
define("_EDITOR_ADVIMAGE_GENERAL","全般");//General
define("_EDITOR_ADVIMAGE_TITLE","タイトル");//Title
define("_EDITOR_ADVIMAGE_PREVIEW","プレビュー");//Preview
define("_EDITOR_ADVIMAGE_CONSTRAIN_PROPORTIONS","縦横比を固定");//Constrain proportions
define("_EDITOR_ADVIMAGE_LANGDIR","言語の方向");//Language direction
define("_EDITOR_ADVIMAGE_LANGCODE","言語コード");//Language code
define("_EDITOR_ADVIMAGE_LONG_DESC","長い説明リンク");//Long description link
define("_EDITOR_ADVIMAGE_STYLE","スタイル");//Style
define("_EDITOR_ADVIMAGE_CLASSES","クラス");//Classes
define("_EDITOR_ADVIMAGE_LTR","左から右へ");//Left to right
define("_EDITOR_ADVIMAGE_RTL","右から左へ");//Right to left
define("_EDITOR_ADVIMAGE_ID","番号");//Id
define("_EDITOR_ADVIMAGE_IMAGE_MAP","イメージマップ");//Image map
define("_EDITOR_ADVIMAGE_SWAP_IMAGE","スワップイメージ");//Swap image
define("_EDITOR_ADVIMAGE_ALT_IMAGE","代替イメージ");//Alternative image
define("_EDITOR_ADVIMAGE_MOUSEOVER","にマウスを置く");//for mouse over
define("_EDITOR_ADVIMAGE_MOUSEOUT","マウスアウト");//for mouse out
define("_EDITOR_ADVIMAGE_MISC","その他");//Miscellaneous
define("_EDITOR_ADVIMAGE_EXAMPLE_IMG","外観プレビュー画像");//Appearance&nbsp;preview&nbsp;image
define("_EDITOR_ADVIMAGE_MISSING_ALT","してもよろしいですを続行するには、説明書の画像を含むですか？なくて、イメージすることはできませんのユーザーがアクセスできるようにいくつかの障害か、またはテキストブラウザを使用しているか、または無効になって画像は、 Webブラウズをします。");//Are you sure you want to continue without including an Image description? Without  it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.
define("_EDITOR_ADVLINK_GENERAL_TAB","全般");//General
define("_EDITOR_ADVLINK_POPUP_TAB","ポップアップ");//Popup
define("_EDITOR_ADVLINK_ADVANCED_TAB","高度な");//Advanced
define("_EDITOR_ADVLINK_GENERAL_PROPS","全般プロパティ");//General properties
define("_EDITOR_ADVLINK_POPUP_PROPS","ポップアップのプロパティ");//Popup properties
define("_EDITOR_ADVLINK_EVENT_PROPS","イベント");//Events
define("_EDITOR_ADVLINK_ADVANCED_PROPS","詳細プロパティ");//Advanced properties
define("_EDITOR_ADVLINK_POPUP_OPTS","オプション");//Options
define("_EDITOR_ADVLINK_ANCHOR_NAMES","アンカー");//Anchors
define("_EDITOR_ADVLINK_TARGET_SAME","このウィンドウで開きます/フレーム");//Open in this window / frame
define("_EDITOR_ADVLINK_TARGET_PARENT","オープンで親ウィンドウ/フレーム");//Open in parent window / frame
define("_EDITOR_ADVLINK_TARGET_TOP","開いて上のフレーム（すべてのフレームに代わる）");//Open in top frame (replaces all frames)
define("_EDITOR_ADVLINK_TARGET_BLANK","新しいウィンドウで開く");//Open in new window
define("_EDITOR_ADVLINK_POPUP","JavaScriptのポップアップ");//Javascript popup
define("_EDITOR_ADVLINK_POPUP_URL","ポップアップのURL");//Popup URL
define("_EDITOR_ADVLINK_POPUP_NAME","ウィンドウ名");//Window name
define("_EDITOR_ADVLINK_POPUP_RETURN","挿入\\に\" return false \\ \"");//Insert \\\"return false\\\"
define("_EDITOR_ADVLINK_POPUP_SCROLLBARS","詳細スクロールバー");//Show scrollbars
define("_EDITOR_ADVLINK_POPUP_STATUSBAR","詳細ステータスバー");//Show status bar
define("_EDITOR_ADVLINK_POPUP_TOOLBAR","詳細ツールバー");//Show toolbars
define("_EDITOR_ADVLINK_POPUP_MENUBAR","詳細メニューバー");//Show menu bar
define("_EDITOR_ADVLINK_POPUP_LOCATION","詳細ロケーションバー");//Show location bar
define("_EDITOR_ADVLINK_POPUP_RESIZABLE","ウィンドウのサイズ変更する");//Make window resizable
define("_EDITOR_ADVLINK_POPUP_DEPENDENT","依存性（のMozilla / Firefoxのみ）");//Dependent (Mozilla/Firefox only)
define("_EDITOR_ADVLINK_POPUP_SIZE","寸法");//Size
define("_EDITOR_ADVLINK_POPUP_POSITION","位置（のx / y ）");//Position (X/Y)
define("_EDITOR_ADVLINK_ID","番号");//Id
define("_EDITOR_ADVLINK_STYLE","スタイル");//Style
define("_EDITOR_ADVLINK_CLASSES","クラス");//Classes
define("_EDITOR_ADVLINK_TARGET_NAME","ターゲット名");//Target name
define("_EDITOR_ADVLINK_LANGDIR","言語の方向");//Language direction
define("_EDITOR_ADVLINK_TARGET_LANGCODE","ターゲットとする言語");//Target language
define("_EDITOR_ADVLINK_LANGCODE","言語コード");//Language code
define("_EDITOR_ADVLINK_ENCODING","ターゲットの文字エンコーディング");//Target character encoding
define("_EDITOR_ADVLINK_MIME","ターゲットMIMEタイプ");//Target MIME type
define("_EDITOR_ADVLINK_REL","関係のページをターゲットに設定する");//Relationship page to target
define("_EDITOR_ADVLINK_REV","関係をターゲットにしたページ");//Relationship target to page
define("_EDITOR_ADVLINK_TABINDEX","tabindexの");//Tabindex
define("_EDITOR_ADVLINK_ACCESSKEY","accesskey");//Accesskey
define("_EDITOR_ADVLINK_LTR","左から右へ");//Left to right
define("_EDITOR_ADVLINK_RTL","右から左へ");//Right to left
define("_EDITOR_EMOTIONS_TITLE","感情を挿入");//Insert emotion
define("_EDITOR_EMOTIONS_DESC","感情");//Emotions
define("_EDITOR_EMOTIONS_COOL","涼しい");//Cool
define("_EDITOR_EMOTIONS_CRY","泣く");//Cry
define("_EDITOR_EMOTIONS_EMBARASSED","恥ずかしい");//Embarassed
define("_EDITOR_EMOTIONS_FOOT_IN_MOUTH","口の中に足を踏み入れる");//Foot in mouth
define("_EDITOR_EMOTIONS_FROWN","まゆをひそめて");//Frown
define("_EDITOR_EMOTIONS_INNOCENT","罪のない");//Innocent
define("_EDITOR_EMOTIONS_KISS","キス");//Kiss
define("_EDITOR_EMOTIONS_LAUGHING","笑い");//Laughing
define("_EDITOR_EMOTIONS_MONEY_MOUTH","お金口");//Money mouth
define("_EDITOR_EMOTIONS_SEALED","密閉型");//Sealed
define("_EDITOR_EMOTIONS_SMILE","笑み");//Smile
define("_EDITOR_EMOTIONS_SURPRISED","驚き");//Surprised
define("_EDITOR_EMOTIONS_TONGUE_OUT","舌アウト");//Tongue out
define("_EDITOR_EMOTIONS_UNDECIDED","未定");//Undecided
define("_EDITOR_EMOTIONS_WINK","ウインク");//Wink
define("_EDITOR_EMOTIONS_YELL","叫ぶ");//Yell
define("_EDITOR_IESPELL_IESPELL_DESC","スペルチェックを実行する");//Run spell checking
define("_EDITOR_IESPELL_IESPELL_DOWNLOAD","iespellは検出されませんでした。ダウンロードページに行く[ OK ]をクリックします。");//ieSpell not detected. Click OK to go to download page.
define("_EDITOR_INSERTDATETIME_INSERTDATE_DEF_FMT","％のyメートル- ％ d個％");//%Y-%m-%d
define("_EDITOR_INSERTDATETIME_INSERTTIME_DEF_FMT","％ h ： ％メートル： ％ sの");//%H:%M:%S
define("_EDITOR_INSERTDATETIME_INSERTDATE_DESC","挿入日");//Insert date
define("_EDITOR_INSERTDATETIME_INSERTTIME_DESC","挿入時間");//Insert time
define("_EDITOR_INSERTDATETIME_INSERTTIME_MONTHS_LONG","新しい配列（ &#39; 1月&#39; 、 &#39;年2月&#39; 、 &#39; 3月&#39; 、 &#39; 4月&#39; 、 &#39; 5月&#39; 、 &#39;年6月&#39; 、 &#39; 7月&#39; 、 &#39; 8月&#39; 、 &#39; 9月&#39; 、 &#39; 10月&#39; 、 &#39; 11月&#39; 、 &#39; 12月&#39; ）");//new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December')
define("_EDITOR_INSERTDATETIME_INSERTTIME_MONTHS_SHORT","新しい配列（ &#39;月&#39; 、 &#39; 02月&#39; 、 &#39; 03 &#39; 、 &#39; 04月&#39; 、 &#39; 5月&#39; 、 &#39; 06月&#39; 、 &#39; 2007年07月&#39; 、 &#39; 08月&#39; 、 &#39; 09 &#39; 、 &#39; 10 &#39; 、 &#39; 11 &#39; 、 &#39; 12 &#39; ）");//new Array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
define("_EDITOR_INSERTDATETIME_INSERTTIME_DAY_LONG","新しい配列（ &#39;日曜日&#39; 、 &#39;月曜日&#39; 、 &#39;火曜日&#39; 、 &#39;水曜日&#39; 、 &#39;木曜日&#39; 、 &#39;金曜日&#39; 、 &#39;土曜日&#39; 、 &#39;日曜日&#39; ）");//new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')
define("_EDITOR_INSERTDATETIME_INSERTTIME_DAY_SHORT","新しい配列（ &#39;太陽&#39; 、 &#39;月&#39; 、 &#39;火曜&#39; 、 &#39;水&#39; 、 &#39;木&#39; 、 &#39;金&#39; 、 &#39;土&#39; 、 &#39;太陽&#39; ）");//new Array('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun')
define("_EDITOR_MATHTYPE_INSERT_MATHTYPE_TITLE","挿入mathtype");//Insert mathtype
define("_EDITOR_MATHTYPE_TITLE","挿入mathtype");//Insert mathtype
define("_EDITOR_MATHTYPE_MATHTYPE_DESC","mathtype");//Mathtype
define("_EDITOR_MATHTYPE_DESC","mathtype");//Mathtype
define("_EDITOR_MEDIA_TITLE","挿入/編集埋め込まれたメディア");//Insert / edit embedded media
define("_EDITOR_MEDIA_DESC","挿入/編集埋め込まれたメディア");//Insert / edit embedded media
define("_EDITOR_MEDIA_GENERAL","全般");//General
define("_EDITOR_MEDIA_ADVANCED","高度な");//Advanced
define("_EDITOR_MEDIA_FILE","ファイル");//File
define("_EDITOR_MEDIA_LIST","表示価格");//List
define("_EDITOR_MEDIA_SIZE","外形寸法");//Dimensions
define("_EDITOR_MEDIA_PREVIEW","プレビュー");//Preview
define("_EDITOR_MEDIA_CONSTRAIN_PROPORTIONS","縦横比を固定");//Constrain proportions
define("_EDITOR_MEDIA_TYPE","種類");//Type
define("_EDITOR_MEDIA_ID","番号");//Id
define("_EDITOR_MEDIA_NAME","名前");//Name
define("_EDITOR_MEDIA_CLASS_NAME","クラス");//Class
define("_EDITOR_MEDIA_VSPACE","v -の空間");//V-Space
define("_EDITOR_MEDIA_HSPACE","h -の空間");//H-Space
define("_EDITOR_MEDIA_PLAY","自動再生");//Auto play
define("_EDITOR_MEDIA_LOOP","ループ");//Loop
define("_EDITOR_MEDIA_MENU","詳細メニュー");//Show menu
define("_EDITOR_MEDIA_QUALITY","品質");//Quality
define("_EDITOR_MEDIA_SCALE","スケール");//Scale
define("_EDITOR_MEDIA_ALIGN","整列");//Align
define("_EDITOR_MEDIA_SALIGN","salign");//SAlign
define("_EDITOR_MEDIA_WMODE","wmode");//WMode
define("_EDITOR_MEDIA_BGCOLOR","背景");//Background
define("_EDITOR_MEDIA_BASE","基地");//Base
define("_EDITOR_MEDIA_FLASHVARS","flashvars");//Flashvars
define("_EDITOR_MEDIA_LIVECONNECT","swliveconnect");//SWLiveConnect
define("_EDITOR_MEDIA_AUTOHREF","autohref");//AutoHREF
define("_EDITOR_MEDIA_CACHE","キャッシュ");//Cache
define("_EDITOR_MEDIA_HIDDEN","隠し");//Hidden
define("_EDITOR_MEDIA_CONTROLLER","コントローラ");//Controller
define("_EDITOR_MEDIA_KIOSKMODE","kioskモード");//Kiosk mode
define("_EDITOR_MEDIA_PLAYEVERYFRAME","プレイごとにフレーム");//Play every frame
define("_EDITOR_MEDIA_TARGETCACHE","ターゲットのキャッシュ");//Target cache
define("_EDITOR_MEDIA_CORRECTION","いいえ補正");//No correction
define("_EDITOR_MEDIA_ENABLEJAVASCRIPT","JavaScriptを有効に");//Enable JavaScript
define("_EDITOR_MEDIA_STARTTIME","開始時刻");//Start time
define("_EDITOR_MEDIA_ENDTIME","終了時間");//End time
define("_EDITOR_MEDIA_HREF","href");//Href
define("_EDITOR_MEDIA_QTSRCCHOKESPEED","チョーク速度");//Choke speed
define("_EDITOR_MEDIA_TARGET","目標物");//Target
define("_EDITOR_MEDIA_VOLUME","巻");//Volume
define("_EDITOR_MEDIA_AUTOSTART","自動起動");//Auto start
define("_EDITOR_MEDIA_ENABLED","有効になって");//Enabled
define("_EDITOR_MEDIA_FULLSCREEN","フルスクリーン");//Fullscreen
define("_EDITOR_MEDIA_INVOKEURLS","URLを呼び出す");//Invoke URLs
define("_EDITOR_MEDIA_MUTE","ミュート");//Mute
define("_EDITOR_MEDIA_STRETCHTOFIT","ストレッチに合わせて");//Stretch to fit
define("_EDITOR_MEDIA_WINDOWLESSVIDEO","窓のビデオ");//Windowless video
define("_EDITOR_MEDIA_BALANCE","バランス");//Balance
define("_EDITOR_MEDIA_BASEURL","ベースURL");//Base URL
define("_EDITOR_MEDIA_CAPTIONINGID","キャプション番号");//Captioning id
define("_EDITOR_MEDIA_CURRENTMARKER","現在のマーカー");//Current marker
define("_EDITOR_MEDIA_CURRENTPOSITION","現在の位置");//Current position
define("_EDITOR_MEDIA_DEFAULTFRAME","デフォルトのフレーム");//Default frame
define("_EDITOR_MEDIA_PLAYCOUNT","プレイ数");//Play count
define("_EDITOR_MEDIA_RATE","比率");//Rate
define("_EDITOR_MEDIA_UIMODE","UIモード");//UI Mode
define("_EDITOR_MEDIA_FLASH_OPTIONS","フラッシュオプション");//Flash options
define("_EDITOR_MEDIA_QT_OPTIONS","QuickTimeのオプション");//Quicktime options
define("_EDITOR_MEDIA_WMP_OPTIONS","Windows Media Playerのオプション");//Windows media player options
define("_EDITOR_MEDIA_RMP_OPTIONS","本当のメディアプレーヤーのオプション");//Real media player options
define("_EDITOR_MEDIA_SHOCKWAVE_OPTIONS","ショックウェーブオプション");//Shockwave options
define("_EDITOR_MEDIA_AUTOGOTOURL","自動後藤のURL");//Auto goto URL
define("_EDITOR_MEDIA_CENTER","センター");//Center
define("_EDITOR_MEDIA_IMAGESTATUS","画像の状態");//Image status
define("_EDITOR_MEDIA_MAINTAINASPECT","アスペクトを維持する");//Maintain aspect
define("_EDITOR_MEDIA_NOJAVA","いいえジャワ");//No java
define("_EDITOR_MEDIA_PREFETCH","プリフェッチ");//Prefetch
define("_EDITOR_MEDIA_SHUFFLE","シャッフル");//Shuffle
define("_EDITOR_MEDIA_CONSOLE","コンソール");//Console
define("_EDITOR_MEDIA_NUMLOOP","NUM件のループ");//Num loops
define("_EDITOR_MEDIA_CONTROLS","コントロール");//Controls
define("_EDITOR_MEDIA_SCRIPTCALLBACKS","スクリプトのコールバック");//Script callbacks
define("_EDITOR_MEDIA_SWSTRETCHSTYLE","ストレッチスタイル");//Stretch style
define("_EDITOR_MEDIA_SWSTRETCHHALIGN","ストレッチh -整列");//Stretch H-Align
define("_EDITOR_MEDIA_SWSTRETCHVALIGN","ストレッチv -整列");//Stretch V-Align
define("_EDITOR_MEDIA_SOUND","サウンド");//Sound
define("_EDITOR_MEDIA_PROGRESS","進捗状況");//Progress
define("_EDITOR_MEDIA_QTSRC","qt src");//QT Src
define("_EDITOR_MEDIA_QT_STREAM_WARN","RTSPのリソースをストリームに直接接続できるqtが追加されるはずの詳細設定]タブの下にsrcフィールドです。ストリーミングする必要も以外のバージョンを追加するにはsrcフィールド..");//Streamed rtsp resources should be added to the QT Src field under the advanced tab.You should also add a non streamed version to the Src field..
define("_EDITOR_PREVIEW_PREVIEW_DESC","プレビュー");//Preview
define("_EDITOR_PRINT_PRINT_DESC","印刷");//Print
define("_EDITOR_SAVE_SAVE_DESC","保存する");//Save
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_SEARCH_DESC","見つける");//Find
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_SEARCHNEXT_DESC","検索を再度");//Find again
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACE_DESC","検索/置換");//Find/Replace
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_NOTFOUND","検索が完了します。検索文字列が見つかりませんでした。");//The search has been completed. The search string could not be found.
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_SEARCH_TITLE","見つける");//Find
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACE_TITLE","検索/置換");//Find/Replace
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_ALLREPLACED","すべての検索文字列の出現が置き換えられてしまいます。");//All occurrences of the search string were replaced.
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_FINDWHAT","検索する文字列");//Find what
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACEWITH","置き換える");//Replace with
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_DIRECTION","方向");//Direction
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_UP","上へ");//Up
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_DOWN","下に");//Down
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_CASE","大文字と小文字を区別");//Match case
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_FINDNEXT","次を検索");//Find&nbsp;next
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACE","置き換える");//Replace
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACEALL","すべて置換");//Replace&nbsp;all
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_CANCEL","キャンセル");//Cancel
define("_EDITOR_TABLE_GENERAL_TAB","全般");//General
define("_EDITOR_TABLE_ADVANCED_TAB","高度な");//Advanced
define("_EDITOR_TABLE_GENERAL_PROPS","全般プロパティ");//General properties
define("_EDITOR_TABLE_ADVANCED_PROPS","詳細プロパティ");//Advanced properties
define("_EDITOR_TABLE_DESC","新しいテーブルを挿入する");//Inserts a new table
define("_EDITOR_TABLE_ROW_BEFORE_DESC","行を挿入する前に");//Insert row before
define("_EDITOR_TABLE_ROW_AFTER_DESC","行を挿入した後");//Insert row after
define("_EDITOR_TABLE_DELETE_ROW_DESC","行を削除");//Delete row
define("_EDITOR_TABLE_COL_BEFORE_DESC","列を挿入する前に");//Insert column before
define("_EDITOR_TABLE_COL_AFTER_DESC","列を挿入した後");//Insert column after
define("_EDITOR_TABLE_DELETE_COL_DESC","列を削除");//Remove column
define("_EDITOR_TABLE_ROWTYPE","テーブルの行を部分");//Row in table part
define("_EDITOR_TABLE_TITLE","挿入/変更テーブル");//Insert/Modify table
define("_EDITOR_TABLE_WIDTH","幅");//Width
define("_EDITOR_TABLE_HEIGHT","高さ");//Height
define("_EDITOR_TABLE_COLS","コラム");//Columns
define("_EDITOR_TABLE_ROWS","行");//Rows
define("_EDITOR_TABLE_CELLSPACING","セル");//Cellspacing
define("_EDITOR_TABLE_CELLPADDING","セル");//Cellpadding
define("_EDITOR_TABLE_BORDER","国境");//Border
define("_EDITOR_TABLE_ALIGN","アライメント");//Alignment
define("_EDITOR_TABLE_ALIGN_DEFAULT","債務不履行");//Default
define("_EDITOR_TABLE_ALIGN_LEFT","左");//Left
define("_EDITOR_TABLE_ALIGN_RIGHT","右");//Right
define("_EDITOR_TABLE_ALIGN_MIDDLE","センター");//Center
define("_EDITOR_TABLE_ROW_TITLE","テーブルの行のプロパティ");//Table row properties
define("_EDITOR_TABLE_CELL_TITLE","表のセルのプロパティ");//Table cell properties
define("_EDITOR_TABLE_CELL_TYPE","細胞のタイプ");//Cell type
define("_EDITOR_TABLE_ROW_DESC","テーブルの行のプロパティ");//Table row properties
define("_EDITOR_TABLE_CELL_DESC","表のセルのプロパティ");//Table cell properties
define("_EDITOR_TABLE_VALIGN","縦方向の配置");//Vertical alignment
define("_EDITOR_TABLE_ALIGN_TOP","頂上");//Top
define("_EDITOR_TABLE_ALIGN_BOTTOM","底");//Bottom
define("_EDITOR_TABLE_PROPS_DESC","テーブルのプロパティ");//Table properties
define("_EDITOR_TABLE_BORDERCOLOR","枠線の色");//Border color
define("_EDITOR_TABLE_BGCOLOR","背景色");//Background color
define("_EDITOR_TABLE_MERGE_CELLS_TITLE","表のセルをマージ");//Merge table cells
define("_EDITOR_TABLE_SPLIT_CELLS_DESC","分割表のセル");//Split table cells
define("_EDITOR_TABLE_MERGE_CELLS_DESC","表のセルをマージ");//Merge table cells
define("_EDITOR_TABLE_CUT_ROW_DESC","カットテーブルの行");//Cut table row
define("_EDITOR_TABLE_COPY_ROW_DESC","テーブルの行をコピー");//Copy table row
define("_EDITOR_TABLE_PASTE_ROW_BEFORE_DESC","テーブルの行の前に貼り付ける");//Paste table row before
define("_EDITOR_TABLE_PASTE_ROW_AFTER_DESC","テーブルの行の後に貼り付ける");//Paste table row after
define("_EDITOR_TABLE_ID","番号");//Id
define("_EDITOR_TABLE_STYLE","スタイル");//Style
define("_EDITOR_TABLE_LANGDIR","言語の方向");//Language direction
define("_EDITOR_TABLE_LANGCODE","言語コード");//Language code
define("_EDITOR_TABLE_MIME","ターゲットMIMEタイプ");//Target MIME type
define("_EDITOR_TABLE_LTR","左から右へ");//Left to right
define("_EDITOR_TABLE_RTL","右から左へ");//Right to left
define("_EDITOR_TABLE_BGIMAGE","背景画像");//Background image
define("_EDITOR_TABLE_SUMMARY","概要");//Summary
define("_EDITOR_TABLE_TD","データ");//Data
define("_EDITOR_TABLE_TH","ヘッダー");//Header
define("_EDITOR_TABLE_CELL_CELL","更新プログラムの現在のセル");//Update current cell
define("_EDITOR_TABLE_CELL_ROW","更新プログラムのすべてのセルで行");//Update all cells in row
define("_EDITOR_TABLE_CELL_ALL","更新プログラムのすべてのセルで表");//Update all cells in table
define("_EDITOR_TABLE_ROW_ROW","更新プログラムの現在の行");//Update current row
define("_EDITOR_TABLE_ROW_ODD","テーブルの行を更新プログラムの奇数");//Update odd rows in table
define("_EDITOR_TABLE_ROW_EVEN","テーブルの行を更新プログラムも");//Update even rows in table
define("_EDITOR_TABLE_ROW_ALL","更新プログラムの全ての行をテーブル");//Update all rows in table
define("_EDITOR_TABLE_THEAD","テーブルfead");//Table fead
define("_EDITOR_TABLE_TBODY","テーブルボディ");//Table body
define("_EDITOR_TABLE_TFOOT","テーブルの足");//Table foot
define("_EDITOR_TABLE_DEL","表を削除");//Delete table
define("_EDITOR_TABLE_SCOPE","領域");//Scope
define("_EDITOR_TABLE_ROW","行");//Row
define("_EDITOR_TABLE_COL","列");//Col
define("_EDITOR_TABLE_ROWGROUP","行グループ");//Row group
define("_EDITOR_TABLE_COLGROUP","列グループ");//Col group
define("_EDITOR_TABLE_COL_LIMIT","あなたの最大のカラム数を超えました。");//You have exceeded the maximum number of columns.
define("_EDITOR_TABLE_ROW_LIMIT","あなたの最大の行数を超えました。");//You have exceeded the maximum number of rows.
define("_EDITOR_TABLE_CELL_LIMIT","あなたは細胞の最大数を超えています。");//You have exceeded the maximum number of cells.
define("_EDITOR_TABLE_MISSING_SCOPE","を続行してもよろしいしたい範囲を指定せずにこのテーブルのヘッダセルです。そうしなければ、それは難しいかもしれませんいくつかの障害を理解してユーザーにコンテンツやデータを表示するには、表です。");//Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.
define("_EDITOR_AUTOSAVE_AUTOSAVE_UNLOAD_MSG","に行った変更をする場合に失われることは、このページから移動します。");//The changes you made will be lost if you navigate away from this page.
define("_EDITOR_DIRECTIONALITY_DIRECTIONALITY_LTR_DESC","左から右への方向");//Direction left to right
define("_EDITOR_DIRECTIONALITY_DIRECTIONALITY_RTL_DESC","右から左方向に");//Direction right to left
define("_EDITOR_LAYER_INSERTLAYER_DESC","新しい層を挿入");//Insert new layer
define("_EDITOR_LAYER_FORWARD_DESC","移動進む");//Move forward
define("_EDITOR_LAYER_BACKWARD_DESC","後方に移動");//Move backward
define("_EDITOR_LAYER_ABSOLUTE_DESC","toggle絶対的な位置決め");//Toggle absolute positioning
define("_EDITOR_LAYER_CONTENT","新規レイヤー...");//New layer...
define("_EDITOR_NONBREAKING_DESC","non - breaking空白文字を挿入");//Insert non-breaking space character
define("_EDITOR_THEME_THEME_STYLE_SELECT","-スタイル-");//-- Styles --
define("_EDITOR_THEME_THEME_CODE_DESC","HTMLソースを編集");//Edit HTML Source
define("_EDITOR_THEME_THEME_CODE_TITLE","HTMLソースエディタ");//HTML Source Editor
define("_EDITOR_THEME_THEME_CODE_WORDWRAP","ワードラップ");//Word wrap
define("_EDITOR_THEME_THEME_SUB_DESC","添字");//Subscript
define("_EDITOR_THEME_THEME_SUP_DESC","上");//Superscript
define("_EDITOR_THEME_THEME_HR_DESC","挿入水平ルーラ");//Insert horizontal ruler
define("_EDITOR_THEME_THEME_REMOVEFORMAT_DESC","書式設定を削除");//Remove formatting
define("_EDITOR_THEME_THEME_CUSTOM1_DESC","ここにして、カスタム説明書");//Your custom description here
define("_EDITOR_THEME_INSERT_IMAGE_BORDER","国境");//Border
define("_EDITOR_THEME_INSERT_IMAGE_DIMENSIONS","外形寸法");//Dimensions
define("_EDITOR_THEME_INSERT_IMAGE_VSPACE","垂直空間");//Vertical space
define("_EDITOR_THEME_INSERT_IMAGE_HSPACE","水平方向のスペース");//Horizontal space
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN","アライメント");//Alignment
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_DEFAULT","-未設定-");//-- Not set --
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_BASELINE","ベースライン");//Baseline
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_TOP","頂上");//Top
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_MIDDLE","真ん中");//Middle
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_BOTTOM","底");//Bottom
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_TEXTTOP","texttop");//TextTop
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_ABSMIDDLE","絶対真ん中");//Absolute middle
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_ABSBOTTOM","絶対的な底");//Absolute bottom
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_LEFT","左");//Left
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_RIGHT","右");//Right
define("_EDITOR_THEME_THEME_FONT_SIZE","-フォントサイズ-");//-- Font size --
define("_EDITOR_THEME_THEME_FONTDEFAULT","-フォントファミリー-");//-- Font family --
define("_EDITOR_THEME_THEME_BLOCK","-フォーマット-");//-- Format --
define("_EDITOR_THEME_THEME_PARAGRAPH","段落");//Paragraph
define("_EDITOR_THEME_THEME_DIV","部");//Div
define("_EDITOR_THEME_THEME_ADDRESS","住所");//Address
define("_EDITOR_THEME_THEME_PRE","プリフォーマット");//Preformatted
define("_EDITOR_THEME_THEME_H1","見出し1");//Heading 1
define("_EDITOR_THEME_THEME_H2","見出し2");//Heading 2
define("_EDITOR_THEME_THEME_H3","見出し3");//Heading 3
define("_EDITOR_THEME_THEME_H4","見出し4");//Heading 4
define("_EDITOR_THEME_THEME_H5","見出し5");//Heading 5
define("_EDITOR_THEME_THEME_H6","見出し6");//Heading 6
define("_EDITOR_THEME_THEME_BLOCKQUOTE","引用");//Blockquote
define("_EDITOR_THEME_THEME_CODE","コード");//Code
define("_EDITOR_THEME_THEME_SAMP","サンプルコード");//Code sample
define("_EDITOR_THEME_THEME_DT","用語の定義");//Definition term 
define("_EDITOR_THEME_THEME_DD","で定義されて説明書");//Definition description
define("_EDITOR_THEME_THEME_COLORPICKER_TITLE","色を選択する");//Select a color
define("_EDITOR_THEME_THEME_COLORPICKER_APPLY","適用する");//Apply
define("_EDITOR_THEME_THEME_FORECOLOR_DESC","テキストの色を選択");//Select text color
define("_EDITOR_THEME_THEME_BACKCOLOR_DESC","背景色を選択");//Select background color
define("_EDITOR_THEME_THEME_CHARMAP_TITLE","カスタムの文字を選択");//Select custom character
define("_EDITOR_THEME_THEME_CHARMAP_DESC","カスタムの文字を挿入");//Insert custom character
define("_EDITOR_THEME_THEME_VISUALAID_DESC","toggleガイドライン/目に見えない要素");//Toggle guidelines/invisible elements
define("_EDITOR_THEME_INSERT_ANCHOR_TITLE","挿入/編集アンカー");//Insert/edit anchor
define("_EDITOR_THEME_INSERT_ANCHOR_NAME","アンカー名");//Anchor name
define("_EDITOR_THEME_THEME_ANCHOR_DESC","挿入/編集アンカー");//Insert/edit anchor
define("_EDITOR_THEME_THEME_INSERT_LINK_TITLEFIELD","タイトル");//Title
define("_EDITOR_THEME_THEME_CLIPBOARD_MSG","コピー/カット/貼り付けではない利用可能なMozillaやFirefoxを起動します。関連情報を参照するようにこの問題を解決したいですか？");//Copy/Cut/Paste is not available in Mozilla and Firefox.Do you want more information about this issue?
define("_EDITOR_THEME_THEME_PATH","道");//Path
define("_EDITOR_THEME_CUT_DESC","切る");//Cut
define("_EDITOR_THEME_COPY_DESC","コピー");//Copy
define("_EDITOR_THEME_PASTE_DESC","貼り付け");//Paste
define("_EDITOR_THEME_LINK_LIST","リンクのリスト");//Link list
define("_EDITOR_THEME_IMAGE_LIST","画像一覧");//Image list
define("_EDITOR_THEME_BROWSE","ブラウズする");//Browse
define("_EDITOR_THEME_IMAGE_PROPS_DESC","画像のプロパティ");//Image properties
define("_EDITOR_THEME_NEWDOCUMENT_DESC","新しいドキュメント");//New document
define("_EDITOR_THEME_CLASS_NAME","クラス");//Class
define("_EDITOR_THEME_NEWDOCUMENT","すべてクリアしてもよろしいしたい内容ですか？");//Are you sure you want clear all contents?
define("_EDITOR_THEME_ABOUT_TITLE","約tinymce");//About TinyMCE
define("_EDITOR_THEME_ABOUT","〜について");//About
define("_EDITOR_THEME_LICENSE","ライセンス");//License
define("_EDITOR_THEME_PLUGINS","プラグイン");//Plugins
define("_EDITOR_THEME_PLUGIN","差込式");//Plugin
define("_EDITOR_THEME_AUTHOR","著者");//Author
define("_EDITOR_THEME_VERSION","バージョン");//Version
define("_EDITOR_THEME_LOADED_PLUGINS","読み込まれたプラグイン");//Loaded plugins
define("_EDITOR_THEME_HELP","ヘルプ");//Help
define("_EDITOR_THEME_NOT_SET","-未設定-");//-- Not set --
define("_EDITOR_THEME_CLOSE","閉じる");//Close
define("_EDITOR_THEME_TOOLBAR_FOCUS","』移動ツールボタン-A ltキー+問、エディタ』移動- Al tキー-レディZ、 』移動要素のパス-オルト=エクス");//Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X
define("_EDITOR_THEME_INVALID_DATA","エラー：無効な値を入力すると、これらはスパムが赤色に点灯します。");//Error: Invalid values entered, these are marked in red.
define("_EDITOR_PASTE_PASTE_TEXT_DESC","プレーンテキストとして貼り付け");//Paste as plain text
define("_EDITOR_PASTE_PASTE_TEXT_TITLE","Ctrl + Vキーを使用してテキストをキーボードに貼り付けるにはウィンドウを開きます。");//Use CTRL+V on your keyboard to paste the text into the window.
define("_EDITOR_PASTE_PASTE_TEXT_LINEBREAKS","保つlinebreaks");//Keep linebreaks
define("_EDITOR_PASTE_PASTE_WORD_DESC","Wordから貼り付け");//Paste from Word
define("_EDITOR_PASTE_PASTE_WORD_TITLE","Ctrl + Vキーを使用してテキストをキーボードに貼り付けるにはウィンドウを開きます。");//Use CTRL+V on your keyboard to paste the text into the window.
define("_EDITOR_PASTE_SELECTALL_DESC","すべて選択");//Select all
define("_EDITOR_FULLSCREEN_FULLSCREEN_DESC","フルスクリーンモードを切り替える");//Toggle fullscreen mode (New)
define("_EDITOR_LESSONSINFO_LANG_LESSONS_INFO_LINKDESCRIPTION","次のページへ：レッスン情報");//Go to: lessons info (New)
define("_EDITOR_LESSONSINFO_LANG_LESSONS_INFO_DESC","レッスン情報リンク");//Lessons info link (New)
define("_EDITOR_INDEXLINK_LANG_INDEX_LINK_LINKDESCRIPTION","ログイン");//Login (New)
define("_EDITOR_INDEXLINK_LANG_INDEX_LINK_DESC","ログイン情報リンク");//Login link (New)
define("_CHOOSELANGUGETOSYNC","を同期する言語を選択");//Choose language to synchronize
define("_INSERTJAVA","javaファイルを挿入");//Insert java file
define("_INSERTMEDIA","メディアファイルの挿入");//Insert media file
define("_CHANGEORDER","変更命令");//Change order
define("_DRAGITEMSTOCHANGEQUESTIONSORDER","項目をドラッグし、質問の順序を変更して表示");//Drag items to change the display order of the questions
define("_TERM","用語");//Term
define("_OPERATIONS","オペレーション");//Operations
define("_AREYOUSUREYOUWANTTODELETELESSON","を削除してもよろしいですレッスンをしたいですか？");//Are you sure you want to delete lesson?
define("_EDITLESSON","レッスンの設定");//Edit lesson
define("_DIRECTIONS","カテゴリー");//Categories
define("_UPDATEDIRECTIONS","編集カテゴリー");//Edit categories
define("_PARENTDIRECTIONS","親カテゴリ");//Parent category
define("_AREYOUSUREYOUWANTTODELETEDIRECTION","してもよろしいのカテゴリを削除するにしたいですか？");//Are you sure you want to delete the category?
define("_YOUMUSTDELETEALLLESSONSANDSUBDIRECTIONSINTHISDIRECTIONBEFOREDELETINGIT","削除する必要がありますとすべてのサブカテゴリに属するすべてのレッスンをする前に、このカテゴリに削除されてしまいます");//You must delete all lessons and all subcategories that belong to this category before deleting it
define("_ROOTDIRECTION","----ルートカテゴリ----");//----Root category----
define("_CHECK","点検する");//Check
define("_REQUIREDNOTE","*必須フィールド");//*Mandatory fields
define("_BEFOREJAVASCRIPTERROR","は、次のエラーが発生しました：");//The following errors occured:
define("_AFTERJAVASCRIPTERROR","上記のエラー訂正してください。");//Please correct the above errors
define("_ISMANDATORY","は必須");//is mandatory
define("_HASINVALIDCHARACTERS","には無効な文字");//has invalid characters
define("_ONLYALLOWEDCHARACTERSLOGIN","文字と文字のみ<strong>です。 -_ @が</strong>許可");//Only letters and the characters <strong>. - _ @</strong> are allowed
define("_ALREADYEXISTS","既に存在する");//already exists
define("_PASSWORDSDONOTMATCH","のパスワードが一致しません");//The passwords do not match
define("_ONLYALLOWEDCHARACTERSTEXT","引用符ではご遠慮およびその他の特殊文字を使用します。");//Please do not use quotes and other special characters.
define("_REPEATPASSWORD","パスワードを繰り返します。");//Repeat password
define("_TERMS","利用規約");//Terms of Service
define("_REGISTRATIONFAILEDCONTACTADMIN","ユーザ登録に失敗しました。システム管理者に連絡してください。");//Registration failed. Please contact the system administrator.
define("_THELOGIN","ユーザー名");//The user name
define("_THEEMAIL","電子メール");//The email
define("_PASSWORDMUSTBE6CHARACTERS","パスワードをしなければならない、少なくとも6文字以上");//Password must be at least 6 characters
define("_DEFAULTCONTACTMESSAGE","私インフォームドコンセントを希望されるお客様のレッスンの内容や仕様だけでなく、任意のコースの参加要件");//I would like to be informed on the content and specifications of your lessons, as well as on any course participation requirements
define("_DEFAULTTERMSOFUSAGE","本サイトの利用方法efrontプラットフォームのすべてのユーザー登録してから、現在のe -ラーニングシステムを遵守しなければ読み取りおよび適切な利用方法は、次の条件です。 1 。ことは禁じられている理由以外のシステムを使用して学習の手順を実行すると、例えば：製品やサービスの促進や、これらの任意の組み合わせを、個人情報や他の人のプロモーション慣行は、ほかの人への侮辱は、管理システムの利用者かどうかのどちらか");//\teFront platform terms of usage\n\nEvery user registering to the present e-learning system must read and comply with the following terms of proper usage.\n\n1. It is forbidden to use the system for reasons other than performing a learning procedure, as for example: Promotion of products or services or any combination of these, personal or other person promotional practices, affront to other person, either registered system users or not
define("_YOUMUSTAGREEWITHTERMSOFUSAGETOCONTINUE","本利用規約に同意する必要があります利用方法を継続するために");//You must agree with the terms of usage in order to continue
define("_INVALIDFIELDDATA","無効なフィールドデータ");//Invalid field data
define("_SUCCESFULLYINSERTEDNEWUNIT","正常に挿入した新ユニット");//Succesfully inserted new unit
define("_ACCEPTTERMS","利用規約");//Accept terms
define("_SUCCESFULLYUPDATEDUNIT","正常に更新さ単位");//Succesfully updated unit
define("_ACTIVE2","アクティブ");//Active
define("_ACTIVEFEM","アクティブ");//Active
define("_LESSONSNUMBER","多くのレッスン");//Number of lessons
define("_PARENTDIRECTION","親カテゴリ");//Parent category
define("_EXPANDCOLLAPSE","展開/折りたたみ");//Expand/Collapse
define("_RAWTEXT","生のテキスト");//Raw text
define("_SUCCESFULLYADDEDTEST","正常に追加されましたテスト");//Succesfully added test
define("_SUCESSFULLYDELETEDTEST","正常に削除さ試験");//Succesfully deleted test
define("_SUCCESFULLYMODIFIEDTEST","正常に更新試験");//Succesfully modified test
define("_USEQUESTION","使用する質問");//Use question
define("_SHUFFLEANSWERS","shuffleの回答");//Shuffle answers
define("_SHUFFLEQUESTIONS","shuffleの質問");//Shuffle questions
define("_QUESTIONS","質問");//Questions
define("_INSERTMULTIPLEQUESTIONS","複数の選択肢を挿入して");//Insert the multiple choices
define("_INSERTEXPLANATION","挿入説明");//Insert explanation
define("_THISQUESTIONIS","この質問は");//This question is
define("_CREATEEMPTYSPACES","スペースを作成");//Create empty spaces
define("_EMPTYSPACESEXPLANATION","質問を書いてテキストを挿入する必要がどこに空白スペースを挿入＃ ＃ ＃ 。変更が終了したら、をクリックして、 \"空のスペースを作成する\"ボタンをクリックしてください");//Write the question text and wherever you need to insert a blank space, insert ###. When you are done, click on the &quot;Create empty spaces&quot; button below
define("_INSERTMATCHCOUPLES","マッチングのペアを挿入");//Insert matching pairs
define("_ADDOPTION","追加オプション");//Add option
define("_GOTOCALENDAR","カレンダーに行く");//Go to calendar
define("_EXPANDALL","すべて展開");//Expand all
define("_COLLAPSEALL","すべて折りたたんで");//Collapse all
define("_SURVEY","調査");//Survey
define("_SURVEYADDEDSUCCESSFULLY","調査で正常に追加されました");//Survey added successfully
define("_SURVEYFAILEDTOBEADDED","調査に失敗しましたが追加されました");//Survey failed to be added
define("_SURVEYDELETEDSUCCESSFULLY","調査を削除しました");//Survey deleted successfully
define("_QUESTIONADDEDSUCCESSFULLY","質問を正常に追加されました");//Question added successfully
define("_QUESTIONFAILEDTOBEADDED","質問の追加に失敗しました");//Failed to add question
define("_CREATESURVEYQUESTION","調査の質問を作成する");//Create question for survey
define("_CREATESURVEY","作成調査");//Create survey
define("_EDITSURVEY","編集調査");//Edit survey
define("_NOSURVEYFORLESSON","調査は、レッスンはありません。");//There is no survey for the lesson
define("_NOQUESTIONSFORSURVEY","調査のために質問はありません。");//There are no questions for the survey
define("_SURVEYCODE","コード");//Code
define("_SURVEYNAME","名前");//Name
define("_SURVEYSTATUS","地位");//Status
define("_SURVEYNUMBEROFQUESTIONS","質問基数");//Question cardinality
define("_SURVEYAVALIABLEFROM","から入手できる");//Availiable from
define("_SURVEYUNTIL","〜まで");//Until
define("_PUBLISH","刊行");//Publish
define("_SURVEYSELECTION","選択");//Select
define("_SELECTALL","すべて選択");//Select all
define("_SURVEYINFO","調査のために字幕");//Subtitle for the survey
define("_SURVEYINTROTEXT","調査入門テキスト");//Survey introductory text
define("_SURVEYENDTEXT","調査終了のテキスト");//Survey ending text
define("_YES_NO","はい/いいえ");//Yes/No
define("_SURVEYQUESTIONMULTIPLEONE","複数の選択肢の1つの答え");//Multiple choices-one answer
define("_SURVEYQUESTIONMULTIPLEMANY","複数の選択肢-複数回答可");//Multiple choices-multiple answers
define("_ENTERMAILMESSAGE","メッセージが表示さ");//Message
define("_PLEASESELECTAVALIDTYPEOFQUESTION","有効なタイプの質問を選択してくださいは、前のステップに進みます。");//Please select a valid type of question in the previous step.
define("_SURVEYDATAUPDATEDSUCCESSFULLY","調査データを更新しました");//Survey data updated successfully
define("_SURVEYDATAFAILEDTOBEUPDATED","調査データに更新に失敗しました");//Survey data failed to be updated
define("_QUESTIONDELETEDSUCCESSFULLY","質問を削除しました");//Question deleted successfully
define("_THEQUESTIONWASSUCCESSFULLYMOVED","という質問を正常に移動");//The question moved successfully
define("_THEQUESTIONFAILEDTOBEMOVED","の質問に失敗しましたに移動");//The question failed to be moved
define("_NOSUCHOPERATION","そのような操作");//No such operation
define("_SHOWDATAFORUNIT","詳細データの単位を");//Show data for unit
define("_ALLUNITS","すべてのユニット");//All units
define("_YOUMUSTUPLOADFILE","を示唆するにファイルをアップロードする必要があります。");//You must indicate a file to upload
define("_TOTALINSERTED","完全に挿入");//Totally inserted
define("_PERSONALOPTIONSFOR","個人用のオプションをユーザ");//Personal options for user
define("_LESSONOPTIONSFOR","のオプションを教訓");//Options for lesson
define("_NEWLESSONOPTIONS","新しいレッスンオプション");//New lesson options
define("_ROLES","ユーザーの種類");//User types
define("_TYPENAME","タイプ名");//Type name
define("_UPDATEUSERTYPEFOR","従業員の種類を更新プログラム");//Update user type for
define("_SYSTEMANNOUNCEMENTS","システムのお知らせ");//System announcements
define("_CREATEUNIT","作成単位");//Create unit
define("_DONETIMES","回完了");//Times completed
define("_QUESTIONSTATISTICS","質問統計");//Question statistics
define("_ADDQUESTIONOFTYPE","質問のタイプを追加");//Add question of type
define("_NOSYSTEMANNOUNCEMENTSPOSTED","システムアナウンス投稿");//No system announcements posted
define("_DURATIONINMINUTES","所要時間を分単位で");//Duration in minutes
define("_ADDCALENDAR","カレンダーにイベントを追加");//Add calendar event
define("_EVENTS","イベント");//events
define("_NOEVENTSPLANNED","イベントの予定はありません。");//There are no events planned
define("_UNITOPERATIONS","単位操作");//Unit operations
define("_LESSONINFORMATION","レッスンの情報");//Lesson information
define("_GENERALDESCRIPTION","一般的な説明");//General description
define("_OBJECTIVES","目標");//Objectives
define("_OTHERINFO","その他の情報");//Other information
define("_ASSESSMENT","査定");//Assessment
define("_RESOURCES","リソース");//Resources
define("_LESSONTOPICS","レッスンのトピック");//Lesson topics
define("_NODESCRIPTIONSET","頂ける説明書がセットにはこのレッスン");//There is no description set for this lesson
define("_HASINVALIDEMAILADDRESS","電子メールアドレスが無効です");//has invalid email address
define("_SUCCESFULLYADDEDDIRECTION","正常に追加されましたカテゴリ");//Succesfully added category
define("_SUCCESFULLYUPDATEDDIRECTION","正常に更新さカテゴリ");//Succesfully updated category
define("_LESSONRULES","レッスンのルール");//Lesson rules
define("_BASEDONTERM","に基づいて用語");//Based on term
define("_HASNOTSEENTHEUNIT","見ていないの単位");//Has not seen the unit
define("_HASNOTPASSEDTHETEST","テストが完了していない");//Has not completed the test
define("_ALWAYS","常に");//Always
define("_WITHNAME","お名前");//With name
define("_ANDSCOREGREATEROREQUAL","とによるスコアより大きいか等しい");//And score greater or equal to
define("_INVALIDRULE","無効なルールのタイプ");//Invalid rule type
define("_INVALIDSCORE","無効なスコア");//Invalid score
define("_SUCCESFULLYUPDATEDRULE","succefully更新済みのルール");//Succefully updated rule
define("_SUCCESFULLYINSERTEDRULE","succefully挿入規則");//Succefully inserted rule
define("_ADDRULE","追加ルール");//Add rule
define("_RULEDELETED","ルールを削除しました");//Rule deleted successfully
define("_NEWSURVEYPUBLISHED","調査：");//Survey:
define("_DOSURVEY","調査には、");//Do the survey
define("_THANKYOU","ありがとうございました");//Thank you
define("_THISEMAIL","この電子メールに");//This email
define("_CONTAINSINFORMATIONABOUTYOURACCOUNTINTHEPLATFORM","お客様のアカウントに関する情報が含まれ、プラットフォーム");//contains information about your account in the platform
define("_SURVEYPUBLISHEDSUCCESSFULLY","調査で公開されました。");//Survey published sucessfully
define("_STARTSURVEY","スタート]ボタンを調査");//Start survey
define("_SURVEYSUBMISSIONSUCCESSFUL","正常に提出した調査");//Survey submitted successfully
define("_YOUCANNOTACCESSTHISPAGE","このページにアクセスすることはできません。");//You cannot access this page
define("_NOCONTENTFOUND","コンテンツ");//No content
define("_EDITLESSONSDIRECTION","カテゴリのレッスン");//Category lessons
define("_EXTERNALLYSIGNUP","外部からの申し込み");//External signup
define("_EVENT","イベント");//Event
define("_EDITEVENT","編集イベント");//Edit event
define("_DELETEEVENT","イベントを削除");//Delete event
define("_ADDEVENT","カートイベント");//Add event
define("_SUCCESFULLYADDEDEVENT","正常に追加されましたイベント");//Succesfully added event
define("_SUCCESFULLYUPDATEDEDEVENT","正常に更新さイベント");//Succesfully updated event
define("_SUCCESFULLYDELETEDEVENT","正常に削除さイベント");//Succesfully deleted event
define("_SHOWALLEVENTS","詳細すべてのイベント");//Show all events
define("_NOEVENTSPLANNEDTHISWEEK","今週のイベント予定はありません。");//There are no events planned this week
define("_NOEVENTSPLANNEDTHISMONTH","今月のイベント予定はありません。");//There are no events planned this month
define("_NOEVENTSPLANNEDTODAY","この日のイベント予定はありません。");//There are no events planned this day
define("_SHOWDAYEVENTS","詳細この日のイベント");//Show this day&#039;s events
define("_SHOWWEEKEVENTS","詳細は今週のイベント");//Show this week&#039;s events
define("_SHOWMONTHEVENTS","詳細は今月のイベント");//Show this month&#039;s events
define("_SUBTITLE","字幕");//Subtitle
define("_SURVEYSTATISTICS","調査報告書");//Survey reports
define("_PROJECT","プロジェクト");//Project
define("_DEADLINE","締め切り");//Deadline
define("_ADDPROJECT","プロジェクトの追加");//Add project
define("_PROJECTCREATEDSUCCESSFULLY","プロジェクトを作成しました");//Project created successfully
define("_PROJECTUPDATEDSUCCESSFULLY","プロジェクトを更新しました");//Project updated successfully
define("_CREATOR","創作");//Creator
define("_EDITPROJECT","編集プロジェクト");//Edit project
define("_NOPROJECTS","このレッスンのプロジェクトはありません。");//There are no projects for this lesson
define("_SURVEYDONE","アンケート調査");//Survey done
define("_DONESURVEYUSERS","調査参加者");//Survey participants
define("_SURVEYPREVIEWFORUSER","調査のプレビューユーザー：");//Survey preview for user:
define("_QUESTIONSKIND","種の質問");//Questions types
define("_QUESTIONUPDATEDSUCCESSFULLY","質問を更新しました");//Question updated successfully
define("_QUESTIONFAILEDTOBEUPDATED","質問される更新プログラムに失敗しました");//Question failed to be update
define("_INVALIDPERCENTAGE","無効な割合");//Invalid percentage
define("_PASSEDALLUNITS","見られるすべてのユニット");//Seen all units
define("_PERCENTAGEUNITS","台の端数を見られる");//Seen a fraction of units
define("_SPECIFICUNIT","見られる、特定のユニット");//Seen a specific unit
define("_PASSEDALLTESTS","渡されたすべてのテスト");//Passed all tests
define("_SPECIFICTEST","渡される、特定のテスト");//Passed a specific test
define("_INVALIDCONDITION","無効な状態");//Invalid condition
define("_THEUSERMUSTHAVE","その生徒必要があります。");//The student must have
define("_UNITSPERCENTAGE","割合");//Percentage
define("_SUCCESFULLYADDEDCONDITION","正常に追加されました条件");//Succesfully added condition
define("_SUCCESFULLYUPDATEDCONDITION","正常に更新さ条件");//Succesfully updated condition
define("_SUCCESFULLYDELETEDCONDITION","正常に削除さ条件");//Succesfully deleted condition
define("_LESSONCONDITIONS","レッスンを完了条件");//Lesson completion conditions
define("_ADDCONDITION","追加条件");//Add condition
define("_CONDITION","条件");//Condition
define("_CONDITIONTYPE","条件の種類");//Condition type
define("_RELATIONTOOTHERS","関係を他の");//Relation to others
define("_SCROLLTOTOPOFPAGE","スクロールしてページのトップへ");//Scroll to top of page
define("_SCROLLTOBOTTOMOFPAGE","ページ下部までスクロールして");//Scroll to bottom of page
define("_NOUSERHAVEDONETHISSURVEYYET","従業員は、この調査の完了はまだありません");//No employee has done this survey yet
define("_SYSTEM","システム");//System
define("_EMAILCONFIGURATIONS","電子メールサーバーの設定");//E-mail server configuration
define("_SAWUNIT","単位として設定して完了");//Set the unit as completed
define("_NOTSAWUNIT","単位として設定するには完了する");//Set the unit as not completed
define("_CONDITIONSCOMPLETED","条件を完了");//Conditions completed
define("_OUTOF","アウトの");//out of
define("_LESSONPROGRESS","レッスン進捗状況");//Lesson progress
define("_YOUMUSTSEEUNIT","ユニットを参照する必要があります。");//You must see unit
define("_YOUMUSTSEEALLUNITS","すべてのユニットを参照する必要があります。");//You must see all units
define("_OFLESSONUNITS","ユニットのレッスン");//of lesson units
define("_YOUMUSTSEE","を参照する必要があります。");//You must see
define("_YOUMUSTCOMPLETEALLTESTSWITHSCORE","すべてのテストを完了する必要があります平均スコア");//You must complete all tests with mean score
define("_YOUMUSTCOMPLETETEST","完全なテストをする必要があります。");//You must complete test
define("_WITHSCORE","性によるスコア");//with score
define("_NOCONDITIONSSET","条件の設定がないこのレッスン");//There are no conditions set for this lesson
define("_CONDITIONS","条件");//conditions
define("_RESUMELESSON","レッスンを再開する");//Resume lesson
define("_STARTLESSON","スタート]ボタンを教訓");//Start lesson
define("_TRACKING","トラッキング");//Tracking
define("_FORMATCERTIFICATE","形式の証明書");//Format certificate
define("_TRAFFIC","トラフィック");//Traffic
define("_LESSONTRAFFIC","レッスンのトラフィック");//Lesson traffic
define("_EDITTEST","編集テスト");//Edit test
define("_EDITQUESTION","編集の質問");//Edit question
define("_CERTIFICATE","証明書");//Certificate
define("_SUCCESFULLYUPDATEDCERTIFICATE","正常に更新済みの証明書");//Succesfully updated certificate
define("_EDITCONDITION","編集条件");//Edit condition
define("_SMTPSERVERCONFIGURATIONS","SMTPサーバーの構成");//SMTP server Configuration
define("_SMTPSERVER","SMTPサーバー");//SMTP server
define("_SMTPPASSWORD","SMTPのパスワード");//SMTP password
define("_SMTPPORT","サーバーのSMTPポート");//Server SMTP port
define("_TOTALACCESS","トータルアクセス数を表示");//Total number of accesses
define("_ACCESSNUMBER","アクセス数を表示");//Number of accesses
define("_LESSONTRAFFICANALYSIS","レッスンのトラフィックの分析");//Analysis of Lesson&#039;s Traffic
define("_SETTINGS","設定");//Settings
define("_LESSONACCESS","多くのレッスン&#39;にアクセス");//Number of lessons&#039; accesses
define("_ACCESSPERLESSON","1レッスンアクセス数を表示");//Number of Accesses per Lesson
define("_NOFILESFOUNDDIGITALLIBRARY","任意のファイルを特定するには、デジタル図書館");//There aren&#039;t any files in the digital library
define("_BLANKFORUNLIMITED","空白のままで無制限に");//Leave blank for unlimited
define("_CERTIFICATES","証明書");//Certificates
define("_NOUSERDATAFOUND","従業員の進捗状況のデータが見つかりません");//No employee progress data found
define("_ISSUECERTIFICATE","問題の証明書");//Issue certificate
define("_LESSONFILES","レッスンファイル");//Lesson files
define("_TOTALACCESSTIME","トータルアクセス時間");//Total access time
define("_DEFAULTPAGE","デフォルトのページ");//Default page
define("_NEWPAGE","新しいページ");//New page
define("_UPDATEPAGES","更新プログラムのページ");//Update pages
define("_PAGECONTENT","ページのコンテンツ");//Page content
define("_UPDATEPAGE","更新プログラムのページ");//Update page
define("_TOTALSTATISTICS","総統計");//Total statistics
define("_LOGINS","ログイン");//Logins
define("_USENONE","使用なし");//Use none
define("_PAGEDELETED","ページを削除");//Page deleted
define("_AREYOUSUREYOUWANTTODELETEPAGE","してもよろしいですをまとめて削除するページですか？");//Are you sure you want to delete page?
define("_SUCCESFULLYADDEDPAGE","ページを正常に追加されました");//Page added successfully
define("_LESSONMAINPAGE","レッスンメインページ");//Lesson main page
define("_GOTOPROJECTS","トップにプロジェクト");//Go to projects
define("_ACCESSSTATISTICS","アクセス統計");//Access statistics
define("_ANALYTICLOG","ログ解析");//Analytic log
define("_SHOWANALYTICLOG","詳細分析ログ");//Show analytic log
define("_SHOWALLLESSONS","詳細すべてのレッスン");//Show all lessons
define("_CHATROOMDEACTIVATEDBYADMIN","チャットルームの管理者に無効にされ");//Chat room deactivated by administrator
define("_IPADDRESS","IPアドレス");//IP address
define("_YOUHAVEALREADYUPLOADEDAFILE","あなたは既にアップロードするファイル");//You have uploaded a file
define("_FILEDELETEDSUCCESSFULLY","ファイルを削除しました");//File deleted successfully
define("_GRADE","等級");//Grade
define("_PROFESSORCOMMENTS","教授のコメント");//Professor comments
define("_DEADLINEPASSEDYOUCANNOLONGERUPLOADFILES","締め切りが過ぎています。もはやファイルをアップロードすることができます。");//The deadline has passed. You can no longer upload files.
define("_UPLOADEDFILE","アップロードされたファイル");//Uploaded file
define("_CMS","外部のウェブページ");//External pages
define("_YOUMAYNOTSIGNUPCONTACTADMINISTRATOR","サインアップすることはできません;お問い合わせは、システム管理者");//You may not sign up; contact the system administrator
define("_OPERATIONCOMPLETEDSUCCESFULLY","操作が正常に完了した");//Operation completed successfully
define("_REMOVECHOICE","削除の選択");//Remove choice
define("_SURVEYDISABLEDSUCCESSFULLY","調査無効になって正常に");//Survey disabled successfully
define("_SURVEYENABLEDSUCCESSFULLY","調査有効になって正常に");//Survey enabled successfully
define("_SURVEYSUBMIT","提出調査");//Submit survey
define("_ROWSPERPAGE","1ページの行");//Rows per page
define("_FILTER","フィルタ");//Filter
define("_OF","の");//of
define("_SENDALSOVIAEMAIL","電子メールで招待状を送る");//Send invitation via e-mail
define("_STYLE","スタイル");//Style
define("_MENU","メニュー");//Menu
define("_SELECTION","セレクション");//Selection
define("_SMTPCONFIGURATIONARECORRECT","SMTPサーバーの構成が正しいか");//The configurations of the Smtp server are correct
define("_SMTPCONFIGURATIONERROR","中にエラーが発生SMTPサーバーの構成管理者までご連絡");//There is an error with the configurations please contact Smtp server administrator
define("_ADDNEWFIELD","新しいフィールドを追加");//Add new field
define("_FIELDCREATED","のフィールドが作成さ");//The field was created
define("_FIELDUPDATED","のフィールドが更新さ");//The field was updated
define("_LESSONSCORE","レッスンによるスコア");//Lesson score
define("_COMPLETED","完了");//Completed
define("_NOTCOMPLETED","未完成");//Not completed
define("_CONDITIONSMET","条件を満たし、現在承認待ち");//Conditions met and awaiting approval
define("_STUDENTSTATUSCHANGED","学生のレッスンを正常にステータスが変更されました");//Student lesson status changed successfully
define("_MUSTBENUMERIC","数値しなければならない");//Must be numeric
define("_DEFAULTCERTIFICATE","eラーニングプラットフォーム組織efront user_nameの証明が＃ ＃ ＃ ＃は正常に完了user_surnameグレード＃ ＃ ＃ course_nameこの証明書が発行さグレード＃ ＃日付＃");//eFront elearning platform organization certifies that \n\n #user_name# #user_surname# \n\n has successfully completed \n #course_name# \n with grade \n\n #grade# \n\nThis certificate was issued on #date#
define("_NOQUESTIONSTOCORRECT","質問はありませんを修正するには");//There are no questions to correct
define("_RESTTESTSCORE","スコアは、残りのテスト");//Score at the remaining of the test
define("_CORRECTQUESTION","正しい質問");//Correct question
define("_FILEMANAGER","ファイルマネージャ");//File manager
define("_NOFILESFOUND","ファイルが見つかりました");//No files found
define("_LASTMODIFIED","最終更新日");//Last modified
define("_KB","KBの");//KB
define("_UPONELEVEL","1つ上のレベル");//Up one level
define("_DOWNLOADFILE","ダウンロードファイル");//Download file
define("_ZIPANDDOWNLOAD","圧縮ファイルをダウンロード");//Compress file and download
define("_COMPRESSTOZIP","をzip形式で圧縮");//Compress to zip
define("_SELECT","選択");//Select
define("_WITHSELECTEDFILES","選択したファイルを");//With selected files
define("_UNCOMPRESS","解凍");//Uncompress
define("_UNZIPFILE","解凍したファイル");//Unzip file
define("_OVERWRITEFILESWITHSAMENAME","同じ名前のファイルを上書きする");//Overwrite files with the same name
define("_UPLOAD","アップロード");//Upload
define("_SUCCESFULLYCREATEDFOLDER","フォルダを作成しました");//Folder created successfully
define("_CANNOTDELETEFILE","ファイルを削除することはできません");//Cannot delete file
define("_FILEWILLUNZIPINFOLDERWITHSAMENAME","非圧縮されるのは、フォルダ内のファイルと同じ名前");//The file will be uncompressed in a folder with the same name
define("_FILEALREADYEXISTS","ファイルが既に存在");//File already exists
define("_ROOTDIR","ルートフォルダ");//Root folder
define("_GOTOCORRECTQUESTIONS","質問正しいページに行く");//Go to questions correct page
define("_THEREARE","には、");//There are
define("_YOUCANNOTACCESSTHISLESSONORITDOESNOTEXIST","このレッスンのいずれかにアクセスすることはできませんか、またはこのレッスンは存在しません");//Either you may not access this lesson, or this lesson does not exist
define("_SHOWSIDEBAR","詳細サイドバー");//Show sidebar
define("_HIDESIDEBAR","サイドバーを非表示");//Hide sidebar
define("_YOURPROJECTSCOREIS","お客様によるスコア");//Your score
define("_USERSEXPORTUSINGCSVFORMATCOMMA","従業員のデータを使用してCSV形式でエクスポート（分離性\" 、 \" ）");//Export employees data using csv format (separated with &quot;,&quot;)
define("_USERSEXPORTUSINGCSVFORMATQM","従業員のデータを使用してCSV形式でエクスポートする（区切りに\" ; \" ）");//Export employees data using csv format (separated with &quot;;&quot;)
define("_SHOWGIVENANSWERS","詳細与えられた回答");//Show given answers
define("_SHOWRIGHTANSWERS","詳細正しい答え");//Show correct answers
define("_COULDNOTBESEND","送信できませんでした");//Could not be sent
define("_ENVIRONMENTALCHECK","環境チェック");//Environmental check
define("_REPAIRTREE","復元カテゴリ");//Restore tree
define("_RULEPROPERTIES","ルールのプロパティ");//Rule properties
define("_CONDITIONPROPERTIES","条件のプロパティ");//Condition properties
define("_ORPHANLESSONFOLDERSCHECK","孤児のレッスンフォルダの検索]チェック");//Orphan lesson folders check
define("_LESSONSWITHOUTFOLDERSCHECK","レッスンでフォルダの検索]チェック");//Lessons without folders check
define("_FOLDERSWITHOUTALESSONASSOCIATED","は、次のフォルダに関連付けられた教訓はありません。");//The following folders do not have a lesson associated
define("_LESSONSWITHOUTAFOLDER","は、次のレッスンのフォルダはありません。");//The following lessons do not have a folder
define("_PROBLEM","問題");//Problem
define("_CLEANUP","清潔度アップ");//Clean up
define("_OK","ok");//OK
define("_PEMANENTLYDELETEFOLLOWINGFOLDERS","このアクションは、次のフォルダが永久に削除さ");//This action will permanently delete the following folders
define("_PEMANENTLYDELETEFOLLOWINGLESSONS","このアクションは、次のレッスンが永久に削除さ");//This action will permanently delete the following lessons
define("_CREATEFOLLOWINGLESSONFOLDERS","このアクションは、次のフォルダが作成さレッスン");//This action will create folders for the following lessons
define("_AREYOUSURE","してもよろしいですか？");//Are you sure?
define("_CHECKAGAIN","確認してください");//Check again
define("_GENERICQUERIES","汎用的なクエリ");//Generic queries
define("_SENDINFOVIAEMAIL","電子メールアカウントのログイン情報を送る");//Send login information in email account
define("_NOONEHASBEENASSIGNEDTHISPROJECT","このプロジェクトに割り当てられているすべての学生されていない");//This project has not been assigned to any student
define("_PROJECTINFO","プロジェクト情報");//Project information
define("_ANNOUNCEMENTGO","アナウンスのページに行く");//Go to announcements page
define("_PROJECTAVERAGESCOREFORLESSON","平均スコアはレッスンのプロジェクト");//Average score for lesson&#039;s projects
define("_NEWPOLL","新しい投票");//New poll
define("_NOBOOKMARKSFOUND","のブックマークが見つかりました");//No bookmarks found
define("_FOLDERSTATISTICS","フォルダの統計情報");//Folder statistics
define("_DROPAUNITTOCOPY","ユニットをドロップすると、指定した位置にコピーすることが");//Drop a unit to copy it to the designated position
define("_DRAGAUNITTOCOPY","ユニットをドラッグしてコピーすること");//Drag the unit to copy it
define("_ERROR","エラーが発生");//Error
define("_ERRORUPLOADINGFILE","ファイルのアップロードにエラーが発生");//Error uploading file
define("_EDITANNOUNCEMENT","編集発表");//Edit announcement
define("_ANNOUNCEMENT","アナウンス");//Announcement
define("_THEFOLLOWINGFOLDERSCOULDNOTBEDELETED","は、次のフォルダを削除できませんでした");//The following folders could not be deleted
define("_SUCCESFULLYCLEANEDUPFOLDERS","フォルダを正常にクリーンアップ");//Succesfully cleaned up folders
define("_THEFOLLOWINGLESSONSCOULDNOTBEDELETED","は、次のレッスンを削除できませんでした");//The following lessons could not be deleted
define("_SUCCESFULLYCLEANEDUPLESSONS","正常にクリーンアップのレッスン");//Succesfully cleaned up lessons
define("_SUCCESFULLYCREATEDLESSONFOLDERS","レッスンのフォルダを作成しました");//Succesfully created lesson folders
define("_THEFOLLOWINGLESSONFOLDERSCOULDNOTBECREATED","は、次のレッスンのフォルダを作成できませんでした");//The folders for the following lessons could not be created
define("_EDITCONTENT","コンテンツを編集");//Edit content
define("_NORMALSTATUS","正常な状態");//Normal status
define("_APPLICATIONPENDING","アプリケーション保留中です。プレス\"送信\"を確認する");//Application pending. Press &quot;Submit&quot to verify
define("_SUCCESS","成功");//Success
define("_WARNING","警告");//Warning
define("_DEFINITIONCOULDNOTBEINSERTED","で定義されて挿入できませんでした。");//Definition could not be inserted
define("_SUCCESFULLYUPDATEDDEFINITION","正常に更新さで定義されて");//Succesfully updated definition
define("_SUCCESFULLYDELETEDDEFINITION","正常に削除さで定義されて");//Succesfully deleted definition
define("_DEFINITIONCOULDNOTBEUPDATED","deinitionを更新できませんでした");//Deinition could not be updated
define("_SUBMITTERM","提出期間");//Submit term
define("_EDITDEFINITION","編集で定義されて");//Edit definition
define("_NOFOLDERSFOUNDTOCOPYTO","がないのフォルダをコピー/移動を");//There are no folders to copy/move to
define("_SCORMFILE","SCORMをファイル");//SCORM file
define("_SMILIES","スマイル");//Smilies
define("_SURVEYS","アンケート");//Surveys
define("_MODULES","モジュール");//Modules
define("_INSTALLMODULE","インストールモジュール");//Install module
define("_COULDNOTOPENZIPFILE","zipファイル開くことができませんでした");//The ZIP file could not be opened
define("_MODULEINFORMATION","モジュール情報");//Module information
define("_MODULESUCCESFULLYINSTALLED","このモジュールは、正常にインストールさ");//The module was successfully installed
define("_DESCRIPTIONFILECOULDNOTBEFOUND","このモジュールをインストールできませんでしたので、説明書ファイル、 module.xmlが見つかりませんでした。");//The module could not be installed because the description file, module.xml, was not found.
define("_SUCCESFULLYDELETEDMODULE","このモジュールは正常に削除さ");//The module was successfully deleted
define("_AUTHOR","著者");//Author
define("_VERSION","バージョン");//Version
define("_THEFIELDSINYOURCSVFILEMUSTCONTAINTHEFOLLOWINGFIELDS","csvファイルのフィールドにしては、次のフィールドを含む必要があります。");//The fields in your csv file must contain the following fields
define("_IFEMPTYNEWPASSWORD","赤のフィールドは必須項目です。与えられたパスワードがない場合は、最初のパスワードは同じに設定してログインしてください。");//Fields in red are mandatory. If there is no password given, the initial password will be set the same as the login.
define("_PLEASECHECKYOURCSVFILEFORMAT","確認してください。 csvファイルの形式をして");//Please check the format of your CSV file
define("_CERTIFICATEINSTRUCTIONS","＃ ＃ user_nameに使用するユーザーの名前、 ＃ ＃ user_surnameのユーザーの姓、 ＃ ＃ forコースのcourse_nameの名前を、 ＃グレード＃ ＃日付＃日付等級とします。");//In the template, use #organization# for organization&#039;s name, #user_name# for user&#039;s name, #user_surname# for user&#039;s surname, #course_name# for course&#039;s name, #grade# for grade and #date# for date.
define("_VOTES","投票");//Votes
define("_PERCENTAGE","割合");//Percentage
define("_CERTIFICATEISSUED","証明書の発行");//Certificate issued
define("_ISSUE","問題");//Issue
define("_PROBLEMISSUINGCERTIFICATE","証明書の発行できませんでした。");//The certificate could not be issued
define("_REVOKECERTIFICATE","証明書の失効");//Revoke certificate
define("_VIEWCERTIFICATE","証明書の表示");//View certificate
define("_CERTIFICATEREVOKED","証明書が失効し、正常に");//The certificate was revoked successfully
define("_PROBLEMREVOKINGCERTIFICATE","証明書の失効できませんでした。");//The certificate could not be revoked
define("_CHECKFORUPDATES","姉妹プロジェクトの更新プログラム");//Check for updates
define("_MODULEUPDATE","更新プログラムのモジュール");//Update module
define("_PENDING","未決定の");//Pending
define("_DEADLINEPASSED","締め切りが過ぎて");//The deadline has passed
define("_PROJECTFINISHED","このプロジェクトが完了したら");//The project is finished
define("_FILEUPLOADEDAWAITINGGRADE","は、ファイルがアップロードされていないが、プロジェクトの等級はまだありません。");//The file was uploaded, but the project has not been graded yet.
define("_LOCKDOWN","ロックダウン");//Lock down
define("_LOCKDOWNFROM","ロックダウンのシステムから");//Lock down system from
define("_LOCKDOWNTO","システムをロックダウン");//Lock down system to
define("_DISPLAYINDEXMESSAGE","通知システムの最初のページにメッセージを表示");//Display notification message to system first page
define("_SETANNOUNCEMENT","を設定するシステムを発表");//Set a system announcement
define("_NOLESSONSFOUND","いいえレッスンが見つかりました");//No lessons found
define("_SUCCESFULLYSETORDER","レッスンの順序を設定するコースは正常に");//The lessons order in course was set successfully 
define("_PROBLEMSETTINGORDER","このコースのレッスンの順序を設定できませんでした。");//The lessons order in the course could not be set
define("_ENABLEDAPI","XMLのAPIを有効になって");//Enabled XML API
define("_OLDUPGRADEBACKUPS","古いアップグレードのバックアップ");//Old upgrade backups
define("_CLEANUPALL","清潔度をすべて");//Clean up all
define("_THISOPERATIONALTERSYSTEM","この操作はデータやファイルを完全に削除するシステムです。本当に本当にそうですか？");//This operation will permanently delete data and files from the system. Are you absolutely sure?
define("_SMTPAUTH","SMTP認証");//SMTP authentication
define("_FLAG","フラグ");//Flag
define("_SETNORMALPRIORITY","通常の優先度を設定する");//Set priority to normal
define("_SETHIGHPRIORITY","高い優先度を設定する");//Set priority to high
define("_YOUMUSTSELECTMESSAGESTOFLAG","フラグのメッセージを選択する必要があります。");//You must select messages to flag
define("_SYSTEMEMAIL","システムの電子メール");//System email
define("_MAXFILESIZE","最大ファイルサイズ");//Maximum file size
define("_SUCCESFULLYUPDATECONFIGURATION","正常に更新された設定変数");//Succesfully updated configuration variables
define("_COULDNOTUPDATE","更新できませんでした。");//Could not update
define("_WITHVALUE","の値");//with value
define("_INVALIDFIELDDATAFORFIELD","無効なデータをフィールド");//Invalid data for field
define("_LDAPVARIABLES","LDAPサーバーの構成");//LDAP server configuration
define("_EMAILCOULDNOTBESENDBECAUSE","電子メールを送信できませんでした");//The email could not be sent
define("_EMAILSENDTOYOURADDRESS","電子メールは、お客様の電子メールアドレスに送信する");//The email was send to your email address
define("_YOUMUSTFIRSTCREATEDIRECTION","レッスンを作成するために、最初のカテゴリーを作成する必要があります");//In order to create a lesson, you must first create a category
define("_SAVEQUESTIONANDCREATENEW","別の質問を作成保存");//Save question and create another
define("_SAVEASNEWQUESTION","新しい質問を付けて保存");//Save as new question
define("_SUCCESFULLYUPDATEDPOLL","今回の調査は、正常に更新済み");//The poll was updated successfully
define("_YOUHAVESEENALLCONTENT","すべてのコンテンツが完了");//You have completed all content
define("_CONDITIONMET","条件満たさ");//Condition met
define("_CONDITIONNOTMET","条件が満たさ");//Condition not met
define("_OLDMODULES","古いモジュール");//Old modules
define("_PHPLDAPEXTENSIONISNOTLOADED","拡張子は、 PHPのLDAP読み込まれていない");//The PHP LDAP extension is not loaded
define("_LESSONCONDITIONSCOMPLETED","レッスンの完全な条件を満たしている。このレッスンを完了する必要がありますとして設定された教授");//You meet the lesson's complete conditions. This lesson needs to be set as completed by the professor
define("_LESSONCOMPLETE","レッスンを完了する");//Lesson completed
define("_CERTIFICATEISSUEDSUCCESFULLY","証明書は発行さ正常に");//Certificate issued successfully
define("_NOTITLE","いいえタイトル");//No title
define("_AUTOMATICCERTIFICATES","自動証明書");//Automatic certificates
define("_OFF","切れて");//off
define("_POLLDELETEDSUCCESSFULLY","今回の調査は削除しました");//The poll was deleted successfully
define("_POLLS","世論調査");//Polls
define("_TWOOPTIONSATMINIMUMREQUIRED","少なくとも2つのオプションが必要です。世論調査");//At minimum two different options are required for the poll
define("_POLL","世論調査");//Poll
define("_VOTE","投票");//Vote
define("_YOUHAVEALREADYVOTED","この世論調査を既に投票");//You have already voted for this poll
define("_SUCCESFULLYVOTED","あなたの投票されsubmited");//Your vote has been submited
define("_VIEWRESULTS","対象の結果");//View results
define("_TOTALVOTES","投票数合計");//Total votes
define("_SUBMITTEST","提出テスト");//Submit test
define("_RATEMUSTBEBETWEEN1100","の間に、 1から100までの範囲によるスコア必要があります。");//The score must range between 1 and 100
define("_NUMOFQUESTIONS","いくつかの質問を");//Number of questions
define("_TESTDURATION","テスト期間");//Test duration
define("_QUESTIONSARESHOWN","ご質問が表示さ");//Questions are shown
define("_YOUCANDOTHETEST","には、テストすることができます。");//You can do the test
define("_DONETIMESSOFAR","これまでのところ、このテストをしてしまったか");//So far you have done this test
define("_ALLTOGETHER","全部で");//All together
define("_ONEBYONEQUESTIONS","1つずつ");//One by one
define("_TIMES","回");//times
define("_LDAPACCOUNTPASSWORD","LDAPのアカウントのパスワード");//LDAP account password
define("_USELDAPACCOUNT","LDAPアカウントの資格情報を使用して、システムを使用するために");//Use your LDAP account credentials in order to use the system
define("_ONLYLDAPREGISTRATIONPERMITTED","ユーザ登録を使用して、有効なLDAPアカウントのみが許可さ");//Only registration using a valid LDAP account is permitted
define("_GENERALLYAVAILABLE","は一般的に利用できる");//is generally available
define("_DELETECONDITION","削除の条件");//Delete condition
define("_ADDFORUMPOSTONTHISUNIT","フォーラムのメッセージを投稿このユニット");//Post forum message for this unit
define("_AUTOCOMPLETE","自動補完");//Auto complete
define("_DUPLICATESARENOTALLOWED","使用することはできませんの2倍のレッスンで同じルール");//You can&#039;t use twice the same lesson in a rule
define("_TIMEINLESSON","時間のレッスン");//Time in lesson
define("_ACCOUNTACTIVATIONMAILSUBJECT","電子メールアカウントの活性化");//Account activation email
define("_YOUWILLRECEIVEMAILFORACCOUNTACTIVATION","お客様宛てに電子メールアカウントを有効に");//You will receive an email to activate your account
define("_ACCOUNTACTIVATIONMAILBODY","ようこそefront eラーニングプラットフォームです。アカウントを有効に以下リンクをご覧ください：");//Welcome to eFront eLearning platform. Follow link below to activate your account:
define("_ACCOUNTSUCCESSFULLYACTIVATED","お客様のアカウントは正常に活性化");//Your account was successfully activated
define("_SUCCESSFULLYINSERTEDVALUES","正常に挿入値");//Successfully inserted values
define("_NEWFORUM","新しいフォーラム");//New forum
define("_FORUMS","フォーラム");//Forums
define("_FORUMADDEDSUCCESSFULLY","フォーラム正常に追加されました");//Forum added succesfully
define("_FORUMUPDATEDSUCCESSFULLY","フォーラムを更新しました");//Forum updated succesfully
define("_ACCESSIBLEBYUSERSOFLESSON","の教訓");//For lesson
define("_FORUMDELETEDSUCCESSFULLY","フォーラムを削除しました");//Forum deleted succesfully
define("_ACCESSIBLEBY","アクセス");//Accessible by
define("_NEWFORUM","新しいフォーラム");//New forum
define("_ROOTUNIT","---ルートユニット----");//---Root unit----
define("_GENERICLESSONINFO","汎用的なレッスン情報をもっと見る");//Generic lesson info
define("_LOGRECORD","ログレコード");//Log record
define("_NOFORUMPOSTSYET","このフォーラムの投稿はありませんはまだありません");//There are no posts in this forum yet
define("_NOTOPICSFOUNDINTHISFORUM","このフォーラムのトピックはありません。");//There are no topics in this forum
define("_NOMESSAGESFOUNDINTHISTOPIC","このトピックのメッセージはない。");//There are no messages in this topic
define("_AVAILABLEFROM","から入手できる");//Available from
define("_SUCCESSFULLYADDEDPOLL","正常に追加されました世論調査");//Successfully added poll
define("_RECIPIENT","受信者");//Recipient
define("_SENDASEMAILALSO","また、電子メールを送信");//Send also as email
define("_NOSUBJECT","件名なし");//No subject
define("_THEMESSAGEWASNOTSENTASEMAIL","電子メールのメッセージが表示できませんでした。");//The message could not be emailed
define("_TOTALLOGINTIME","合計時間、システム");//Total time in system
if (defined('MODULE_HCD_INTERFACE') && MODULE_HCD_INTERFACE == 1) {
define("_THENEWFORMOFADDITIVELEARNING","eラーニングと人的資本の開発");//eLearning and Human Capital Development
define("_AUTOMATICUSERACTIVATION","自動従業員の活性化");//Automatic employee activation
define("_USERSEXPORT","輸出の従業員");//Export employees
define("_USERSIMPORT","インポートの従業員");//Import employees
define("_NEWUSERS","新しい従業員");//New employees
define("_USER","従業員");//Employee
define("_CHOOSEUSER","従業員の選択");//Select employee
define("_USERS","従業員");//Employees
define("_ALLSYSTEMUSERS","すべてのシステムの従業員");//All system employees
define("_USERSCONNECTEDTOSPECIFICCOURSE","従業員かかわってコース");//Employees involved with course
define("_USERSCONNECTEDTOSPECIFICLESSON","従業員かかわってレッスン");//Employees involved with lesson
define("_SPECIFICTYPEUSERS","特定の種類の従業員");//Specific type of employees
define("_USERTYPE","基本的な学習のタイプ");//Basic learner type
define("_ACTIVEUSER","アクティブな従業員");//Active employee
define("_USERDELETED","従業員が削除されました。");//Employee was deleted.
define("_THEUSER","従業員");//The employee
define("_CHOOSEUSERTODISCONNECT","従業員選択して接続を切断する");//Select a employee to disconnect
define("_LOGOUTUSER","ログアウト従業員");//Log out employee
define("_THEREARENOOTHERUSERSRIGHTNOWINTHISROOM","現在このチャットルームでの従業員");//No employee currently in this chat room
define("_USERSONLINE","従業員のオンライン");//Employees online
define("_ANDTHEMESSAGESOFUSER","とのメッセージの従業員");//And the messages of employee
define("_ALLUSERS","すべての従業員");//All employees
define("_INVALIDUSER","従業員の名前が無効です");//Invalid employee name
define("_REPLACEEXISTINGUSERS","重複する従業員に置き換えます");//Replace duplicate employees
define("_KEEPEXISTINGUSERS","重複する従業員の維持");//Keep duplicate employees
define("_NOOTHERUSERSONLINE","現在オンライン上の他の従業員");//No other employees currently online
define("_USERNAME","従業員名");//Employee name
define("_STATISTICSFORUSER","従業員のレポートを作成");//Reports for employee
define("_GENERALUSERINFO","総従業員の情報");//General employee information
define("_USERCOMMUNICATIONINFO","従業員の情報を通信");//Employee information on communication
define("_USERUSAGEINFO","従業員の情報をシステムの利用方法");//Employee information on system usage
define("_THEUSERHASNOTDONEANYTESTSINTHISLESSON","従業員のすべてのテストが完了し、この教訓");//The employee has not completed any tests in this lesson
define("_USERSTATISTICS","従業員の報告書");//Employee reports
define("_REPORTSFORUSER","従業員のレポート");//Reports for employee (New)
define("_OTHERUSERSINROOM","他の従業員での朝食");//Other employees in the room
define("_NOMESSAGESFOUNDFORTHISINTERVALANDUSER","のメッセージが見つかりました、指定した間隔で、ルームと従業員");//No messages found for the specified interval, room and employee
define("_INVITEUSERS","招待の従業員");//Invite employees
define("_SPECIFICUSER","特定の従業員");//Specific employee
define("_ALLACTIVESYSTEMUSERS","すべてのアクティブなシステムの従業員");//All active system employees
define("_WAITINGFORUSER","待機中の従業員");//Waiting for employee
define("_YOUHAVEINVITEDUSER","従業員のご招待");//You have invited employee
define("_DEARUSER","親愛なる従業員");//Dear employee
define("_ISVISIBLEFROMOTHERUSERS","すべての従業員に見えるからですか？");//Visible from any employee?
define("_CUSTOMIZEUSERSPROFILE","従業員のプロファイルをカスタマイズ");//Customize employee profile
define("_USERAVERAGESCOREFORLESSON","平均スコアのレッスンのテスト");//Average score for lesson&#039;s tests
define("_USERISONLINE","従業員がオンラインに");//The employee is online
define("_USERJUSTLOGGEDIN","従業員だけに記録さ");//The employee just logged in
define("_UPDATEUSERSTOLESSONS","従業員に割り当てるレッスン");//Assign employees to lesson
define("_EDITUSERSLESSON","ユーザのレッスン");//Lesson users
define("_NEWUSER","新しい従業員");//New employee
define("_UPDATEUSERS","更新プログラムの従業員");//Update employees
define("_EDITUSER","従業員の設定");//Employee settings
define("_EDITUSEREDIT","編集の従業員");//Edit employee (New)
define("_ADDUSERSTOSURVEY","従業員の調査を追加");//Add employees to the survey
define("_UPDATEUSERTYPES","更新プログラムの従業員の種類");//Update employee types
define("_EDITUSERTYPE","編集従業員のタイプ");//Edit employee type (New)
define("_OPTIONSUSERTYPEFOR","従業員のタイプのオプション");//Options for employee type (New)
define("_NEWUSERTYPE","新しい従業員のタイプ");//New employee type
define("_BASICUSERTYPE","基本的な従業員のタイプ");//Basic employee type
define("_AREYOUSUREYOUWANTTODELETEUSERTYPE","してもよろしいの従業員をまとめて削除するタイプですか？");//Are you sure you want to delete employee type?
define("_SUCCESFULLYUPDATEDUSERTYPE","従業員のタイプが更新されました");//Employee type was updated successfully
define("_SUCCESFULLYADDEDUSERTYPE","正常に従業員のタイプが追加されました。");//Employee type was added successfully
define("_USERSMANAGEMENT","従業員の管理");//Employees management
define("_AREYOUSUREYOUWANTTODELETEUSER","を削除してもよろしいの従業員したいですか？");//Are you sure you want to delete employee?
define("_USERTYPEDELETED","従業員のタイプ削除");//Employee type deleted
define("_EDITUSERSCOURSE","コースの従業員");//Course employees
define("_USERDEACTIVATED","従業員の無効化");//Employee deactivated
define("_USERACTIVATED","従業員の活性化");//Employee activated
define("_USERSKIND","従業員の種類");//Employee types
define("_USERTYPES","従業員の種類");//Employee types
define("_SMTPUSER","SMTPのログイン");//SMTP login
define("_USERCREATED","従業員の作成");//Employee created
define("_USERTRAFFIC","従業員のトラフィック");//Employee&#039;s traffic
define("_USERSPROGRESS","従業員のステータス");//Employees status
define("_THEUSERHASNOTCOMPLETEDTHELESSON","このレッスンを完了していない従業員はまだありません");//The employee has not completed this lesson yet
define("_MOSTACTIVEUSERS","最も活動的な従業員");//Most active employees
define("_5MOSTACTIVEUSERS","5最も活動的な従業員");//5 most active employees
define("_NOUSERFORTHISSURVEYYET","この調査の従業員はまだありません。");//No employees for this survey yet.
define("_SHOWALLUSERS","詳細すべての従業員");//Show all employees
define("_THEREARENOLESSONSDEFINEDFORTHEUSERLANGUAGE","レッスンはありませんが定義されて、従業員の言語");//There are no lessons defined for the employees&#39;s language
define("_VIEWUSERLESSONPROGRESS","生徒が進歩してレッスンを参照して");//View the student progress throughout the lesson
define("_USERCAPITAL","従業員");//Employee
define("_USERSDATA","インポート/エクスポートの従業員");//Import/Export employees
define("_ORPHANUSERFOLDERSCHECK","孤児従業員のフォルダの検索]チェック");//Orphan employee folders check
define("_USERSWITHOUTFOLDERSCHECK","従業員とフォルダの検索]チェック");//Employees without folders check
define("_FOLDERSWITHOUTAUSERASSOCIATED","は、次のフォルダを従業員に関連はありません。");//The following folders do not have a employee associated
define("_USERSWITHOUTAFOLDER","は、次の従業員のフォルダはありません。");//The following employees do not have a folder
define("_PEMANENTLYDELETEFOLLOWINGUSERS","このアクションは、次の従業員が永久に削除さ");//This action will permanently delete the following employees
define("_CREATEFOLLOWINGUSERFOLDERS","このアクションは、次の従業員のフォルダが作成さ");//This action will create folders for the following employees
define("_USERPROGRESS","従業員の進捗状況");//Employee progress
define("_LOGOUTUSERS","従業員のオンラインログアウト");//Log out employees online
define("_USERTRACKINGINFORMATION","従業員のトラッキング情報の詳細について");//Employee tracking information
define("_MAILUSERACTIVATION","従業員の活性化を電子メール");//Employee activation by email
define("_USERSMAYADDFORUMS","従業員の5月に追加フォーラム");//Employees may add forums
define("_NONEWAPPLICATIONS","新しい従業員のアプリケーションから");//No application from new employees
define("_EXPORTUSERSDATA","従業員のデータのエクスポート");//Export employees data
define("_IMPORTUSERSDATA","従業員のデータのインポート");//Import employees data
define("_THEUSERHASNOTBEENASSIGNEDANYPROJECT","いいえ、このプロジェクトは従業員に割り当てられている");//No project has been assigned to this employee
define("_SUCCESFULLYCLEANEDUPUSERS","正常にクリーンアップの従業員");//Succesfully cleaned up employees
define("_SUCCESFULLYCREATEDUSERFOLDERS","従業員のフォルダを正常に作成さ");//Succesfully created employee folders
define("_THEFOLLOWINGUSERFOLDERSCOULDNOTBECREATED","従業員は、次のフォルダを作成できませんでした。");//The following employee folders could not be created
define("_GROUP","従業員のグループ");//Employee group
define("_USERSINFO","従業員の情報をもっと見る");//Employees info
define("_PROFESSORSINFO","教授の情報をもっと見る");//Professors info
define("_EMPLOYEEWASASSIGNEDGROUP","従業員はグループに割り当てられている");//Employee was assigned to group
define("_EMPLOYEEWASRELEASEDFROMGROUP","グループの従業員がリリース");//Employee was released from group
define("_PROFESSORCAPITAL","教授");//Professor
define("_STUDENTROLE","従業員の役割");//Employee role
define("_PROFESSORROLE","教授の役割");//Professor role
} else {
define("_THENEWFORMOFADDITIVELEARNING","eラーニングと人的資本の開発");//Refreshing eLearning
define("_AUTOMATICUSERACTIVATION","自動従業員の活性化");//Automatic user activation
define("_USERSEXPORT","輸出の従業員");//Export users
define("_USERSIMPORT","インポートの従業員");//Import users
define("_NEWUSERS","新しい従業員");//New users
define("_USER","従業員");//User
define("_CHOOSEUSER","従業員の選択");//Select user
define("_USERS","従業員");//Users
define("_ALLSYSTEMUSERS","すべてのシステムの従業員");//All system users
define("_USERSCONNECTEDTOSPECIFICCOURSE","従業員かかわってコース");//Users involved with specific course
define("_USERSCONNECTEDTOSPECIFICLESSON","従業員かかわってレッスン");//Users involved with specific lesson
define("_SPECIFICTYPEUSERS","特定の種類の従業員");//Specific type of users
define("_USERTYPE","基本的な学習のタイプ");//User type
define("_ACTIVEUSER","アクティブな従業員");//Active user
define("_USERDELETED","従業員が削除されました。");//User deleted.
define("_THEUSER","従業員");//The user
define("_CHOOSEUSERTODISCONNECT","従業員選択して接続を切断する");//Select a user to disconnect
define("_LOGOUTUSER","ログアウト従業員");//Log out user
define("_THEREARENOOTHERUSERSRIGHTNOWINTHISROOM","現在このチャットルームでの従業員");//No user currently in this chat room
define("_USERSONLINE","従業員のオンライン");//Users online
define("_ANDTHEMESSAGESOFUSER","とのメッセージの従業員");//And the messages of user
define("_ALLUSERS","すべての従業員");//All users
define("_INVALIDUSER","従業員の名前が無効です");//Invalid user name
define("_REPLACEEXISTINGUSERS","重複する従業員に置き換えます");//Replace duplicate users
define("_KEEPEXISTINGUSERS","重複する従業員の維持");//Keep duplicate users
define("_NOOTHERUSERSONLINE","現在オンライン上の他の従業員");//No other users currently online
define("_USERNAME","従業員名");//User name
define("_STATISTICSFORUSER","従業員のレポートを作成");//Reports for user
define("_GENERALUSERINFO","総従業員の情報");//General user information
define("_USERCOMMUNICATIONINFO","従業員の情報を通信");//User information on communication
define("_USERUSAGEINFO","従業員の情報をシステムの利用方法");//User information on system usage
define("_THEUSERHASNOTDONEANYTESTSINTHISLESSON","従業員のすべてのテストが完了し、この教訓");//The user has not completed any tests in this lesson
define("_USERSTATISTICS","従業員の報告書");//User reports
define("_REPORTSFORUSER","ユーザーのレポート");//Reports for user (New)
define("_OTHERUSERSINROOM","他の従業員での朝食");//Other users in the room
define("_NOMESSAGESFOUNDFORTHISINTERVALANDUSER","のメッセージが見つかりました、指定した間隔で、ルームと従業員");//No messages found for the specified interval, room and user
define("_INVITEUSERS","招待の従業員");//Invite users
define("_SPECIFICUSER","特定の従業員");//Specific user
define("_ALLACTIVESYSTEMUSERS","すべてのアクティブなシステムの従業員");//All active system users
define("_WAITINGFORUSER","待機中の従業員");//Waiting for user
define("_YOUHAVEINVITEDUSER","従業員のご招待");//You have invited user
define("_DEARUSER","親愛なる従業員");//Dear user
define("_ISVISIBLEFROMOTHERUSERS","すべての従業員に見えるからですか？");//Visible from any user?
define("_CUSTOMIZEUSERSPROFILE","従業員のプロファイルをカスタマイズ");//Customize user profile
define("_USERISONLINE","従業員がオンラインに");//The user is online
define("_USERJUSTLOGGEDIN","従業員だけに記録さ");//The user just logged in
define("_UPDATEUSERSTOLESSONS","従業員に割り当てるレッスン");//Select lesson users
define("_EDITUSERSLESSON","ユーザのレッスン");//Lesson users
define("_NEWUSER","新しい従業員");//New user
define("_UPDATEUSERS","更新プログラムの従業員");//Update users
define("_EDITUSER","従業員の設定");//User settings
define("_EDITUSEREDIT","ユーザーの編集");//Edit user (New)
define("_ADDUSERSTOSURVEY","従業員の調査を追加");//Add users to the survey
define("_UPDATEUSERTYPES","更新プログラムの従業員の種類");//Update user types
define("_EDITUSERTYPE","ユーザーのタイプを編集する");//Edit user type (New)
define("_OPTIONSUSERTYPEFOR","ユーザーのタイプのオプション");//Options for user type (New)
define("_NEWUSERTYPE","新しい従業員のタイプ");//New user type
define("_BASICUSERTYPE","基本的な従業員のタイプ");//Basic user type
define("_AREYOUSUREYOUWANTTODELETEUSERTYPE","してもよろしいの従業員をまとめて削除するタイプですか？");//Are you sure you want to delete user type?
define("_SUCCESFULLYUPDATEDUSERTYPE","従業員のタイプが更新されました");//User type was updated successfully
define("_SUCCESFULLYADDEDUSERTYPE","正常に従業員のタイプが追加されました。");//User type was added successfully
define("_USERSMANAGEMENT","従業員の管理");//Users management
define("_AREYOUSUREYOUWANTTODELETEUSER","を削除してもよろしいの従業員したいですか？");//Are you sure you want to delete user?
define("_USERTYPEDELETED","従業員のタイプ削除");//User type deleted
define("_EDITUSERSCOURSE","コースの従業員");//Course users
define("_USERDEACTIVATED","従業員の無効化");//User deactivated
define("_USERACTIVATED","従業員の活性化");//User activated
define("_USERSKIND","従業員の種類");//User types
define("_USERTYPES","従業員の種類");//User types
define("_SMTPUSER","SMTPのログイン");//SMTP user
define("_USERCREATED","従業員の作成");//User created
define("_USERTRAFFIC","従業員のトラフィック");//User&#039;s traffic
define("_USERSPROGRESS","従業員のステータス");//Users status
define("_THEUSERHASNOTCOMPLETEDTHELESSON","このレッスンを完了していない従業員はまだありません");//The user has not completed this lesson yet
define("_MOSTACTIVEUSERS","最も活動的な従業員");//Most active users
define("_5MOSTACTIVEUSERS","5最も活動的な従業員");//5 most active users
define("_NOUSERFORTHISSURVEYYET","この調査の従業員はまだありません。");//No users for this survey yet.
define("_SHOWALLUSERS","詳細すべての従業員");//Show all users
define("_THEREARENOLESSONSDEFINEDFORTHEUSERLANGUAGE","レッスンはありませんが定義されて、従業員の言語");//There are no lessons defined for the users&#39;s language
define("_VIEWUSERLESSONPROGRESS","生徒が進歩してレッスンを参照して");//View the student progress throughout the lesson
define("_USERCAPITAL","従業員");//User
define("_USERSDATA","インポート/エクスポートの従業員");//Import/Export users
define("_ORPHANUSERFOLDERSCHECK","孤児従業員のフォルダの検索]チェック");//Orphan user folders check
define("_USERSWITHOUTFOLDERSCHECK","従業員とフォルダの検索]チェック");//Users without folders check
define("_FOLDERSWITHOUTAUSERASSOCIATED","は、次のフォルダを従業員に関連はありません。");//The following folders do not have a user associated
define("_USERSWITHOUTAFOLDER","は、次の従業員のフォルダはありません。");//The following users do not have a folder
define("_PEMANENTLYDELETEFOLLOWINGUSERS","このアクションは、次の従業員が永久に削除さ");//This action will permanently delete the following users
define("_CREATEFOLLOWINGUSERFOLDERS","このアクションは、次の従業員のフォルダが作成さ");//This action will create folders for the following users
define("_USERPROGRESS","従業員の進捗状況");//User progress
define("_LOGOUTUSERS","従業員のオンラインログアウト");//Log out users online
define("_USERTRACKINGINFORMATION","従業員のトラッキング情報の詳細について");//User tracking information
define("_MAILUSERACTIVATION","従業員の活性化を電子メール");//User activation by email
define("_USERSMAYADDFORUMS","従業員の5月に追加フォーラム");//Users may add forums
define("_NONEWAPPLICATIONS","新しい従業員のアプリケーションから");//No application from new users
define("_EXPORTUSERSDATA","従業員のデータのエクスポート");//Export users data
define("_IMPORTUSERSDATA","従業員のデータのインポート");//Import users data
define("_THEUSERHASNOTBEENASSIGNEDANYPROJECT","いいえ、このプロジェクトは従業員に割り当てられている");//No project has been assigned to this user
define("_SUCCESFULLYCLEANEDUPUSERS","正常にクリーンアップの従業員");//Succesfully cleaned up users
define("_SUCCESFULLYCREATEDUSERFOLDERS","従業員のフォルダを正常に作成さ");//Succesfully created user folders
define("_THEFOLLOWINGUSERFOLDERSCOULDNOTBECREATED","従業員は、次のフォルダを作成できませんでした。");//The following user folders could not be created
define("_GROUP","従業員のグループ");//User group
define("_USERSINFO","従業員の情報をもっと見る");//Users info
define("_PROFESSORSINFO","教授の情報をもっと見る");//Professors info
define("_EMPLOYEEWASASSIGNEDGROUP","従業員はグループに割り当てられている");//User was assigned to group
define("_EMPLOYEEWASRELEASEDFROMGROUP","グループの従業員がリリース");//User was released from group
define("_PROFESSORCAPITAL","教授");//Professor
define("_STUDENTROLE","従業員の役割");//Student role
define("_PROFESSORROLE","教授の役割");//Professor role
}
define("_COURSES","コース");//Courses
define("_COURSEDELETED","コースの削除");//Course deleted
define("_COURSEDEACTIVATED","コースの無効化");//Course deactivated
define("_COURSEACTIVATED","コースの活性化");//Course activated
define("_COURSENAME","コース名");//Course name
define("_COURSEUPDATED","コースの更新済み");//Course updated
define("_SUCCESFULLYCREATEDCOURSE","コースが正常に作成さ");//Course was created successfully
define("_COURSEOPTIONSFOR","コースのオプションを");//Options for course
define("_NEWCOURSEOPTIONS","新しいコースのオプション");//New course options
define("_EDITCOURSE","編集コース");//Edit course
define("_EDITLESSONSCOURSE","コースレッスン");//Course lessons
define("_NEWCOURSE","新しいコース");//New course
define("_UPDATECOURSES","更新プログラムのコース");//Update courses
define("_COURSE","コース");//Course
define("_COURSEONLY","排他的を通してコース");//Exclusively through course
define("_AREYOUSUREYOUWANTTODELETECOURSE","を削除してもよろしいですコースしたいですか？");//Are you sure you want to delete course?
define("_NOCOURSESFOUND","いいえコース定義されて");//No courses defined
define("_UPDATEEMPLOYEES","更新プログラムの従業員");//Update employees
define("_NEWJOB","新しい仕事を割り当てる");//Assign new job
define("_AREYOUSUREYOUWANTTOCANCELJOB","してもよろしいしたい、この従業員からこの仕事をキャンセルしています。");//Are you sure you want to cancel this employee from this job.
define("_AREYOUSUREYOUWANTTOFIREEMPLOYEE","火災をしてもよろしいですから、この会社の従業員ですか？");//Are you sure you want to fire this employee from the company?
define("_FIRE","火");//Fire
define("_WAGE","賃金");//Wage
define("_VATREGNUMBER","付加価値税reg.no.");//VAT Reg.No.
define("_HIREDON","採用する");//Hired on
define("_SUPERVISOR","スーパーバイザー");//Supervisor
define("_JOBDESCRIPTIONS","仕事の説明");//Job descriptions
define("_EMPLOYEERELEASEDFROMJOB","従業員の仕事から解放");//Employee released from job
define("_SKILLS","技術");//Skills
define("_SKILL","技術");//Skill
define("_SPECIFICATION","仕様");//Specification
define("_DETAILS","詳細");//Details
define("_PLACEMENTS","位置");//Placements
define("_JOBALREADYASSIGNED","選択配置は、すでにこの従業員に割り当てられている");//Selected placement is already assigned to this employee
define("_BRANCHNAME","支店名");//Branch name
define("_EMPLOYEEPOSITION","従業員の地位");//Employee position
define("_JOBDESCRIPTION","職務記述書");//Job description
define("_UPDATEBRANCHES","更新プログラムの枝");//Update branches
define("_NEWBRANCH","新しいブランチ");//New branch
define("_FATHERBRANCHNAME","父親支店");//Father branch
define("_BRANCHES","支店");//Branches
define("_BRANCHDELETED","枝削除");//Branch deleted
define("_AREYOUSUREYOUWANTTODISMISSTHEBRANCH","解任してもよろしいですが支店したいですか？");//Are you sure you want to dismiss that branch?
define("_COUNTRY","国");//Country
define("_TELEPHONE","電話");//Telephone
define("_BRANCHRECORD","枝の記録");//Branch record
define("_BRANCHDATAUPDATED","支店のデータ更新済み");//Branch data updated
define("_FATHERBRANCH","父親支店");//Father branch
define("_HCD","人的資本の開発");//Human Capital Development
define("_ORGANISATIONCHART","機関チャート");//Organisation chart
define("_CANDIDATES","候補者");//Candidates
define("_SUCCSSFULLYCREATEDBRANCH","枝が正常に作成さ");//Branch was successfully created
define("_ATBRANCH","先支店");// at branch 
define("_FATHERBRANCHCOULDNOTBESET","ターゲットの父枝が設定できないことは、それがこのブランチの下の階層に");//Target father branch could not be set, because it is inferior to this branch in the hierarchy
define("_JOBSASSIGNED","ジョブに割り当てられた");//Jobs assigned
define("_AREYOUSUREYOUWANTTOREMOVETHATSKILL","を選択してもよろしいのリストからスキルを削除することですか？");//Are you sure you want to remove that skill from the list?
define("_SKILLDATA","技能データ");//Skill data
define("_NEWSKILL","新しい技能");//New skill
define("_SKILLDESCRIPTION","技能説明書");//Skill description
define("_HAVINGSKILL","技能を持つ");// having the skill 
define("_EMPLOYEESWITHTHATSKILL","従業員に技能");//Employees with skill
define("_UPDATESKILLS","更新プログラムのスキル");//Update skills
define("_THISSKILLSELEMENTSCOULDNOTBEDELETED","このスキルを削除できませんでした");//This skill could not be deleted
define("_SKILLDATAUPDATED","技能説明書更新済み");//Skill description updated
define("_SKILLCOULDNOTBECREATED","技能を作成できませんでした。");//Skill could not be created
define("_SUCCESSFULLYCREATEDSKILL","技能を作成しました");//Skill created successfully
define("_SKILLDELETED","スキル削除");//Skill deleted
define("_NOEMPLOYEESPOSSESSSKILL","いいえ、この技能を持つ従業員");//No employees possess this skill
define("_NOEMPLOYEESWORKATBRANCH","このブランチで働く従業員は現在ない");//No employees currently work at this branch
define("_UPDATEJOBDESCRIPTIONS","更新プログラムの仕事の説明");//Update job descriptions
define("_NEWJOBDESCRIPTION","新しい仕事の説明");//New job description
define("_CURRENTLYEMPLOYEED","現在の雇用");//Currently employed
define("_VACANCIES","利用可能な位置");//Available placements
define("_AREYOUSUREYOUWANTTOREMOVETHATJOBDESCRIPTION","を削除してもよろしいですが仕事を説明したいですか？");//Are you sure you want to remove that job description?
define("_JOBDESCRIPTIONDATA","職務記述書データ");//Job description data
define("_HAVINGJOBDESCRIPTION","職務記述書を持つ");// having the job description 
define("_NOEMPLOYEESPOSSESSJOBDESCRIPTION" , "No employees are currently assigned to this job description");
define("_SUCCESSFULLYCREATEDJOBDESCRIPTION","職務記述書を作成しました");//Successfully created job description
define("_JOBDESCRIPTIONCOULDNOTBECREATED","職務記述書を作成できませんでした。");//Job description could not be created
define("_JOBDESCRIPTIONDATAUPDATED","職務記述書のデータが正常に更新済み");//Job description data were successfully updated
define("_JOBDESCRIPTIONDELETED","職務記述書削除");//Job description deleted
define("_THISJOBDESCRIPTIONSELEMENTSCOULDNOTBEDELETED","の職務記述書の要素を削除できませんでした");//The job description&#039;s elements could not be deleted
define("_EDITJOBDESCRIPTION","編集職務記述書");//Edit job description
define("_SKILLSREQUIRED","スキルが必要となります。");//Skills desired
define("_EMPLOYEESOFBRANCH","従業員の支店");//Employees of branch
define("_EMPLOYEESWITHSKILL","従業員に技能");//Employees with skill
define("_FILERECORD","ファイルレコード");//File record
define("_VIEW","視野");//View
define("_SORRYYOUDONOTHAVEPERMISSIONTOPERFORMTHISACTION","申し訳ありませんの許可する必要はありません。このアクションを実行する");//Sorry you do not have the permission to perform this action
define("_MOBILEPHONE","携帯電話");//Mobile phone
define("_EMPLOYEESDATASUCCESSFULLYUPDATED","従業員のデータは正常に更新さ");//Employee data successfully updated
define("_EMPLOYEESRECORDCOULDNOTBEUPDATED","従業員のレコードを更新できませんでした");//Employee record could not be updated
define("_NOPLACEMENTSASSIGNEDYET","割り当てられたの位置はまだありません");//No placements assigned yet
define("_BRANCHCOULDNOTBECREATED","枝を作成できませんでした。");//Branch could not be created
define("_NOSKILLSHAVEBEENREGISTERED","いいえスキルが登録されて");//No skills have been registered
define("_NOJOBDESCRIPTIONSHAVEBEENREGISTERED","仕事の説明が登録されてない");//No job descriptions have been registered
define("_PLACEMENTCOULDNOTBEASSIGNED","割り当てられた配置できませんでした。");//Placement could not be assigned
define("_NOSKILLSASSIGNED","いいえスキルに割り当てられた");//No skills assigned
define("_NOSKILLSREGISTEREDASPREREQUISITES","スキルの前提条件として登録されない");//No skills registered as prerequisites
define("_SATISFYANYCRITERIA","任意の基準を満たす");//Satisfy any criteria
define("_SATISFYALLCRITERIA","すべての基準を満たす");//Satisfy all criteria
define("_WORKINGATBRANCH","働いて支店");//Working at branch
define("_WITHJOBDESCRIPTION" ,"With job description");
define("_FINDEMPLOYEES","従業員数して下さい");//Find employees (New)
define("_WITHSKILL","と技能");//With skill
define("_EMPLOYEESFULFILLINGCRITERIA","従業員の基準を満たす");//Employees fulfilling the criteria
define("_NOEMPLOYEESFULFILLTHESPECIFIEDCRITERIA","指定した条件を満たすの従業員");//No employees fulfill the specified criteria
define("_ORGANIZATIONCHARTTREE","組織図のカテゴリ");//Organization chart tree
define("_ANYBRANCH","任意の枝");//Any branch
define("_ANYJOBDESCRIPTION","どんな仕事で説明書");//Any job description
define("_EXPORTVACANCIES","輸出求人情報");//Export vacancies
define("_NATIONALSERVICECOMPLETED","国家への奉仕");//National service
define("_DRIVINGLICENSE","運転免許証");//Driver license
define("_BANKACCOUNT","口座");//Account
define("_BANK","銀行");//Bank
define("_TAXOFFICE","税務署");//Tax office
define("_POLICEIDNUMBER","警察の番号");//Police id
define("_WORKPERMISSIONDATA","仕事の許可データ");//Work permission data
define("_WAYOFWORKING","作業として");//Working as
define("_EMPLOYMENTTYPE","employementのタイプ");//Employement type
define("_MARRIED","結婚");//Married
define("_SINGLE","単一の");//Single
define("_MARITALSTATUS","配偶者の有無");//Marital status
define("_FEMALE","女性");//Female
define("_MALE","男性");//Male
define("_GENDER","性");//Gender
define("_FATHERNAME","父名");//Father name
define("_MOTHERTONGUE","母国語");//Mother tongue
define("_NATIONALITY","国籍");//Nationality
define("_PARTTIME","パートタイム");//Part time
define("_FULLTIME","フルタイムで");//Full time
define("_BIRTHDAY","誕生日");//Birthday
define("_BIRTHPLACE","市の誕生");//City of birth
define("_BIRTHCOUNTRY","出生国");//Country of birth
define("_EMPLOYEES","従業員");//Employees
define("_NEWEMPLOYEE","新しい従業員");//New employee
define("_OFFICE","事務所");//Office
define("_COMPANYINTERNALPHONE","企業の内部電話で確認電話");//Company internal phone
define("_EMPLOYEECREATED","従業員を作成しました");//Employee created successfully
define("_EMPLOYEEDELETED","従業員の削除");//Employee deleted
define("_SKILLSOFFERED","技能提供");//Skills offered
define("_NOSKILLSOFFERED","いいえスキル提供");//No skills offered
define("_NOJOBDESCRIPTIONSSHAVEBEENREGISTERED","仕事の説明が登録されてない");//No job descriptions have been registered
define("_INSERTEDINTOTHESYSTEM","システムに挿入される");//Inserted into the system
define("_HIRED","雇わ");//Hired
define("_RAISEOF","の賃上げを");//Raise of
define("_EMPLOYEESNEWWAGEIS","新しい賃金は、従業員の");//The employee&#039;s new wage is
define("_DECREASEOF","減少した");//Decrease of
define("_EMPLOYEEWASASSIGNEDJOB","従業員は、割り当てられた仕事");//Employee was assigned job
define("_EMPLOYEEWASRELEASEDFROMDJOB","従業員の仕事がリリース");//Employee was released from job
define("_EMPLOYEEWASASSIGNEDSKILL","従業員のスキルに割り当てられた");//Employee was assigned skill
define("_WASRELEASEDFROMEMPLOYEE","従業員がリリース");//was released from employee
define("_EMPLOYEESSKILLSPECIFICATIONSFORSKILL","従業員のスキルの仕様を技能");//Employee&#039;s skill specifications for skill
define("_WERECHANGEDTO","変更された");//were changed to
define("_FIRED","解雇");//Fired
define("_NOHISTORYREGARDINGTHISEMPLOYEE","これについて従業員の履歴を記録");//No history regarding this employee recorded
define("_HISTORYOFEMPLOYEE","歴史の従業員");//History of employee
define("_HISTORY","履歴");//History
define("_NOANNOUNCEMENTSPOSTEDADMIN","掲載のお知らせ");//No announcements posted
define("_SEPARATEMULTIPLEUSERS","別の複数の受信者に;");//Separate multiple recipients with ;
define("_STARTTYPINGFORRELEVENTMATCHES","関連性の高いマッチを得るスタート]ボタンを入力する（すべてのタイプ％ ）");//Start typing to get relevant matches (Type % for all)
define("_ADVANCEDSEARCH","高度な検索オプション");//Advanced search options
define("_REGISTERADVANCEDSEARCHFIELDS","高度な検索フィールドを登録する");//Register advanced search fields
define("_EDITBRANCH","編集ブランチ");//Edit branch
define("_ASSIGNEMPLOYEES","従業員に割り当てる");//Assign employees
define("_ASSIGNEMPLOYEESTOBRANCH","支店の従業員を割り当てる");//Assign employees to branch 
define("_EDITSKILL","編集技能");//Edit skill
define("_ASSIGNSKILL","スキルを割り当てる");//Assign skill
define("_ASSIGNEMPLOYEESTHESKILL","従業員のスキルを割り当てる");//Assign employees the skill 
define("_NOBRANCHESHAVEBEENREGISTERED","いいえ枝が登録されて");//No branches have been registered
define("_ORGANIZATION","組織");//Organization
define("_SEARCHFOREMPLOYEE","検索の従業員[組織基準]");//Search for employee [Organization criteria]
define("_SUBFORUMS","サブフォーラム");//Subforums
define("_NOSUBFORUMSFOUND","サブフォーラムがないこのフォーラムで定義されて");//There are no subforums defined in this forum
define("_NONEWMESSAGELOCKED","すべての新しいメッセージを投稿することはできませんこのトピックまたはフォーラムがロックされているため");//You cannot post any new messages because this topic or forum is locked
define("_ACTIVITY","活動");//Activity
define("_ISVALID","有効な");//Valid
define("_LEFTON","左に");//Left on
define("_ADVANCED","高度な基準");//Advanced criteria
define("_MYSTUDENTS","私の生徒");//My students
define("_EMPLOYEE","従業員");//Employee
define("_NOBRANCHJOBSERROR","仕事の説明はこの枝が登録されて");//No job descriptions have been registered for this branch
define("_TESTSTATISTICS","検査報告書");//Tests reports
define("_CHOOSETEST","選択テスト");//Choose test
define("_USERPROFILE","ユーザープロファイル");//User profile
define("_VIEWBRANCHES","対象の枝");//View branches
define("_NOEMPLOYEESFOUND","の従業員は見つかりませんでした");//No employees were found
define("_SEARCHEMPLOYEE","検索の従業員");//Search employee
define("_ALLBRANCHES","すべての枝");//All branches
define("_ANSWERS","回答");//Answers
define("_GROUPDOESNOTEXIST","同グループは存在しません");//The group doesn&#039;t exist
define("_SUBBRANCHES","サブブランチ");//Sub-branches
define("_OFBRANCH","枝");// of branch 
define("_NEWSUBBRANCH","新しいサブブランチ");//New sub-branch
define("_SMTPTIMEOUT","SMTPのタイムアウト");//SMTP timeout
define("_ILLEGALPATH","違法なパス");//Illegal path
define("_FILEWASPARTIALLYUPLOADED","アップロードされたファイルが部分的にアップロードのみ");//The uploaded file was only partially uploaded
define("_NOFILEUPLOADED","いいえファイルがアップロードさ");//No file was uploaded
define("_NOTMPDIR","行方不明の一時フォルダをアップロードするシステムです。したがってphp.iniの設定を更新");//Missing a system upload temporary folder. Please update php.ini settings accordingly
define("_UPLOADCANTWRITE","ファイルをディスクの書き込みに失敗しました");//Failed to write file to disk
define("_UPLOADERREXTENSION","ファイルのアップロード拡張子を止められる");//File upload stopped by extension
define("_CANNOTCOPYFILE","このファイルにコピーすることはできません");//The file cannot be copied
define("_CANNOTMOVEFILE","そのファイルに移動することはできません。");//The file cannot be moved
define("_DIRECTORYDOESNOTEXIST","のディレクトリが存在しません");//The directory does not exist
define("_COULDNOTCREATEDIRECTORY","のディレクトリを作成できませんでした");//The directory could not be created
define("_CANNOTCOPYDIRECTORY","のディレクトリにコピーすることはできません");//The directory cannot be copied
define("_DIRECTORYALREADYEXISTS","のディレクトリが既に存在する");//The directory already exists
define("_AUTOASSIGNTONEWUSERS","新規ユーザーを自動的に割り当てられます。");//Automatically assign to new users
define("_CANNOTOPENCOMPRESSEDFILE","圧縮されたファイルをオープンすることはできません。");//The compressed file cannot be opened
define("_CHOOSEWHATTODELETE","中にシステムの初期化を削除するものを選択し");//Choose what to delete during system initialization
define("_PERIODS","期間");//Periods
define("_IMPORTLESSON","インポートのレッスン");//Import lesson
define("_EXPORTLESSON","輸出のレッスン");//Export lesson
define("_LESSONEXPORTEDSUCCESFULLY","レッスンを正常にエクスポート");//Lesson succesfully exported
define("_LESSONIMPORTEDSUCCESFULLY","レッスンを正常にインポート");//Lesson succesfully imported
define("_FILESIZEMUSTBESMALLERTHAN","そのファイルよりも小さい必要があります。");//The file must be smaller than
define("_PROBLEMIMPORTINGFILE","問題のファイルのインポート");//Problem importing file
define("_PAGE","ページ");//Page
define("_ACTIVE_PROJECTS","アクティブ");//Active
define("_INACTIVE_PROJECTS","非アクティブ");//Inactive
define("_TIMEREMAIN","とどまる");//Remain
define("_WEEKS","週");//weeks
define("_WEEKs","週間以内に");//week
define("_DAYS","日中");//days
define("_DAY","日");//Day
define("_EVALUATIONDATAUPDATED","評価データを更新しました");//Evaluation data updated successfully
define("_EVALUATION","評価");//Evaluation
define("_EVALUATIONOFEMPLOYEE","従業員の評価");//Evaluation of employee
define("_NEWEVALUATION","新しい評価");//New evaluation
define("_EVALUATIONCOMMENT","評価コメント");//Evaluation comment
define("_EVALUATIONDELETED","評価削除");//Evaluation deleted
define("_THEEVALUATIONCOULDNOTBEDELETED","の評価を削除できませんでした");//The evaluation could not be deleted
define("_SUCCESSFULLYCREATEDEVALUATION","正常に作成さ評価");//Successfully created evaluation
define("_EVALUATIONCOULDNOTBECREATED","評価を作成できませんでした。");//Evaluation could not be created
define("_AREYOUSUREYOUWANTTODELETEEVALUATION","を削除してもよろしいの評価したいですか？");//Are you sure you want to delete the evaluation?
define("_NOEVALUATIONSASSIGNEDYET","書かれたの評価はまだありません");//No evaluation written yet
define("_BRANCH","枝");//Branch
define("_PLACEMENT","配置");//Placement
define("_EVALUATIONS","評価");//Evaluations
define("_TRANSPORTMEANS","の交通手段");//Means of transport
define("_YOUCANNOTDELETESOMEELSESEVALUATION","評価することはできません。書かれた別のユーザーを削除する");//You cannot delete an evaluation written by another user
define("_YOUCANNOTEDITSOMEELSESEVALUATION","評価することはできません。書かれた別のユーザーが編集する");//You cannot edit an evaluation written by another user
define("_EMPLOYEEFORM","従業員のフォーム");//Employee form
define("_EMPLOYEEFORMPRINTPREVIEW","従業員のフォームを印刷プレビュー");//Employee form print preview
define("_PRINTPREVIEW","印刷プレビュー");//Print preview
define("_PRINTEMPLOYEEFORM","従業員のフォームを印刷する");//Print employee form
define("_PRINT","印刷");//Print
define("_NOSPECIFICJOB","特定の職務記述書");//No specific job description
define("_GROUPS","ユーザーグループ");//User groups
define("_NEWGROUP","新しいグループ");//New group
define("_NOGROUPSDEFINED","のグループに定義されて");//No groups defined
define("_UPDATEGROUPS","更新プログラムのグループ");//Update groups
define("_GROUPDEACTIVATED","同グループは無効に");//The group was deactivated
define("_GROUPACTIVATED","同グループは、活性化");//The group was activated
define("_EDITGROUP","編集グループ");//Edit group
define("_UPDATEGROUP","更新プログラムのグループ");//Update group
define("_SUCCESFULLYADDEDGROUP","同グループは、正常に追加されました");//The group was succesfully added
define("_AREYOUSUREYOUWANTTODELETEGROUP","してもよろしいグループを削除するにしたいですか？");//Are you sure you want to delete the group?
define("_GROUPDELETED","同グループが削除さ");//The group was deleted
define("_GROUPFILTER","グループフィルタ");//Group filter
define("_NOUSERSFOUND","のユーザーがどこが見つかりました");//No users where found
define("_SEPARATEALTERNATIVESEXAMPLE","正しい答えを別の代替| 、例えば：ブルー|ブラック|ホワイト");//Separate alternative correct answers with |, for example: Blue|Black|White
define("_CREATERANODOMTEST","ランダムなテストを作成");//Create random test
define("_USING","を使用して");//Using
define("_EASY","簡単な");//Easy
define("_HARD","辛い");//Hard
define("_LOCALESETTINGS","ロケール設定");//Locale settings
define("_CURRENCY","通貨");//Currency
define("_DECIMALPOINT","小数点");//Decimal point
define("_THOUSANDSSEPARATOR","数千区切り");//Thousands separator
define("_DATEFORMAT","日付のフォーマット");//Date format
define("_SPECIFICLOCALE","特定のロケール");//Specific locale
define("_LOCATION","場所");//Location
define("_TIMEZONE","タイムゾーン");//Time zone
define("_INVALIDRECIPIENT","無効な受信者");//Invalid recipient
define("_NOBRANCHSELECTED","いいえ枝が選択さ");//No branch was selected
define("_AREYOUSUREYOUWANTTODELETEPROJECT","してもよろしい、このプロジェクトをまとめて削除することですか？");//Are you sure that you want to delete this project?
define("_TIMESDONE","回行わ");//Times done
define("_HASLEFT","左");//Left
define("_EMPLOYEESINGROUP","従業員のグループ");//Employees of group
define("_ERRORRESTORINGFILE","復元中に問題やってき");//A problem came up during restore
define("_DATABASEONLY","データベースのみ");//Database only
define("_ALLDATABACKUP","すべてのデータのバックアップ");//All data backup
define("_LESSONDIRECTORYCANNOTBCREATED","ここでの教訓ディレクトリを作成できませんでした");//The lesson directory could not be created
define("_YOUHAVENOTCOMPLETEDTHEFOLLOWINGQUESTIONS","質問が完了していません");//You have not completed questions
define("_AREYOUSUREYOUWANTTOSUBMITTEST","してもよろしい提出してテストをしたいですか？");//Are you sure you want to submit the test?
define("_JOBANALYTICALDESCRIPTION","詳細な説明");//Detailed description
define("_INCLUDESUBBRANCHES","含まれてsubbranches");//Include subbranches
define("_PDFFORMAT","PDF形式");//PDF format
define("_XLSFORMAT","Excel形式");//EXCEL format
define("_ATTENDING","出席");//Attending
define("_USERAVERAGESCOREFORTESTS","平均スコアのレッスンのテスト");//Average score for lesson&#039;s tests
define("_PROJECTSCOMPRESSED","プロジェクトファイルをダウンロード");//Download project files
define("_EDUCATIONALROLE","教育の役割");//Educational role
define("_ORGANIZATIONALROLE","組織の役割");//Organizational role
define("_TYPEOFUSER","ユーザーのタイプ");//User type
define("_MESSAGEBODY","メッセージの本文");//Message body
define("_ONLYRECIPIENTSDEFINEDBELOW","受信者の下で定義されたフィールドのみ");//Only recipients defined in the field below
define("_NORECIPIENTSHAVEBEENSELECTED","の受信者が選ば");//No recipients have been selected
define("_NORECIPIENTSHAVEBEENFOUND","受信者が発見されてない");//No recipients have been found
define("_CHANGELESSON","変更のレッスン");//Change lesson
define("_HOME","家");//Home
define("_FFROM","〜から");//from
define("_CALENDARTYPE","カレンダーのタイプ");//Calendar type
define("_ORGANIZATIONPROFILE","組織のプロフィール");//Organization profile
define("_CURRENTLESSON","現在のレッスン");//Current lesson
define("_SUBMITANDADDANOTHER","別の提出を追加");//Submit and add another
define("_EDUCATIONAL","教育");//Educational
define("_PAYPALTITLE","ペイパル");//Paypal
define("_PAYPALCONFIGURATIONPANEL","ペイパルの設定パネル");//Paypal configuration panel
define("_PAYPALMYTRANSACTIONS","マイ取引");//My transactions
define("_PAYPALTRANSACTION","トランザクション");//Transaction
define("_PAYPALCONFIGURATION","構成");//Configuration
define("_PAYPALBUSINESSMAIL","PayPalのビジネスの住所");//Paypal business address
define("_PAYPALBUSINESSMAILPLZ","PayPalのビジネスの住所記入して");//Fill in the Paypal business address
define("_PAYPALMAILSTUDENTS","通知の学生");//Inform students
define("_PAYPALMAILPROFESSORS","通知教授");//Inform professors
define("_PAYPALMAILADMINS","情報管理者");//Inform admins
define("_PAYPALORDERPREVIEW","プレビュー注文");//Preview order
define("_PAYPALFINALPRICE","最終価格");//Final price
define("_PAYPALPAYNOW","今すぐ支払うとペイパル");//Pay now with Paypal
define("_PAYPALNOCONFIGURATION","このサービスを使用することはできませんので、正しく構成されています。");//You can not use this service because its not configured properly.
define("_PAYPALORDERPROCESSING","お客様のご注文されてPayPalの処理をします。");//Your order is being processing through Paypal.
define("_PAYPALORDERPROCESSINGERROR","お客様のご注文を中にエラーが発生します。");//There was an error with your order.
define("_PAYPALORDERSSUCCESS","終了");//Finished
define("_PAYPALORDERSNOSUCCESS","終えていない");//Not-Finished
define("_PAYPALTABLEPRICE","量");//Amount
define("_PAYPALITEMCODE","コード");//Code
define("_PAYPALTABLEDATESUBMIT","注文した日");//Order date
define("_PAYPALTABLEDATEPAYPAL","支払期日");//Payment date
define("_PAYPALTRANSACTIONCODE","トランザクションコード");//Transaction code
define("_PAYPALTABLEUSER","ユーザ");//User
define("_PAYPALTABLESTATUS","お支払いのステータス");//Payment status
define("_PAYPALTABLELESSONS","レッスン");//Lessons
define("_PAYPALORDERINFO","トランザクションの詳細");//Transaction details
define("_PAYPALCUSTOMERINFO","お客様の情報");//Customer&#039;s information
define("_PAYPALITEMSINFO","商品の情報");//Items information
define("_PAYPALPURCHASEORDER","購入注文");//Purchase order
define("_PAYPALPURCHASEORDERFOR","支払いを");//Payment to
define("_ADDTOCART","カートに入れる");//Add to cart
define("_REMOVEFROMCART","ショッピングカートから削除");//Remove from cart
define("_REMOVEALLFROMCART","すべて削除から入れる");//Remove all from cart
define("_CART","ショッピングカート");//Shopping cart
define("_NOCART","のショッピングカートは空に");//The cart is empty
define("_FREEOFCHARGE","自由な");//Free
define("_LOGINFIRST","最初にログインを進めて購入依頼");//Log in first to proceed purchase
define("_RESULTS","結果");//results
define("_RESULT","結果");//result
define("_PAYPALORDERSUCCESS","トランザクションが正常に完了した");//The transaction completed successfully
define("_PAYPALORDERFAILURE","中にエラーが発生するトランザクション");//There was an error with the transaction
define("_PAYPALFREEORDERSUCCESS","ユーザ登録が正常に終了したレッスン");//Lessons registration finished successfully
define("_FREEREGISTRATION","無料のユーザ登録");//Free registration
define("_VIEWDIRECTORY","詳細レッスン/コースカタログ");//Show lesson/courses catalog
define("_VIEWDIRECTORYYESAFTERLOGIN","はい（ログインした後にのみ）");//Yes (only after login)
define("_VIEWDIRECTORYYESONLOGIN","はい（上のログインページとログインした後）");//Yes (on login page and after login)
define("_VIEWDIRECTORYNO","いいえ");//No
define("_VIEWDIRECTORYDISABLED","この瞬間calatogが非アクティブにする");//The calatog is inactive this moment
define("_INTERFACEVIEW","インターフェイスのインデックスページを選択して");//Select the interface of index page
define("_INTERFACEVIEWSIMPLE","単純な");//Simple
define("_INTERFACEVIEWEXTENDED","拡張");//Extended
define("_PAYPALUSE","ペイパルの使用");//Payments through Paypal
define("_DIRECTORY","ディレクトリ");//Directory
define("_LESSONSDIRECTORY","コースカタログ");//Course catalog
define("_ASSOCIATEDLESSONS","関連付けられた教訓");//Associated lessons
define("_APPLYTOALLDESCRIPTIONSWITHDESCRIPTION","適用されるすべてのジョブを説明：");//Apply to all jobs with description: 
define("_AREYOUSUREYOUWANTTOREMOVETHATSKILLFROMTHISEMPLOYEE","を削除してもよろしいですが、その従業員のスキルですか？");//Are you sure you want to remove that skill from that employee?
define("_JOBDESCRIPTIONEXISTSALREADY","職務記述書既に存在しています");//Job description exists already
define("_EVENTFIELDISMANDATORY","イベントのフィールドは必須");//Event field is mandatory
define("_SKILLCATEGORY","スキルカテゴリ");//Skill category
define("_ADDSKILLCATEGORY","スキルのカテゴリを追加");//Add skill category
define("_EDITSKILLCATEGORY","編集スキルカテゴリ");//Edit skill category
define("_DELETESKILLCATEGORY","スキルのカテゴリを削除");//Delete skill category
define("_AREYOUSUREYOUWANTTODISMISSTHISSKILLCATEGORY","解任してもよろしいですこのスキルカテゴリしたいですか？");//Are you sure you want to dismiss this skill category?
define("_UPDATESKILLSCATEGORY","更新プログラムのスキルカテゴリー");//Update skill category
define("_SKILLCATEGORYDATAUPDATED","スキルのカテゴリのデータ更新済み");//Skill category data updated
define("_SUCCESSFULLYCREATEDSKILLCATEGORY","スキルカテゴリ正常に作成さ");//Skill category successfully created
define("_SKILLCATEGORYDELETED","スキルカテゴリ削除");//Skill category deleted
define("_USERDOESNOTEXIST","のユーザーは存在しません");//The user does not exist
define("_INVALIDSURNAME","最終更新しないのユーザー名は有効ではありません");//The user last name specified is not valid
define("_INVALIDEMAIL","指定は、ユーザーのメールは有効ではありません");//The user email specified is not valid
define("_USERALREADYEXISTS","ログインすると、指定したユーザーが既に存在する");//A user with the specified login already exists
define("_EMAILALREADYEXISTS","指定されたメールを持つユーザーが既に存在する");//A user with the specified email already exists
define("_COULDNOTINSERTUSER","、ユーザが指定をデータベースに挿入できませんでした。");//The user specified could not be inserted to database
define("_INVALIDUSERTYPE","指定されたユーザーのタイプは有効ではありません");//The specified user type is not valid
define("_REMEMBERME","次回から入力を省略");//Remember me
define("_INVALIDPASSWORD","無効なパスワード");//Invalid password
define("_INVALIDPASSWORDFORUSER","ユーザーのパスワードを無効");//Invalid password for user
define("_PROBLEMACTIVATINGACCOUNT","中にアカウントの活性化に問題がありました。");//There was a problem during account activation
define("_THEUSERCOULDNOTBEDELETED","の使用を削除できませんでした");//The use could not be deleted
define("_THEUSERCOULDNOTBEDEACTIVATED","そのユーザーに無効にできませんでした。");//The user could not be deactivated
define("_THEUSERCOULDNOTBEACTIVATED","ユーザー活性化できませんでした。");//The user could not be activated
define("_USERDIRECTORYCOULDNOTBEDELETED","ユーザディレクトリを削除できませんでした");//The user directory could not be deleted
define("_INVALIDLESSONID","無効なレッスン番号");//Invalid lesson id
define("_UNITDOESNOTEXIST","このユニットは存在しません");//The unit does not exist
define("_DOWNLOADEXPORTED","ダウンロードエクスポートレッスン");//Download exported lesson
define("_SUCCESFULLYRESTOREDSYSTEM","プロシージャが正常に完了したのを復元する");//The restoring procedure completed successfully
define("_LESSONDOESNOTEXIST","ここでの教訓が存在しない場合はしない");//The lesson specified does not exist
define("_UNDOCHANGES","変更を元に戻す");//Undo changes
define("_CONTENTTREEMANAGEMENT","コンテンツカテゴリ管理");//Content tree management
define("_ORDERWILLPERMANENTLYCHANGE","この操作は恒久的に変更するとユニット発注を取り消すことはできません。してもよろしいですか？");//This operation will permanently change unit ordering and cannot be undone. Are you sure?
define("_ERRORLOADINGCONTENT","エラーが発生レッスンのコンテンツを読み込んでいます");//Error loading content for lesson
define("_USERROLE","ユーザーの役割");//User role
define("_CANNOTUPDATEUSERLESSONINFORMATION","このユーザーのレッスン情報を更新できませんでした");//The lesson information on this user could not be updated
define("_PROBLEMUPDATINGUSERSTOLESSON","中に問題が発生情報を更新してユーザのレッスン");//There was a problem updating the user lesson information
define("_INVALIDPROJECTID","無効なプロジェクト番号");//Invalid project Id
define("_PROJECTNOTFOUND","指定したプロジェクトが見つかりませんでした。");//The specified project was not found
define("_USERDOESNOTHAVETHISLESSON","ユーザー登録してこのレッスンではない");//The user is not registered to this lesson
define("_COURSEDOESNOTEXIST","指定したコースは存在しません");//The specified course does not exist
define("_NODEDOESNOTEXIST","指定されたノードが存在しません");//The specified node does not exist
define("_PROJECTCOULDNOTBEDELETED","このプロジェクトを削除できませんでした");//The project could not be deleted
define("_FREELESSON","無料レッスンを受けて");//Free lesson
define("_BUYCOURSE","購入するコース");//Buy course
define("_FREECOURSE","無料コース");//Free course
define("_USERDOESNOTHAVETHISPROJECT","このプロジェクトのユーザーはありません");//The user does not have this project
define("_SCOREMUSTBEINTEGERBETWEEN0100","このプロジェクトによるスコアしなければならないの整数に至る0から100まで");//The project score must be an integer ranging from 0 to 100
define("_THEPROJECTGRADECOULDNOTBEUPDATED","プロジェクトの等級を更新できませんでした");//The project grade could not be updated
define("_INVALIDDATA","無効なデータ");//Invalid data
define("_UPLOADEDON","アップロードする");//Uploaded on
define("_PROJECTDELETEDSUCCESSFULLY","このプロジェクトは、削除しました");//The project was deleted succesfully
define("_FILESCOULDNOTBEDOWNLOADED","して、プロジェクトファイルをダウンロードできませんでした");//The project files could not be downloaded
define("_RESULTSFORPROJECT","プロジェクトの検索結果");//Results for project
define("_VIEWPROJECT","対象プロジェクト");//View project
define("_REMAINING","残り");//Remaining
define("_PROJECTEXPIRED","このプロジェクトの締め切りは期限が切れて");//The project deadline has expired
define("_SENDPROJECT","送るプロジェクト");//Send project
define("_NEWLESSONS","新しいレッスン");//New lessons
define("_YOUMUSTDELETEALLLESSONSANDSUBDIRECTIONSINTHISDIRECTIONBEFOREDEACTIVATINGIT","無効にすることはできません非空範疇");//You cannot deactivate a non-empty category
define("_CANNOTUPDATEUSERCOURSEINFORMATION","このユーザーのコースの情報を更新できませんでした");//The course information on this user could not be updated
define("_CANNOTADDUSERTOCOURSE","のユーザーをコースに追加できませんでした。");//The user could not be added to course
define("_CANNOTREMOVEUSERFROMCOURSE","ユーザーのコースから削除できませんでした。");//The user could not be removed from the course
define("_USERHASNOTDONETEST","このテストは、ユーザーがいない");//The user has not done this test
define("_TESTISNOTDONE","テストではない完了");//The test is not done
define("_INVALIDQUESTIONTYPE","無効な質問のタイプ");//Invalid question type
define("_YOUCANNOTDEACTIVATEANONEMPTYDIRECTION","無効にすることはできません非空範疇");//You cannot deactivate a non-empty category
define("_YOUCANNOTDELETEANONEMPTYDIRECTION","を削除するにすることはできません非空範疇");//You cannot delete a non-empty category
define("_MAXFILEISAFFECTEDANDIS","アップロードファイルの最大サイズにも影響を受けてPHPの使用の設定を変更します。現在の真の最大ファイルサイズは、");//The maximum upload file size is also affected by PHP ini settings. Current true max file size is
define("_CAREFULNOTLOCKOUT","IPアクセスリストを設定するときは、自分を禁止しないように注意して！");//When setting ip access lists, be careful not to ban yourself out!
define("_ADMINISTRATORWILLACTIVATEYOURACCOUNT","ユーザ登録は完了です。お客様のアカウントは、システム管理者に活性化される");//Registration is complete. Your account will be activated by the system administrator
define("_USERPENDING","活性化されていないのアカウントの管理者はまだありません");//The account has not been activated yet by the administrator
define("_DOWNLOADDEFAULTSTYLE","ダウンロードのデフォルトのスタイル");//Download default style
define("_SETDEFAULTSTYLE","デフォルトのスタイル設定をアクティブ");//Set default style as active
define("_SUCCESFULLYUPDATEDLOGO","ロゴのファイルが更新されました");//Logo file was updated successfully
define("_USEDEFAULTLOGO","デフォルトのロゴを使用");//Use default logo
define("_GROUPOPTIONS","グループオプション");//Group options
define("_GROUPUSERS","グループのユーザー");//Group users
define("_USETHIS","使用する");//Use this
define("_PAGESETSUCCESSFULLY","ページ設定を正常");//Page set succesfully
define("_TEXTBOX","テキストボックスに");//Text box
define("_SELECTBOX","選択リスト");//Select list
define("_EDITFIELD","編集フィールド");//Edit field
define("_COULDNOTADDFIELD","のフィールドを追加できませんでした");//The field could not be added
define("_COULDNOTUPDATEFIELD","のフィールドを更新できませんでした");//The field could not be updated
define("_FIELDALREADYEXISTS","この名前のフィールドが既に存在する");//A field with this name already exists
define("_INTEGER","整数");//Integer
define("_DEFAULTVALUE","デフォルト値");//Default value
define("_VALUES","値");//Values
define("_ADDVALUES","追加値");//Add values
define("_DELETEBOOKMARK","ブックマークを削除");//Delete bookmark
define("_SUCCESSFULLYINSERTEDBOOKMARK","このページは、ブックマーク");//The page was bookmarked
define("_ERRORINSERTINGBOOKMARK","このページをブックマークできませんでした。");//The page could not be bookmarked
define("_LOADING","読み込んでいます...");//Loading...
define("_UNITS","ユニット");//Units
define("_USERCOULDNOTBECREATED","のユーザーを作成できませんでした。");//The user could not be created
define("_PROCEEDTOTEST","続行をテストする");//Proceed to test
define("_OPERATIONWILLAFFECTMANYAREYOUSURE","この操作は取り返しがつかないまでに、多数のエンティティに影響を与える。続行ですか？");//This operation will affect irreversibly a large number of entities. Proceed?
define("_CLICKTOTOGGLE","を切り替えるをクリックします");//Click to toggle
define("_COMPRESSDOWNLOAD","圧縮してダウンロードする");//Compress and download
define("_SELECTEDENTRYTO","のエントリを選択した");//the selected entry to
define("_YOUWANTTO","したい");//You want to
define("_UPLOADTODIGITALLIBRARY","アップロードの図書館がデジタル化");//Upload to digital library
define("_SHARE","共有する");//Share
define("_OPERATIONSUCCESFULLYAPPLIEDON","操作を正常に適用され");//Operation successfully applied on
define("_BYUSER","ユーザ");//by user
define("_VIEWSOLVEDTEST","対象解決テスト");//View solved test
define("_VIEWQUESTION","対象の質問");//View question
define("_COULDNOTCREATETESTSDIRECTORY","テストのフォルダを作成できませんでした。");//The tests folder could not be created
define("_SAVEASNEWTEST","新しいテストを付けて保存");//Save as new test
define("_SELECTLESSONTOCOPYFROM","選択してから教訓をコピーする");//Select a lesson to copy from
define("_VIEWCOMMENT","対象コメント");//View comment
define("_SHOWEVALUATIONS","詳細評価");//Show evaluations
define("_RECIPIENTS","受信者");//Recipients
define("_SHOWRECIPIENTSCATEGORIES","詳細受信者の定義済みのカテゴリー");//Show recipient&#039;s predefined categories
define("_HIDERECIPIENTSCATEGORIES","受信者の定義済みのカテゴリを非表示");//Hide recipient&#039;s predefined categories
define("_TOYOURSUPERVISORS","すべてのスーパーバイザー");//All your supervisors
define("_BASICINFO","基本的な情報をもっと見る");//Basic info
define("_TRAININGCAP","訓練");//T R A I N I N G
define("_COURSESAVERAGE","平均スコアすべてのコースに");//Average score in all courses
define("_LESSONSAVERAGE","平均スコアすべてのレッスン");//Average score in all lessons
define("_TESTSAVERAGE","平均スコアはすべてのテスト");//Average score in all tests
define("_DONTTAKEINTOACCOUNT","はありませんを考慮に入れる");//Do not take into account
define("_CANNOTADDUSERTOLESSON","ユーザーを追加することはできませんレッスン");//Cannot add user to lesson
define("_UNKNOWNUSER","不明なユーザー");//Unknown user
define("_DEPENDSON","に依存して");//Depends on
define("_COURSEINFORMATION","コース情報");//Course information
define("_NODATAFOUND","データが見つかりません");//No data found
define("_ERROROPENINGATTACHMENT","添付ファイルを開くときのエラー");//Error opening attachment
define("_USERAVERAGESCOREFORLESSON","平均スコアのレッスンのテスト");//User&#039;s average score for lesson
define("_LESSONSINFO","レッスン情報をもっと見る");//Lessons info
define("_USERSINGROUP","のユーザーがグループ");//Users in group
define("_PROFESSORSOFLESSON","教授のレッスン");//Professors of lesson
define("_TOBRANCHSUPERVISORS","あなたの上司にのみ支店");//Only your branch supervisors
define("_OTHERBRANCHJOBS","他の支店から仕事の説明");//Job descriptions from other branches
define("_SENDMESSAGETOALLFOUNDEMPLOYEES","メッセージを送信するすべての従業員が見つかりました");//Send messages to all employees found
define("_SEARCHCOURSEUSERS","検索の従業員[コース基準]");//Search for employee [Course criteria]
define("_COMPLETIONDATE","完成予定日");//Completion date
define("_YEAR","年");//Year
define("_NOTASSIGNED","割り当てはまだありません");//Not assigned yet 
define("_NEWSEARCHCRITERIUM","追加の検索クリテリウム");//Add search criterium
define("_NOSEARCHCRITERIADEFINED","の検索条件に定義されて");//No search criteria defined
define("_ERRORSAVINGTREE","エラーが発生節約カテゴリ");//Error saving tree
define("_MAXEXECUTIONTIME","実行時間の最大値");//Maximum execution time
define("_MEMORYLIMIT","メモリの制限");//Memory limit
define("_PHPSETTINGS","PHPの設定");//PHP settings
define("_MEGABYTES","メガバイト");//megabytes
define("_LEAVEBLANKTOUSEPHPINI","空欄のままにphp.iniのデフォルトの設定を使用するために");//Leave fields blank in order to use php.ini default settings
define("_DISPLAYERRORS","ディスプレイのエラー");//Display errors
define("_UPLOADLESSONFILE","ファイルのアップロードのレッスン");//Upload lesson file
define("_DCTITLE","タイトル");//Title
define("_DCCREATOR","創作");//Creator
define("_DCSUBJECT","主題");//Subject
define("_DCDESCRIPTION","説明書");//Description
define("_DCPUBLISHER","発行元");//Publisher
define("_DCCONTRIBUTOR","寄稿者");//Contributor
define("_DCDATE","日付");//Date
define("_DCTYPE","種類");//Type
define("_DCFORMAT","形式");//Format
define("_DCIDENTIFIER","識別子");//Identifier
define("_DCSOURCE","源泉");//Source
define("_DCLANGUAGE","言語");//Language
define("_DCRELATION","関係");//Relation
define("_DCCOVERAGE","カバレッジ");//Coverage
define("_DCRIGHTS","権利");//Rights
define("_NOENTRYFOUNDFOR","いいえエントリは見つかりませんでした。");//No entry found for
define("_FIELD","競技場");//field
define("_COURSECERTIFICATES","コース証明書");//Course certificates
define("_LDAPUSERMUSTCONTACTADMIN","お客様のアカウントには、 LDAPサーバーを介してアクセスします。システム管理者に連絡して");//Your account is accessed through the LDAP server. Please contact the system administrator at 
define("_COURSEMETADATA","コースのメタデータ");//Course metadata
define("_COURSESTATUS","コースの状態");//Course status
define("_LESSONSCOMPLETED","完了レッスン");//Completed lessons
define("_COURSESCORE","コースによるスコア");//Course score
define("_LESSONSCOMPLETED","完了レッスン");//Lessons completed and awaiting approval
define("_VIEWUSERCOURSEPROGRESS","対象のユーザーの進展してコース");//View the user progress throughout the course
define("_COURSERULES","コースのルール");//Course rules
define("_INFORMATIONFORCOURSE","コースの情報を");//Information for course
define("_CERTIFICATESFORCOURSE","コースの証明書を");//Certificates for course
define("_FORMATCERTIFICATEFORCOURSE","形式の証明書をコース");//Format certificate for course
define("_RULESFORCOURSE","コースのルールを");//Rules for course
define("_CONTENTDONE","コンテンツの完了");//Content done
define("_LESSONSPROGRESS","レッスン進捗状況");//Lessons progress
define("_COMPLETECOURSE","完全なコース");//Complete course
define("_PROPOSEDSCOREISAVERAGELESSONSCORE","レッスンの提案によるスコアは、平均スコア");//The proposed score is the average lessons score
define("_INTHESELECTEDLANGUAGE","説明書は、ご希望の言語を入力して");//Type the description in the prefered language
define("_SUCCESSFULLYDELETEDFIELD","正常に削除さフィールド");//Successfully deleted field
define("_COMPLETELESSON","完全なレッスン");//Complete lesson
define("_AUTOCOMPLETEDCOURSE","このコースは、すべてのレッスンが完了したときに自動的に完了する");//The course was automatically completed when all lessons were completed
define("_INFORMATIONFORLESSON","レッスンの情報を");//Information for lesson
define("_LESSONMETADATA","レッスンのメタデータ");//Lesson metadata
define("_DISPLAYINGRESULTS","結果の表示");//Displaying results
define("_LOADINGDATA","データを読み込んでいます");//Loading data
define("_COURSESTATISTICS","コース報告書");//Course reports
define("_CHOOSECOURSE","選択コース");//Choose course
define("_HISTORYRECORDDELETED","履歴レコードの削除");//History record deleted
define("_AREYOUSUREYOUWANTTODELETETHEHISOTYRECORD","してもよろしいの歴史をまとめて削除するレコードのですか？");//Are you sure you want to delete the history record?
define("_HIDEALL","すべて非表示");//Hide all
define("_COURSEORDER","コースオーダー");//Course order
define("_ORDERFORCOURSE","注文をコース");//Order for course
define("_DRAGITEMSTOCHANGELESSONSORDER","ドラッグアイテムの表示順序を変更するには、コースレッスン");//Drag items to change the display order of the course lessons
define("_IRREVERSIBLEACTIONDELETESUBUNITSAREYOUSURE","このアクションは、このユニットとirreversably削除することがありますが任意のサブユニットです。してもよろしいですか？");//This action will irreversably delete this unit and any subunits it may have. Are you sure?
define("_CLICKOKTOACTIVATEITEM","[ OK ]をクリックを有効/無効にアイテム");//Click OK to activate/deactivate item
define("_ANDITSSUBNODES","とのサブノード");//and it&#039;s sub nodes
define("_ERRORDELETINGUNIT","エラーが発生ユニットを削除する");//Error deleting unit
define("_ERRORACTIVATINGUNIT","エラーが発生活性化ユニット");//Error activating unit
define("_ERRORDEACTIVATINGUNIT","エラーが発生停止ユニット");//Error deactivating unit
define("_ERRORDEPOSITIONINGUNIT","エラーが発生位置決め装置");//Error positioning unit
define("_ERRORREPAIRINGTREE","エラーを修復カテゴリ");//Error repairing tree
define("_DRAGAUNITTOCHANGEITSPOSITION","の位置にドラッグする単位を変更するには");//Drag a unit to change its position
define("_IFUSESSLTHENPHPOPENSSL","SSLを使用したい場合は、ことを確認してPHPのOpenSSLサポートが有効になって");//If you want to use ssl, make sure that PHP openssl support is enabled
define("_COURSECOMPLETED","コース完成");//Course completed
define("_COURSECERTIFICATE","コース証明書");//Course certificate
define("_COURSESINFO","コースに関する情報");//Courses info
define("_DRAGTOMOVEMAILTOFOLDER","この電子メールにドラッグして移動を別のフォルダに");//Drag to move this email to another folder
define("_SCORMOPTIONS","SCORMをオプション");//Scorm options
define("_SCORMOPTIONSFOR","SCORMをオプションを");//Scorm options for
define("_SCORMREVIEW","日SCORMをデータ");//Review SCORM data
define("_REVIEWSCORMDATAFOR","SCORMをした日のデータを");//Review SCORM data for
define("_SCORMFILEINZIPFORMAT","SCORMをzipファイル");//SCORM zip file
define("_TREEROOT","ツリーのルート");//Tree root
define("_INVALIDPAGE","無効なページ");//Invalid page
define("_VALUEISSMALLERTHATPHPINI","この値が小さい場合、 php.iniの1つで設定さ");//The value is smaller than the one set by php.ini
define("_PERMISSIONS","アクセス許可");//Permissions
define("_UNSHARE","キャンセルの共有");//Cancel sharing
define("_UNSHARESELECTED","選択したファイルの共有を中止");//Cancel sharing of selected files
define("_SHARESELECTED","選択したファイルの共有");//Share selected files
define("_YOUDONTHAVEPERMISSION","あなたドン\"トンが許可を行うには、選択したアクション");//You don&quot;t have permission to perform the selected action
define("_EXPORT","輸出");//Export
define("_NOMODULECLASSFOUND","モジュールのクラス名が見つかりましたがない");//No module class found with name
define("_ERRORLOADINGMODULE","エラーが発生モジュールを読み込んでいます");//Error loading module
define("_VERSIONKEYTITLE","バージョンキー");//Version Key
define("_VERSIONKEY","バージョンキー");//Version key
define("_VERSIONALLOEDUSERS","許可されたユーザー");//Allowed Users
define("_VERSIONTYPE","バージョンタイプ");//Version Type
define("_VERSIONSERIAL","シリアル番号");//Serial Number
define("_USERSEXCEEDED","使用しているバージョンのタイプは許可されませんし、新規ユーザを作成");//Your version type does not allow the creation of new users
define("_BASICCRITERIA","基本的な基準");//Basic criteria
define("_BASICSEARCHOPTIONS","基本的な検索オプション");//Basic search options
define("_DELETEDATA","データの削除");//Delete data
define("_ERRORDETAILS","エラーの詳細");//Error Details
define("_PARTOFTHISGROUP","このグループのユーザーが部分");//The user is part of this group
define("_SUCCESSFULLYIMPORTEDSCORMFILE","SCORMをファイルが正常にインポート");//SCORM file was successfully imported
define("_CONVERTTOSCORMCONTENT","SCORMをコンテンツ単位に変換する");//Convert to SCORM content unit
define("_CONVERTTOSCORMTEST","SCORMをテスト単位に変換する");//Convert to SCORM test unit
define("_SCORMTREE","SCORMをカテゴリ");//SCORM tree
define("_MASTERYSCORE","熟練によるスコア");//Mastery score
define("_GZHANDLER","ハンドラのgz");//GZ handler
define("_PROJECTPENDING","このプロジェクトは保留中です");//This project is pending
define("_USERHASNOTDONETEST","このテストは、ユーザーがいない");//The user has not done this test
define("_USERHASNOTTHISLESSON","ユーザー登録をこのレッスンではない");//The user is not registered for this lesson
define("_SHIFTSCHEDULEFORNEWUSERS","新規ユーザーのスケジュールをシフト");//Shift schedule for new users
define("_CURRENTSCHEDULE","現在のスケジュール");//Current schedule
define("_NOSCHEDULESET","のスケジュール設定");//No schedule set
define("_DELETESCHEDULE","スケジュールを削除");//Delete schedule
define("_SCHEDULINGFORCOURSE","コーススケジュール");//Scheduling for course
define("_ADDSCHEDULE","追加スケジュール");//Add schedule
define("_COURSESCHEDULE","コーススケジュール");//Course schedule
define("_AVAILABLEUNTIL","ご利用されるまで");//Available until
define("_FILETYPE","ファイルの種類");//File type
define("_FULLPATH","フルパス");//Full path
define("_MIMETYPE","MIMEタイプ");//MIME type
define("_CANNOTSHAREFILE","共有ファイルことはできません。");//Cannot share file
define("_SHAREDFILES","共有ファイル");//Shared files
define("_CLICKTOEXPORT","ボタンをクリックしてレッスンをエクスポートする");//Click the button to export lesson
define("_EXISTINGFILE","は、次のファイルが既に存在");//The following file already exists
define("_PROBLEMADDINGUSERSTOLESSON","ユーザのレッスンに追加してできませんでした。");//The user could not be added to the lesson
define("_TRANSLATEFILESYSTEM","エンコード以外のファイルの名前をラテン語");//Encode non-latin file names to
define("_CANNOTMOVEFILE","そのファイルに移動することはできません。");//Cannot move file
define("_INCOMPATIBLEVERSIONS","互換性のないバージョン");//Incompatible versions
define("_BACKUPVERSION","バックアップバージョン");//Backup version
define("_CURRENTVERSION","現在のバージョン");//Current Version
define("_MAXIMUMUPLOADSIZE","最大ファイルサイズ");//Maximum file size
define("_BACKUPFAILED","バックアップに失敗しました");//Backup failed
define("_PERSONALFILES","個人的なファイル");//Personal files
define("_MAXIMUMUSERSNUMBERREACHED","ユーザの最大数に達した時点で");//The maximum number of users is reached
define("_UPLOADING","アップロード");//Uploading
define("_SELECTEDFILESTO","選択したファイルを");//selected files to
define("_CATEGORYDOESNOTEXIST","このカテゴリは存在しません。");//The category does not exist
define("_CATEGORIES","カテゴリー");//Categories
define("_NEWCATEGORY","新しいカテゴリ");//New category
define("_EDITCATEGORY","カテゴリを編集");//Edit category
define("_CATEGORYSETTINGS","カテゴリの設定");//Category settings
define("_YOUWANTTOBEDONE","したい");//You want to
define("_OVERWRITE","上書き");//Overwrite
define("_USERSPROGRESS","従業員のステータス");//Users progress
define("_LESSONUSERS","ユーザのレッスン");//Lesson users
define("_ASSOCIATEDCOURSES","関連付けられたコース");//Associated courses
define("_OUTPUT","出力");//Output
define("_TOKEN","トークン");//Token
define("_PERMITTEDROLESMODULEERROR","1つまたは複数のモジュールの役割が間違って許可");//One or more module permitted roles are wrong
define("_SMARTYTEMPLATEDOESNOTEXIST","れるSmartyのテンプレートファイルが存在しません");//The smarty template file does not exist
define("_FOLDERWITHMODULENAMEEXISTSIN","フォルダにモジュール名は既に存在して");//Folder with module name already exists in 
define("_SITENAME","サイト名");//Site name
define("_SITEMOTO","サイトモト");//Site moto
define("_UNKNOWNSEPARATOR","未知の区切り");//Unknown separator
define("_LDAPUSER","このユーザーを認証するLDAPサーバー");//This user authenticates through the LDAP server
define("_EXECUTE","実行");//Execute
define("_RECREATE","再現");//Recreate
define("_CLICKHERETOREINDEX","ここをクリックして、再度検索テーブル");//Click here to recreate the search table
define("_TRANSLATION","翻訳");//Translation
define("_ENGLISHNAME","英語の名前を");//Name in english
define("_SUCCESSFULLYADDEDLANGUAGE","その言語が正常に作成さ");//The language was successfully created
define("_SUCCESSFULLYUPDATEDLANGUAGE","その言語が正常に更新済み");//The language was successfully updated
define("_LANGUAGES","言語");//Languages
define("_SERIALRULE","ユーザーのコンテンツを参照する必要がありますシリアル注文");//Users must see content in a serial order
define("_TREERULE","ユーザーを完了する必要があります。支店\"のノードに移動する前に、次の1つ");//Users must complete a branch&quot;s nodes before moving to the next one
define("_ADDCUSTOMRULE","カスタムルールを追加");//Add custom rule
define("_ADDREADYRULE","準備のルールを追加");//Add ready rule
define("_THEFOLLOWINGUSERSCOULDNOTBEIMPORTED","は、次のユーザをインポートできませんでした");//The following users could not be imported
define("_STARTHERE","スタート]ボタンをここに");//Start here
define("_COPYSELECTED","コピーを選択");//Copy selected
define("_USERACCESSESINLESSON","ユーザーのアクセス権を教訓");//User access in lesson
define("_NUMBEROFFIELDSMUSTBE","フィールドの数をしなければならない");//The number of fields must be
define("_BUTFOUND","しかしがあったが見つかりました");//but there was found
define("_APPLYAVATARCHANGES","アバターの変更を適用");//Apply avatar changes
define("_TERMFIELDISMANDATORY","任期フィールドは必須");//Term field is mandatory
define("_DEFINITIONFIELDISMANDATORY","フィールドは必須で定義されて");//Definition field is mandatory
define("_TOPLEFTCORNER","左上隅");//Top left corner
define("_TOPRIGHTCORNER","右上隅");//Top right corner
define("_BOTTOMLEFTCORNER","左下隅");//Bottom left corner
define("_BOTTOMRIGHTCORNER","右下隅");//Bottom right corner
define("_LOGOPOSITION","ロゴの位置");//Logo position
define("_LOGOFILE","ロゴファイル");//Logo file
define("_LESSONSKILLSSELECTION","レッスンを提供スキルの選択");//Lesson offered skills selection
define("_TOPCENTER","トップへセンター");//Top center
define("_BOTTOMCENTER","下部センター");//Bottom center
define("_HIDECOMPLETEUNITICON","完全な単位のアイコンを非表示");//Hide complete unit icon
define("_HIDENAVIGATION","ナビゲーションハンドルを隠す");//Hide navigation handles
define("_AUTOCOMPLETEDAT","自動完了で");//Auto completed at
define("_SECOND","2番目");//second
define("_NOACCESSDATA","アクセスデータ");//No access data
define("_USERAVATAR","ユーザーアバター");//User avatar
define("_MOSTACTIVELESSONS","最も活動的なレッスン");//Most active lessons
define("_LESSONSACTIVITY","レッスン活動");//Lessons activity
define("_USERSACTIVITY","ユーザの活動");//Users activity
define("_USERHASNOTTHELESSON","このレッスンを行う必要はありません。");//The user doesn&#039;t have this lesson
define("_USERHASTHELESSON","このレッスンは、ユーザーが");//The user has this lesson
define("_TESTSINFORMATION","テスト情報");//Tests information
define("_QUESTIONSINFORMATION","ご質問の情報");//Questions information
define("_PROJECTSINFORMATION","プロジェクト情報");//Projects Information
define("_MCEXPLANATION","*カセット=複数の選択肢-1つの回答");//* MC = Multiple choices - Single Answers
define("_MCMAEXPLANATION","* mcma =複数の選択肢-複数回答可");//* MCMA = Multiple choices - Multiple Answers
define("_MAEXPLANATION","*マサチューセッツ=マッチング");//* MA = Matching
define("_FBEXPLANATION","*にfb =記入すると、空の");//* FB = Fill the blank
define("_OAEXPLANATION","*オープンアクセス=開いて回答");//* OA = Open answer
define("_YNEXPLANATION","*あなたの=はい/いいえ");//* YN = Yes/No
define("_PROJECTNAME","プロジェクト名");//Project name
define("_STATISTICSFORCOURSE","コースの統計情報を");//Statistics for course
define("_YOUARENOTAUTHORISEDTOSEETHISTEST","あなた、このテストを表示する権限がありません");//You are not authorized to see this test
define("_YOUCANNOTREDOTHISTEST","このテストをやり直しすることはできません。");//You cannot redo this test
define("_ACCESSEDLESSON","アクセスのレッスン");//Accessed lesson
define("_ACCESSEDCONTENT","アクセスコンテンツ単位");//Accessed content unit
define("_ACCESSEDTEST","アクセステスト");//Accessed test
define("_BEGUNTEST","テストを開始");//Begun test
define("_NAVIGATEDSYSTEM","ナビゲートを通じて、システム");//Navigated through the system
define("_PROJECTDESCRIPTION","プロジェクトの説明");//Project description
define("_CONTENTTRAVERSINGRULES","コンテンツを横断のルール");//Content traversing rules
define("_FILEUPLOADEDON","上のファイルがアップロードさ");//The file was uploaded on
define("_DIRECTIONOPTIONSFOR","のオプションを見る");//Options for category
define("_NEWDIRECTIONOPTIONS","新しいカテゴリのオプション");//New category options
define("_COURSELESSONS","コースレッスン");//Course lessons
define("_RELATEDTO","関連して");//Related to
define("_SUCCESSFULLYEXPORTEDSCORMFILE","その教訓は、 SCORMを形式でエクスポートして正常に");//The lesson was exported to SCORM format succesfully
define("_LDAPEXTENSIONNOTLOADED","警告： LDAPの拡張子を読み込まれない");//Warning: LDAP Extension  not loaded
define("_PERCENTAGEMUSTBEBETWEEN1100","1から100までの間にしなければならないの割合");//Percentage must be between 1 and 100
define("_MUSTSEECONTENTSERIALSOMUSTFIRSTREADUNIT","のコンテンツを参照する必要がありますシリアル注文ので、最初の読み取りユニットする必要があります。");//You must see content in a serial order, so you must first read unit
define("_YOUDONTHAVEANYLESSONS","する必要はありません。任意のレッスンやコース");//You don&#039;t have any lessons or courses
define("_THEADMINISTRATORWILLASSIGNYOULESSONS","は、システム管理者は、レッスンやコースを割り当てます。");//The system administrator will assign you lessons or courses
define("_BACKTOINDEX","先頭のページをインデックスに登録する");//Back to index page
define("_LESSONAVAILABLE","レッスンは入手可能");//Lesson is available
define("_DIRECTLY","直接");//Directly
define("_ADDFILE","追加ファイル");//Add file
define("_DOWNLOADSCORMEXPORTEDFILE","SCORMをダウンロードファイルにエクスポート");//Download exported SCORM file
define("_EMPTYUNIT","空のユニット");//Empty unit
define("_YOUMUSTPROVIDELOGINLINK","ログインする必要がありますリンクを提供する、それ以外の場合は、直接に接続することはできません。ログインフォームが利用できるのリンク： ". G_SERVERNAME."index.php?index_efront");//You must provide a login link, otherwise you will not be able to connect directly. Login form is available through the link: ".G_SERVERNAME."index.php?index_efront
define("_NOFILEUPLOADED","いいえファイルがアップロードさ");//No file was uploaded
define("_FONTSIZE","フォントサイズ");//Font size
define("_FONTSTYLE","フォントスタイル");//Font style
define("_PROBLEMINSERTINGPARSEDXMLVALUESORMODULEEXISTS","問題のXMLの値を挿入して、データベース解析します。かどうかをご確認してください説明書ファイルまたはモジュールが既にインストールさ");//Problem inserting the parsed XML values to the database. Please check your description file or whether the module is already installed
define("_NOMODULEPERMITTEDROLESDEFINED","許可の役割のモジュールを定義します。チェック機能getpermittedroles （ ）");//No module permitted roles defined. Check function getPermittedRoles()
define("_MODULECLASSNOTEXISTSIN","モジュールのクラスで定義されてではない");//module class is not defined in
define("_MODULEDBERRORONINSTALL","データベースの関数の実行中にエラーが発生oninstallは、モジュール");//Database error during the execution of function onInstall for the module
define("_MODULEISALREADYINSTALLED","このモジュールは既にインストールさ");//The module is already installed
define("_LOGOUTREDIRECT","ログアウトした後にリダイレクトする");//Redirect after logout to
define("_INFORMATIONFORFILE","ファイルの情報を");//Information for file
define("_METADATA","メタデータ");//Metadata
define("_FILEMETADATA","ファイルのメタデータ");//File metadata
define("_NOENTRYFOUNDFORTHEFIELD","フィールドのエントリは見つかりませんでした。");//No entry found for the field
define("_CONTENTMETADATA","コンテンツメタデータ");//Content Metadata
define("_METADATAFORUNIT","メタデータの単位を");//Metadata for unit
define("_RESOURCEREQUESTEDREQUIRESLOGIN","お客様のリクエストのリソースを最初にログインする必要があります。");//The resource that you requested requires that you login first
define("_DATABASEERROR","データベースエラーが発生");//Database error
define("_CANNOTACCESSRESOURCE","する必要はありません。このリソースへのアクセス許可が");//You don&#039;t have permission to access this resource
define("_RESOURCEISNOTACCESSIBLEFROMOUTSIDE","このリソースに直接アクセスではない");//This resource is not directly accessible
define("_RESOURCEISNOTAVAILABLE","このリソースは利用できません");//This resource is not available
define("_DIRECTLYACCESSIBLE","URLを直接アクセス");//Accessible with a direct URL
define("_DIRECTLACCESSIBLEEXPLANATION","これは、そのユニットを使用して次のようにアクセスできることの直接のURL ：");//This means that the unit can be accessed using the following direct url:
define("_HIDE","隠す");//Hide
define("_LESSONOPTIONSET","レッスンのオプションを設定");//Lesson option set
define("_BACKUPRESTORE","バックアップ/リストア");//Backup/restore
define("_CONFIGURATIONOPTIONS","設定オプション");//Configuration options
define("_UNAUTHORIZEDACCESS","へのアクセス許可をする必要はありませんこのセクションで");//You do not have permission to access this section
define("_LESSONUSER","ユーザのレッスン");//Lesson user
define("_PROGRESSFORUSER","進行中のユーザー");//Progress for user
define("_LESSONSORDER","レッスンオーダー");//Lessons order
define("_COURSEUSER","コースのユーザー");//Course user
define("_COURSELESSON","コースレッスン");//Course lesson
define("_CANNOTDELETEOWNTYPE","自分のタイプを削除することはできません。");//You may not delete your own type
define("_GROUPUSER","グループのユーザー");//Group user
define("_EXPLICITIFRAMESIZE","明示的なiframeのサイズ");//Explicit iframe size
define("_EXPLICITSIZEEXPLANATION","これは、フレームのサイズを、 SCORMを含むコンテンツです。空白のままにしてそれを自動的に計算");//This is the size of the SCORM content containing frame. Leave it blank to have it automatically calculated
define("_USERROLEINLESSON","ユーザーの役割を果たすのレッスン");//User role in lesson
define("_LESSONROLE","レッスンな役割を果たす");//Role in lesson
define("_COURSEROLE","コースの役割を果たす");//Role in course
define("_PAYPAL","ペイパル");//Paypal
define("_DOWNLOADEXAMPLE","ダウンロードの例");//Download example
define("_CONTENTTREEFIRSTPAGE","コンテンツのカテゴリでの最初のページ");//Content tree in first page
define("_LAYOUT","レイアウト");//Layout
define("_CONNECTIONERROR","接続エラーが発生");//Connection error
define("_ONLYEFRONTNOTSCORM","このレッスンで使用efront形式をアップロードするのみです。 SCORMをアップロードを、 SCORMを使用して教授のオプションは、 [コントロールパネル]");//Use this to upload lessons in eFront format only. For SCORM uploads, use the SCORM option at the professor's control panel
define("_TESTSMATRIX","テスト行列");//Tests matrix (New)
define("_PROJECTSMATRIX","プロジェクト行列");//Projects matrix (New)
define("_MODULEDBERRORONUPGRADECHECKUPGRADEFUNCTION","onUpgradeモジュールの機能を実行中にデータベースエラー");//Database error during the execution of function onUpgrade for the module (New)
define("_MODULENOTUPGRADEDFOLDERNOTDELETEDCLOSEALLOPENFILES","既存のディレクトリが削除されていない可能性があるため、モジュールのアップグレードに失敗しました。そのディレクトリ内のすべての開いているファイルを閉じ、もう一度お試しください");//Module upgrade failed, because existing directory could not be deleted. Close all open files in that directory and try again (New)
define("_MODULESUCCESFULLYUPGRADED","モジュールを正常にアップグレード");//Module successfully upgraded (New)
define("_USERRESULTS","ユーザーの検索結果");//User results (New)
define("_SKILLSCORES","技能スコア");//Skill scores (New)
define("_PROPOSEDASSIGNMENTS","提案の割り当て");//Proposed assignments (New)
define("_THRESHOLD","糸");//Threshold (New)
define("_SKILLGAPANALYSISFORUSER","ユーザーのスキルギャップ分析");//Skill gap analysis for user (New)
define("_ACCORDINGTOTEST","によるとテスト");//according to test (New)
define("_NOLESSONSPROPOSEDACCORDINGTOANALYSIS","いいえレッスンは、スキルギャップ分析によると提案されている");//No lessons are proposed according to the skill gap analysis (New)
define("_NOCOURSESPROPOSEDACCORDINGTOANALYSIS","いいえコースは、スキルギャップ分析によると提案されている");//No courses are proposed according to the skill gap analysis (New)
define("_CERTIFICATETEMPLATE","証明書（ RTF形式）のテンプレート");//Certificate template (rtf format) (New)
define("_COMMANDS","コマンド");//Commands (New)
define("_SEARCHRESULTSCOMMANDS","コマンドの検索結果");//Search results in commands (New)
define("_TOGGLEHTMLEDITORMODE","トグルエディタ/ HTMLモード");//Toggle editor/html mode (New)
define("_UPLOADFILEFROMURL","URLからファイルのアップロード");//Upload file from url (New)
define("_OPENCLOSEFILEMANAGER","開く/閉じるファイルマネージャ");//Open/close file manager (New)
define("_INSERTEDITOR","挿入エディタに");//Insert to editor (New)
define("_AUTOMATICALLYASSIGNTOALLNEWSTUDENTS","自動的にすべての新入生に割り当てる");//Automatically assign to all new students (New)
define("_SKILLGAPTESTSTOBECOMPLETED","スキルギャップテストを完了する");//Skill gap tests to be completed (New)
define("_SKILLGAPTESTCOMPLETEDSUCCESSFULLY","スキルギャップのテストが正常に完了");//Skill gap test completed successfully (New)
define("_RELEVANCE","関連性");//Relevance (New)
define("_KNOWLEDGEOFLESSON" , "Knowledge of lesson");
define("_KNOWLEDGEOFCOURSE","知識はもちろん");//Knowledge of course (New)
define("_NOSKILLSCORRELATEDWITHTHETESTSQUESTIONS","いいえスキルは、テストの質問との相関");//No skills correlated with the test&#039;s questions (New)
define("_OPENFILEMANAGER","開いているファイルマネージャ");//Open file manager (New)
define("_CLOSEFILEMANAGER","ファイルマネージャを閉じる");//Close file manager (New)
define("_CLICKFORHELP","をクリックして助けを求める");//Click for help (New)
define("_NOSKILLGAPTESTSASSIGNEDTOYOU","スキルギャップに割り当てられていない場合のテスト");//No skill gap tests assigned to you (New)
define("_TESTSOLVEDVIEWTOSEESKILLGAPANALYSIS" , "Test solved: View skill gap analysis");
define("_GENERALTHRESHOLD","一般的な閾値");//General Threshold (New)
define("_UPLOADPDFFORCONTENT","トグルPDFファイル/カスタムコンテンツ");//Toggle pdf/custom content (New)
define("_PDFFILE","新しいPDFファイルをアップロード");//Upload new pdf file (New)
define("_ASSOCIATEDSKILLS","関連するスキル");//Associated skills (New)
define("_SKILLGAPTESTS","スキルギャップのテスト");//Skill gap tests (New)
define("_ASSOCIATEDWITH","関連で");//Associated with (New)
define("_NEWSKILLGAPTESTS","新しいスキルギャップテスト");//New skill gap tests (New)
define("_CORRELATESKILLSTOQUESTION","質問に相関しているスキル");//Correlate skills to question (New)
define("_EDITSKILLGAPTEST","編集のスキルギャップ試験");//Edit skill gap test (New)
define("_ADDSKILLGAPTEST","スキルギャップのテストを追加");//Add skill gap test (New)
define("_YOUMUSTUPLOADAPDFFILE","あなたはpdfファイルをアップロードする必要があります");//You must upload a pdf file (New)
define("_RECENTLYCOMPLETEDSKILLGAP","最近skillgapテストを完了");//Recently completed skillgap tests (New)
define("_NOCOMPLETEDSKILLGAP","skillgapテストを完了していないが見つかりました");//No completed skillgap tests found (New)
define("_SHOWALLSOLVEDSKILLGAPTESTS","すべて表示skillgapテストを解決");//Show all solved skillgap tests (New)
define("_DELETESKILLGAPTESTRECORD","テストレコードを削除するスキルギャップ");//Delete skill gap test record (New)
define("_ASSIGNTOALLNEWSTUDENTS","割り当てるすべての新しい学生に");//Assign to all new students (New)
define("_AUTOMATICALLYASSIGNLESSONS","レッスンを自動的に割り当てる");//Automatically assign lessons (New)
define("_AUTOMATICASSIGNMENTINFO","テストが完了後、自動的にすべての学生に割り当てられる<br>コースのレッスンと、自分の教育ニーズをマッチング");//After completing the test, a student will be automatically assigned with all<br> lessons and courses matching his or her educational needs (New)
define("_SKILLGAPTESTCOMPLETEDSUCCESSFULLYANDTHECORRESPONDING","スキルギャップと、それに対応するテストは正常に完了");//Skill gap test completed successfully and the corresponding (New)
define("_HAVEBEENASSIGNED","あなたに割り当てられている");//have been assigned to you (New)
define("_SKILLGAPTESTRESULTS","スキルギャップ試験結果");//Skill gap test results (New)
define("_CURRENTPDFFILE","現在のpdfファイル");//Current pdf file (New)
define("_SEARCHTEXTWASINSCRIPT","検索テキストは、スクリプトの中に発見された");//Search text was found inside a script (New)
define("_NUMBERFROM000TO9999REQUIRED","数0.00 99.99から必要");//Number from 0.00 to 99.99 required (New)
define("_COMPLETETHESKILLGAPTESTSBELOWSOTHATWECANASSIGNLESSONS","下記のスキルギャップのテストを完了した最もneeedsに適したコースを割り当てることができます。");//Complete the skill gap tests below so that we can assign courses most suitable to your neeeds. (New)
define("_YOUHAVECOMPLETEDALLSKILLGAPSTESTSASSIGNEDTOYOUWAITTOBEASSIGNEDLESSONS","あなたに割り当てられたすべてのスキルギャップのテストを完了している。 <br>あなたの教授になるまでに、お客様のニーズに応じて最も適したコースを割り当てるので、しばらくお待ちください。");//You have completed all skill gap tests assigned to you. <br>Please wait until your professors assign to you the most suitable courses according to your needs. (New)
define("_YOURRESULTSHAVEBEENSENTTOYOURPROFESSORSWHOWILLASSIGNLESSONSACCORDINGTOYOURNEEDS","あなたの結果はすぐにコースを割り当てるとなります。教授に送信されているお客様のお客様のニーズに応じてこのテストからの確認として");//Your results have been sent to your professors who will soon assign courses to your according to your needs as identified from this test (New)
define("_JOBPLACEMENTS","仕事位置");//Job placements (New)
define("_NEWJOBPLACEMENT","新しい仕事位置");//New job placements (New)
define("_UPGRADEMODULE","アップグレードモジュール");//Upgrade module (New)
define("_NEWUNITOPTIONS","新ユニットのオプション");//New unit options (New)
define("_UNITOPTIONSFOR","ユニット用オプション");//Options for unit (New)
define("_OPTIONSFORSKILLGAPTEST","スキルギャップテストのためのオプション");//Options for skill gap test (New)
define("_OPTIONSFORTEST","テストのためのオプション");//Options for test (New)
define("_REPORTSFORCOURSE","レポートコースの");//Reports for course (New)
define("_REPORTSFORTEST","テストのレポート");//Reports for test (New)
define("_USERISNOTVALIDORYOUCANNOTSEEUSER","ユーザーが指定した有効ではありませんか、このユーザーのデータにアクセスすることはできません");//The user specified is not valid, or you cannot access this user&#039;s data (New)
define("_SELECTGROUP","えり抜きのグループ");//Select group (New)
define("_BLANKFORNOLIMIT","時間制限なしに空白のままに");//Leave blank for no time limit (New)
define("_HARDPLURAL","辛い");//Hard (New)
define("_MEDIUMPLURAL","媒体");//Medium (New)
define("_EASYPLURAL","簡単な");//Easy (New)
define("_UNLIMITED","Unilimited");//Unilimited (New)
define("_INCORRECTQUESTION","という質問が間違っています");//The question is incorrect (New)
define("_QUESTIONISCORRECT","という質問が正しいことを");//The question is correct (New)
define("_PARTIALLYCORRECTQUESTION","問題部分が正しいことを");//The question is partially correct (New)
define("_FAILED","失敗");//Failed (New)
define("_PASSED","合格");//Passed (New)
define("_TESTOPTIONS","テストオプション");//Test options (New)
define("_TESTQUESTIONS","テスト質問");//Test questions (New)
define("_SAVETESTANDADDQUESTIONS","保存したり、質問を選択してください");//Save and select questions (New)
define("_RANDOMPOOLTEST","ランダムなプールのテスト");//Random pool test (New)
define("_SUBMITANDCONTINUEEDITING","を送信し、編集を続ける");//Submit and continue editing (New)
define("_SUBMITANDRETURN","提出して戻ってくる");//Submit and return (New)
define("_SUBMITASNEWANDCONTINUEEDITING","新規および継続編集として提出");//Submit as new and continue editing (New)
define("_SUBMITASNEWANDRETURN","提出、新しいとリターン");//Submit as new and return (New)
define("_QUESTIONSINPOOL","プールでの質問");//Questions in pool (New)
define("_SELECTRANDOMQUESTIONS","ランダム質問");//Randomize questions (New)
define("_RANDOMIZE","無作為化");//Randomize (New)
define("_PAUSETEST","テストを一時停止");//Pause test (New)
define("_ALLFORUMS","すべてのフォーラム");//All forums (New)
define("_USERCANDOTEST","ユーザーがテストを行うことができます");//The user can do the test (New)
define("_ANDUSERDIDITIN","それに完成した");//It was completed in (New)
define("_TESTSCOREIS","テストの点数です");//Test score is (New)
define("_USERREDOTEST","やり直しテスト");//Redo test (New)
define("_SOLVEDTEST","試験を解決");//Solved test (New)
define("_CHANGESCORE","変更によるスコア");//Change score (New)
define("_ADDFEEDBACK","フィードバックを追加");//Add feedback (New)
define("_EDITFEEDBACK","編集フィードバック");//Edit feedback (New)
define("_RESETTESTSTATUS","このテストの実行をリセット");//Reset this test execution (New)
define("_THETESTISDONE","テスト行われる");//The test is done (New)
define("_ANDCANBEDONE","と実行することができます");//and can be done (New)
define("_TESTCANBEPAUSED","テストを一時停止することができます");//Test can be paused (New)
define("_TESTSTARTEDAT","このテストで開始");//The test started at (New)
define("_ANDCOMPLETEDAT","で完了");//and completed at (New)
define("_SCOREINTEST","テストのスコア");//Score in test (New)
define("_TESTRESULTS","テスト結果");//Test results (New)
define("_JUMPTOEXECUTION","ジャンプの実行を");//jump to execution (New)
define("_LASTEXECUTION","最後に実行");//Last execution (New)
define("_EXECUTION","実行");//execution (New)
define("_LAST","最後の");//Last (New)
define("_CORRECTIONPENDING","補正保留");//Correction pending (New)
define("_FULLNAME","正式名称");//Full name (New)
define("_PARTIALLYCORRECT","部分的修正");//Partially correct (New)
define("_CORRECT","正しい");//Correct (New)
define("_NOUNIT","いいえユニット");//No unit (New)
define("_TESTANALYSIS","テスト解析");//Test analysis (New)
define("_THISLEVEL","このレベル");//This level (New)
define("_BELOWLEVELS","下のレベル");//Below levels (New)
define("_SUCCESSRATES","成功率");//Success rates (New)
define("_NOPARENT","親がなけれ");//Without parent (New)
define("_THEUSERUNDERGOINGTESTSTARTEDAT","ユーザーが今で開始すると、テストを行っています");//The user is right now undergoing the test, started at (New)
define("_NONEXISTENTTEST","これは、完了検査されていません");//This is not a completed test (New)
define("_FORTEST","テストのため");//for test (New)
define("_ANDUSER","とユーザ");//and user (New)
define("_TESTANALYSISFORTEST","テストのためのテスト分析");//Test analysis for test (New)
define("_RESETALLTESTSSTATUS","すべての実行状態をリセット");//Reset all execution status (New)
define("_ADDANOTHERFILE","別のファイルに追加");//Add another file (New)
define("_YOUPAUSEDTHISTESTON","あなたにこのテストを一時停止");//You paused this test on (New)
define("_RESUMETEST","再開テスト");//Resume test (New)
define("_DISPLAYQUESTIONWEIGHTS","テスト期間中のディスプレイ重量");//Display weights during test (New)
define("_UNAVAILABLEOPTION","このオプションは利用されていません");//This option is not available (New)
define("_SKILLGAPTESTS","スキルギャップのテスト");//Skill gap tests (New)
define("_HOURSSHORTHAND","時間");//h (New)
define("_MINUTESSHORTHAND","メートル");//m (New)
define("_SECONDSSHORTHAND","秒");//s (New)
define("_NONEUNIT","単位なし");//None unit (New)
define("_NOSYSTEMANNOUNCEMENTS","システムのアナウンスがないです");//There are no system announcements (New)
define("_NOONELOGGEDIN","誰も現在に記録されます。");//Noone is currently logged in (New)
define("_ENTERYOUREMAILADDRESS","あなたのメールアドレスを入力してください");//Enter you email address (New)
define("_ENTERMESSAGESUBJECT","メッセージの件名を入力してください");//Enter the message subject (New)
define("_ENTERMESSAGE","メッセージを入力してください");//Enter the message (New)
define("_ENTERANYCOMMENTS","お持ちのかもしれないすべてのコメントを入力してください");//Enter any comments you might have (New)
define("_LOGINOREMAIL","ログインまたはメール");//Login or email (New)
define("_USETHISTORESETPASSWORD","あなたのパスワードをリセットするためにこのフォームを使用して");//Use this form to reset your password (New)
define("_USETHISTOREGISTERANEWACCOUNT","新しいユーザーアカウントを作成し、このフォームを使用して");//Use this form to create a new user account (New)
define("_USETHISTOCONTACTUS","このフォームを使用して任意の問題に対するお問い合わせください");//Use this form to contact us for any issue (New)
define("_AVAILABLELESSONS","レッスンとコースは、システムで利用可能");//Lessons and courses available in the system (New)
define("_SELECTLAYOUT","レイアウトを選択してください");//Select a layout (New)
define("_ENROLL","登録");//Enroll (New)
define("_INFORMATION","情報");//Information (New)
define("_STARTPAGE","スタートページ");//Start page (New)
define("_SIGNUP","サインアップ");//Sign up (New)
define("_INFOFORLESSON","情報の授業のため");//Information for lesson (New)
define("_DONTHAVEACCOUNT","私はアカウントを持っていない");//I do not have an account (New)
define("_FORGOTPASSWORD","私は自分のパスワードを忘れてしまった");//I forgot my password (New)
define("_LOGINFORM","ログインフォーム");//Login form (New)
define("_SEARCHFORM","検索フォーム");//Search form (New)
define("_CARTBLOCK","ショッピングカートをブロック");//Shopping Cart block (New)
define("_CUSTOMBLOCK","カスタムブロック");//Custom block (New)
define("_LESSONSLIST","レッスン一覧");//Lessons list (New)
define("_SYSTEMNEWS","システムニュース");//System news (New)
define("_REMOVE","取り外す");//Remove (New)
define("_TWOCOLUMNSRIGHT","2つの列を右揃え");//Two columns right-aligned (New)
define("_TWOCOLUMNSLEFT","左の2つの列に整列した");//Two columns left-aligned (New)
define("_THREECOLUMNS","3列");//Three columns (New)
define("_SIMPLE","単純な");//Simple (New)
define("_SAVELAYOUT","割引率のレイアウト");//Save layout (New)
define("_ADDBLOCK","ブロックに追加");//Add block (New)
define("_RESTOREDEFAULTLAYOUT","デフォルトのレイアウトを復元");//Restore default layout (New)
define("_INFOFORCOURSE","情報コースの");//Information for course (New)
define("_PLEASELOGINTOCOMPLETEREGISTRATION","登録を完了するにはログインしてください。");//Please login to complete registration (New)
define("_GOTOLESSONSLIST","レッスンをリストへ");//Go to lessons list (New)
define("_PUBLISHED","公開");//Published (New)
define("_NOTPUBLISHED","公開しない");//Not published (New)
define("_OPTIONSFORPROJECT","プロジェクトのオプション");//Options for project (New)
define("_SKILLGAPTESTRESULTSREMOVEDFROMUSERTHETESTCANBEREPEATED","このユーザーのテスト結果が正常に削除されている。これで、テストは再び完了することができます。");//Test results have been successfully removed for this user. The test can now be completed again. (New)
define("_HOMEOFLESSON","ホームレッスンの");//Home of lesson (New)
define("_OPTIONSFORGROUP","グループのオプション");//Options for group (New)
define("_SURVEYFAILEDTOBEDELETED","調査に削除されることができなかった");//Survey failed to be deleted (New)
define("_COURSESNUMBER","数のコースの");//Number of courses (New)
define("_GROUPSNUMBER","数グループの");//Number of groups (New)
define("_FORUMTITLE","フォーラムのタイトル");//Forum title (New)
define("_OTHERLESSONS","その他のレッスン");//Other lessons (New)
define("_CONTENTREPORT","コンテンツのエラーを報告");//Content error report (New)
define("_CONTENTREPORTTOPROFS","教授に報告内容のエラー");//Report content error to professors (New)
define("_TOPIC","トピック");//Topic (New)
define("_LINK","リンク");//Link (New)
define("_REPORT","報告書");//Report (New)
define("_SUCCESFULLYSENDREPORT","レポートは正常に送信されました");//Your report was successfully sent (New)
define("_ERRORREPORTFOR","レッスンのコンテンツのエラーを報告");//Content error report for lesson (New)
define("_YOUSHOULDCHANGEHEADERLANGUAGETAG","あなたの_HEADERLANGUAGETAG変更してください");//You should change _HEADERLANGUAGETAG in (New)
define("_LANGUAGEFILE","言語ファイル");//language file (New)
define("_YOURSYSTEMSUPPORTS","お使いのシステムをサポートしています");//Your system supports (New)
define("_LINKTOTOPIC","トピックへのリンク");//Link to topic (New)
define("_SCOREINEACHUNIT","各ユニットにスコア");//Score in each unit (New)
define("_SCOREINUNIT","単位でスコアを");//Score in unit (New)
define("_SHOWDETAILS","詳細を表示");//Show details (New)
define("_DISPLAYORDEREDLIST","表示リストに指示");//Display ordered list (New)
define("_AVERAGESCOREON","平均スコアを");//average score on (New)
define("_SCOREONLASTEXECUTION","最後の実行のスコア");//score on last execution (New)
define("_EXECUTIONS","死刑執行");//Executions (New)
define("_RECENTLYCOMPLETEDTESTS","最近のテストを完了");//Recently completed tests (New)
define("_IMPORTNOTICE","警告：既存のすべてのレッスンの情報が消去さ教訓をインポートする");//Warning: importing a lesson will erase all existing lesson information (New)
define("_RESET","リセット");//Reset (New)
define("_RESETGRAPH","リセットグラフ");//Reset graph (New)
define("_CANNOTAUTOMATICALLYLOGIN","自動的にログインできません");//You cannot login automatically (New)
define("_LOGINENTRANCE","ログイン");//Login (New)
define("_SELECTEDLESSONS","選択授業");//Selected lessons (New)
define("_ADDTOLESSONS","レッスンに追加");//Add to lessons (New)
define("_AVAILABLEBLOCKS","利用可能なブロック");//Available blocks (New)
define("_ADDCUSTOMBLOCK","カスタムブロックを追加");//Add custom block (New)
define("_CURRENTLAYOUT","現在のレイアウト");//Current layout (New)
define("_UNDOALLCHANGES","すべての変更を元に戻す");//Undo all changes (New)
define("_BLOCKTITLE","ブロックのタイトル");//Block title (New)
define("_BLOCKCONTENT","ブロックコンテンツ");//Block content (New)
define("_YOUCANNOTACCESSREQUESTEDRESOURCE","あなたは、要求されたリソースへのアクセスすることはできません");//You cannot access the requested resource (New)
define("_TOTALUNITS","総戸数");//Total units (New)
?>
