<?php
if (is_file($GLOBALS['path']."language/custom-chinese_traditional.php.inc")) {
include($GLOBALS['path']."language/custom-chinese_traditional.php.inc");
}
define("_HEADERLANGUAGEHTMLTAG","ch");//en
define("_CURRENTLANGUAGESYMBOL","ch_td");//en
define("_HEADERLANGUAGETAG","chinese");//english
define("_CHARSET","x-Chinese-CNS");//ISO-8859-1
define("_LANGUAGE","語言");//Language
define("_PASSWORD","密碼");//Password
define("_SUBMIT","提交");//Submit
define("_REGISTER","註冊");//Register
define("_CONTACT","聯繫我們");//Contact us
define("_FROM","自");//From
define("_SENDSUCCESS","您的留言已成功發送。感謝您與我們聯繫!");//Your message was sent successfully. Thank you for contacting us!
define("_SENDFAILURE","有一種錯誤。請再試一次。");//A problem has come up. Please try again.
define("_LOGIN","註冊");//Login
define("_NAME","名字");//Name
define("_SURNAME","姓氏");//Surname
define("_ADDRESS","地址");//Address
define("_POSTCODE","郵遞區號");//Post code
define("_CITY","城市");//City
define("_HOMEPHONE","電話號碼");//Phone number
define("_EMAILADDRESS","電子郵件地址");//Email address
define("_COMMENTS","評論");//Comments
define("_TIME","時間");//Time
define("_BACK","&larr;&nbsp;回");//&larr;&nbsp;Back
define("_CONFIGURATIONVARIABLES","系統配置");//System configuration
define("_CHANGESITELOGO","改變網站徽標");//Change site logo
define("_ONLYONELANGUAGE","支持只有一個（默認）語言");//Support only one (the default) Language
define("_YES","是");//Yes
define("_NO","否");//No
define("_UPDATELESSONS","教訓更新");//Update lessons
define("_ADMINEMAIL","管理員電子郵件");//Administrator email
define("_LESSONSDELETED","教訓已刪除");//The lesson was deleted
define("_SHOWFOOTER","顯示頁腳");//Show footer
define("_DEFAULTLANGUAGE","默認語言");//Default language
define("_DIGITALLIBRARY","數位檔案");//Digital file library
define("_BACKUP","備份系統");//Backup system
define("_RESTORE","恢復系統");//Restore system
define("_FREE","這個教訓是免費提供給所有");//This lesson is free for all
define("_SUCCESSREGISTER","您已註冊成功");//You have registered successfully
define("_LESSONSREGISTRATION","教訓登記");//Lesson registration
define("_YOUREMAIL","您的電子郵件");//Your e-mail 
define("_MESSAGESUBJECT","郵件主題");//Message subject
define("_PASSWORDLEAVEBLANK","密碼（空白離開不變）");//Password (blank to leave unchanged)
define("_PERSONALDATACHANGESUCCESS","您的個人信息已成功地改變了");//Your personal info has been successfully altered
define("_REGISTRATIONDATE","登記日期");//Registration date
define("_SAVECHANGES","保存更改");//Save changes
define("_PERSONALDATA","個人信息");//Personal info
define("_LESSONOPTIONS","教訓選項");//Lesson options
define("_PERSONALOPTIONS","工具");//Tools
define("_QUESTIONWEIGHT","問題重量（ 1-10 ）");//Question weight (1-10)
define("_WEIGHT","重量");//Weight
define("_NONEWLESSONREGISTRATIONS","沒有新的教訓登記");//No new lesson registration
define("_LESSONS","教訓");//Lessons
define("_RECREATESEARCHTABLE","重新搜索表");//Recreate search table
define("_LESSONSREGISTRATIONS","教訓登記");//Lesson registrations
define("_TOOLS","工具");//Tools
define("_ONLINEUSERS","對線路用戶");//On line users
define("_DATE","日期");//Date
define("_STUDENT","學生");//Student
define("_LINE","線");//Line
define("_SOMEPROBLEMEMERGED","有些問題已經發生");//Some problem has occured
define("_CORRECTION","正確的 它");//Correct it
define("_LESSONNAME","教訓名稱");//Lesson name
define("_DIRECTION","類別");//Categories
define("_DIRECTIONNAME","類別名稱");//Category name
define("_NEWLESSON","新的教訓");//New lesson
define("_NEWDIRECTION","新的類別");//New category
define("_EMAILSENDAT","電子郵件被送往");//Email was sent to 
define("_CHOOSELESSON","選擇的教訓");//Choose lesson
define("_SUBJECT","題目");//Subject
define("_RECIPIENTSSELECTION","受助人的選擇");//Recipients selection
define("_EMAILBODY","電子郵件機構");//E-mail body
define("_SENDEMAIL","發送電子郵件");//Send E-mail
define("_EXIT","退出");//Exit
define("_MORE","更多");//more
define("_DELETE","刪除");//Delete
define("_MESSAGES","郵件");// Messages
define("_THEORY","理論");//Theory
define("_PROJECTS","項目");//Projects
define("_TESTS","測試");//Tests
define("_PREVIOUS","&lt;後面");//&lt; Previous
define("_NEXT","下一個&gt;");//Next &gt;
define("_CANNOTACCESSTHISUNIT","您不能看到這個單位的 因為：");//You cannot see this unit because:
define("_SENDPERSONALMESSAGE","發送個人訊息");//Send personal message
define("_SEND","發送");//Send
define("_STATISTICS","報告");//Reports
define("_OPTIONS","選項");//Options
define("_THEFIELD","外地");//The field
define("_WELCOMETO","歡迎您到");//Welcome to the
define("_LESSONANNOUNCEMENT","公佈的教訓");//Announcement for the lesson
define("_COLOR","顏色");//Color
define("_HOUR","小時");//hour
define("_HOURS","小時");//hours
define("_MINUTE","分鐘");//minute
define("_MINUTES","分鐘");//minutes
define("_SECONDS","秒");//seconds
define("_LASTLOGIN","最後登錄在");//Last log-in
define("_MEAN","平均");//Average
define("_LOGINAT","日誌-在在");//Log-in at
define("_TESTHADAT","測試完成");//Test completed at
define("_HASMAXIMUMDURATION","它的最長期限");//It had maximum duration
define("_YOURSCOREIS","你的分數是");//Your score is
define("_FINALSCOREWILLBEFROM","最後的評分將來自");//Final score will be from
define("_ANDYOUDIDITIN","你完成了它在");//and you completed it in
define("_TO","至");//to
define("_DEPENDSONQUESTIONS","根據您的答案，開放式回答問題。");//depending on your answers on open-answer questions.
define("_EXAMPLEANSWER","例如答案");//Example answer
define("_SCORE","評分");//Score
define("_THISQUESTIONCORRECTEDPROFESSOR","這個問題將得到糾正，由教授。");//This question will be corrected by the professor
define("_RIGHTANSWER","正確答案");//Correct answer
define("_TESTSHOULDCOMPLETEIN","這項測試必須完成在");//This test must be completed in
define("_TIMELEFT","剩餘時間");//Time remaining
define("_YOUCANNOTLOGINAS","沒有用戶存在與登錄名：");//No user exists with login name:
define("_WRONGPASSWORDTRYAGAIN","你給了錯誤的密碼。請再試一次。");//You gave a wrong password. Please try again.
define("_NOTACTIVATEDACCOUNTTRYAGAINLATER","您的帳戶尚未激活。請稍後再試。");//Your account has not been activated yet. Please try again later.
define("_YOUHAVEBEENEXCLUDEDBYPROFESSOR","你被排除在教授");//You are excluded by professor
define("_MUSTFIRSTREADUNIT","您必須先閱讀單位");//You must first read unit
define("_MUSTFIRSTTAKEATLEAST","您必須先至少需時");//You must first take at least
define("_YOURTIMEISUP","您的時間了");//Your time is up
define("_ATTEST","在測試");//at test
define("_WANTTOREDOTEST","我想重做這個測試");//I want to redo this test
define("_PERCENT","％");//Percent
define("_CANNOTREDOTEST","你不能重做這項測試！");//You cannot redo this test!
define("_LESSON","教訓");//Lesson
define("_ALL","所有內容");//All content
define("_GOTOFORUM","去論壇");//Go to forum
define("_SENDMESSAGEATFORUM","帖子");//Post message
define("_SENDMESSAGE","發送消息");//Send message
define("_ANNOUNCEMENTS","公告");//Announcements
define("_MESSAGESATFORUM","論壇訊息");//Forum messages
define("_PERSONALMESSAGES","個人信息");//Personal messages
define("_SOLVEDTESTS","解決測試");//Solved tests
define("_ATFORUM","在論壇");//At forum
define("_PRINTERFRIENDLY","印刷股");//Print unit
define("_PRINTERFRIENDLYALLCONTENT","打印的所有內容");//Print all the content
define("_ADDCOMMENT","添加評論");//Add comment
define("_LESSONSELECT","選擇的教訓");//Select lesson
define("_CURRENTCONTENT","目前的內容");//Current content
define("_COMMENTDELETED","評論已被刪除");//The comment has been deleted
define("_COMMENTADD","添加評論");//Add comment
define("_ADDYOURCOMMENT","新增您的評論");//Add your comment
define("_SUCCESFULLYADDEDCOMMENT","有人評論說，成功");//The comment was added successfully
define("_SUCCESFULLYUPDATEDCOMMENT","有人評論成功更新");//The comment was updated successfully
define("_SUCCESFULLYDELETEDFILEWINDOWCLOSE5SECONDS","該文件被刪除。該窗口會自動關閉在5秒內。");//The file was deleted. This window will automatically close in 5 seconds.
define("_SUCCESFULLYDELETEDFOLDERWINDOWCLOSE5SECONDS","該文件夾刪除。該窗口會自動關閉在5秒內。");//The folder was deleted. This window will automatically close in 5 seconds.
define("_NOTSUCCESFULLYDELETEDFOLDERWINDOWCLOSE5SECONDS","該文件夾是不會被刪除。它必須不包含任何文件或文件夾予以刪除。該窗口會自動關閉在5秒內。");//The folder was not deleted. It must not contain any files or folders to be deleted. This window will automatically close in 5 seconds.
define("_SUCCESFULLYCREATEDFOLDERWINDOWCLOSE5SECONDS","該文件夾已創建。該窗口會自動關閉在5秒內。");//The folder was created. This window will automatically close in 5 seconds.
define("_FOLDERNAME","文件夾名稱");//Folder name
define("_CREATE","創建");//Create
define("_LESSONNOTSET","的教訓，並未設定。");//The lesson was not set.
define("_COPYNAMESFROMLEFTTORIGHTTOSAVEIMAGES","複製姓名從左邊向右邊一欄，為了節省圖像文件在您的文件。");//Copy names from the left to the right column, in order to save the image files in your document.
define("_THEFILE","檔案");//The file
define("_MUSTBESMALLERTHAN","必須小於");//must be smaller than
define("_KILOBYTES","千字節.");//Kbytes.
define("_HASBEENSEND","被送往。");//was sent.
define("_SENDFILE","發送文件");//Send file
define("_CLOSEWINDOW","關閉窗口");//Close window
define("_UPDATE","更新");//Update
define("_SUCCESFULLYDELETEDANNOUNCEMENTWINDOWCLOSE5SECONDS","通知已成功刪除");//The announcement was deleted successfully
define("_ANNOUNCEMENTADD","新增公告");//Add announcement
define("_ANNOUNCEMENTTITLE","公告標題");//Announcement title
define("_ANNOUNCEMENTBODY","公佈機構");//Announcement body
define("_SUCCESFULLYADDEDANNOUNCEMENTWINDOWCLOSE5SECONDS","宣布加入成功");//The announcement was added successfully
define("_SUCCESFULLYUPDATEDANNOUNCEMENTWINDOWCLOSE5SECONDS","宣布已成功更新");//The announcement was updated successfully
define("_ENDDATEMUSTBEBEFORESTARTDATE","結束日期必須後開始日期。");//End date must be after start date.
define("_SAVE","保存");//Save
define("_SUCCESFULLYUPDATEDQUESTION","問題是，成功更新");//The question was updated successfully
define("_SUCCESFULLYADDEDQUESTION","問題是，添加成功");//The question was added successfully
define("_QUESTIONTEXT","質詢案文");//Question text
define("_SAVEQUESTION","保存問題");//Save question
define("_UNIT","單位");//Unit
define("_QUESTIONTYPE","問題類型");//Type
define("_DIFFICULTY","困難");//Difficulty
define("_RATEMUSTBEBETWEEN0100","評分範圍必須介於0和100之間");//The score must range between 0 and 100
define("_ALLOFTHEM","所有用戶");//All users
define("_VALIDFOR","有效期為");//Valid for
define("_TOBEEXCLUDEDFROMUNIT","被排除在該單位");//to be excluded from the unit
define("_THEUNIT","單位");//the unit
define("_TESTNAME","測試名稱");//Test name
define("_UNITPARENT","母公司股");//Parent unit
define("_SAVETEST","儲存測試");//Save test
define("_SUCCESFULLYADDEDRATE","率為插入成功");//The rate was inserted successfully
define("_STUDENTANSWER","學生的答案");//Student answer
define("_SEARCHTABLERECREATED","搜索表重現");//The search table was recreated
define("_SAVETHE","保存");//Save the
define("_OFTHELESSONATYOURCOMPUTER","的教訓，在您的計算機上。");//of the lesson at your computer.
define("_ATYOURCOMPUTER","在您的計算機上。");//at your computer.
define("_DATAFILE","數據文件");//Data file
define("_NOTGIVEFILENAME","您沒有供應檔案名稱");//You did not supply a file name
define("_LESSONDATAFILE","教訓的數據文件");//Lesson data file
define("_INSERTDATA","進口數據");//Import data
define("_OFLESSON","的教訓");//Of the lesson
define("_CATEGORY","類別");//Category
define("_SEARCH","搜索");//Search
define("_DESCRIPTION","描述");//Description
define("_TYPE","類型");//Type
define("_POSITION","立場");//Position
define("_LESSONCONTENT","教訓內容");//Lesson content
define("_TITLE","標題");//Title
define("_TEXT","文本");//Text
define("_NORESULTSFOUNDINFORUM","沒有結果發現，在論壇");//No results found in forum
define("_SEARCHRESULTSINLESSONS","搜索結果中的經驗教訓");//Search results in lessons
define("_SEARCHRESULTSINFORUM","搜索結果在論壇");//Search results in forum
define("_SEARCHRESULTSINUSERS","搜索結果在用戶");//Search results in users
define("_NOSEARCHRESULTSFOUND","沒有結果發現，在搜索");//No results found during the search
define("_PRINTIT","打印！");//Print it!
define("_LANGUAGEADMINISTRATION","設置語言");//Set languages
define("_INTERMEDIATESELLER","中級推銷員");//Intermediate salesman
define("_PROFESSOR","教授");//Professor
define("_ADMINSTRATOR","管理員");//Administrator
define("_CONTROLCENTER","控制中心");//Control center
define("_EXAMPLES","例子");//Examples
define("_FORUM","論壇");//Forum
define("_NOCONTENT","單位沒有內容");//Unit without content
define("_INACTIVE","停播單位");//Inactive unit
define("_CONTENTMANAGEMENT","內容");//Content
define("_SCHEDULING","調度");//Scheduling
define("_OFDEVELOPMENT","發展");//development
define("_MULTIPLECHOICEONESELECTION","選擇題");//Multiple choices, single correct answer
define("_MULTIPLECHOICEMULTIPLESELECTIONS","選擇題");//Multiple choices, multiple correct answers
define("_OFMATCH","匹配");//matching
define("_OFEMPTYSPACES","在填補空白");//Fill in the blanks
define("_LOW","低的");//Low
define("_MEDIUM","中等");//Medium
define("_HIGH","高的");//High
define("_PERIODSPERSTUDENT","每名學生");//Periods per student
define("_NETMEETINGSUPPORT","NetMeeting的支持");//Netmeeting support
define("_IFSTUDENTHASNOTSEEN","如果學生沒有看到");//If student has not seen
define("_IFSTUDENTHASNOTPASSED","如果學生不獲通過");//If student has not passed
define("_STUDENTALLWAYS","學生總是");//Student allways
define("_ACCESSRULES","教訓規則");//Lesson rules
define("_EMAILS","電子郵件");//Emails
define("_CHAT","聊天");//Chat
define("_OFJANUARY","一月");//January
define("_OFFEBRUARY","二月");//February
define("_OFMARCH","三月");//March
define("_OFAPRIL","四月");//April
define("_OFMAY","可能");//May
define("_OFJUNE","6月");//June
define("_OFJULY","7月");//July
define("_OFAUGUST","8月");//August
define("_OFSEPTEMBER","9月");//September
define("_OFOCTOBER","10月");//October
define("_OFNOVEMBER","十一月");//November
define("_OFDECEMBER","12月");//December
define("_ADDLANGUAGE","新增語言");//Add language
define("_CURRENTLANGUAGES","當前語文");//Current languages
define("_CHANGE","更改");//Change
define("_RETURN","返回");//Return
define("_UPDATESUCCESFULLYMADE","更新成功完成");//The update was completed successfully
define("_LESSONMATERIAL","教訓材料");//Lesson material
define("_NOQUESTIONSSETFORTHISUNIT","有沒有問題界定");//There are no questions defined
define("_ADDQUESTION","新增檢驗項目");//Add question
define("_PREVIEW","預覽");//Preview
define("_NOTESTSSETFORTHISUNIT","沒有測試，發現");//No tests found
define("_ADDTEST","新增測試");//Add test
define("_UNITANDSUBUNITSTESTS","單位和亞基測試");//Unit and subunits tests
define("_NORESULTSFOUND","沒有結果發現！");//No results found!
define("_PAGES","頁面");//pages
define("_UPLOADFILESANDIMAGES","上傳文件和圖像");//Upload files and images
define("_COPYFROMANOTHERLESSON","複製從另一個教訓");//Copy from another lesson
define("_UNITNAME","單位名稱");//Unit name
define("_CONTENTTYPE","內容類型");//Content type
define("_CONTENT","內容");//Content
define("_UPDATEUNIT","更新單位");//Update unit
define("_CREATESUBUNIT","創建亞基");//Create subunit
define("_CREATETEST","創建測試");//Create test
define("_ADDPERIOD","添加期");//Add period
define("_LESSONPERIODS","教訓時期");//Lesson periods
define("_COPY","複製");//Copy
define("_EXCLUDECONSTRAINT","排斥約束");//Exclusion constraint
define("_EXCLUSIONUNIT","排斥股");//Exclusion unit
define("_FUNCTIONS","職能");//Functions
define("_THETEST","測試");//the test
define("_WITHSCOREATLEAST","與率至少");//with rate at least
define("_NOQUESTIONSTOCORRECTFORTHISLESSON","沒有問題，以正確的這個教訓。");//No questions to correct for this lesson.
define("_QUESTIONSTOCORRECT","問題的正確");//Questions to correct
define("_DELETESELECTED","刪除所選");//Delete selected
define("_REDOABLE","試驗重複");//Test repetitions
define("_PROFESSORS","教授");//Professors
define("_CANNOTOPENFOLDER","文件夾無法打開");//The folder can&#039;t be opened
define("_CREATEFOLDER","創建文件夾");//Create folder
define("_OPENFOLDER","打開文件夾");//Open folder
define("_CUT","切割");//Cut
define("_PASTE","粘貼");//Paste
define("_UNDO","撤消");//Undo
define("_REDO","重做");//Redo
define("_FIND","查找");//Find
define("_INSERTHYPERLINK","插入超鏈接");//Insert hyperlink
define("_INSERTIMAGE","插入圖像");//Insert image
define("_NORMAL","正常");//Normal
define("_DEFAULT","默認");//Default
define("_BOLD","大膽");//Bold
define("_ITALIC","斜體");//Italics
define("_UNDERLINED","強調");//Underlined
define("_FONTCOLOR","字體顏色");//Font color
define("_DIMENSIONS","尺寸");//Dimensions
define("_CANCEL","取消");//Cancel
define("_OR","或");//or
define("_LEFT","左邊");//Left
define("_RIGHT","右邊");//Right
define("_UP","向上");//Up
define("_MIDDLE","中東");//Middle
define("_DOWN","向下的");//Down
define("_FILE","文件");//File
define("_SELECTTHEONEYOUWANTASLINK","選擇一個您想要插入超鏈接");//Select the one you want inserted as hyperlink
define("_SELECTTHEONEYOUWANTAS","選擇一個您想要插入");//Select the one you want inserted as
define("_SMALLCAPSHYPERLINK","超連結");//hyperlink
define("_ADD","添加");//Add
define("_NOTE","注意：");//Note
define("_SELECTLESSON","選擇的教訓");//Choose lesson
define("_STUDENTS","學生");//Students
define("_ADMINISTRATORS","管理員");//Administrators
define("_LESSONSTATISTICS","教訓的報告");//Lesson reports
define("_FILES","檔案");//Files
define("_TOTALSIZE","總面積");//Total size
define("_NEWMESSAGE","新訊息");//New message
define("_PARTICIPATION","參與");//Participation
define("_AVERAGE","平凡");//unremarkable
define("_ACTIVE","活躍");//Active
define("_PASSWORDLOST","忘記您的密碼?");//Forgot your password?
define("_ANEMAILHASBEENSENT","一封電子郵件，指示發送給您。");//An email with instructions was sent to you.
define("_PASSWORDRECOVERY","恢復您的密碼");//Recover your password
define("_THENEWPASSWORDIS","您的新密碼是：");//Your new password is: 
define("_EMAILWITHPASSWORDSENT","一封電子郵件，您的新密碼發送給您。");//An email with your new password was sent to you.
define("_LINEARCONTENT","內容秩序");//Content order
define("_ONEBYONE","顯示的問題，一個一個地");//Show questions one by one
define("_NEXTQUESTION","接下來的問題");//Next question
define("_IDONOTWANTTODOTHETEST","請帶我回。");//I changed my mind. Please take me back
define("_YOUHAVE","你有");//You have
define("_SENDFILEASANSWER","上傳一個文件作為一個答案");//Upload a file as an answer
define("_FILEUPLOADED","上載的文件");//File uploaded
define("_PREVIOUSQUESTION","先前的問題");//Previous question
define("_RESTARTLESSON","教訓初始化");//Lesson initialization
define("_RESTARTLESSONCOMPLETED","教訓已經初始化");//The lesson has been initialized
define("_UPLOADFILE","上傳文件");//Upload file
define("_PROBLEMUPLOADINGFILE","有一個問題與上傳。");//There was a problem while uploading file
define("_SHOW","顯示");//Show
define("_URL","網址");//URL
define("_TARGET","目標");//Target
define("_NONE","毫無");//None
define("_OTHER","其他");//Other
define("_TEXTTOP","texttop");//Texttop
define("_ABSMIDDLE","absmiddle");//Absmiddle
define("_ABSBOTTOM","absbottom");//Absbottom
define("_BASELINE","基線");//Baseline
define("_CELLSPACING","細胞間距");//Cell spacing
define("_CELLPADDING","細胞填充");//Cell padding
define("_EM","教統");//Em
define("_WIDTH","寬度");//Width
define("_ALIGN","對齊");//Align
define("_BORDER","邊境");//Border
define("_BOTTOM","底部");//Bottom
define("_CSS","的CSS");//CSS
define("_CAPTION","標題");//Caption
define("_CENTER","中心");//Center
define("_CHAR","煤焦");//Char
define("_HEIGHT","高度");//Height
define("_JUSTIFY","理由");//Justify
define("_MARGIN","保證金");//Margin
define("_PADDING","填充");//Padding
define("_RULES","規則");//Rules
define("_SUMMARY","摘要");//Summary
define("_TEXTALIGN","文本對齊");//Text align
define("_TOP","頂端");//Top
define("_ENTER","註冊");//Login
define("_HASBEENLOGGEDOUT","已登出");//has been logged out
define("_LOGOUT","登出");//Log out
define("_EACHFILESIZEMUSTBESMALLERTHAN","每個檔案必須小於");//Each file must be smaller than
define("_DONE","做完");//Done
define("_UPLOADTHESCORMFILEINZIPFORMAT","上傳SCORM的檔案在ZIP格式");//Upload SCORM file in ZIP format
define("_SCORMEXPORT","出口的教訓， SCORM的");//Export lesson to SCORM
define("_SCORMIMPORT","進口SCORM的內容");//Import SCORM content
define("_FORUMPOSTS","論壇訊息");//Forum messages
define("_TOTAL","總");//Total
define("_ALLLESSONS","所有的經驗教訓");//All lessons
define("_STUDENTSOFLESSON","學生的教訓");//Students of lesson
define("_REVIEWSCORMDATA","檢討SCORM的數據");//Review SCORM data
define("_IMPORTOFUNIT","進口單位");//Import of unit
define("_SELECTFILE","選擇一個檔案");//Select a file
define("_THESYSTEMSUGGESTSTHEFILES","該系統的建議文件");//The systems suggests the files
define("_CHECKIFITISASINGLESCO","檢查如果是一個單一的上海合作組織");//Check if it is a single SCO
define("_CHOOSESTUDENT","選擇一個學生");//Select a student
define("_NOSCORMDATAFOUNDFORTHISSTUDENT","沒有SCORM的數據，發現這名學生");//No SCORM data found for this student
define("_ENTRY","進入");//Entry
define("_TOTALTIME","總時間");//Total time
define("_MINSCORE","最低分數");//Minimum score
define("_MAXSCORE","最高評分");//Maximum score
define("_FINALSCORE","最後評分");//Final score
define("_TOCAPITAL","至");//To
define("_NOTEPUBLICROOMSARESTOREDANDACCESSED","注意：會話在公共聊天室，都記錄並提供給所有用戶");//Note: Conversations in public rooms are recorded and made available to all users
define("_PRIVATEROOM","私人房間");//Private room
define("_ENTEREDROOM","進入房間");//entered the room
define("_LEFTTHEROOM","離開房間");//left the room
define("_WRONGROOMID","錯誤的房間編號");//Wrong room id
define("_EXITCHAT","退出聊天");//Exit chat
define("_ADJUSTTOPAGE","調整頁");//Adjust to page
define("_CREATEPUBLICROOM","創造公共空間");//Create public room
define("_CREATEPRIVATEROOM","創建私人房間");//Create private room
define("_OPENROOMS","開放室");//Open rooms
define("_NEWPUBLICROOM","新的公共空間");//New public room
define("_NEWPRIVATEROOM","新的私人房間");//New private room
define("_SHOWPASTCOVERSATIONS","查看過去的談話");//Show past conversations
define("_PUBLICROOMS","公共聊天室");//Public rooms
define("_PRIVATEROOMS","單人房");//Private rooms
define("_PARTICIPANTS","與會者");//participants
define("_NOROOMSFOUND","沒有客房發現");//No rooms found
define("_DEACTIVATE","停用");//Deactivate
define("_ACTIVATE","激活");//Activate
define("_SYSTEMMESSAGE","系統訊息");//System message
define("_ROOMALREADYEXISTS","一個房間已經存在具有此名稱");//A room with this name already exists
define("_ROOMNAME","客房名稱");//Room name
define("_ACTIVENEUTRAL","活躍");//Active
define("_SHOWCONVERSATIONSFORROOM","顯示會話為室");//Show conversations for the room
define("_NOMESSAGESFOUNDFORTHISINTERVAL","無會話，發現在這個房間為指定的時間間隔");//No conversations found in this room for the specified interval
define("_MESSAGE","訊息");//Message
define("_FILESIZE","文件大小");//File size
define("_ILLEGALFILENAME","非法文件名");//Illegal file name
define("_IRREVERSIBLEACTIONAREYOUSURE","此操作是不可逆轉的！您是否確定?");//This operation is irreversible! Are you sure?
define("_FILENAME","檔案名稱");//File name
define("_SUCCESFULLYDELETEDFILE","成功刪除文件");//Successfully deleted file
define("_TAKEBACKUP","備份！");//Backup!
define("_SUCCESFULLYBACKEDUP","備份成功地完成了");//Backup successfully completed
define("_NONEXISTINGMAIL","此電子郵件，並不屬於任何用戶");//This email/login does not belong to any user
define("_PORT","服務器端口");//Server port
define("_DATABASE","數據庫名稱");//Database name
define("_ACTIVATELDAP","啟動LDAP支持");//Activate LDAP support
define("_LDAPSERVER","LDAP服務器");//LDAP server
define("_LDAPBINDDN","LDAP的綁定的DN");//LDAP bind DN
define("_LDAPPASSWORD","LDAP的綁定密碼");//LDAP bind password
define("_SUPPORTONLYLDAP","只支持LDAP的註冊");//Support only LDAP registration
define("_LOGINATTRIBUTE","登入名稱屬性");//Login name attribute
define("_LDAPCOMMONNAME","全稱屬性");//Full name attribute
define("_LDAPADDRESS","地址屬性");//Address attribute
define("_LDAPLOCALITY","城市屬性");//City attribute
define("_LDAPTELEPHONENUMBER","電話號碼屬性");//Phone number attribute
define("_LDAPMAIL","電子郵件屬性");//Email attribute
define("_LDAPLANGUAGE","語言屬性");//Language attribute
define("_CHECKSETTINGS","檢查設置");//Check settings
define("_LDAPPORT","LDAP服務器港口");//LDAP server port
define("_USESSL","使用SSL連線");//Use SSL connection
define("_CANNOTCONNECTLDAPSERVER","該系統是無法連接到LDAP服務器");//The system was unable to connect to LDAP server
define("_CANNOTBINDLDAPSERVER","系統無法綁定到LDAP服務器");//The system was unable to bind to LDAP server
define("_LDAPCONFIGURATION","LDAP的配置");//LDAP configuration
define("_LDAPBASEDN","LDAP的基本DN");//LDAP Base DN
define("_YOUHAVEALREADYCORRECTEDTHISQUESTION","你已經糾正了這一問題");//You have already corrected this question
define("_SHOWALL","顯示所有");//Show all
define("_TOTALLOGINS","總系統登錄");//Total system logins
define("_ALLOWEDIPS","允許的IPS");//Allowed IPs
define("_COMMASEPARATEDLISTASTERISKEXAMPLE","以逗號分隔的列表中。星號*是不允許的。例如： 192.168.0 .* ， 192.168.1.1 ， 192.168.1.100");//Comma separated list. The asterisk * is allowed. Example: 192.168.0.*, 192.168.1.1, 192.168.1.100
define("_DISALLOWEDIPS","不允許的IPS");//Disallowed IPs
define("_ALLOWEDEXTENSIONS","允許文件擴展名");//Allowed file extensions
define("_DISALLOWEDEXTENSIONS","不允許的文件擴展名");//Disallowed file extensions
define("_COMMASEPARATEDLISTASTERISKEXTENSIONEXAMPLE","以逗號分隔的列表中。例如： PHP中， js ，壓縮EXE的CGI");//Comma separated list. Example: php, js, exe, cgi
define("_DENIALTAKESPRECEDENCE","拒絕的先導許可。如果這兩個領域都留空，然後一切都讓");//Denial precedes permission. If both fields are left blank, then everything is allowed
define("_EFRONT","eFront");//eFront
define("_CONTACTUS","聯繫我們");//Contact us
define("_EFRONTLOGIN","登錄到eFront");//Login to eFront
define("_LDAPPROTOCOLVERSION","LDAP協議版本");//LDAP Protocol Version
define("_GOTOINBOX","去收件箱");//Go to inbox
define("_RECENTCOMMENTS","最新評論");//Last comments
define("_CONTROLPANEL","控制面板");//Control panel
define("_YOUCANNOTCREATETHISFOLDER","你不能建立這樣一個文件夾");//You cannot create such a folder
define("_INVALIDID","無效的編號");//Invalid id
define("_UNPRIVILEGEDATTEMPT","你沒有特權，以執行這個動作");//You do not have the priviledges to perform this action
define("_INVALIDLOGIN","無效的登錄名");//Invalid login name
define("_DOWNLOADLANGUAGEFILE","下載的語言文件");//Download language file
define("_SOMEPROBLEMOCCURED","有些問題發生");//Some problem occured
define("_ALTERNATIVELYCOPYANDPASTEBROWSER","另外，您也可以鏈接複製並粘貼在您的瀏覽器的地址欄");//Alternatively, you may copy the link and paste it in your browser&#039;s address field
define("_YOUCANNOTACCESSTHISFOLDER","您沒有訪問此文件夾");//You do not have access to this folder
define("_YOUCANNOTDELETETHISFILE","您不能刪除此文件");//You cannot delete this file
define("_TRIEDTODELETE","試圖刪除文件");//Tried to delete file
define("_ACTION","行動");//Action
define("_NOTES","債券");//Notes
define("_SENDFILES","傳送檔案");//Send files
define("_YOUCANNOTUPLOADFILESWITHTHISEXTENSION","你不能上傳文件與此擴展");//You cannot upload files with this extension
define("_YOUMAYONLYUPLOADFILESWITHEXTENSION","你只可以上傳文件與擴展");//You may only upload files with extension
define("_COULDNOTCREATEFOLDER","無法創建文件夾。請檢查文件夾名稱和該文件夾不存在");//Could not create folder. Please check the folder name and that the folder does not already exist
define("_REGISTERANEWACCOUNT","新的用戶帳戶");//New user account
define("_REC","建議");//rec
define("_SUCESSFULLYCONNECTEDTOLDAPSERVER","成功連接到LDAP服務器");//Successfully connected to LDAP server
define("_DIRECTIONDELETED","類別刪除");//Category deleted
define("_NOANNOUNCEMENTSPOSTED","沒有張貼公告，為這個教訓");//No announcements posted for this lesson
define("_NONEWFORUMMESSAGES","沒有論壇的郵件就這個教訓");//No forum messages regarding this lesson
define("_NONEWPERSONALMESSAGES","沒有新的個人信息在您的收件箱");//No new personal messages in your inbox
define("_NONEWCOMMENTS","沒有新的評論");//No new comments
define("_NOMATERIALINTHISLESSON","的教訓，目前是空的");//The lesson is currently empty
define("_NOSOLVEDTESTSFOUND","沒有解決測試");//No solved tests
define("_NORELATEDPOSTSFOUND","沒有職位，與此有關的單位。");//No posts relevant to this unit.
define("_SUCCESSFULLYCREATEDLESSON","教訓是成功創建");//The lesson was created successfully
define("_SORRYNEEDIFRAME","對不起，您需要iframe支持使用聊天室");//Sorry, you need iframe support to use the Chat
define("_TOPICSUBJECT","主題的主旨");//Topic subject
define("_SEARCHRESULTS","搜索結果");//Search results
define("_NORESULTSFOUNDINPERSONALMESSAGES","沒有結果發現，在個人信息");//No results found in personal messages
define("_SEARCHRESULTSINPERSONALMESSAGES","搜索結果，在個人信息");//Search results in personal messages
define("_SEARCHRESULTSINCOURSES","搜索結果在課程");//Search results in courses
define("_MESSAGEFOLDER","消息文件夾");//Message folder
define("_EMAIL","電子郵件");//e-mail
define("_RESETPASSWORD","重設密碼");//Reset password
define("_JOINED","加入");//Joined
define("_MOREINFO","更多信息");//More info
define("_AVERAGESCORE","平均分數");//Average score
define("_CHATMESSAGES","聊天訊息");//Chat messages
define("_MONTHLOGINS","登錄上個月");//Logins last month
define("_WEEKLOGINS","登錄上週");//Logins last week
define("_MEANDURATION","意味著會議時間");//Mean session duration
define("_MONTHMEANDURATION","意味著會議的時間上個月");//Mean session duration last month
define("_WEEKMEANDURATION","意味著會議的時間上星期");//Mean session duration last week
define("_MONTH","一個月");//Month
define("_WEEK","週");//Week
define("_PRICE","價格");//Price
define("_DURATION","會議時間");//Session duration
define("_MAINTENANCE","維修");//Maintenance
define("_FORUMLASTMESSAGE","最近一則留言，在論壇");//Last message in forum
define("_MESSAGESFOLDERS","個人郵件文件夾");//Personal messages folders
define("_FOLDERS","文件夾");//Folders
define("_CHATLASTMESSAGE","最近一則留言，在聊天室");//Last message in chat
define("_INFO","信息");//Information
define("_LASTPOST","最後發表的帖子");//Last post
define("_TOTALQUESTIONS","總的問題");//Total questions
define("_DEVELOPMENT","發展");//Development
define("_MULTIPLEONE","多種選擇-單一的正確答案");//Multiple choices - Single correct answer
define("_MULTIPLEMANY","多種選擇-許多正確的答案");//Multiple choices - Many correct answers
define("_MATCH","比賽");//Match
define("_EMPTYSPACES","空白");//Empty spaces
define("_LOWDIFFICULTY","低難度");//Low difficulty
define("_MEDIUMDIFFICULTY","中等難度");//Medium difficulty
define("_HIGHDIFFICULTY","高困難");//High difficulty
define("_CATEGORIES","類別");//Categories
define("_OVERALL","全部的");//Overall
define("_BACKTOTOP","回到頂部");//Back to top
define("_STATISTICSFORLESSON","報告的教訓");//Reports for lesson
define("_GENERALLESSONINFO","一般的教訓信息");//General lesson information
define("_LESSONPARTICIPATIONINFO","的教訓，參與信息");//Lesson participation information
define("_LESSONCONTENTINFO","課的內容信息");//Lesson content information
define("_TESTINFO","測試信息");//Test information
define("_QUESTIONINFO","問題信息");//Question information
define("_VIEWTEST","鑑於測試");//View test
define("_SYSTEMSTATISTICS","系統報告");//System reports
define("_ORDER","命令");//Order
define("_TEST","測試");//Test
define("_TOPICSUCCESFULLYCREATED","該專題的成功創建");//The topic was created successfully
define("_SUCCESFULLYPOSTEDMESSAGE","您的留言已發布成功");//Your message was posted successfully
define("_SUCCESFULLYUPDATEDTOPIC","該專題已成功更新");//The topic was updated successfully
define("_SUCCESFULLYUPDATEDMESSAGE","您的留言已成功更新");//Your message was updated successfully
define("_INVISIBLE","無形");//Invisible
define("_LOCKED","鎖定");//Locked
define("_PUBLIC","市民");//Public
define("_PREVIEWMESSAGE","預覽郵件");//Preview message
define("_BODY","身體");//Body
define("_ATTACHMENT","附加的");//Attachment
define("_RECENTMESSAGESATFORUM","最近一則留言");//Last messages at Forum
define("_RECENTUNREADPERSONALMESSAGES","最近的未讀的個人信息");//Recent unread personal messages
define("_NOCONTENTAVAILABLE","本單位的內容類型目前無法使用");//No units of this content-type currently available
define("_THEREWASAPROBLEMDELETETINGFILEWINDOWCLOSE5SECONDS","問題發生在文件刪除。該窗口會自動關閉在5秒內");//A problem occured during the file deletion. This window will close automatically in 5 seconds
define("_TRIEDTOCREATEFOLDER","試圖創建文件夾：");//Tried to create folder:
define("_COULDNOTCREATEFOLDERWINDOWCLOSE5SECONDS","文件夾無法建立。該窗口會自動關閉在5秒內");//The folder could not be created. This window will close automatically in 5 seconds
define("_INVALIDNAME","無效的名稱");//Invalid name
define("_THISFOLDERCONTAINS","此文件夾包含");//This folder contains
define("_TOPICS","話題");//Topics
define("_FILEDOESNOTEXIST","文件不存在");//File does not exist
define("_ADDLINK","添加鏈接");//Add link
define("_CONTENTUNITS","內容單位");//Content units
define("_MAINPAGE","主網頁");//Main page
define("_PLEASEGIVEYOURLOGINOREMAIL","請您給您的登錄或電子郵件");//Please give your login or email
define("_LESSONSETTINGS","政府當局");//Administration
define("_ADMINISTRATOR","管理員");//Administrator
define("_PROGRESS","進展");//Progress
define("_IMAGEFILE","圖像文件");//Image file
define("_SETAVATAR","一套化身");//Set avatar
define("_CURRENTAVATAR","目前的化身");//Current avatar
define("_DELETECURRENTAVATAR","刪除當前的化身");//Delete current avatar
define("_ONLYIMAGEFILESAREVALID","只有圖片文件都是有效的。請選擇一個圖像文件。");//Only image files are valid. Please select an image file.
define("_VIEWLIST","檢視清單");//View list
define("_SUCCESFULLYSETAVATAR","新的精靈是設置成功");//New avatar is successfully set
define("_TOPICDELETEDSUCCESSFULLY","話題已成功刪除");//Topic deleted successfully
define("_MESSAGEDELETEDSUCCESSFULLY","信息已成功刪除");//Message deleted successfully
define("_POSTS","職位");//Posts
define("_BY","通過");//by
define("_NEWCATEGORY","新的類別");//New category
define("_FORUMCONFIGURATIONPANEL","論壇配置小組");//Forum configuration panel
define("_VIEWS","意見");//Views
define("_STICKY","手杖");//Sticky
define("_NOTOPICSFOUND","沒有主題發現");//No topics found
define("_NEWTOPIC","新話題");//New topic
define("_POSTEDBY","張貼");//Posted by
define("_ON","在");//on
define("_INREPLYTO","在答复");//in reply to
define("_REPLYWITHQUOTE","引帖回复");//Reply with quote
define("_QUOTE","引用");//quote
define("_REPLY","回复");//Reply
define("_AREYOUSUREYOUWNATTODELETEMESSAGE","您確定要刪除郵件");//Are you sure you want to delete message
define("_EDIT","編輯");//Edit
define("_STATUS","身份");//Status
define("_NOMESSAGESFOUND","沒有郵件，發現");//No messages found
define("_GOTOCHATROOMSLIST","去聊天室名單");//Go to chat rooms list
define("_ROOM","房間");//Room
define("_INVITE","邀請");//Invite
define("_INVITESYOUCLICKLINK","已要求聊天。點擊下面的鏈接，將要採取的聊天室。");//invites you to a chat session. Click the link below to be taken to the chat room.
define("_GOTOCHATROOM","去聊天室");//Go to chat room
define("_CHATINVITATION","聊天邀請");//Chat invitation
define("_NEWCONTENT","新的內容");//New content
define("_NONEWCONTENT","沒有新的內容");//No new content
define("_TEMPLATE","範本");//Template
define("_APPLY","應用");//Apply
define("_PRIVATECONVERSATIONWITH","私人談話");//Private conversation with
define("_TORESPOND","回應...");//to respond...
define("_TOAPRIVATECONVERSATION","以私人談話");//to a private conversation
define("_INVITESYOUTOPRIVATECONVERSATION","是邀請你到一個私人談話");//is inviting you to a private conversation
define("_DOYOU","你");//Do you
define("_QUESTIONMARK","?");//?
define("_CONVERSATIONINVITATIONACCEPTED","您的請求被接受");//The conversation invitation was accepted
define("_CONVERSATIONINVITATIONDENIED","該會話的邀請被拒絕");//The conversation invitation was denied
define("_YOUACCEPT","接受");//accept
define("_YOUDENY","拒絕");//deny
define("_THEMAILCOULDNOTBESENDTRYLATER","該電子郵件無法傳送。請稍後再試，或聯繫系統管理員");//The email could not be send. Please try again later or contact the system administrator
define("_AUTOMATEDEMAILSENTFROM","自動電子郵件發送地址：");//Automated email sent from address:
define("_CLIKCINGONTHELINKWILLCONFIRM","點擊鏈接，將確認您的電子郵件地址是有效的，所以一個新的密碼，可以發送給您。");//Clicking on the link will confirm that your email address is valid so a new password can be sent to you.
define("_FORFURTHERCONTACTADMINAT","如需進一步資料，您可以聯絡系統管理員，在");//For further information, you may contact the system administrator, at
define("_KINDREGARDSEFRONT","的親切問候， eFront系統");//Kind regards, eFront system
define("_THISISANAUTOMATEDEMAILSENTFROM","這是一個自動發送的電子郵件從");//This is an automated email sent from
define("_BECAUSEYOUASKEDTORECOVERPASSWORD","因為你問到要恢復您的密碼。");//because you asked to recover your password.
define("_PLEASECLICKTHECONFIRMATIONLINKBELOW","請確認下面的鏈接：");//Please click the confirmation link below:
define("_WITHTHENEWPASSWORD","與您的新eFront帳戶密碼。");//with your new eFront account password.
define("_REGISTRATIONEMAIL","註冊電子郵件");//Registration email
define("_CURRENCYSYMBOL","&euro;");//&euro;
define("_ELEARNINGPLATFORM","網絡學習平台");//eLearning platform
define("_ACCOUNTACTIVATEDWITHPERSONALINFORMATION","您的帳戶已成功創建與以下個人資料：");//Your account was successfully created with the following personal information:
define("_YOUHAVEAPPLIEDFORTHELESSONS","您已申請參加以下教訓：");//You have applied to attend the following lessons:
define("_YOUMAYSTARTUSINGFREEIMMEDIATELYBUTNOTNONFREE","您可能會開始出席的教訓，都是免費的立即。如果您的選擇，包括教訓，不屬於免費，自由，管理員必須適用於您的選擇，才能使用他們。");//You may start attending lessons that are free immediately. If your selection includes lessons that are not free, the administrator must apply your selection before using them.
define("_YOUMAYALTERPERSONALINFORMATIONFROMSETTINGS","所有個人信息您所提交的，以及您的教訓，選擇，可能會改變在任何時候從您的個人設置頁。");//All the personal info you have submitted, as well as your lessons selection, may be altered at any time from your personal settings page.
define("_YOUMAYLOGINIMMEDIATELY","您可以登錄並開始使用該系統立即");//You may login and start using the system immediately
define("_YOUMAYLOGINWHENADMINACTIVATESYOU","你可以開始使用該系統盡快管理員激活您的帳戶");//You may start using the system as soon as the administrator activates your account
define("_EMAILSENTFROM","發送的電子郵件從");//Email sent from
define("_STUDENTSOFLESSONSMALL","學生的教訓");//students of lesson
define("_DIRECTIONDEACTIVATED","類別停用");//Category deactivated
define("_DIRECTIONACTIVATED","類激活");//Category activated
define("_LESSONUPDATED","教訓更新");//Lesson updated
define("_LESSONDEACTIVATED","教訓停用");//Lesson deactivated
define("_LESSONACTIVATED","教訓啟動");//Lesson activated
define("_VIEWALL","查看所有");//View all
define("_FILESANDSUBFOLDERS","文件和子文件夾");//files and subfolders
define("_ATTACHMENTS","附加的");//Attachments
define("_PROBLEMQUERYINGDATABASE","問題查詢數據庫");//Problem querying database
define("_FIRSTNAME","名字");//First name
define("_LASTNAME","姓氏");//Last name
define("_LESSONSTATUS","教訓地位");//Lesson status
define("_SPACEUSAGE","空間使用");//Space usage
define("_NEWFOLDER","新文件夾");//New folder
define("_VIEWFOLDERSTATISTICS","查看文件夾統計");//View folder statistics
define("_VIEWMESSAGE","檢視郵件");//View message
define("_OFTOTAL","總");//of total
define("_KBYTESUSED","Kbyte的使用");//Kbytes used
define("_MARK","馬克");//Mark
define("_WITHSELECTED","與選定");//With selected
define("_MARKASREAD","馬克&nbsp;as&nbsp;閱讀");//Mark&nbsp;as&nbsp;read
define("_MARKASUNREAD","馬克&nbsp;as&nbsp;未讀");//Mark&nbsp;as&nbsp;unread
define("_MOVETOFOLDER","移至文件夾");//Move to folder
define("_MOVE","移動");//Move
define("_PERSONALMESSAGE","個人訊息");//Personal message
define("_FROM2","來自：");//From:
define("_TO2","到：");//To:
define("_SUBJECT2","主題：");//Subject:
define("_BECAUSEYOURMESSAGEBOXISFULL","因為您的消息框是充分");//because your message box is full
define("_YOURMESSAGETO","您的郵件");//Your message to
define("_COULDNOTBEDELIVERED","無法交付");//could not be delivered
define("_BECAUSEHISMESSAGEBOXISFULL","因為他的消息框是充分");//because his message box is full
define("_THEMESSAGE","訊息");//Message
define("_MESSAGEWASSENT","發送郵件");//Message was sent 
define("_INVALIDFOLDERNAME","無效文件夾名稱");//Invalid folder name
define("_SORRYYOUCANNOTCREATEANYMOREFOLDERS","抱歉，但你不能創造任何其他文件夾");//Sorry but you cannot create any other folders
define("_FOLDERWITHSAMENAMEALREADYEXISTS","一個文件夾具有相同名稱已經存在");//A folder with the same name already exists
define("_FOLDERCREATED","建立的資料夾");//Folder created
define("_FOLDERUPDATED","文件夾更新");//Folder updated
define("_FOLDERDELETED","文件夾刪除");//Folder deleted
define("_NEWFOLDERNAME","新的資料夾名稱");//New folder name
define("_THISFOLDERDOESNOTEXIT","這個文件夾不存在");//This folder does not exist
define("_MODIFY","更改");//Modify
define("_FOLDER","文件夾");//Folder
define("_SIZE","大小");//Size
define("_YOUMUSTSPECIFYANACTION","您必須指定一個行動");//You must specify an action
define("_ALLOWHTMLFPM","允許的HTML在論壇和個人信息");//Allow HTML in Forum and Personal messages
define("_ACTIVATEPOLLS","激活調查");//Activate polls
define("_ALLOWATTACHMENTSINF","允許附件在論壇");//Allow attachments in forum
define("_PMQUOTA","個人信息配額");//Personal messages quota
define("_PMATTACHMENTSQUOTA","個人郵件的附件配額");//Personal messages attachments quota
define("_YOUMUSTSELECTMESSAGESTODELETE","您必須選擇要刪除的郵件");//You must select messages to delete
define("_YOUMUSTSELECTMESSAGESTOMOVE","您必須選擇郵件動議");//You must select messages to move
define("_YOUMUSTSELECTMESSAGESTOMARK","您必須選擇訊息給馬克");//You must select messages to mark
define("_SUCCESSFULLYDELETEDMESSAGES","郵件被成功刪除");//Messages were successfully deleted
define("_AREYOUSURETODELETEFOLDER","您確定要刪除的文件夾");//Are you sure you want to delete folder
define("_ANDALLCONTENTS","和所有其組成部分?");//and all its components?
define("_APPROACHINGMESSAGEQUOTA","您已接近您的郵件配額。");//You are approaching your message quota.
define("_DELETEOLDMESSAGES","請刪除所有舊郵件，以節省空間。");//Please delete any old messages to save space.
define("_MESSAGEBOXSIZECRITICAL","您的郵件框大小是至關重要的。");//Your messages box size is critical.
define("_ERASEMESSAGESNOTRECEIVENEW","如果您不清除的任何訊息，您將無法獲得新的。");//If you don&#039;t erase any messages, you will not be able to receive new ones.
define("_NOMESSAGESINFOLDER","沒有郵件在此文件夾中");//No messages in this folder
define("_AREYOUSURETODELETEMESSAGE","您確定要刪除此訊息?");//Are you sure you want to delete this message?
define("_TRIEDACCESSMESSAGEMALFORMEDID","試圖訪問的訊息，畸形編號");//Tried to access messages with malformed id
define("_THISMESSAGEDOESNOTEXIST","此消息是不存在的");//This message does not exist
define("_RETURNFOLDERSLIST","返回到文件夾列表");//Return to folders list
define("_TOFORUM","至");//To
define("_RE","關於");//Re
define("_INCOMING","傳入");//Incoming
define("_SENT","已發送");//Sent
define("_DRAFTS","草稿");//Drafts
define("_CALENDAR","日曆");//Calendar
define("_JANUARY","一月");//January
define("_FEBRUARY","二月");//February
define("_MARCH","三月");//March
define("_APRIL","四月");//April
define("_MAY","可能");//May
define("_JUNE","6月");//June
define("_JULY","7月");//July
define("_AUGUST","8月");//August
define("_SEPTEMBER","9月");//September
define("_OCTOBER","10月");//October
define("_NOVEMBER","十一月");//November
define("_DECEMBER","12月");//December
define("_MON","米");//M
define("_TUE","噸");//T
define("_WED","瓦特");//W
define("_THU","噸");//T
define("_FRI","f");//F
define("_SAT","s");//S
define("_SUN","s");//S
define("_VALUE","價值");//Value
define("_PERSONALDATACHANGESUCCESSADMIN","個人信息已成功變更");//User&#039;s personal info have been successfully altered
define("_CONTINUE","繼續");//Continue
define("_WEB","個人網頁");//Personal page
define("_DATA","數據");//Data
define("_USERNAMEERROR","請輸入顯示名稱！");//Please enter the a display name!
define("_CVERROR","請填寫在一些關於您的信息！");//Please fill in some information about you!
define("_NUM","股票數量");//Ticker number
define("_SCORM","SCORM的");//SCORM
define("_MYSETTINGS","我的設置");//my Settings
define("_MYLESSONS","我的教訓");//my Lessons
define("_MYOPTIONS","我的選擇");//my Options
define("_YOUHAVENOBOOKMARKS","你有沒有書籤");//You have no bookmarks
define("_ADDCONTENT","新增內容");//Add content
define("_NEWMESSAGES","新郵件");//New messages
define("_DOYOUWANTTOADDTHISPAGETOYOURBOOKMARKS","你要添加此頁到您的書籤嗎?");//Do you want to add this page to your bookmarks?
define("_BOOKMARKS","書籤");//Bookmarks
define("_SHOWBOOKMARKS","顯示書籤");//Show bookmarks
define("_ADDTHISPAGETOYOURBOOKMARKS","將此網頁添加到您的書籤");//Add this page to your bookmarks
define("_YOUCANDOTEST","你可以做的測試");//You can do test
define("_TIMESMORE","額外");//times more
define("_FIELDNAME","字段名稱");//Field name
define("_FIELDDESCRIPTION","實地描述");//Field description
define("_DBTYPE","數據庫類型");//Database type
define("_ADDFIELD","添加字段");//Add field
define("_TREESAVEDSUCCESSFULLY","樹保存succefully");//Tree saved succefully
define("_ERROROCCURED","發生一個錯誤。請再試一次。");//An error occured. Please try again.
define("_EXPORTSTATS","出口報告：");//Export reports:
define("_MATHTYPEHELP1","您可以插入數學表達式在編輯器中使用特殊代碼，其中tranlates一個ASCII的數學符號，以數學表達式。 eFront已建成編輯這個特別的代碼。因此，用戶可以方便地添加數學類型。您可以了解此代碼從下面的表格，或從<a target=\"_blank\" href=\"http://www1.chapman.edu/~jipsen/mathml/asciimath.html\">這個網頁</a>");//You can insert math expressions in the editor by using a special code which tranlates an ASCII math notation to mathematic expressions. eFront has built into editor this special code. So users can easily add math types. You can learn about this code from the table below or from <a target=\"_blank\" href=\"http://www1.chapman.edu/~jipsen/mathml/asciimath.html\">this page</a>
define("_MATHTYPEHELP2","<p>你應該避免使用 \ 象徵，因為它代表著特殊字符為編碼。在情況下，您要使用它");//<p>You should  avoid to use symbol \` because it represents a special character for the encoding. In case you want to use it, use escape character \ before it, e.g. \\\`</p>
define("_PERCENTCORRECT","％正確的");//percent correct
define("_GLOSSARY","詞彙");//Glossary
define("_ADDDEFINITION","新增的定義");//Add definition
define("_SUCCESFULLYADDEDDEFINITION","的定義是添加成功");//The definition was added successfully
define("_DEFINITION","定義");//Definition
define("_NODEFINITIONSFOUNDFORTHISLESSON","沒有定義，發現這個教訓");//No definitions found for this lesson
define("_CHOOSEWHATTOEXPORT","選擇什麼出口（除內容）");//Choose what to export (apart from content)
define("_CREATED","創建");//Created
define("_CANCELTEST","取消測試");//Cancel test
define("_DELETEEXISTINGDATAFROM","刪除現有的數據：");//Delete existing data from:
define("_CLOSE","關閉");//Close
define("_SHOWHIDE","顯示/隱藏");//Show/Hide
define("_EFRONTLOGO","eFront標誌");//eFront logo
define("_READ","閱讀");//Read
define("_UNREAD","未讀");//Unread
define("_SUCCESFULLYADDEDROOM","成功加入室");//Succesfully added room
define("_AND","和");//and
define("_TRUEFALSE","真/假");//True/False
define("_DROPDOWN","從列表中選擇");//Select from list
define("_TRUE","正確的");//True
define("_FALSE","虛假");//False
define("_QUESTIONNUMBER","問題數目");//Question number
define("_QUESTIONTITLE","問題標題");//Question title
define("_NUMBEROFOPTIONS","多項選擇");//Number of options
define("_YOUHAVELOGGEDOUTBECAUSEYOURSESSIONHASTIMEDOUT","您已登出，因為您的會話已超時");//You have logged out because your session has timed out
define("_ORSELECTONEFROMLIST","或選擇其中一個，從名單");//Or select one from list
define("_EXPLANATION","解釋");//Explanation
define("_QUESTION","問題");//Question
define("_CHANGESTYLE","改變主題");//Change theme
define("_PREDEFINED","預定義");//Predefined
define("_SELECTNEWSTYLE","選擇新的主題");//Select new theme
define("_SETSTYLE","設定主題");//Set theme
define("_NOPREVIEWIMAGEFOUND","預覽圖像沒有發現");//Preview image not found
define("_EDITOR_BOLD_DESC","大膽（按Ctrl +二）");//Bold (Ctrl+B)
define("_EDITOR_ITALIC_DESC","斜體（按Ctrl +一）");//Italic (Ctrl+I)
define("_EDITOR_UNDERLINE_DESC","強調（ Ctrl + U加）");//Underline (Ctrl+U)
define("_EDITOR_STRIKETROUGH_DESC","刪除線");//Strikethrough
define("_EDITOR_JUSTIFYLEFT_DESC","左對齊");//Align left
define("_EDITOR_JUSTIFYCENTER_DESC","居中對齊");//Align center
define("_EDITOR_JUSTIFYRIGHT_DESC","右對齊");//Align right
define("_EDITOR_JUSTIFYFULL_DESC","對齊");//Align full
define("_EDITOR_BULLIST_DESC","無序清單");//Unordered list
define("_EDITOR_NUMLIST_DESC","下令名單");//Ordered list
define("_EDITOR_OUTDENT_DESC","outdent");//Outdent
define("_EDITOR_INDENT_DESC","縮進");//Indent
define("_EDITOR_UNDO_DESC","撤消（按Ctrl + Z ）的");//Undo (Ctrl+Z)
define("_EDITOR_REDO_DESC","重做（按Ctrl + y ）的");//Redo (Ctrl+Y)
define("_EDITOR_LINK_DESC","插入/編輯鏈接");//Insert/edit link
define("_EDITOR_UNLINK_DESC","斷開");//Unlink
define("_EDITOR_IMAGE_DESC","插入/編輯圖像");//Insert/edit image
define("_EDITOR_CLEANUP_DESC","清理混亂的代碼");//Cleanup messy code
define("_EDITOR_FOCUS_ALERT","1編輯器，例如必須集中，才能使用此命令。");//A editor instance must be focused before using this command.
define("_EDITOR_EDIT_CONFIRM","你是否想使用所見即所得的模式，這個文本?");//Do you want to use the WYSIWYG mode for this textarea?
define("_EDITOR_INSERT_LINK_TITLE","插入/編輯鏈接");//Insert/edit link
define("_EDITOR_INSERT","插入");//Insert
define("_EDITOR_UPDATE","更新");//Update
define("_EDITOR_CANCEL","取消");//Cancel
define("_EDITOR_INSERT_LINK_URL","鏈接網址");//Link URL
define("_EDITOR_INSERT_LINK_TARGET","目標");//Target
define("_EDITOR_INSERT_LINK_TARGET_SAME","打開鏈接在同一個窗口");//Open link in the same window
define("_EDITOR_INSERT_LINK_TARGET_BLANK","打開鏈接在一個新窗口");//Open link in a new window
define("_EDITOR_INSERT_IMAGE_TITLE","插入/編輯圖像");//Insert/edit image
define("_EDITOR_INSERT_IMAGE_SRC","圖片URL");//Image URL
define("_EDITOR_INSERT_IMAGE_ALT","圖片說明");//Image description
define("_EDITOR_HELP_DESC","幫助");//Help
define("_EDITOR_BOLD_IMG","bold.gif");//bold.gif
define("_EDITOR_ITALIC_IMG","italic.gif");//italic.gif
define("_EDITOR_UNDERLINE_IMG","underline.gif");//underline.gif
define("_EDITOR_CLIPBOARD_MSG","複製/削減/粘貼是不具備的Mozilla和Firefox 。你想了解更多信息有關此問題的呢?");//Copy/Cut/Paste is not available in Mozilla and Firefox.Do you want more information about this issue?
define("_EDITOR_POPUP_BLOCKED","很抱歉，但我們注意到，您的彈出-受體阻滯劑已禁用的一個窗口，提供的應用功能。您將需要禁用彈出封鎖關於這個站點為了充分利用這個工具。");//Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.
define("_EDITOR_JAVA_TITLE","插入/編輯的Java");//Insert / edit Java
define("_EDITOR_JAVA_DESC","插入/編輯的Java");//Insert / edit Java
define("_EDITOR_JAVA_FILE","Java的文件（ 。階級）");//Java-File (.class)
define("_EDITOR_JAVA_SIZE","大小");//Size
define("_EDITOR_JAVA_LIST","java文件");//Java files
define("_EDITOR_JAVA_PROPS","Java的性能");//Java properties
define("_EDITOR_JAVA_GENERAL","一般");//General
define("_EDITOR_JAVA_CODEBASE","的CODEBASE");//Codebase
define("_EDITOR_ADVHR_INSERT_ADVHR_DESC","horizontale規則");//Horizontale rule
define("_EDITOR_ADVHR_INSERT_ADVHR_WIDTH","寬度");//Width
define("_EDITOR_ADVHR_INSERT_ADVHR_SIZE","高度");//Height
define("_EDITOR_ADVHR_INSERT_ADVHR_NOSHADE","沒有影子");//No shadow
define("_EDITOR_ADVIMAGE_TAB_GENERAL","一般");//General
define("_EDITOR_ADVIMAGE_TAB_APPEARANCE","外觀");//Appearance
define("_EDITOR_ADVIMAGE_TAB_ADVANCED","先進");//Advanced
define("_EDITOR_ADVIMAGE_GENERAL","一般");//General
define("_EDITOR_ADVIMAGE_TITLE","標題");//Title
define("_EDITOR_ADVIMAGE_PREVIEW","預覽");//Preview
define("_EDITOR_ADVIMAGE_CONSTRAIN_PROPORTIONS","制約比例");//Constrain proportions
define("_EDITOR_ADVIMAGE_LANGDIR","語文方向");//Language direction
define("_EDITOR_ADVIMAGE_LANGCODE","語言代碼");//Language code
define("_EDITOR_ADVIMAGE_LONG_DESC","長期描述鏈接");//Long description link
define("_EDITOR_ADVIMAGE_STYLE","作風");//Style
define("_EDITOR_ADVIMAGE_CLASSES","班");//Classes
define("_EDITOR_ADVIMAGE_LTR","左向右");//Left to right
define("_EDITOR_ADVIMAGE_RTL","從右至左");//Right to left
define("_EDITOR_ADVIMAGE_ID","編號");//Id
define("_EDITOR_ADVIMAGE_IMAGE_MAP","影像地圖");//Image map
define("_EDITOR_ADVIMAGE_SWAP_IMAGE","掉期的形象");//Swap image
define("_EDITOR_ADVIMAGE_ALT_IMAGE","另類形象");//Alternative image
define("_EDITOR_ADVIMAGE_MOUSEOVER","為鼠標移過");//for mouse over
define("_EDITOR_ADVIMAGE_MOUSEOUT","對小鼠出");//for mouse out
define("_EDITOR_ADVIMAGE_MISC","雜項");//Miscellaneous
define("_EDITOR_ADVIMAGE_EXAMPLE_IMG","外觀預覽圖像");//Appearance&nbsp;preview&nbsp;image
define("_EDITOR_ADVIMAGE_MISSING_ALT","您確定要繼續操作而不包括圖像描述? 沒有它的形象未必方便一些用戶殘疾人士，或那些使用文本瀏覽器，或瀏覽網頁與圖像關掉.");//Are you sure you want to continue without including an Image description? Without  it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.
define("_EDITOR_ADVLINK_GENERAL_TAB","一般");//General
define("_EDITOR_ADVLINK_POPUP_TAB","彈出");//Popup
define("_EDITOR_ADVLINK_ADVANCED_TAB","先進");//Advanced
define("_EDITOR_ADVLINK_GENERAL_PROPS","一般性質");//General properties
define("_EDITOR_ADVLINK_POPUP_PROPS","彈出屬性");//Popup properties
define("_EDITOR_ADVLINK_EVENT_PROPS","事件");//Events
define("_EDITOR_ADVLINK_ADVANCED_PROPS","先進的性能");//Advanced properties
define("_EDITOR_ADVLINK_POPUP_OPTS","選項");//Options
define("_EDITOR_ADVLINK_ANCHOR_NAMES","主播");//Anchors
define("_EDITOR_ADVLINK_TARGET_SAME","開放，在此窗口/幀");//Open in this window / frame
define("_EDITOR_ADVLINK_TARGET_PARENT","開放在父窗口/幀");//Open in parent window / frame
define("_EDITOR_ADVLINK_TARGET_TOP","開放的頂面框架（取代所有幀）");//Open in top frame (replaces all frames)
define("_EDITOR_ADVLINK_TARGET_BLANK","在新窗口中打開");//Open in new window
define("_EDITOR_ADVLINK_POPUP","JavaScript的彈出");//Javascript popup
define("_EDITOR_ADVLINK_POPUP_URL","彈出網址");//Popup URL
define("_EDITOR_ADVLINK_POPUP_NAME","窗口名稱");//Window name
define("_EDITOR_ADVLINK_POPUP_RETURN","插入\\ “返回FALSE \\ "");//Insert \\\"return false\\\"
define("_EDITOR_ADVLINK_POPUP_SCROLLBARS","顯示滾動條");//Show scrollbars
define("_EDITOR_ADVLINK_POPUP_STATUSBAR","顯示狀態欄");//Show status bar
define("_EDITOR_ADVLINK_POPUP_TOOLBAR","顯示工具欄");//Show toolbars
define("_EDITOR_ADVLINK_POPUP_MENUBAR","顯示菜單欄");//Show menu bar
define("_EDITOR_ADVLINK_POPUP_LOCATION","顯示位置酒吧");//Show location bar
define("_EDITOR_ADVLINK_POPUP_RESIZABLE","使窗口大小可調整");//Make window resizable
define("_EDITOR_ADVLINK_POPUP_DEPENDENT","依賴（ Mozilla基金會/ Firefox的只有）");//Dependent (Mozilla/Firefox only)
define("_EDITOR_ADVLINK_POPUP_SIZE","大小");//Size
define("_EDITOR_ADVLINK_POPUP_POSITION","位置（的X / Y ）");//Position (X/Y)
define("_EDITOR_ADVLINK_ID","編號");//Id
define("_EDITOR_ADVLINK_STYLE","作風");//Style
define("_EDITOR_ADVLINK_CLASSES","班");//Classes
define("_EDITOR_ADVLINK_TARGET_NAME","目標名稱");//Target name
define("_EDITOR_ADVLINK_LANGDIR","語文方向");//Language direction
define("_EDITOR_ADVLINK_TARGET_LANGCODE","目標語言");//Target language
define("_EDITOR_ADVLINK_LANGCODE","語言代碼");//Language code
define("_EDITOR_ADVLINK_ENCODING","目標字符編碼");//Target character encoding
define("_EDITOR_ADVLINK_MIME","目標MIME類型");//Target MIME type
define("_EDITOR_ADVLINK_REL","關係轉到目標");//Relationship page to target
define("_EDITOR_ADVLINK_REV","關係的目標頁");//Relationship target to page
define("_EDITOR_ADVLINK_TABINDEX","tabindex");//Tabindex
define("_EDITOR_ADVLINK_ACCESSKEY","快速");//Accesskey
define("_EDITOR_ADVLINK_LTR","左向右");//Left to right
define("_EDITOR_ADVLINK_RTL","從右至左");//Right to left
define("_EDITOR_EMOTIONS_TITLE","插入情感");//Insert emotion
define("_EDITOR_EMOTIONS_DESC","情緒");//Emotions
define("_EDITOR_EMOTIONS_COOL","涼爽的");//Cool
define("_EDITOR_EMOTIONS_CRY","哭");//Cry
define("_EDITOR_EMOTIONS_EMBARASSED","尷尬");//Embarassed
define("_EDITOR_EMOTIONS_FOOT_IN_MOUTH","足部在口");//Foot in mouth
define("_EDITOR_EMOTIONS_FROWN","皺眉");//Frown
define("_EDITOR_EMOTIONS_INNOCENT","無辜");//Innocent
define("_EDITOR_EMOTIONS_KISS","親吻");//Kiss
define("_EDITOR_EMOTIONS_LAUGHING","開懷大笑");//Laughing
define("_EDITOR_EMOTIONS_MONEY_MOUTH","錢口");//Money mouth
define("_EDITOR_EMOTIONS_SEALED","密封");//Sealed
define("_EDITOR_EMOTIONS_SMILE","微笑");//Smile
define("_EDITOR_EMOTIONS_SURPRISED","驚訝");//Surprised
define("_EDITOR_EMOTIONS_TONGUE_OUT","舌出");//Tongue out
define("_EDITOR_EMOTIONS_UNDECIDED","未定");//Undecided
define("_EDITOR_EMOTIONS_WINK","眨眼");//Wink
define("_EDITOR_EMOTIONS_YELL","大聲喝斥");//Yell
define("_EDITOR_IESPELL_IESPELL_DESC","運行拼寫檢查");//Run spell checking
define("_EDITOR_IESPELL_IESPELL_DOWNLOAD","ieSpell未檢出。單擊確定去下載網頁。");//ieSpell not detected. Click OK to go to download page.
define("_EDITOR_INSERTDATETIME_INSERTDATE_DEF_FMT","％ Y型％米- ％ d個");//%Y-%m-%d
define("_EDITOR_INSERTDATETIME_INSERTTIME_DEF_FMT","％ H ：已％米： ％ s的");//%H:%M:%S
define("_EDITOR_INSERTDATETIME_INSERTDATE_DESC","插入日期");//Insert date
define("_EDITOR_INSERTDATETIME_INSERTTIME_DESC","插入時間");//Insert time
define("_EDITOR_INSERTDATETIME_INSERTTIME_MONTHS_LONG","新的數組（ &#39;一月&#39; ， &#39;二月&#39; ， &#39;三月&#39; ， &#39;四月&#39; ， &#39;可能&#39; ， &#39;六月&#39; ， &#39;七月&#39; ， &#39;八月&#39; ， &#39;九月&#39; ， &#39; 10月&#39; ， &#39;十一月&#39; ， &#39; 12月&#39; ）");//new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December')
define("_EDITOR_INSERTDATETIME_INSERTTIME_MONTHS_SHORT","新的數組（ &#39;一月&#39; ， &#39;二月&#39; ， &#39;三月&#39; ， &#39;四月&#39; ， &#39;可能&#39; ， &#39;軍&#39; ， &#39;七月&#39; ， &#39;八月&#39; ， &#39; 9 &#39; ， &#39; 10月&#39; ， &#39; 11月&#39; ， &#39; 12月&#39; ）");//new Array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
define("_EDITOR_INSERTDATETIME_INSERTTIME_DAY_LONG","新的數組（ &#39;週日&#39; ， &#39;星期一&#39; ， &#39;星期二&#39; ， &#39;星期三&#39; ， &#39;星期四&#39; ， &#39;星期五&#39; ， &#39;星期六&#39; ， &#39;星期日&#39; ）");//new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')
define("_EDITOR_INSERTDATETIME_INSERTTIME_DAY_SHORT","新的數組（ &#39;孫&#39; ， &#39;星期一&#39; ， &#39;星期二&#39; ， &#39;星期三&#39; ， &#39;星期四&#39; ， &#39;五&#39; ， &#39;星期六&#39; ， &#39;孫&#39; ）");//new Array('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun')
define("_EDITOR_MATHTYPE_INSERT_MATHTYPE_TITLE","插入mathtype");//Insert mathtype
define("_EDITOR_MATHTYPE_TITLE","插入mathtype");//Insert mathtype
define("_EDITOR_MATHTYPE_MATHTYPE_DESC","mathtype");//Mathtype
define("_EDITOR_MATHTYPE_DESC","mathtype");//Mathtype
define("_EDITOR_MEDIA_TITLE","插入/編輯嵌入式媒體");//Insert / edit embedded media
define("_EDITOR_MEDIA_DESC","插入/編輯嵌入式媒體");//Insert / edit embedded media
define("_EDITOR_MEDIA_GENERAL","一般");//General
define("_EDITOR_MEDIA_ADVANCED","先進");//Advanced
define("_EDITOR_MEDIA_FILE","文件");//File
define("_EDITOR_MEDIA_LIST","名單");//List
define("_EDITOR_MEDIA_SIZE","尺寸");//Dimensions
define("_EDITOR_MEDIA_PREVIEW","預覽");//Preview
define("_EDITOR_MEDIA_CONSTRAIN_PROPORTIONS","制約比例");//Constrain proportions
define("_EDITOR_MEDIA_TYPE","類型");//Type
define("_EDITOR_MEDIA_ID","編號");//Id
define("_EDITOR_MEDIA_NAME","名字");//Name
define("_EDITOR_MEDIA_CLASS_NAME","工人階級");//Class
define("_EDITOR_MEDIA_VSPACE","V型空間");//V-Space
define("_EDITOR_MEDIA_HSPACE","H -空間");//H-Space
define("_EDITOR_MEDIA_PLAY","自動播放");//Auto play
define("_EDITOR_MEDIA_LOOP","閉環");//Loop
define("_EDITOR_MEDIA_MENU","顯示菜單");//Show menu
define("_EDITOR_MEDIA_QUALITY","質量");//Quality
define("_EDITOR_MEDIA_SCALE","規模");//Scale
define("_EDITOR_MEDIA_ALIGN","對齊");//Align
define("_EDITOR_MEDIA_SALIGN","salign");//SAlign
define("_EDITOR_MEDIA_WMODE","wmode");//WMode
define("_EDITOR_MEDIA_BGCOLOR","背景");//Background
define("_EDITOR_MEDIA_BASE","基地");//Base
define("_EDITOR_MEDIA_FLASHVARS","flashvars");//Flashvars
define("_EDITOR_MEDIA_LIVECONNECT","swliveconnect");//SWLiveConnect
define("_EDITOR_MEDIA_AUTOHREF","autohref");//AutoHREF
define("_EDITOR_MEDIA_CACHE","緩存");//Cache
define("_EDITOR_MEDIA_HIDDEN","隱藏");//Hidden
define("_EDITOR_MEDIA_CONTROLLER","控制器");//Controller
define("_EDITOR_MEDIA_KIOSKMODE","Kiosk模式");//Kiosk mode
define("_EDITOR_MEDIA_PLAYEVERYFRAME","發揮每一個框架");//Play every frame
define("_EDITOR_MEDIA_TARGETCACHE","目標高速緩存");//Target cache
define("_EDITOR_MEDIA_CORRECTION","沒有校正");//No correction
define("_EDITOR_MEDIA_ENABLEJAVASCRIPT","啟用JavaScript");//Enable JavaScript
define("_EDITOR_MEDIA_STARTTIME","開始時間");//Start time
define("_EDITOR_MEDIA_ENDTIME","結束時間");//End time
define("_EDITOR_MEDIA_HREF","href");//Href
define("_EDITOR_MEDIA_QTSRCCHOKESPEED","窒息的速度");//Choke speed
define("_EDITOR_MEDIA_TARGET","目標");//Target
define("_EDITOR_MEDIA_VOLUME","數量");//Volume
define("_EDITOR_MEDIA_AUTOSTART","自動啟動");//Auto start
define("_EDITOR_MEDIA_ENABLED","啟用");//Enabled
define("_EDITOR_MEDIA_FULLSCREEN","全屏");//Fullscreen
define("_EDITOR_MEDIA_INVOKEURLS","引用網址");//Invoke URLs
define("_EDITOR_MEDIA_MUTE","靜音");//Mute
define("_EDITOR_MEDIA_STRETCHTOFIT","舒展，以適應");//Stretch to fit
define("_EDITOR_MEDIA_WINDOWLESSVIDEO","沒有窗戶的視頻");//Windowless video
define("_EDITOR_MEDIA_BALANCE","平衡");//Balance
define("_EDITOR_MEDIA_BASEURL","基地網址");//Base URL
define("_EDITOR_MEDIA_CAPTIONINGID","字幕編號");//Captioning id
define("_EDITOR_MEDIA_CURRENTMARKER","當前標記");//Current marker
define("_EDITOR_MEDIA_CURRENTPOSITION","當前位置");//Current position
define("_EDITOR_MEDIA_DEFAULTFRAME","預設框架");//Default frame
define("_EDITOR_MEDIA_PLAYCOUNT","發揮計數");//Play count
define("_EDITOR_MEDIA_RATE","比率");//Rate
define("_EDITOR_MEDIA_UIMODE","UI模式");//UI Mode
define("_EDITOR_MEDIA_FLASH_OPTIONS","閃光選項");//Flash options
define("_EDITOR_MEDIA_QT_OPTIONS","的QuickTime選項");//Quicktime options
define("_EDITOR_MEDIA_WMP_OPTIONS","Windows Media Player的選項");//Windows media player options
define("_EDITOR_MEDIA_RMP_OPTIONS","真正的媒體播放器的選項");//Real media player options
define("_EDITOR_MEDIA_SHOCKWAVE_OPTIONS","衝擊波選項");//Shockwave options
define("_EDITOR_MEDIA_AUTOGOTOURL","汽車後藤網址");//Auto goto URL
define("_EDITOR_MEDIA_CENTER","中心");//Center
define("_EDITOR_MEDIA_IMAGESTATUS","形象地位");//Image status
define("_EDITOR_MEDIA_MAINTAINASPECT","保持方面");//Maintain aspect
define("_EDITOR_MEDIA_NOJAVA","沒有的Java");//No java
define("_EDITOR_MEDIA_PREFETCH","預取");//Prefetch
define("_EDITOR_MEDIA_SHUFFLE","shuffle的");//Shuffle
define("_EDITOR_MEDIA_CONSOLE","控制台");//Console
define("_EDITOR_MEDIA_NUMLOOP","NUM個循環");//Num loops
define("_EDITOR_MEDIA_CONTROLS","管制");//Controls
define("_EDITOR_MEDIA_SCRIPTCALLBACKS","腳本回調");//Script callbacks
define("_EDITOR_MEDIA_SWSTRETCHSTYLE","舒展的作風");//Stretch style
define("_EDITOR_MEDIA_SWSTRETCHHALIGN","舒展的H -對齊");//Stretch H-Align
define("_EDITOR_MEDIA_SWSTRETCHVALIGN","拉伸V型對齊");//Stretch V-Align
define("_EDITOR_MEDIA_SOUND","健全");//Sound
define("_EDITOR_MEDIA_PROGRESS","進展");//Progress
define("_EDITOR_MEDIA_QTSRC","Qt的鋼骨混凝土");//QT Src
define("_EDITOR_MEDIA_QT_STREAM_WARN","流RTSP協議的資源，應該被添加到Qt的鋼骨混凝土場下的高級選項卡。您還應該添加一個非流版本的src領域..");//Streamed rtsp resources should be added to the QT Src field under the advanced tab.You should also add a non streamed version to the Src field..
define("_EDITOR_PREVIEW_PREVIEW_DESC","預覽");//Preview
define("_EDITOR_PRINT_PRINT_DESC","打印");//Print
define("_EDITOR_SAVE_SAVE_DESC","保存");//Save
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_SEARCH_DESC","查找");//Find
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_SEARCHNEXT_DESC","再次找到");//Find again
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACE_DESC","查找/替換");//Find/Replace
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_NOTFOUND","搜尋工作已經完成。搜尋字串無法找到。");//The search has been completed. The search string could not be found.
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_SEARCH_TITLE","查找");//Find
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACE_TITLE","查找/替換");//Find/Replace
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_ALLREPLACED","所有發生的搜尋字串的取代。");//All occurrences of the search string were replaced.
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_FINDWHAT","尋找什麼");//Find what
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACEWITH","替換");//Replace with
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_DIRECTION","方向");//Direction
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_UP","向上");//Up
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_DOWN","向下的");//Down
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_CASE","匹配大小寫");//Match case
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_FINDNEXT","尋找下一個");//Find&nbsp;next
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACE","取代");//Replace
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACEALL","全部替換");//Replace&nbsp;all
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_CANCEL","取消");//Cancel
define("_EDITOR_TABLE_GENERAL_TAB","一般");//General
define("_EDITOR_TABLE_ADVANCED_TAB","先進");//Advanced
define("_EDITOR_TABLE_GENERAL_PROPS","一般性質");//General properties
define("_EDITOR_TABLE_ADVANCED_PROPS","先進的性能");//Advanced properties
define("_EDITOR_TABLE_DESC","插入一個新表");//Inserts a new table
define("_EDITOR_TABLE_ROW_BEFORE_DESC","插入行之前");//Insert row before
define("_EDITOR_TABLE_ROW_AFTER_DESC","插入行後，");//Insert row after
define("_EDITOR_TABLE_DELETE_ROW_DESC","刪除行");//Delete row
define("_EDITOR_TABLE_COL_BEFORE_DESC","插入列前");//Insert column before
define("_EDITOR_TABLE_COL_AFTER_DESC","插入列後");//Insert column after
define("_EDITOR_TABLE_DELETE_COL_DESC","刪除欄");//Remove column
define("_EDITOR_TABLE_ROWTYPE","列在表中的一部分");//Row in table part
define("_EDITOR_TABLE_TITLE","插入/修改表");//Insert/Modify table
define("_EDITOR_TABLE_WIDTH","寬度");//Width
define("_EDITOR_TABLE_HEIGHT","高度");//Height
define("_EDITOR_TABLE_COLS","專欄");//Columns
define("_EDITOR_TABLE_ROWS","行");//Rows
define("_EDITOR_TABLE_CELLSPACING","cellspacing");//Cellspacing
define("_EDITOR_TABLE_CELLPADDING","cellpadding");//Cellpadding
define("_EDITOR_TABLE_BORDER","邊境");//Border
define("_EDITOR_TABLE_ALIGN","對齊");//Alignment
define("_EDITOR_TABLE_ALIGN_DEFAULT","默認");//Default
define("_EDITOR_TABLE_ALIGN_LEFT","左邊");//Left
define("_EDITOR_TABLE_ALIGN_RIGHT","右邊");//Right
define("_EDITOR_TABLE_ALIGN_MIDDLE","中心");//Center
define("_EDITOR_TABLE_ROW_TITLE","表行屬性");//Table row properties
define("_EDITOR_TABLE_CELL_TITLE","表格單元格屬性");//Table cell properties
define("_EDITOR_TABLE_CELL_TYPE","細胞類型");//Cell type
define("_EDITOR_TABLE_ROW_DESC","表行屬性");//Table row properties
define("_EDITOR_TABLE_CELL_DESC","表格單元格屬性");//Table cell properties
define("_EDITOR_TABLE_VALIGN","垂直對齊");//Vertical alignment
define("_EDITOR_TABLE_ALIGN_TOP","頂端");//Top
define("_EDITOR_TABLE_ALIGN_BOTTOM","底部");//Bottom
define("_EDITOR_TABLE_PROPS_DESC","表屬性");//Table properties
define("_EDITOR_TABLE_BORDERCOLOR","邊框顏色");//Border color
define("_EDITOR_TABLE_BGCOLOR","背景顏色");//Background color
define("_EDITOR_TABLE_MERGE_CELLS_TITLE","合併表細胞");//Merge table cells
define("_EDITOR_TABLE_SPLIT_CELLS_DESC","細胞分裂表");//Split table cells
define("_EDITOR_TABLE_MERGE_CELLS_DESC","合併表細胞");//Merge table cells
define("_EDITOR_TABLE_CUT_ROW_DESC","削減表行");//Cut table row
define("_EDITOR_TABLE_COPY_ROW_DESC","複製表行");//Copy table row
define("_EDITOR_TABLE_PASTE_ROW_BEFORE_DESC","粘貼表行前");//Paste table row before
define("_EDITOR_TABLE_PASTE_ROW_AFTER_DESC","粘貼表行後，");//Paste table row after
define("_EDITOR_TABLE_ID","編號");//Id
define("_EDITOR_TABLE_STYLE","作風");//Style
define("_EDITOR_TABLE_LANGDIR","語文方向");//Language direction
define("_EDITOR_TABLE_LANGCODE","語言代碼");//Language code
define("_EDITOR_TABLE_MIME","目標MIME類型");//Target MIME type
define("_EDITOR_TABLE_LTR","左向右");//Left to right
define("_EDITOR_TABLE_RTL","從右至左");//Right to left
define("_EDITOR_TABLE_BGIMAGE","背景圖像");//Background image
define("_EDITOR_TABLE_SUMMARY","摘要");//Summary
define("_EDITOR_TABLE_TD","數據");//Data
define("_EDITOR_TABLE_TH","標題");//Header
define("_EDITOR_TABLE_CELL_CELL","更新目前的細胞");//Update current cell
define("_EDITOR_TABLE_CELL_ROW","更新所有細胞在連續");//Update all cells in row
define("_EDITOR_TABLE_CELL_ALL","更新所有細胞的表");//Update all cells in table
define("_EDITOR_TABLE_ROW_ROW","更新當前行");//Update current row
define("_EDITOR_TABLE_ROW_ODD","更新奇的行表");//Update odd rows in table
define("_EDITOR_TABLE_ROW_EVEN","更新，甚至排在表");//Update even rows in table
define("_EDITOR_TABLE_ROW_ALL","更新所有的行表");//Update all rows in table
define("_EDITOR_TABLE_THEAD","表fead");//Table fead
define("_EDITOR_TABLE_TBODY","表機構");//Table body
define("_EDITOR_TABLE_TFOOT","表腳");//Table foot
define("_EDITOR_TABLE_DEL","刪除表");//Delete table
define("_EDITOR_TABLE_SCOPE","範圍");//Scope
define("_EDITOR_TABLE_ROW","行");//Row
define("_EDITOR_TABLE_COL","中校");//Col
define("_EDITOR_TABLE_ROWGROUP","連續組");//Row group
define("_EDITOR_TABLE_COLGROUP","中校組");//Col group
define("_EDITOR_TABLE_COL_LIMIT","您已經超過了最高的列數。");//You have exceeded the maximum number of columns.
define("_EDITOR_TABLE_ROW_LIMIT","您已經超過了最高的行數。");//You have exceeded the maximum number of rows.
define("_EDITOR_TABLE_CELL_LIMIT","您已超出最多的細胞。");//You have exceeded the maximum number of cells.
define("_EDITOR_TABLE_MISSING_SCOPE","您確定要繼續操作而不指定的範圍，這表頭細胞。沒有它，它可能很難為一些殘疾人用戶了解的內容或數據，顯示該表。");//Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.
define("_EDITOR_AUTOSAVE_AUTOSAVE_UNLOAD_MSG","的變化，你將會失去，如果你瀏覽遠離這一頁。");//The changes you made will be lost if you navigate away from this page.
define("_EDITOR_DIRECTIONALITY_DIRECTIONALITY_LTR_DESC","方向左向右");//Direction left to right
define("_EDITOR_DIRECTIONALITY_DIRECTIONALITY_RTL_DESC","方向從右至左");//Direction right to left
define("_EDITOR_LAYER_INSERTLAYER_DESC","插入新層");//Insert new layer
define("_EDITOR_LAYER_FORWARD_DESC","向前邁進");//Move forward
define("_EDITOR_LAYER_BACKWARD_DESC","動議落後");//Move backward
define("_EDITOR_LAYER_ABSOLUTE_DESC","切換絕對定位");//Toggle absolute positioning
define("_EDITOR_LAYER_CONTENT","新的層...");//New layer...
define("_EDITOR_NONBREAKING_DESC","插入非打破空間的性質");//Insert non-breaking space character
define("_EDITOR_THEME_THEME_STYLE_SELECT","-風格-");//-- Styles --
define("_EDITOR_THEME_THEME_CODE_DESC","編輯HTML源代碼");//Edit HTML Source
define("_EDITOR_THEME_THEME_CODE_TITLE","HTML源代碼編輯器");//HTML Source Editor
define("_EDITOR_THEME_THEME_CODE_WORDWRAP","自動換行");//Word wrap
define("_EDITOR_THEME_THEME_SUB_DESC","標");//Subscript
define("_EDITOR_THEME_THEME_SUP_DESC","標");//Superscript
define("_EDITOR_THEME_THEME_HR_DESC","插入水平尺");//Insert horizontal ruler
define("_EDITOR_THEME_THEME_REMOVEFORMAT_DESC","刪除格式");//Remove formatting
define("_EDITOR_THEME_THEME_CUSTOM1_DESC","您的自定義描述在這裡");//Your custom description here
define("_EDITOR_THEME_INSERT_IMAGE_BORDER","邊境");//Border
define("_EDITOR_THEME_INSERT_IMAGE_DIMENSIONS","尺寸");//Dimensions
define("_EDITOR_THEME_INSERT_IMAGE_VSPACE","垂直空間");//Vertical space
define("_EDITOR_THEME_INSERT_IMAGE_HSPACE","橫向空間");//Horizontal space
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN","對齊");//Alignment
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_DEFAULT","-未設置-");//-- Not set --
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_BASELINE","基線");//Baseline
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_TOP","頂端");//Top
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_MIDDLE","中東");//Middle
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_BOTTOM","底部");//Bottom
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_TEXTTOP","texttop");//TextTop
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_ABSMIDDLE","絕對中東");//Absolute middle
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_ABSBOTTOM","絕對底部");//Absolute bottom
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_LEFT","左邊");//Left
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_RIGHT","右邊");//Right
define("_EDITOR_THEME_THEME_FONT_SIZE","-字體大小-");//-- Font size --
define("_EDITOR_THEME_THEME_FONTDEFAULT","-字體的家庭-");//-- Font family --
define("_EDITOR_THEME_THEME_BLOCK","-格式-");//-- Format --
define("_EDITOR_THEME_THEME_PARAGRAPH","段");//Paragraph
define("_EDITOR_THEME_THEME_DIV","除法");//Div
define("_EDITOR_THEME_THEME_ADDRESS","地址");//Address
define("_EDITOR_THEME_THEME_PRE","預");//Preformatted
define("_EDITOR_THEME_THEME_H1","標題 1");//Heading 1
define("_EDITOR_THEME_THEME_H2","標題 2");//Heading 2
define("_EDITOR_THEME_THEME_H3","標題 3");//Heading 3
define("_EDITOR_THEME_THEME_H4","標題 4");//Heading 4
define("_EDITOR_THEME_THEME_H5","標題 5");//Heading 5
define("_EDITOR_THEME_THEME_H6","標題 6");//Heading 6
define("_EDITOR_THEME_THEME_BLOCKQUOTE","引用");//Blockquote
define("_EDITOR_THEME_THEME_CODE","代碼");//Code
define("_EDITOR_THEME_THEME_SAMP","代碼示例");//Code sample
define("_EDITOR_THEME_THEME_DT","定義任期");//Definition term 
define("_EDITOR_THEME_THEME_DD","定義說明");//Definition description
define("_EDITOR_THEME_THEME_COLORPICKER_TITLE","選擇一種顏色");//Select a color
define("_EDITOR_THEME_THEME_COLORPICKER_APPLY","應用");//Apply
define("_EDITOR_THEME_THEME_FORECOLOR_DESC","選擇文字顏色");//Select text color
define("_EDITOR_THEME_THEME_BACKCOLOR_DESC","選擇背景顏色");//Select background color
define("_EDITOR_THEME_THEME_CHARMAP_TITLE","選擇自定義字符");//Select custom character
define("_EDITOR_THEME_THEME_CHARMAP_DESC","插入自定義字符");//Insert custom character
define("_EDITOR_THEME_THEME_VISUALAID_DESC","切換指引/無形要素");//Toggle guidelines/invisible elements
define("_EDITOR_THEME_INSERT_ANCHOR_TITLE","插入/編輯錨");//Insert/edit anchor
define("_EDITOR_THEME_INSERT_ANCHOR_NAME","錨點名稱");//Anchor name
define("_EDITOR_THEME_THEME_ANCHOR_DESC","插入/編輯錨");//Insert/edit anchor
define("_EDITOR_THEME_THEME_INSERT_LINK_TITLEFIELD","標題");//Title
define("_EDITOR_THEME_THEME_CLIPBOARD_MSG","複製/削減/粘貼是不具備的Mozilla和Firefox 。你想了解更多信息有關此問題的呢?");//Copy/Cut/Paste is not available in Mozilla and Firefox.Do you want more information about this issue?
define("_EDITOR_THEME_THEME_PATH","路徑");//Path
define("_EDITOR_THEME_CUT_DESC","切割");//Cut
define("_EDITOR_THEME_COPY_DESC","複製");//Copy
define("_EDITOR_THEME_PASTE_DESC","粘貼");//Paste
define("_EDITOR_THEME_LINK_LIST","鏈接列表");//Link list
define("_EDITOR_THEME_IMAGE_LIST","圖像列表");//Image list
define("_EDITOR_THEME_BROWSE","瀏覽");//Browse
define("_EDITOR_THEME_IMAGE_PROPS_DESC","圖像屬性");//Image properties
define("_EDITOR_THEME_NEWDOCUMENT_DESC","新文件");//New document
define("_EDITOR_THEME_CLASS_NAME","工人階級");//Class
define("_EDITOR_THEME_NEWDOCUMENT","您確定要清除所有的內容?");//Are you sure you want clear all contents?
define("_EDITOR_THEME_ABOUT_TITLE","關於tinymce");//About TinyMCE
define("_EDITOR_THEME_ABOUT","大約");//About
define("_EDITOR_THEME_LICENSE","許可");//License
define("_EDITOR_THEME_PLUGINS","插件");//Plugins
define("_EDITOR_THEME_PLUGIN","插件");//Plugin
define("_EDITOR_THEME_AUTHOR","作者");//Author
define("_EDITOR_THEME_VERSION","版本");//Version
define("_EDITOR_THEME_LOADED_PLUGINS","加載插件");//Loaded plugins
define("_EDITOR_THEME_HELP","幫助");//Help
define("_EDITOR_THEME_NOT_SET","-未設置-");//-- Not set --
define("_EDITOR_THEME_CLOSE","關閉");//Close
define("_EDITOR_THEME_TOOLBAR_FOCUS","跳轉到工具按鈕-按A lt+的Q跳轉到編輯器-按A l t-Z型，跳轉到元素的路徑-按Al t -X的");//Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X
define("_EDITOR_THEME_INVALID_DATA","錯誤：無效的價值觀進入，這些都是以紅色標示。");//Error: Invalid values entered, these are marked in red.
define("_EDITOR_PASTE_PASTE_TEXT_DESC","粘貼為純文本");//Paste as plain text
define("_EDITOR_PASTE_PASTE_TEXT_TITLE","使用CTRL + V對您的鍵盤，文本粘貼到窗口。");//Use CTRL+V on your keyboard to paste the text into the window.
define("_EDITOR_PASTE_PASTE_TEXT_LINEBREAKS","保持linebreaks");//Keep linebreaks
define("_EDITOR_PASTE_PASTE_WORD_DESC","粘貼從Word");//Paste from Word
define("_EDITOR_PASTE_PASTE_WORD_TITLE","使用CTRL + V對您的鍵盤，文本粘貼到窗口。");//Use CTRL+V on your keyboard to paste the text into the window.
define("_EDITOR_PASTE_SELECTALL_DESC","選擇所有");//Select all
define("_EDITOR_FULLSCREEN_FULLSCREEN_DESC","切換全屏模式");//Toggle fullscreen mode (New)
define("_EDITOR_LESSONSINFO_LANG_LESSONS_INFO_LINKDESCRIPTION","轉到：吸取信息");//Go to: lessons info (New)
define("_EDITOR_LESSONSINFO_LANG_LESSONS_INFO_DESC","總結信息鏈接");//Lessons info link (New)
define("_EDITOR_INDEXLINK_LANG_INDEX_LINK_LINKDESCRIPTION","註冊");//Login (New)
define("_EDITOR_INDEXLINK_LANG_INDEX_LINK_DESC","登錄連結");//Login link (New)
define("_CHOOSELANGUGETOSYNC","選擇語言同步");//Choose language to synchronize
define("_INSERTJAVA","插入的Java檔案");//Insert java file
define("_INSERTMEDIA","插入媒體文件");//Insert media file
define("_CHANGEORDER","修改訂單");//Change order
define("_DRAGITEMSTOCHANGEQUESTIONSORDER","拖移項目，以改變顯示順序的問題");//Drag items to change the display order of the questions
define("_TERM","任期");//Term
define("_OPERATIONS","行動");//Operations
define("_AREYOUSUREYOUWANTTODELETELESSON","您確定要刪除的教訓呢?");//Are you sure you want to delete lesson?
define("_EDITLESSON","教訓設置");//Edit lesson
define("_DIRECTIONS","類別");//Categories
define("_UPDATEDIRECTIONS","編輯類別");//Edit categories
define("_PARENTDIRECTIONS","家長類");//Parent category
define("_AREYOUSUREYOUWANTTODELETEDIRECTION","您確定要刪除類別?");//Are you sure you want to delete the category?
define("_YOUMUSTDELETEALLLESSONSANDSUBDIRECTIONSINTHISDIRECTIONBEFOREDELETINGIT","您必須刪除所有的教訓和所有子屬於這一類刪除之前");//You must delete all lessons and all subcategories that belong to this category before deleting it
define("_ROOTDIRECTION","----熱門分類----");//----Root category----
define("_CHECK","檢查");//Check
define("_REQUIREDNOTE","*必填");//*Mandatory fields
define("_BEFOREJAVASCRIPTERROR","以下錯誤發生：");//The following errors occured:
define("_AFTERJAVASCRIPTERROR","請更正上述錯誤");//Please correct the above errors
define("_ISMANDATORY","是強制性的");//is mandatory
define("_HASINVALIDCHARACTERS","無效字符");//has invalid characters
define("_ONLYALLOWEDCHARACTERSLOGIN","只能使用字母和字符<strong>。 -_ @允</strong>許");//Only letters and the characters <strong>. - _ @</strong> are allowed
define("_ALREADYEXISTS","已經存在");//already exists
define("_PASSWORDSDONOTMATCH","該密碼不匹配");//The passwords do not match
define("_ONLYALLOWEDCHARACTERSTEXT","請不要使用報價和其他特殊字符。");//Please do not use quotes and other special characters.
define("_REPEATPASSWORD","重複密碼");//Repeat password
define("_TERMS","服務條款");//Terms of Service
define("_REGISTRATIONFAILEDCONTACTADMIN","註冊失敗。請聯繫系統管理員。");//Registration failed. Please contact the system administrator.
define("_THELOGIN","用戶名");//The user name
define("_THEEMAIL","電子郵件");//The email
define("_PASSWORDMUSTBE6CHARACTERS","密碼必須至少6個字符");//Password must be at least 6 characters
define("_DEFAULTCONTACTMESSAGE","我想被告知的內容和規格，您的經驗教訓，以及對任何課程的參與要求");//I would like to be informed on the content and specifications of your lessons, as well as on any course participation requirements
define("_DEFAULTTERMSOFUSAGE","eFront平台使用條款的每個用戶登記，以目前的電子學習系統必須閱讀並遵守以下條款的正確用法。 1 。這是禁止使用該系統的理由以外的其他表演了學習過程，例如：推廣產品或服務，或任何組合這些，個人或其他人的宣傳手法，侮辱其他人，無論是註冊系統的用戶或不");//\teFront platform terms of usage\n\nEvery user registering to the present e-learning system must read and comply with the following terms of proper usage.\n\n1. It is forbidden to use the system for reasons other than performing a learning procedure, as for example: Promotion of products or services or any combination of these, personal or other person promotional practices, affront to other person, either registered system users or not
define("_YOUMUSTAGREEWITHTERMSOFUSAGETOCONTINUE","您必須同意與使用條款，以便繼續");//You must agree with the terms of usage in order to continue
define("_INVALIDFIELDDATA","無效的野外數據");//Invalid field data
define("_SUCCESFULLYINSERTEDNEWUNIT","成功地插入新的單位");//Succesfully inserted new unit
define("_ACCEPTTERMS","同意條款");//Accept terms
define("_SUCCESFULLYUPDATEDUNIT","成功更新單位");//Succesfully updated unit
define("_ACTIVE2","活躍");//Active
define("_ACTIVEFEM","活躍");//Active
define("_LESSONSNUMBER","一些教訓");//Number of lessons
define("_PARENTDIRECTION","家長類");//Parent category
define("_EXPANDCOLLAPSE","展開/折疊");//Expand/Collapse
define("_RAWTEXT","原料文本");//Raw text
define("_SUCCESFULLYADDEDTEST","添加成功測試");//Succesfully added test
define("_SUCESSFULLYDELETEDTEST","成功刪除測試");//Succesfully deleted test
define("_SUCCESFULLYMODIFIEDTEST","成功修改測試");//Succesfully modified test
define("_USEQUESTION","使用問題");//Use question
define("_SHUFFLEANSWERS","shuffle的答案");//Shuffle answers
define("_SHUFFLEQUESTIONS","shuffle的問題");//Shuffle questions
define("_QUESTIONS","問題");//Questions
define("_INSERTMULTIPLEQUESTIONS","插入多種選擇");//Insert the multiple choices
define("_INSERTEXPLANATION","插入解釋");//Insert explanation
define("_THISQUESTIONIS","這個問題是");//This question is
define("_CREATEEMPTYSPACES","創建空白");//Create empty spaces
define("_EMPTYSPACESEXPLANATION","寫文本的問題，不管走到哪裡，需要插入一張空白的空間，插入＃ ＃ ＃ 。當你完成後，點擊“創建空白”下面的按鈕");//Write the question text and wherever you need to insert a blank space, insert ###. When you are done, click on the &quot;Create empty spaces&quot; button below
define("_INSERTMATCHCOUPLES","插入匹配對");//Insert matching pairs
define("_ADDOPTION","添加選項");//Add option
define("_GOTOCALENDAR","轉到日曆");//Go to calendar
define("_EXPANDALL","全部展開");//Expand all
define("_COLLAPSEALL","全部折疊");//Collapse all
define("_SURVEY","調查");//Survey
define("_SURVEYADDEDSUCCESSFULLY","調查添加成功");//Survey added successfully
define("_SURVEYFAILEDTOBEADDED","調查無法加入");//Survey failed to be added
define("_SURVEYDELETEDSUCCESSFULLY","調查成功刪除");//Survey deleted successfully
define("_QUESTIONADDEDSUCCESSFULLY","問題補充成功");//Question added successfully
define("_QUESTIONFAILEDTOBEADDED","沒有添加問題");//Failed to add question
define("_CREATESURVEYQUESTION","創造問題的調查");//Create question for survey
define("_CREATESURVEY","建立調查");//Create survey
define("_EDITSURVEY","編輯調查");//Edit survey
define("_NOSURVEYFORLESSON","有沒有調查的教訓");//There is no survey for the lesson
define("_NOQUESTIONSFORSURVEY","有沒有問題，以供調查");//There are no questions for the survey
define("_SURVEYCODE","代碼");//Code
define("_SURVEYNAME","名字");//Name
define("_SURVEYSTATUS","身份");//Status
define("_SURVEYNUMBEROFQUESTIONS","問題基數");//Question cardinality
define("_SURVEYAVALIABLEFROM","可從");//Availiable from
define("_SURVEYUNTIL","直到");//Until
define("_PUBLISH","發布");//Publish
define("_SURVEYSELECTION","選擇");//Select
define("_SELECTALL","選擇所有");//Select all
define("_SURVEYINFO","副標題為調查");//Subtitle for the survey
define("_SURVEYINTROTEXT","調查的介紹性文字");//Survey introductory text
define("_SURVEYENDTEXT","調查結束文本");//Survey ending text
define("_YES_NO","是/否");//Yes/No
define("_SURVEYQUESTIONMULTIPLEONE","多種選擇-一個答案");//Multiple choices-one answer
define("_SURVEYQUESTIONMULTIPLEMANY","多種選擇-多個答案");//Multiple choices-multiple answers
define("_ENTERMAILMESSAGE","訊息");//Message
define("_PLEASESELECTAVALIDTYPEOFQUESTION","請選擇一個有效的類型的問題在前面的步驟。");//Please select a valid type of question in the previous step.
define("_SURVEYDATAUPDATEDSUCCESSFULLY","調查數據更新成功");//Survey data updated successfully
define("_SURVEYDATAFAILEDTOBEUPDATED","調查數據沒有更新");//Survey data failed to be updated
define("_QUESTIONDELETEDSUCCESSFULLY","問題已成功刪除");//Question deleted successfully
define("_THEQUESTIONWASSUCCESSFULLYMOVED","問題的動議成功");//The question moved successfully
define("_THEQUESTIONFAILEDTOBEMOVED","問題沒有被提出");//The question failed to be moved
define("_NOSUCHOPERATION","沒有這樣的運作");//No such operation
define("_SHOWDATAFORUNIT","數據顯示單位");//Show data for unit
define("_ALLUNITS","各單位");//All units
define("_YOUMUSTUPLOADFILE","您必須表明要上傳的文件");//You must indicate a file to upload
define("_TOTALINSERTED","完全插入");//Totally inserted
define("_PERSONALOPTIONSFOR","個人選擇用戶");//Personal options for user
define("_LESSONOPTIONSFOR","選擇的教訓");//Options for lesson
define("_NEWLESSONOPTIONS","新的教訓，選擇");//New lesson options
define("_ROLES","用戶類型");//User types
define("_TYPENAME","類型名稱");//Type name
define("_UPDATEUSERTYPEFOR","更新僱員類型");//Update user type for
define("_SYSTEMANNOUNCEMENTS","系統公告");//System announcements
define("_CREATEUNIT","創建單位");//Create unit
define("_DONETIMES","時代完成");//Times completed
define("_QUESTIONSTATISTICS","問題統計");//Question statistics
define("_ADDQUESTIONOFTYPE","添加的問題類型");//Add question of type
define("_NOSYSTEMANNOUNCEMENTSPOSTED","沒有系統的公告張貼");//No system announcements posted
define("_DURATIONINMINUTES","在幾分鐘的時間");//Duration in minutes
define("_ADDCALENDAR","新增日曆事件");//Add calendar event
define("_EVENTS","事件");//events
define("_NOEVENTSPLANNED","有沒有活動計劃");//There are no events planned
define("_UNITOPERATIONS","單元操作");//Unit operations
define("_LESSONINFORMATION","教訓信息");//Lesson information
define("_GENERALDESCRIPTION","一般說明");//General description
define("_OBJECTIVES","目標");//Objectives
define("_OTHERINFO","其他信息");//Other information
define("_ASSESSMENT","估價");//Assessment
define("_RESOURCES","資源");//Resources
define("_LESSONTOPICS","教訓話題");//Lesson topics
define("_NODESCRIPTIONSET","有沒有說明訂定這個教訓");//There is no description set for this lesson
define("_HASINVALIDEMAILADDRESS","已無效的電子郵件地址");//has invalid email address
define("_SUCCESFULLYADDEDDIRECTION","成功添加類");//Succesfully added category
define("_SUCCESFULLYUPDATEDDIRECTION","成功更新類別");//Succesfully updated category
define("_LESSONRULES","教訓規則");//Lesson rules
define("_BASEDONTERM","基於對任期");//Based on term
define("_HASNOTSEENTHEUNIT","有沒有看到單位");//Has not seen the unit
define("_HASNOTPASSEDTHETEST","未完成測試");//Has not completed the test
define("_ALWAYS","總是");//Always
define("_WITHNAME","與名稱");//With name
define("_ANDSCOREGREATEROREQUAL","和評分大於或等於");//And score greater or equal to
define("_INVALIDRULE","無效的規則類型");//Invalid rule type
define("_INVALIDSCORE","無效的評分");//Invalid score
define("_SUCCESFULLYUPDATEDRULE","succefully更新規則");//Succefully updated rule
define("_SUCCESFULLYINSERTEDRULE","succefully插入規則");//Succefully inserted rule
define("_ADDRULE","添加規則");//Add rule
define("_RULEDELETED","法治的成功刪除");//Rule deleted successfully
define("_NEWSURVEYPUBLISHED","調查報告：");//Survey:
define("_DOSURVEY","這樣做的調查");//Do the survey
define("_THANKYOU","謝謝您");//Thank you
define("_THISEMAIL","此電子郵件");//This email
define("_CONTAINSINFORMATIONABOUTYOURACCOUNTINTHEPLATFORM","包含有關您的帳戶在該平台");//contains information about your account in the platform
define("_SURVEYPUBLISHEDSUCCESSFULLY","發表的調查成功");//Survey published sucessfully
define("_STARTSURVEY","開始調查");//Start survey
define("_SURVEYSUBMISSIONSUCCESSFUL","調查提交成功");//Survey submitted successfully
define("_YOUCANNOTACCESSTHISPAGE","你不能進入此頁");//You cannot access this page
define("_NOCONTENTFOUND","沒有內容");//No content
define("_EDITLESSONSDIRECTION","類的教訓");//Category lessons
define("_EXTERNALLYSIGNUP","對外註冊");//External signup
define("_EVENT","事件");//Event
define("_EDITEVENT","編輯活動");//Edit event
define("_DELETEEVENT","刪除活動");//Delete event
define("_ADDEVENT","添加活動");//Add event
define("_SUCCESFULLYADDEDEVENT","成功添加事件");//Succesfully added event
define("_SUCCESFULLYUPDATEDEDEVENT","成功更新事件");//Succesfully updated event
define("_SUCCESFULLYDELETEDEVENT","成功刪除事件");//Succesfully deleted event
define("_SHOWALLEVENTS","顯示所有活動");//Show all events
define("_NOEVENTSPLANNEDTHISWEEK","有沒有活動計劃在本星期");//There are no events planned this week
define("_NOEVENTSPLANNEDTHISMONTH","有沒有活動計劃在本月");//There are no events planned this month
define("_NOEVENTSPLANNEDTODAY","有沒有活動計劃這一天");//There are no events planned this day
define("_SHOWDAYEVENTS","顯示這一天的活動");//Show this day&#039;s events
define("_SHOWWEEKEVENTS","顯示這週的活動");//Show this week&#039;s events
define("_SHOWMONTHEVENTS","顯示這一個月的活動");//Show this month&#039;s events
define("_SUBTITLE","副標題");//Subtitle
define("_SURVEYSTATISTICS","調查報告");//Survey reports
define("_PROJECT","項目");//Project
define("_DEADLINE","截止日期");//Deadline
define("_ADDPROJECT","添加項目");//Add project
define("_PROJECTCREATEDSUCCESSFULLY","項目的成功創建");//Project created successfully
define("_PROJECTUPDATEDSUCCESSFULLY","項目已成功更新");//Project updated successfully
define("_CREATOR","創作者");//Creator
define("_EDITPROJECT","編輯項目");//Edit project
define("_NOPROJECTS","有沒有項目，這個教訓");//There are no projects for this lesson
define("_SURVEYDONE","調查");//Survey done
define("_DONESURVEYUSERS","調查參與者");//Survey participants
define("_SURVEYPREVIEWFORUSER","調查預覽用戶：");//Survey preview for user:
define("_QUESTIONSKIND","種問題");//Questions types
define("_QUESTIONUPDATEDSUCCESSFULLY","問題的成功更新");//Question updated successfully
define("_QUESTIONFAILEDTOBEUPDATED","問題未能得到更新");//Question failed to be update
define("_INVALIDPERCENTAGE","無效的百分比");//Invalid percentage
define("_PASSEDALLUNITS","看到各單位");//Seen all units
define("_PERCENTAGEUNITS","看到的一小部分單位");//Seen a fraction of units
define("_SPECIFICUNIT","看到一個具體單位");//Seen a specific unit
define("_PASSEDALLTESTS","通過所有測試");//Passed all tests
define("_SPECIFICTEST","通過一個具體的測試");//Passed a specific test
define("_INVALIDCONDITION","無效的條件");//Invalid condition
define("_THEUSERMUSTHAVE","學生必須有");//The student must have
define("_UNITSPERCENTAGE","百分比");//Percentage
define("_SUCCESFULLYADDEDCONDITION","成功的附加條件");//Succesfully added condition
define("_SUCCESFULLYUPDATEDCONDITION","成功更新條件");//Succesfully updated condition
define("_SUCCESFULLYDELETEDCONDITION","成功刪除條件");//Succesfully deleted condition
define("_LESSONCONDITIONS","教訓完成條件");//Lesson completion conditions
define("_ADDCONDITION","添加條件");//Add condition
define("_CONDITION","條件");//Condition
define("_CONDITIONTYPE","條件類型");//Condition type
define("_RELATIONTOOTHERS","與他人的關係");//Relation to others
define("_SCROLLTOTOPOFPAGE","翻閱到返回頁首");//Scroll to top of page
define("_SCROLLTOBOTTOMOFPAGE","滾動到頁面底部");//Scroll to bottom of page
define("_NOUSERHAVEDONETHISSURVEYYET","沒有僱員所做的這項調查，但");//No employee has done this survey yet
define("_SYSTEM","系統");//System
define("_EMAILCONFIGURATIONS","電子郵件服務器配置");//E-mail server configuration
define("_SAWUNIT","設置單位為完成");//Set the unit as completed
define("_NOTSAWUNIT","設置單位未完成");//Set the unit as not completed
define("_CONDITIONSCOMPLETED","條件完成");//Conditions completed
define("_OUTOF","出於");//out of
define("_LESSONPROGRESS","教訓進展");//Lesson progress
define("_YOUMUSTSEEUNIT","你必須看到單位");//You must see unit
define("_YOUMUSTSEEALLUNITS","你必須看到，各單位");//You must see all units
define("_OFLESSONUNITS","課單位");//of lesson units
define("_YOUMUSTSEE","您必須見");//You must see
define("_YOUMUSTCOMPLETEALLTESTSWITHSCORE","您必須完成所有測試，平均得分");//You must complete all tests with mean score
define("_YOUMUSTCOMPLETETEST","您必須完成測試");//You must complete test
define("_WITHSCORE","與評分");//with score
define("_NOCONDITIONSSET","有沒有條件，訂定這個教訓");//There are no conditions set for this lesson
define("_CONDITIONS","條件");//conditions
define("_RESUMELESSON","恢復的教訓");//Resume lesson
define("_STARTLESSON","開始的教訓");//Start lesson
define("_TRACKING","跟踪");//Tracking
define("_FORMATCERTIFICATE","格式證書");//Format certificate
define("_TRAFFIC","交通");//Traffic
define("_LESSONTRAFFIC","教訓交通");//Lesson traffic
define("_EDITTEST","編輯測試");//Edit test
define("_EDITQUESTION","編輯問題");//Edit question
define("_CERTIFICATE","證書");//Certificate
define("_SUCCESFULLYUPDATEDCERTIFICATE","成功更新證書");//Succesfully updated certificate
define("_EDITCONDITION","編輯條件");//Edit condition
define("_SMTPSERVERCONFIGURATIONS","SMTP服務器配置");//SMTP server Configuration
define("_SMTPSERVER","SMTP服務器");//SMTP server
define("_SMTPPASSWORD","的SMTP密碼");//SMTP password
define("_SMTPPORT","服務器SMTP端口");//Server SMTP port
define("_TOTALACCESS","總數通道");//Total number of accesses
define("_ACCESSNUMBER","有多少通道");//Number of accesses
define("_LESSONTRAFFICANALYSIS","分析教訓的交通");//Analysis of Lesson&#039;s Traffic
define("_SETTINGS","設置");//Settings
define("_LESSONACCESS","一些教訓&#39;通道");//Number of lessons&#039; accesses
define("_ACCESSPERLESSON","有多少通道，每教訓");//Number of Accesses per Lesson
define("_NOFILESFOUNDDIGITALLIBRARY","有沒有任何文件在數字圖書館");//There aren&#039;t any files in the digital library
define("_BLANKFORUNLIMITED","留空無限");//Leave blank for unlimited
define("_CERTIFICATES","證書");//Certificates
define("_NOUSERDATAFOUND","沒有僱員的進展數據發現");//No employee progress data found
define("_ISSUECERTIFICATE","問題證書");//Issue certificate
define("_LESSONFILES","教訓檔案");//Lesson files
define("_TOTALACCESSTIME","總存取時間");//Total access time
define("_DEFAULTPAGE","默認頁");//Default page
define("_NEWPAGE","新的一頁");//New page
define("_UPDATEPAGES","更新頁面");//Update pages
define("_PAGECONTENT","網頁內容");//Page content
define("_UPDATEPAGE","更新網頁");//Update page
define("_TOTALSTATISTICS","總統計");//Total statistics
define("_LOGINS","登錄");//Logins
define("_USENONE","使用無");//Use none
define("_PAGEDELETED","網頁已刪除");//Page deleted
define("_AREYOUSUREYOUWANTTODELETEPAGE","您確定要刪除的網頁?");//Are you sure you want to delete page?
define("_SUCCESFULLYADDEDPAGE","網頁添加成功");//Page added successfully
define("_LESSONMAINPAGE","教訓主要頁");//Lesson main page
define("_GOTOPROJECTS","去項目");//Go to projects
define("_ACCESSSTATISTICS","訪問統計");//Access statistics
define("_ANALYTICLOG","解析日誌");//Analytic log
define("_SHOWANALYTICLOG","查看解析日誌");//Show analytic log
define("_SHOWALLLESSONS","顯示所有的經驗教訓");//Show all lessons
define("_CHATROOMDEACTIVATEDBYADMIN","聊天室停用，由管理員");//Chat room deactivated by administrator
define("_IPADDRESS","IP地址");//IP address
define("_YOUHAVEALREADYUPLOADEDAFILE","您已上傳的文件");//You have uploaded a file
define("_FILEDELETEDSUCCESSFULLY","文件已成功刪除");//File deleted successfully
define("_GRADE","職系");//Grade
define("_PROFESSORCOMMENTS","教授的評論");//Professor comments
define("_DEADLINEPASSEDYOUCANNOLONGERUPLOADFILES","截止日期已經過去了。您可以不再上傳文件。");//The deadline has passed. You can no longer upload files.
define("_UPLOADEDFILE","上傳的文件");//Uploaded file
define("_CMS","外部網頁");//External pages
define("_YOUMAYNOTSIGNUPCONTACTADMINISTRATOR","您可能沒有註冊;聯繫系統管理員");//You may not sign up; contact the system administrator
define("_OPERATIONCOMPLETEDSUCCESFULLY","操作成功完成");//Operation completed successfully
define("_REMOVECHOICE","刪除選擇");//Remove choice
define("_SURVEYDISABLEDSUCCESSFULLY","調查殘疾人士成功");//Survey disabled successfully
define("_SURVEYENABLEDSUCCESSFULLY","調查成功啟用");//Survey enabled successfully
define("_SURVEYSUBMIT","提交調查");//Submit survey
define("_ROWSPERPAGE","每頁上的行數");//Rows per page
define("_FILTER","過濾器");//Filter
define("_OF","出於");//of
define("_SENDALSOVIAEMAIL","發送邀請通過電子郵件");//Send invitation via e-mail
define("_STYLE","作風");//Style
define("_MENU","菜單");//Menu
define("_SELECTION","選擇");//Selection
define("_SMTPCONFIGURATIONARECORRECT","該配置的SMTP服務器是正確的");//The configurations of the Smtp server are correct
define("_SMTPCONFIGURATIONERROR","有一個錯誤的配置，請聯絡SMTP服務器管理員");//There is an error with the configurations please contact Smtp server administrator
define("_ADDNEWFIELD","添加的新領域");//Add new field
define("_FIELDCREATED","外地的創造");//The field was created
define("_FIELDUPDATED","外地已更新");//The field was updated
define("_LESSONSCORE","教訓評分");//Lesson score
define("_COMPLETED","完成");//Completed
define("_NOTCOMPLETED","未完成");//Not completed
define("_CONDITIONSMET","條件符合並等待批准");//Conditions met and awaiting approval
define("_STUDENTSTATUSCHANGED","學生的教訓，成功地改變現狀");//Student lesson status changed successfully
define("_MUSTBENUMERIC","必須數字");//Must be numeric
define("_DEFAULTCERTIFICATE","eFront網絡學習平台的組織，證明用戶名＃ ＃ ＃ ＃ user_surname已成功地完成＃ course_name ＃級＃級＃這證書簽發對＃日期＃");//eFront elearning platform organization certifies that \n\n #user_name# #user_surname# \n\n has successfully completed \n #course_name# \n with grade \n\n #grade# \n\nThis certificate was issued on #date#
define("_NOQUESTIONSTOCORRECT","有沒有問題，以正確的");//There are no questions to correct
define("_RESTTESTSCORE","評分在其餘的測試");//Score at the remaining of the test
define("_CORRECTQUESTION","正確的問題");//Correct question
define("_FILEMANAGER","檔案管理員");//File manager
define("_NOFILESFOUND","沒有找到檔案");//No files found
define("_LASTMODIFIED","最後修改");//Last modified
define("_KB","千字節.");//KB
define("_UPONELEVEL","一水平");//Up one level
define("_DOWNLOADFILE","下載文件");//Download file
define("_ZIPANDDOWNLOAD","壓縮文件和下載");//Compress file and download
define("_COMPRESSTOZIP","壓縮郵編");//Compress to zip
define("_SELECT","選擇");//Select
define("_WITHSELECTEDFILES","與選定的文件");//With selected files
define("_UNCOMPRESS","解壓縮");//Uncompress
define("_UNZIPFILE","解壓縮文件");//Unzip file
define("_OVERWRITEFILESWITHSAMENAME","覆蓋文件具有相同名稱");//Overwrite files with the same name
define("_UPLOAD","上傳");//Upload
define("_SUCCESFULLYCREATEDFOLDER","文件夾已成功創建");//Folder created successfully
define("_CANNOTDELETEFILE","無法刪除文件");//Cannot delete file
define("_FILEWILLUNZIPINFOLDERWITHSAMENAME","該文件將被解壓縮在一個文件夾中具有相同名稱");//The file will be uncompressed in a folder with the same name
define("_FILEALREADYEXISTS","文件已經存在");//File already exists
define("_ROOTDIR","根文件夾中");//Root folder
define("_GOTOCORRECTQUESTIONS","去的問題，正確的網頁");//Go to questions correct page
define("_THEREARE","有");//There are
define("_YOUCANNOTACCESSTHISLESSONORITDOESNOTEXIST","無論您可能無法訪問此教訓，這個教訓，或不存在");//Either you may not access this lesson, or this lesson does not exist
define("_SHOWSIDEBAR","顯示側欄");//Show sidebar
define("_HIDESIDEBAR","隱藏側欄");//Hide sidebar
define("_YOURPROJECTSCOREIS","您的評分");//Your score
define("_USERSEXPORTUSINGCSVFORMATCOMMA","出口僱員使用的數據格式（分離“ ， ” ）");//Export employees data using csv format (separated with &quot;,&quot;)
define("_USERSEXPORTUSINGCSVFORMATQM","出口僱員使用的數據格式（分開“ ; ” ）");//Export employees data using csv format (separated with &quot;;&quot;)
define("_SHOWGIVENANSWERS","顯示給予的答案");//Show given answers
define("_SHOWRIGHTANSWERS","查看正確答案");//Show correct answers
define("_COULDNOTBESEND","無法寄出");//Could not be sent
define("_ENVIRONMENTALCHECK","環境檢查");//Environmental check
define("_REPAIRTREE","還原樹");//Restore tree
define("_RULEPROPERTIES","法治的屬性");//Rule properties
define("_CONDITIONPROPERTIES","條件屬性");//Condition properties
define("_ORPHANLESSONFOLDERSCHECK","孤兒的教訓，文件夾的所有內容");//Orphan lesson folders check
define("_LESSONSWITHOUTFOLDERSCHECK","教訓，沒有文件夾檢查");//Lessons without folders check
define("_FOLDERSWITHOUTALESSONASSOCIATED","下列文件夾中沒有一個相關的教訓");//The following folders do not have a lesson associated
define("_LESSONSWITHOUTAFOLDER","以下教訓，沒有一個文件夾");//The following lessons do not have a folder
define("_PROBLEM","問題");//Problem
define("_CLEANUP","清理");//Clean up
define("_OK","好的");//OK
define("_PEMANENTLYDELETEFOLLOWINGFOLDERS","這一行動將永久地刪除下列文件夾");//This action will permanently delete the following folders
define("_PEMANENTLYDELETEFOLLOWINGLESSONS","這一行動將永久刪除以下教訓");//This action will permanently delete the following lessons
define("_CREATEFOLLOWINGLESSONFOLDERS","這一行動將創建文件夾為以下的經驗教訓");//This action will create folders for the following lessons
define("_AREYOUSURE","您是否確定?");//Are you sure?
define("_CHECKAGAIN","再次檢查");//Check again
define("_GENERICQUERIES","通用查詢");//Generic queries
define("_SENDINFOVIAEMAIL","發送登錄信息在電子郵件帳戶");//Send login information in email account
define("_NOONEHASBEENASSIGNEDTHISPROJECT","這個項目還沒有被分配到任何學生");//This project has not been assigned to any student
define("_PROJECTINFO","項目信息");//Project information
define("_ANNOUNCEMENTGO","去公告頁");//Go to announcements page
define("_PROJECTAVERAGESCOREFORLESSON","平均分數為教訓的項目");//Average score for lesson&#039;s projects
define("_NEWPOLL","新的民意調查");//New poll
define("_NOBOOKMARKSFOUND","沒有書籤發現");//No bookmarks found
define("_FOLDERSTATISTICS","文件夾統計");//Folder statistics
define("_DROPAUNITTOCOPY","下降一個單位，將它複製到指定位置");//Drop a unit to copy it to the designated position
define("_DRAGAUNITTOCOPY","拖曳單位將它複製");//Drag the unit to copy it
define("_ERROR","錯誤");//Error
define("_ERRORUPLOADINGFILE","錯誤上傳文件");//Error uploading file
define("_EDITANNOUNCEMENT","編輯公告");//Edit announcement
define("_ANNOUNCEMENT","公告");//Announcement
define("_THEFOLLOWINGFOLDERSCOULDNOTBEDELETED","下列文件夾無法刪除");//The following folders could not be deleted
define("_SUCCESFULLYCLEANEDUPFOLDERS","成功清理文件夾");//Succesfully cleaned up folders
define("_THEFOLLOWINGLESSONSCOULDNOTBEDELETED","以下的經驗教訓無法刪除");//The following lessons could not be deleted
define("_SUCCESFULLYCLEANEDUPLESSONS","成功清理了教訓");//Succesfully cleaned up lessons
define("_SUCCESFULLYCREATEDLESSONFOLDERS","成功創建文件夾的教訓");//Succesfully created lesson folders
define("_THEFOLLOWINGLESSONFOLDERSCOULDNOTBECREATED","文件夾以下的教訓，無法建立");//The folders for the following lessons could not be created
define("_EDITCONTENT","編輯內容");//Edit content
define("_NORMALSTATUS","正常狀態");//Normal status
define("_APPLICATIONPENDING","未決申請。按下“送出” ，以核實");//Application pending. Press &quot;Submit&quot to verify
define("_SUCCESS","成功");//Success
define("_WARNING","警告");//Warning
define("_DEFINITIONCOULDNOTBEINSERTED","的定義，無法插入");//Definition could not be inserted
define("_SUCCESFULLYUPDATEDDEFINITION","成功更新的定義");//Succesfully updated definition
define("_SUCCESFULLYDELETEDDEFINITION","成功刪除的定義");//Succesfully deleted definition
define("_DEFINITIONCOULDNOTBEUPDATED","deinition無法更新");//Deinition could not be updated
define("_SUBMITTERM","提交任期");//Submit term
define("_EDITDEFINITION","編輯的定義");//Edit definition
define("_NOFOLDERSFOUNDTOCOPYTO","有沒有文件夾複製/移動到");//There are no folders to copy/move to
define("_SCORMFILE","SCORM的檔案");//SCORM file
define("_SMILIES","笑臉");//Smilies
define("_SURVEYS","調查");//Surveys
define("_MODULES","模塊");//Modules
define("_INSTALLMODULE","安裝模塊");//Install module
define("_COULDNOTOPENZIPFILE","ZIP文件無法打開");//The ZIP file could not be opened
define("_MODULEINFORMATION","模塊信息");//Module information
define("_MODULESUCCESFULLYINSTALLED","該模塊已成功安裝");//The module was successfully installed
define("_DESCRIPTIONFILECOULDNOTBEFOUND","該模塊無法安裝，因為說明文件， module.xml ，沒有被發現。");//The module could not be installed because the description file, module.xml, was not found.
define("_SUCCESFULLYDELETEDMODULE","該模塊已成功刪除");//The module was successfully deleted
define("_AUTHOR","作者");//Author
define("_VERSION","版本");//Version
define("_THEFIELDSINYOURCSVFILEMUSTCONTAINTHEFOLLOWINGFIELDS","該領域在您的CSV文件必須包含下列領域");//The fields in your csv file must contain the following fields
define("_IFEMPTYNEWPASSWORD","在紅色領域是強制性的。如果沒有密碼，給出初始密碼將被設置相同的登錄。");//Fields in red are mandatory. If there is no password given, the initial password will be set the same as the login.
define("_PLEASECHECKYOURCSVFILEFORMAT","請檢查格式的CSV文件");//Please check the format of your CSV file
define("_CERTIFICATEINSTRUCTIONS","使用用戶名＃ ＃為使用者的名稱，編號user_surname ＃為用戶的姓， ＃ course_name ＃課程的名稱，編號＃級，一級和＃日期＃日期。");//In the template, use #organization# for organization&#039;s name, #user_name# for user&#039;s name, #user_surname# for user&#039;s surname, #course_name# for course&#039;s name, #grade# for grade and #date# for date.
define("_VOTES","票");//Votes
define("_PERCENTAGE","百分比");//Percentage
define("_CERTIFICATEISSUED","頒發證書");//Certificate issued
define("_ISSUE","問題");//Issue
define("_PROBLEMISSUINGCERTIFICATE","該證書無法發出");//The certificate could not be issued
define("_REVOKECERTIFICATE","撤銷證書");//Revoke certificate
define("_VIEWCERTIFICATE","查看證書");//View certificate
define("_CERTIFICATEREVOKED","該證書被撤銷成功");//The certificate was revoked successfully
define("_PROBLEMREVOKINGCERTIFICATE","證書不能被撤銷");//The certificate could not be revoked
define("_CHECKFORUPDATES","檢查更新");//Check for updates
define("_MODULEUPDATE","更新模塊");//Update module
define("_PENDING","緊迫的");//Pending
define("_DEADLINEPASSED","限期已通過");//The deadline has passed
define("_PROJECTFINISHED","該項目完成");//The project is finished
define("_FILEUPLOADEDAWAITINGGRADE","該文件上傳，但該項目尚未分級。");//The file was uploaded, but the project has not been graded yet.
define("_LOCKDOWN","鎖定");//Lock down
define("_LOCKDOWNFROM","鎖定系統，從");//Lock down system from
define("_LOCKDOWNTO","鎖定系統");//Lock down system to
define("_DISPLAYINDEXMESSAGE","顯示通知訊息系統的第一頁");//Display notification message to system first page
define("_SETANNOUNCEMENT","設定一個系統公佈");//Set a system announcement
define("_NOLESSONSFOUND","沒有的經驗教訓，發現");//No lessons found
define("_SUCCESFULLYSETORDER","經驗教訓，以便在課程設置成功");//The lessons order in course was set successfully 
define("_PROBLEMSETTINGORDER","經驗教訓，以便在這個過程中無法定");//The lessons order in the course could not be set
define("_ENABLEDAPI","啟用XML的空氣污染指數");//Enabled XML API
define("_OLDUPGRADEBACKUPS","舊升級備份");//Old upgrade backups
define("_CLEANUPALL","清理所有");//Clean up all
define("_THISOPERATIONALTERSYSTEM","此操作將永久地刪除數據和文件從系統。你絕對肯定?");//This operation will permanently delete data and files from the system. Are you absolutely sure?
define("_SMTPAUTH","SMTP驗證");//SMTP authentication
define("_FLAG","國旗");//Flag
define("_SETNORMALPRIORITY","設置優先正常");//Set priority to normal
define("_SETHIGHPRIORITY","設定優先次序，以高");//Set priority to high
define("_YOUMUSTSELECTMESSAGESTOFLAG","您必須選擇訊息給國旗");//You must select messages to flag
define("_SYSTEMEMAIL","電子郵件系統");//System email
define("_MAXFILESIZE","檔案大小上限");//Maximum file size
define("_SUCCESFULLYUPDATECONFIGURATION","成功更新配置變量");//Succesfully updated configuration variables
define("_COULDNOTUPDATE","無法更新");//Could not update
define("_WITHVALUE","與價值");//with value
define("_INVALIDFIELDDATAFORFIELD","無效的數據為外地");//Invalid data for field
define("_LDAPVARIABLES","LDAP服務器配置");//LDAP server configuration
define("_EMAILCOULDNOTBESENDBECAUSE","該電子郵件無法寄出");//The email could not be sent
define("_EMAILSENDTOYOURADDRESS","電子郵件被發送到您的電子郵件地址");//The email was send to your email address
define("_YOUMUSTFIRSTCREATEDIRECTION","以創造一個教訓，您必須先建立一個類別");//In order to create a lesson, you must first create a category
define("_SAVEQUESTIONANDCREATENEW","保存問題，並創建另一個");//Save question and create another
define("_SAVEASNEWQUESTION","另存為新問題");//Save as new question
define("_SUCCESFULLYUPDATEDPOLL","這項調查是在成功更新");//The poll was updated successfully
define("_YOUHAVESEENALLCONTENT","您已經完成了所有內容");//You have completed all content
define("_CONDITIONMET","條件滿足");//Condition met
define("_CONDITIONNOTMET","條件不符合");//Condition not met
define("_OLDMODULES","舊模塊");//Old modules
define("_PHPLDAPEXTENSIONISNOTLOADED","PHP的LDAP的擴展是不加載");//The PHP LDAP extension is not loaded
define("_LESSONCONDITIONSCOMPLETED","你滿足教訓的完全條件。這個教訓，需要設置完成所教授");//You meet the lesson's complete conditions. This lesson needs to be set as completed by the professor
define("_LESSONCOMPLETE","教訓完成");//Lesson completed
define("_CERTIFICATEISSUEDSUCCESFULLY","簽發的證書成功");//Certificate issued successfully
define("_NOTITLE","無標題");//No title
define("_AUTOMATICCERTIFICATES","自動證書");//Automatic certificates
define("_OFF","遠的");//off
define("_POLLDELETEDSUCCESSFULLY","這項調查是在已成功刪除");//The poll was deleted successfully
define("_POLLS","調查");//Polls
define("_TWOOPTIONSATMINIMUMREQUIRED","最低的兩個不同的方案，都需要調查");//At minimum two different options are required for the poll
define("_POLL","民意調查");//Poll
define("_VOTE","投票");//Vote
define("_YOUHAVEALREADYVOTED","你已經投了票，為這次調查");//You have already voted for this poll
define("_SUCCESFULLYVOTED","您的投票已submited");//Your vote has been submited
define("_VIEWRESULTS","查看結果");//View results
define("_TOTALVOTES","總票數");//Total votes
define("_SUBMITTEST","提交測試");//Submit test
define("_RATEMUSTBEBETWEEN1100","分數必須範圍1到100之間");//The score must range between 1 and 100
define("_NUMOFQUESTIONS","若干問題");//Number of questions
define("_TESTDURATION","測試持續時間");//Test duration
define("_QUESTIONSARESHOWN","問題顯示");//Questions are shown
define("_YOUCANDOTHETEST","你可以做的測試");//You can do the test
define("_DONETIMESSOFAR","到目前為止，你做了這個測試");//So far you have done this test
define("_ALLTOGETHER","所有一起");//All together
define("_ONEBYONEQUESTIONS","一個又一個");//One by one
define("_TIMES","時代");//times
define("_LDAPACCOUNTPASSWORD","LDAP的帳戶密碼");//LDAP account password
define("_USELDAPACCOUNT","使用您的LDAP帳戶憑據，以便使用該系統");//Use your LDAP account credentials in order to use the system
define("_ONLYLDAPREGISTRATIONPERMITTED","只有註冊使用有效的LDAP帳戶允許");//Only registration using a valid LDAP account is permitted
define("_GENERALLYAVAILABLE","一般可用");//is generally available
define("_DELETECONDITION","刪除條件");//Delete condition
define("_ADDFORUMPOSTONTHISUNIT","論壇會議後的信息，這個單位的");//Post forum message for this unit
define("_AUTOCOMPLETE","自動完成");//Auto complete
define("_DUPLICATESARENOTALLOWED","您不能使用兩次同樣的教訓，在一個法治");//You can&#039;t use twice the same lesson in a rule
define("_TIMEINLESSON","時間在一課");//Time in lesson
define("_ACCOUNTACTIVATIONMAILSUBJECT","激活帳戶的電子郵件");//Account activation email
define("_YOUWILLRECEIVEMAILFORACCOUNTACTIVATION","您會收到一封電子郵件來啟動您的帳戶");//You will receive an email to activate your account
define("_ACCOUNTACTIVATIONMAILBODY","歡迎eFront eLearning的平台。按照下面的鏈接，以激活您的帳戶：");//Welcome to eFront eLearning platform. Follow link below to activate your account:
define("_ACCOUNTSUCCESSFULLYACTIVATED","您的帳戶已成功啟動");//Your account was successfully activated
define("_SUCCESSFULLYINSERTEDVALUES","成功插入的價值觀");//Successfully inserted values
define("_NEWFORUM","新論壇");//New forum
define("_FORUMS","論壇");//Forums
define("_FORUMADDEDSUCCESSFULLY","論壇的成功添加");//Forum added succesfully
define("_FORUMUPDATEDSUCCESSFULLY","論壇已成功更新");//Forum updated succesfully
define("_ACCESSIBLEBYUSERSOFLESSON","為教訓");//For lesson
define("_FORUMDELETEDSUCCESSFULLY","論壇已成功刪除");//Forum deleted succesfully
define("_ACCESSIBLEBY","到達");//Accessible by
define("_NEWFORUM","新論壇");//New forum
define("_ROOTUNIT","---熱門股----");//---Root unit----
define("_GENERICLESSONINFO","通用教訓信息");//Generic lesson info
define("_LOGRECORD","日誌記錄");//Log record
define("_NOFORUMPOSTSYET","有沒有職位，在這個論壇上，但");//There are no posts in this forum yet
define("_NOTOPICSFOUNDINTHISFORUM","有沒有主題在這個論壇");//There are no topics in this forum
define("_NOMESSAGESFOUNDINTHISTOPIC","有沒有訊息在這個主題");//There are no messages in this topic
define("_AVAILABLEFROM","可從");//Available from
define("_SUCCESSFULLYADDEDPOLL","成功將加入調查");//Successfully added poll
define("_RECIPIENT","受贈人");//Recipient
define("_SENDASEMAILALSO","發送電子郵件，也作為");//Send also as email
define("_NOSUBJECT","無主題");//No subject
define("_THEMESSAGEWASNOTSENTASEMAIL","郵件無法通過電子郵件發送");//The message could not be emailed
define("_TOTALLOGINTIME","總時間在系統");//Total time in system
if (defined('MODULE_HCD_INTERFACE') && MODULE_HCD_INTERFACE == 1) {
define("_THENEWFORMOFADDITIVELEARNING","網絡學習和人力資本發展");//eLearning and Human Capital Development
define("_AUTOMATICUSERACTIVATION","僱員自動激活");//Automatic employee activation
define("_USERSEXPORT","出口僱員");//Export employees
define("_USERSIMPORT","進口僱員");//Import employees
define("_NEWUSERS","新員工");//New employees
define("_USER","僱員");//Employee
define("_CHOOSEUSER","選擇僱員");//Select employee
define("_USERS","僱員");//Employees
define("_ALLSYSTEMUSERS","所有系統僱員");//All system employees
define("_USERSCONNECTEDTOSPECIFICCOURSE","所涉及的僱員與課程");//Employees involved with course
define("_USERSCONNECTEDTOSPECIFICLESSON","所涉及的僱員與教訓");//Employees involved with lesson
define("_SPECIFICTYPEUSERS","特定類型的員工");//Specific type of employees
define("_USERTYPE","學習者的基本類型");//Basic learner type
define("_ACTIVEUSER","積極僱員");//Active employee
define("_USERDELETED","僱員已刪除。");//Employee was deleted.
define("_THEUSER","僱員");//The employee
define("_CHOOSEUSERTODISCONNECT","選擇一個僱員斷開");//Select a employee to disconnect
define("_LOGOUTUSER","登出僱員");//Log out employee
define("_THEREARENOOTHERUSERSRIGHTNOWINTHISROOM","沒有僱員，目前在這聊天室");//No employee currently in this chat room
define("_USERSONLINE","僱員在線");//Employees online
define("_ANDTHEMESSAGESOFUSER","和郵件的員工");//And the messages of employee
define("_ALLUSERS","所有僱員");//All employees
define("_INVALIDUSER","無效的僱員名稱");//Invalid employee name
define("_REPLACEEXISTINGUSERS","取代重複的僱員");//Replace duplicate employees
define("_KEEPEXISTINGUSERS","不斷重複的僱員");//Keep duplicate employees
define("_NOOTHERUSERSONLINE","沒有其他的僱員目前在線");//No other employees currently online
define("_USERNAME","僱員姓名");//Employee name
define("_STATISTICSFORUSER","報告為僱員");//Reports for employee
define("_GENERALUSERINFO","一般員工信息");//General employee information
define("_USERCOMMUNICATIONINFO","僱員的信息溝通");//Employee information on communication
define("_USERUSAGEINFO","僱員的信息系統的使用情況");//Employee information on system usage
define("_THEUSERHASNOTDONEANYTESTSINTHISLESSON","僱員的還沒有完成任何測試，在這方面的教訓");//The employee has not completed any tests in this lesson
define("_USERSTATISTICS","僱員報告");//Employee reports
define("_REPORTSFORUSER","報告的員工");//Reports for employee (New)
define("_OTHERUSERSINROOM","其他僱員在房間內");//Other employees in the room
define("_NOMESSAGESFOUNDFORTHISINTERVALANDUSER","沒有郵件，發現為指定的時間間隔，房間和僱員");//No messages found for the specified interval, room and employee
define("_INVITEUSERS","邀請僱員");//Invite employees
define("_SPECIFICUSER","具體的僱員");//Specific employee
define("_ALLACTIVESYSTEMUSERS","所有活躍的僱員制度");//All active system employees
define("_WAITINGFORUSER","等待僱員");//Waiting for employee
define("_YOUHAVEINVITEDUSER","您邀請的僱員");//You have invited employee
define("_DEARUSER","親愛的僱員");//Dear employee
define("_ISVISIBLEFROMOTHERUSERS","可見，從任何僱員?");//Visible from any employee?
define("_CUSTOMIZEUSERSPROFILE","自定義僱員的個人資料");//Customize employee profile
define("_USERAVERAGESCOREFORLESSON","平均分數為教訓的測試");//Average score for lesson&#039;s tests
define("_USERISONLINE","該僱員是在線");//The employee is online
define("_USERJUSTLOGGEDIN","僱員在剛剛登入");//The employee just logged in
define("_UPDATEUSERSTOLESSONS","指派僱員的教訓");//Assign employees to lesson
define("_EDITUSERSLESSON","教訓用戶");//Lesson users
define("_NEWUSER","新僱員");//New employee
define("_UPDATEUSERS","更新僱員");//Update employees
define("_EDITUSER","僱員設置");//Employee settings
define("_EDITUSEREDIT","編輯僱員");//Edit employee (New)
define("_ADDUSERSTOSURVEY","新增僱員的調查");//Add employees to the survey
define("_UPDATEUSERTYPES","更新僱員類型");//Update employee types
define("_EDITUSERTYPE","編輯僱員類型");//Edit employee type (New)
define("_OPTIONSUSERTYPEFOR","選擇僱員類型");//Options for employee type (New)
define("_NEWUSERTYPE","新僱員類型");//New employee type
define("_BASICUSERTYPE","僱員的基本類型");//Basic employee type
define("_AREYOUSUREYOUWANTTODELETEUSERTYPE","您確定要刪除僱員的類型?");//Are you sure you want to delete employee type?
define("_SUCCESFULLYUPDATEDUSERTYPE","僱員型成功更新");//Employee type was updated successfully
define("_SUCCESFULLYADDEDUSERTYPE","僱員類型是添加成功");//Employee type was added successfully
define("_USERSMANAGEMENT","僱員管理");//Employees management
define("_AREYOUSUREYOUWANTTODELETEUSER","您確定要刪除的僱員呢?");//Are you sure you want to delete employee?
define("_USERTYPEDELETED","僱員類型刪除");//Employee type deleted
define("_EDITUSERSCOURSE","當然僱員");//Course employees
define("_USERDEACTIVATED","僱員停用");//Employee deactivated
define("_USERACTIVATED","僱員激活");//Employee activated
define("_USERSKIND","僱員類型");//Employee types
define("_USERTYPES","僱員類型");//Employee types
define("_SMTPUSER","的SMTP登錄");//SMTP login
define("_USERCREATED","僱員創造");//Employee created
define("_USERTRAFFIC","僱員的交通");//Employee&#039;s traffic
define("_USERSPROGRESS","僱員的地位");//Employees status
define("_THEUSERHASNOTCOMPLETEDTHELESSON","僱員的還沒有完成，但這個教訓");//The employee has not completed this lesson yet
define("_MOSTACTIVEUSERS","最活躍的僱員");//Most active employees
define("_5MOSTACTIVEUSERS","5最活躍的僱員");//5 most active employees
define("_NOUSERFORTHISSURVEYYET","沒有僱員，但本次調查.");//No employees for this survey yet.
define("_SHOWALLUSERS","顯示所有僱員");//Show all employees
define("_THEREARENOLESSONSDEFINEDFORTHEUSERLANGUAGE","有沒有經驗教訓的定義為僱員的語言");//There are no lessons defined for the employees&#39;s language
define("_VIEWUSERLESSONPROGRESS","鑑於學生的進展，整個的教訓");//View the student progress throughout the lesson
define("_USERCAPITAL","僱員");//Employee
define("_USERSDATA","匯入/匯出僱員");//Import/Export employees
define("_ORPHANUSERFOLDERSCHECK","孤兒僱員文件夾檢查");//Orphan employee folders check
define("_USERSWITHOUTFOLDERSCHECK","僱員沒有文件夾檢查");//Employees without folders check
define("_FOLDERSWITHOUTAUSERASSOCIATED","下列文件夾中沒有一個相關的僱員");//The following folders do not have a employee associated
define("_USERSWITHOUTAFOLDER","以下的僱員沒有一個文件夾");//The following employees do not have a folder
define("_PEMANENTLYDELETEFOLLOWINGUSERS","這一行動將永久刪除以下僱員");//This action will permanently delete the following employees
define("_CREATEFOLLOWINGUSERFOLDERS","這一行動將創建文件夾為以下僱員");//This action will create folders for the following employees
define("_USERPROGRESS","僱員進展");//Employee progress
define("_LOGOUTUSERS","登出僱員在線");//Log out employees online
define("_USERTRACKINGINFORMATION","僱員跟踪信息");//Employee tracking information
define("_MAILUSERACTIVATION","僱員激活通過電子郵件");//Employee activation by email
define("_USERSMAYADDFORUMS","僱員可添加論壇");//Employees may add forums
define("_NONEWAPPLICATIONS","沒有申請新僱員");//No application from new employees
define("_EXPORTUSERSDATA","出口僱員數據");//Export employees data
define("_IMPORTUSERSDATA","進口僱員資料");//Import employees data
define("_THEUSERHASNOTBEENASSIGNEDANYPROJECT","沒有項目已分配給這名僱員");//No project has been assigned to this employee
define("_SUCCESFULLYCLEANEDUPUSERS","成功清理僱員");//Succesfully cleaned up employees
define("_SUCCESFULLYCREATEDUSERFOLDERS","成功地建立了僱員的文件夾");//Succesfully created employee folders
define("_THEFOLLOWINGUSERFOLDERSCOULDNOTBECREATED","以下僱員的文件夾無法創建");//The following employee folders could not be created
define("_GROUP","僱員組");//Employee group
define("_USERSINFO","僱員信息");//Employees info
define("_PROFESSORSINFO","教授信息");//Professors info
define("_EMPLOYEEWASASSIGNEDGROUP","僱員被分配到組");//Employee was assigned to group
define("_EMPLOYEEWASRELEASEDFROMGROUP","僱員被釋放，從組");//Employee was released from group
define("_PROFESSORCAPITAL","教授");//Professor
define("_STUDENTROLE","僱員的作用");//Employee role
define("_PROFESSORROLE","教授的作用");//Professor role
} else {
define("_THENEWFORMOFADDITIVELEARNING","網絡學習和人力資本發展");//Refreshing eLearning
define("_AUTOMATICUSERACTIVATION","僱員自動激活");//Automatic user activation
define("_USERSEXPORT","出口僱員");//Export users
define("_USERSIMPORT","進口僱員");//Import users
define("_NEWUSERS","新員工");//New users
define("_USER","僱員");//User
define("_CHOOSEUSER","選擇僱員");//Select user
define("_USERS","僱員");//Users
define("_ALLSYSTEMUSERS","所有系統僱員");//All system users
define("_USERSCONNECTEDTOSPECIFICCOURSE","所涉及的僱員與課程");//Users involved with specific course
define("_USERSCONNECTEDTOSPECIFICLESSON","所涉及的僱員與教訓");//Users involved with specific lesson
define("_SPECIFICTYPEUSERS","特定類型的員工");//Specific type of users
define("_USERTYPE","學習者的基本類型");//User type
define("_ACTIVEUSER","積極僱員");//Active user
define("_USERDELETED","僱員已刪除。");//User deleted.
define("_THEUSER","僱員");//The user
define("_CHOOSEUSERTODISCONNECT","選擇一個僱員斷開");//Select a user to disconnect
define("_LOGOUTUSER","登出僱員");//Log out user
define("_THEREARENOOTHERUSERSRIGHTNOWINTHISROOM","沒有僱員，目前在這聊天室");//No user currently in this chat room
define("_USERSONLINE","僱員在線");//Users online
define("_ANDTHEMESSAGESOFUSER","和郵件的員工");//And the messages of user
define("_ALLUSERS","所有僱員");//All users
define("_INVALIDUSER","無效的僱員名稱");//Invalid user name
define("_REPLACEEXISTINGUSERS","取代重複的僱員");//Replace duplicate users
define("_KEEPEXISTINGUSERS","不斷重複的僱員");//Keep duplicate users
define("_NOOTHERUSERSONLINE","沒有其他的僱員目前在線");//No other users currently online
define("_USERNAME","僱員姓名");//User name
define("_STATISTICSFORUSER","報告為僱員");//Reports for user
define("_GENERALUSERINFO","一般員工信息");//General user information
define("_USERCOMMUNICATIONINFO","僱員的信息溝通");//User information on communication
define("_USERUSAGEINFO","僱員的信息系統的使用情況");//User information on system usage
define("_THEUSERHASNOTDONEANYTESTSINTHISLESSON","僱員的還沒有完成任何測試，在這方面的教訓");//The user has not completed any tests in this lesson
define("_USERSTATISTICS","僱員報告");//User reports
define("_REPORTSFORUSER","用戶報告");//Reports for user (New)
define("_OTHERUSERSINROOM","其他僱員在房間內");//Other users in the room
define("_NOMESSAGESFOUNDFORTHISINTERVALANDUSER","沒有郵件，發現為指定的時間間隔，房間和僱員");//No messages found for the specified interval, room and user
define("_INVITEUSERS","邀請僱員");//Invite users
define("_SPECIFICUSER","具體的僱員");//Specific user
define("_ALLACTIVESYSTEMUSERS","所有活躍的僱員制度");//All active system users
define("_WAITINGFORUSER","等待僱員");//Waiting for user
define("_YOUHAVEINVITEDUSER","您邀請的僱員");//You have invited user
define("_DEARUSER","親愛的僱員");//Dear user
define("_ISVISIBLEFROMOTHERUSERS","可見，從任何僱員?");//Visible from any user?
define("_CUSTOMIZEUSERSPROFILE","自定義僱員的個人資料");//Customize user profile
define("_USERISONLINE","該僱員是在線");//The user is online
define("_USERJUSTLOGGEDIN","僱員在剛剛登入");//The user just logged in
define("_UPDATEUSERSTOLESSONS","指派僱員的教訓");//Select lesson users
define("_EDITUSERSLESSON","教訓用戶");//Lesson users
define("_NEWUSER","新僱員");//New user
define("_UPDATEUSERS","更新僱員");//Update users
define("_EDITUSER","僱員設置");//User settings
define("_EDITUSEREDIT","編輯用戶");//Edit user (New)
define("_ADDUSERSTOSURVEY","新增僱員的調查");//Add users to the survey
define("_UPDATEUSERTYPES","更新僱員類型");//Update user types
define("_EDITUSERTYPE","編輯用戶類型");//Edit user type (New)
define("_OPTIONSUSERTYPEFOR","選擇用戶類型");//Options for user type (New)
define("_NEWUSERTYPE","新僱員類型");//New user type
define("_BASICUSERTYPE","僱員的基本類型");//Basic user type
define("_AREYOUSUREYOUWANTTODELETEUSERTYPE","您確定要刪除僱員的類型?");//Are you sure you want to delete user type?
define("_SUCCESFULLYUPDATEDUSERTYPE","僱員型成功更新");//User type was updated successfully
define("_SUCCESFULLYADDEDUSERTYPE","僱員類型是添加成功");//User type was added successfully
define("_USERSMANAGEMENT","僱員管理");//Users management
define("_AREYOUSUREYOUWANTTODELETEUSER","您確定要刪除的僱員呢?");//Are you sure you want to delete user?
define("_USERTYPEDELETED","僱員類型刪除");//User type deleted
define("_EDITUSERSCOURSE","當然僱員");//Course users
define("_USERDEACTIVATED","僱員停用");//User deactivated
define("_USERACTIVATED","僱員激活");//User activated
define("_USERSKIND","僱員類型");//User types
define("_USERTYPES","僱員類型");//User types
define("_SMTPUSER","的SMTP登錄");//SMTP user
define("_USERCREATED","僱員創造");//User created
define("_USERTRAFFIC","僱員的交通");//User&#039;s traffic
define("_USERSPROGRESS","僱員的地位");//Users status
define("_THEUSERHASNOTCOMPLETEDTHELESSON","僱員的還沒有完成，但這個教訓");//The user has not completed this lesson yet
define("_MOSTACTIVEUSERS","最活躍的僱員");//Most active users
define("_5MOSTACTIVEUSERS","5最活躍的僱員");//5 most active users
define("_NOUSERFORTHISSURVEYYET","沒有僱員，但本次調查.");//No users for this survey yet.
define("_SHOWALLUSERS","顯示所有僱員");//Show all users
define("_THEREARENOLESSONSDEFINEDFORTHEUSERLANGUAGE","有沒有經驗教訓的定義為僱員的語言");//There are no lessons defined for the users&#39;s language
define("_VIEWUSERLESSONPROGRESS","鑑於學生的進展，整個的教訓");//View the student progress throughout the lesson
define("_USERCAPITAL","僱員");//User
define("_USERSDATA","匯入/匯出僱員");//Import/Export users
define("_ORPHANUSERFOLDERSCHECK","孤兒僱員文件夾檢查");//Orphan user folders check
define("_USERSWITHOUTFOLDERSCHECK","僱員沒有文件夾檢查");//Users without folders check
define("_FOLDERSWITHOUTAUSERASSOCIATED","下列文件夾中沒有一個相關的僱員");//The following folders do not have a user associated
define("_USERSWITHOUTAFOLDER","以下的僱員沒有一個文件夾");//The following users do not have a folder
define("_PEMANENTLYDELETEFOLLOWINGUSERS","這一行動將永久刪除以下僱員");//This action will permanently delete the following users
define("_CREATEFOLLOWINGUSERFOLDERS","這一行動將創建文件夾為以下僱員");//This action will create folders for the following users
define("_USERPROGRESS","僱員進展");//User progress
define("_LOGOUTUSERS","登出僱員在線");//Log out users online
define("_USERTRACKINGINFORMATION","僱員跟踪信息");//User tracking information
define("_MAILUSERACTIVATION","僱員激活通過電子郵件");//User activation by email
define("_USERSMAYADDFORUMS","僱員可添加論壇");//Users may add forums
define("_NONEWAPPLICATIONS","沒有申請新僱員");//No application from new users
define("_EXPORTUSERSDATA","出口僱員數據");//Export users data
define("_IMPORTUSERSDATA","進口僱員資料");//Import users data
define("_THEUSERHASNOTBEENASSIGNEDANYPROJECT","沒有項目已分配給這名僱員");//No project has been assigned to this user
define("_SUCCESFULLYCLEANEDUPUSERS","成功清理僱員");//Succesfully cleaned up users
define("_SUCCESFULLYCREATEDUSERFOLDERS","成功地建立了僱員的文件夾");//Succesfully created user folders
define("_THEFOLLOWINGUSERFOLDERSCOULDNOTBECREATED","以下僱員的文件夾無法創建");//The following user folders could not be created
define("_GROUP","僱員組");//User group
define("_USERSINFO","僱員信息");//Users info
define("_PROFESSORSINFO","教授信息");//Professors info
define("_EMPLOYEEWASASSIGNEDGROUP","僱員被分配到組");//User was assigned to group
define("_EMPLOYEEWASRELEASEDFROMGROUP","僱員被釋放，從組");//User was released from group
define("_PROFESSORCAPITAL","教授");//Professor
define("_STUDENTROLE","僱員的作用");//Student role
define("_PROFESSORROLE","教授的作用");//Professor role
}
define("_COURSES","課程");//Courses
define("_COURSEDELETED","當然刪除");//Course deleted
define("_COURSEDEACTIVATED","當然停用");//Course deactivated
define("_COURSEACTIVATED","當然激活");//Course activated
define("_COURSENAME","課程名稱");//Course name
define("_COURSEUPDATED","當然更新");//Course updated
define("_SUCCESFULLYCREATEDCOURSE","當然，成功創建");//Course was created successfully
define("_COURSEOPTIONSFOR","當然選擇");//Options for course
define("_NEWCOURSEOPTIONS","新課程的選擇");//New course options
define("_EDITCOURSE","編輯過程中");//Edit course
define("_EDITLESSONSCOURSE","當然，教訓");//Course lessons
define("_NEWCOURSE","新課程");//New course
define("_UPDATECOURSES","更新課程");//Update courses
define("_COURSE","課程");//Course
define("_COURSEONLY","當然，僅通過");//Exclusively through course
define("_AREYOUSUREYOUWANTTODELETECOURSE","您確定要刪除課程?");//Are you sure you want to delete course?
define("_NOCOURSESFOUND","沒有課程的定義");//No courses defined
define("_UPDATEEMPLOYEES","更新僱員");//Update employees
define("_NEWJOB","指派新的就業");//Assign new job
define("_AREYOUSUREYOUWANTTOCANCELJOB","您確定要取消這名僱員從這個工作。");//Are you sure you want to cancel this employee from this job.
define("_AREYOUSUREYOUWANTTOFIREEMPLOYEE","您確定要小心防火這名僱員從該公司?");//Are you sure you want to fire this employee from the company?
define("_FIRE","火");//Fire
define("_WAGE","工資");//Wage
define("_VATREGNUMBER","增值稅reg.no.");//VAT Reg.No.
define("_HIREDON","僱用的");//Hired on
define("_SUPERVISOR","監");//Supervisor
define("_JOBDESCRIPTIONS","職務說明");//Job descriptions
define("_EMPLOYEERELEASEDFROMJOB","僱員發表的求職者");//Employee released from job
define("_SKILLS","技能");//Skills
define("_SKILL","技能");//Skill
define("_SPECIFICATION","規格");//Specification
define("_DETAILS","詳情");//Details
define("_PLACEMENTS","位置");//Placements
define("_JOBALREADYASSIGNED","選定的位置是已經分配給這名僱員");//Selected placement is already assigned to this employee
define("_BRANCHNAME","分公司名稱");//Branch name
define("_EMPLOYEEPOSITION","僱員的立場");//Employee position
define("_JOBDESCRIPTION","職位描述");//Job description
define("_UPDATEBRANCHES","更新黨支部");//Update branches
define("_NEWBRANCH","新科");//New branch
define("_FATHERBRANCHNAME","父親科");//Father branch
define("_BRANCHES","黨支部");//Branches
define("_BRANCHDELETED","科刪除");//Branch deleted
define("_AREYOUSUREYOUWANTTODISMISSTHEBRANCH","您確定要取消該分公司?");//Are you sure you want to dismiss that branch?
define("_COUNTRY","國籍");//Country
define("_TELEPHONE","電話");//Telephone
define("_BRANCHRECORD","科創紀錄");//Branch record
define("_BRANCHDATAUPDATED","分行的數據更新");//Branch data updated
define("_FATHERBRANCH","父親科");//Father branch
define("_HCD","人力資本開發");//Human Capital Development
define("_ORGANISATIONCHART","組織架構圖");//Organisation chart
define("_CANDIDATES","候選人");//Candidates
define("_SUCCSSFULLYCREATEDBRANCH","科已成功創建");//Branch was successfully created
define("_ATBRANCH","在科");// at branch 
define("_FATHERBRANCHCOULDNOTBESET","目標父親分行不能成立，因為它是劣，這科在層次結構");//Target father branch could not be set, because it is inferior to this branch in the hierarchy
define("_JOBSASSIGNED","工作分配");//Jobs assigned
define("_AREYOUSUREYOUWANTTOREMOVETHATSKILL","您確定要刪除的技能從名單中?");//Are you sure you want to remove that skill from the list?
define("_SKILLDATA","技巧數據");//Skill data
define("_NEWSKILL","新技能");//New skill
define("_SKILLDESCRIPTION","技能描述");//Skill description
define("_HAVINGSKILL","有技巧");// having the skill 
define("_EMPLOYEESWITHTHATSKILL","僱員技能");//Employees with skill
define("_UPDATESKILLS","更新技能");//Update skills
define("_THISSKILLSELEMENTSCOULDNOTBEDELETED","此技能無法刪除");//This skill could not be deleted
define("_SKILLDATAUPDATED","技能說明更新");//Skill description updated
define("_SKILLCOULDNOTBECREATED","技能無法建立");//Skill could not be created
define("_SUCCESSFULLYCREATEDSKILL","技能創造成功");//Skill created successfully
define("_SKILLDELETED","技能刪除");//Skill deleted
define("_NOEMPLOYEESPOSSESSSKILL","沒有僱員擁有這種技巧");//No employees possess this skill
define("_NOEMPLOYEESWORKATBRANCH","沒有工作的僱員目前在這個科");//No employees currently work at this branch
define("_UPDATEJOBDESCRIPTIONS","更新的職務說明");//Update job descriptions
define("_NEWJOBDESCRIPTION","新的職務說明");//New job description
define("_CURRENTLYEMPLOYEED","目前受聘");//Currently employed
define("_VACANCIES","可配售");//Available placements
define("_AREYOUSUREYOUWANTTOREMOVETHATJOBDESCRIPTION","您確定要刪除的就業說明?");//Are you sure you want to remove that job description?
define("_JOBDESCRIPTIONDATA","職位描述數據");//Job description data
define("_HAVINGJOBDESCRIPTION","有職位描述");// having the job description 
define("_NOEMPLOYEESPOSSESSJOBDESCRIPTION" , "No employees are currently assigned to this job description");
define("_SUCCESSFULLYCREATEDJOBDESCRIPTION","成功地建立了職位描述");//Successfully created job description
define("_JOBDESCRIPTIONCOULDNOTBECREATED","職位描述無法創建");//Job description could not be created
define("_JOBDESCRIPTIONDATAUPDATED","職位描述數據已成功更新");//Job description data were successfully updated
define("_JOBDESCRIPTIONDELETED","職位描述刪除");//Job description deleted
define("_THISJOBDESCRIPTIONSELEMENTSCOULDNOTBEDELETED","該職位描述的元素無法刪除");//The job description&#039;s elements could not be deleted
define("_EDITJOBDESCRIPTION","編輯職位描述");//Edit job description
define("_SKILLSREQUIRED","所需技能");//Skills desired
define("_EMPLOYEESOFBRANCH","僱員科");//Employees of branch
define("_EMPLOYEESWITHSKILL","僱員技能");//Employees with skill
define("_FILERECORD","檔案記錄");//File record
define("_VIEW","查看");//View
define("_SORRYYOUDONOTHAVEPERMISSIONTOPERFORMTHISACTION","對不起，您沒有權限執行此操作");//Sorry you do not have the permission to perform this action
define("_MOBILEPHONE","移動電話");//Mobile phone
define("_EMPLOYEESDATASUCCESSFULLYUPDATED","僱員數據成功更新");//Employee data successfully updated
define("_EMPLOYEESRECORDCOULDNOTBEUPDATED","僱員的記錄無法更新");//Employee record could not be updated
define("_NOPLACEMENTSASSIGNEDYET","沒有位置的分配，但");//No placements assigned yet
define("_BRANCHCOULDNOTBECREATED","科無法建立");//Branch could not be created
define("_NOSKILLSHAVEBEENREGISTERED","沒有技能，已登記");//No skills have been registered
define("_NOJOBDESCRIPTIONSHAVEBEENREGISTERED","沒有工作，說明已登記");//No job descriptions have been registered
define("_PLACEMENTCOULDNOTBEASSIGNED","就業不能被指派");//Placement could not be assigned
define("_NOSKILLSASSIGNED","沒有技能分配");//No skills assigned
define("_NOSKILLSREGISTEREDASPREREQUISITES","沒有技能，登記為先決條件");//No skills registered as prerequisites
define("_SATISFYANYCRITERIA","滿足任何準則");//Satisfy any criteria
define("_SATISFYALLCRITERIA","滿足所有的準則");//Satisfy all criteria
define("_WORKINGATBRANCH","工作在科");//Working at branch
define("_WITHJOBDESCRIPTION" ,"With job description");
define("_FINDEMPLOYEES","尋找員工");//Find employees (New)
define("_WITHSKILL","與技巧");//With skill
define("_EMPLOYEESFULFILLINGCRITERIA","僱員履行的準則");//Employees fulfilling the criteria
define("_NOEMPLOYEESFULFILLTHESPECIFIEDCRITERIA","沒有僱員，完成指定的標準");//No employees fulfill the specified criteria
define("_ORGANIZATIONCHARTTREE","組織結構圖樹");//Organization chart tree
define("_ANYBRANCH","任何分行");//Any branch
define("_ANYJOBDESCRIPTION","任何職位描述");//Any job description
define("_EXPORTVACANCIES","出口空缺");//Export vacancies
define("_NATIONALSERVICECOMPLETED","國民服務");//National service
define("_DRIVINGLICENSE","駕駛執照");//Driver license
define("_BANKACCOUNT","帳戶");//Account
define("_BANK","銀行");//Bank
define("_TAXOFFICE","國稅廳");//Tax office
define("_POLICEIDNUMBER","警方編號");//Police id
define("_WORKPERMISSIONDATA","工作許可數據");//Work permission data
define("_WAYOFWORKING","工作");//Working as
define("_EMPLOYMENTTYPE","就業類別");//Employement type
define("_MARRIED","已婚");//Married
define("_SINGLE","單個");//Single
define("_MARITALSTATUS","婚姻狀況");//Marital status
define("_FEMALE","女性");//Female
define("_MALE","男性");//Male
define("_GENDER","性別");//Gender
define("_FATHERNAME","父親姓名");//Father name
define("_MOTHERTONGUE","母語");//Mother tongue
define("_NATIONALITY","國籍");//Nationality
define("_PARTTIME","部份時間");//Part time
define("_FULLTIME","全職");//Full time
define("_BIRTHDAY","生日");//Birthday
define("_BIRTHPLACE","出生的城市");//City of birth
define("_BIRTHCOUNTRY","出生國家");//Country of birth
define("_EMPLOYEES","僱員");//Employees
define("_NEWEMPLOYEE","新僱員");//New employee
define("_OFFICE","辦公室");//Office
define("_COMPANYINTERNALPHONE","公司內部電話");//Company internal phone
define("_EMPLOYEECREATED","僱員已成功創建");//Employee created successfully
define("_EMPLOYEEDELETED","僱員刪除");//Employee deleted
define("_SKILLSOFFERED","技能提供");//Skills offered
define("_NOSKILLSOFFERED","沒有技能提供");//No skills offered
define("_NOJOBDESCRIPTIONSSHAVEBEENREGISTERED","沒有工作，說明已登記");//No job descriptions have been registered
define("_INSERTEDINTOTHESYSTEM","插入到系統");//Inserted into the system
define("_HIRED","聘請");//Hired
define("_RAISEOF","提高");//Raise of
define("_EMPLOYEESNEWWAGEIS","僱員的新的工資是");//The employee&#039;s new wage is
define("_DECREASEOF","減少");//Decrease of
define("_EMPLOYEEWASASSIGNEDJOB","僱員被指派的工作");//Employee was assigned job
define("_EMPLOYEEWASRELEASEDFROMDJOB","僱員被釋放，從就業");//Employee was released from job
define("_EMPLOYEEWASASSIGNEDSKILL","僱員被指派的技巧");//Employee was assigned skill
define("_WASRELEASEDFROMEMPLOYEE","被釋放的僱員");//was released from employee
define("_EMPLOYEESSKILLSPECIFICATIONSFORSKILL","僱員的技能，技巧的規格");//Employee&#039;s skill specifications for skill
define("_WERECHANGEDTO","改為");//were changed to
define("_FIRED","發射");//Fired
define("_NOHISTORYREGARDINGTHISEMPLOYEE","歷史上沒有關於這名僱員記錄");//No history regarding this employee recorded
define("_HISTORYOFEMPLOYEE","歷史僱員");//History of employee
define("_HISTORY","歷史");//History
define("_NOANNOUNCEMENTSPOSTEDADMIN","沒有張貼公告");//No announcements posted
define("_SEPARATEMULTIPLEUSERS","分隔多個受助人;");//Separate multiple recipients with ;
define("_STARTTYPINGFORRELEVENTMATCHES","開始輸入，以獲取有關比賽（鍵入％ ，為所有）");//Start typing to get relevant matches (Type % for all)
define("_ADVANCEDSEARCH","高級搜索選項");//Advanced search options
define("_REGISTERADVANCEDSEARCHFIELDS","註冊進階搜尋欄位");//Register advanced search fields
define("_EDITBRANCH","編輯科");//Edit branch
define("_ASSIGNEMPLOYEES","指派員工");//Assign employees
define("_ASSIGNEMPLOYEESTOBRANCH","指派員工分行");//Assign employees to branch 
define("_EDITSKILL","編輯技巧");//Edit skill
define("_ASSIGNSKILL","轉讓的技術");//Assign skill
define("_ASSIGNEMPLOYEESTHESKILL","指派員工技能");//Assign employees the skill 
define("_NOBRANCHESHAVEBEENREGISTERED","沒有分行已登記");//No branches have been registered
define("_ORGANIZATION","組織");//Organization
define("_SEARCHFOREMPLOYEE","搜索為僱員[組織準則]");//Search for employee [Organization criteria]
define("_SUBFORUMS","subforums");//Subforums
define("_NOSUBFORUMSFOUND","有沒有subforums界定在這個論壇");//There are no subforums defined in this forum
define("_NONEWMESSAGELOCKED","您無法張貼任何新的訊息，因為這個題目或論壇被鎖定");//You cannot post any new messages because this topic or forum is locked
define("_ACTIVITY","活動");//Activity
define("_ISVALID","有效");//Valid
define("_LEFTON","左對");//Left on
define("_ADVANCED","先進標準");//Advanced criteria
define("_MYSTUDENTS","我的學生");//My students
define("_EMPLOYEE","僱員");//Employee
define("_NOBRANCHJOBSERROR","沒有工作，說明已登記為這個分支");//No job descriptions have been registered for this branch
define("_TESTSTATISTICS","測試報告");//Tests reports
define("_CHOOSETEST","選擇測試");//Choose test
define("_USERPROFILE","用戶配置文件");//User profile
define("_VIEWBRANCHES","鑑於黨支部");//View branches
define("_NOEMPLOYEESFOUND","沒有僱員被發現");//No employees were found
define("_SEARCHEMPLOYEE","搜索僱員");//Search employee
define("_ALLBRANCHES","所有分行");//All branches
define("_ANSWERS","答案");//Answers
define("_GROUPDOESNOTEXIST","該集團不存在");//The group doesn&#039;t exist
define("_SUBBRANCHES","分理處");//Sub-branches
define("_OFBRANCH","分行");// of branch 
define("_NEWSUBBRANCH","新的分支行");//New sub-branch
define("_SMTPTIMEOUT","的SMTP超時");//SMTP timeout
define("_ILLEGALPATH","非法路徑");//Illegal path
define("_FILEWASPARTIALLYUPLOADED","上傳的文件只有部分上傳");//The uploaded file was only partially uploaded
define("_NOFILEUPLOADED","沒有文件被上傳");//No file was uploaded
define("_NOTMPDIR","失踪系統上傳臨時文件夾中。請更新php.ini中設置相應的");//Missing a system upload temporary folder. Please update php.ini settings accordingly
define("_UPLOADCANTWRITE","無法寫入文件到磁盤");//Failed to write file to disk
define("_UPLOADERREXTENSION","文件上傳停止擴建");//File upload stopped by extension
define("_CANNOTCOPYFILE","該文件不能被複製");//The file cannot be copied
define("_CANNOTMOVEFILE","該文件無法移動");//The file cannot be moved
define("_DIRECTORYDOESNOTEXIST","目錄不存在");//The directory does not exist
define("_COULDNOTCREATEDIRECTORY","目錄無法創建");//The directory could not be created
define("_CANNOTCOPYDIRECTORY","目錄無法複製");//The directory cannot be copied
define("_DIRECTORYALREADYEXISTS","目錄已經存在");//The directory already exists
define("_AUTOASSIGNTONEWUSERS","自動分配給新用戶");//Automatically assign to new users
define("_CANNOTOPENCOMPRESSEDFILE","壓縮文件無法打開");//The compressed file cannot be opened
define("_CHOOSEWHATTODELETE","選擇要刪除系統初始化期間");//Choose what to delete during system initialization
define("_PERIODS","期");//Periods
define("_IMPORTLESSON","進口的教訓");//Import lesson
define("_EXPORTLESSON","出口的教訓");//Export lesson
define("_LESSONEXPORTEDSUCCESFULLY","的教訓，成功地出口");//Lesson succesfully exported
define("_LESSONIMPORTEDSUCCESFULLY","的教訓，成功導入");//Lesson succesfully imported
define("_FILESIZEMUSTBESMALLERTHAN","該文件必須小於");//The file must be smaller than
define("_PROBLEMIMPORTINGFILE","問題的進口文件");//Problem importing file
define("_PAGE","頁");//Page
define("_ACTIVE_PROJECTS","活躍");//Active
define("_INACTIVE_PROJECTS","停播");//Inactive
define("_TIMEREMAIN","保持");//Remain
define("_WEEKS","週");//weeks
define("_WEEKs","週");//week
define("_DAYS","天");//days
define("_DAY","白天");//Day
define("_EVALUATIONDATAUPDATED","評價數據更新成功");//Evaluation data updated successfully
define("_EVALUATION","評價");//Evaluation
define("_EVALUATIONOFEMPLOYEE","評價僱員");//Evaluation of employee
define("_NEWEVALUATION","新的評價");//New evaluation
define("_EVALUATIONCOMMENT","評價評論");//Evaluation comment
define("_EVALUATIONDELETED","評價刪除");//Evaluation deleted
define("_THEEVALUATIONCOULDNOTBEDELETED","評價無法刪除");//The evaluation could not be deleted
define("_SUCCESSFULLYCREATEDEVALUATION","成功地建立了評價");//Successfully created evaluation
define("_EVALUATIONCOULDNOTBECREATED","評價無法建立");//Evaluation could not be created
define("_AREYOUSUREYOUWANTTODELETEEVALUATION","您確定要刪除評價?");//Are you sure you want to delete the evaluation?
define("_NOEVALUATIONSASSIGNEDYET","沒有書面評價，但");//No evaluation written yet
define("_BRANCH","分支");//Branch
define("_PLACEMENT","安置");//Placement
define("_EVALUATIONS","評價");//Evaluations
define("_TRANSPORTMEANS","運輸途徑");//Means of transport
define("_YOUCANNOTDELETESOMEELSESEVALUATION","您不能刪除評價的書面交由另一名用戶");//You cannot delete an evaluation written by another user
define("_YOUCANNOTEDITSOMEELSESEVALUATION","您不能編輯評價書面交由另一名用戶");//You cannot edit an evaluation written by another user
define("_EMPLOYEEFORM","僱員的形式");//Employee form
define("_EMPLOYEEFORMPRINTPREVIEW","僱員的形式打印預覽");//Employee form print preview
define("_PRINTPREVIEW","打印預覽");//Print preview
define("_PRINTEMPLOYEEFORM","打印僱員的形式");//Print employee form
define("_PRINT","打印");//Print
define("_NOSPECIFICJOB","沒有具體的職位描述");//No specific job description
define("_GROUPS","用戶群體");//User groups
define("_NEWGROUP","新組");//New group
define("_NOGROUPSDEFINED","沒有團體的定義");//No groups defined
define("_UPDATEGROUPS","更新團體");//Update groups
define("_GROUPDEACTIVATED","該集團已停用");//The group was deactivated
define("_GROUPACTIVATED","該集團被激活");//The group was activated
define("_EDITGROUP","編輯組");//Edit group
define("_UPDATEGROUP","更新組");//Update group
define("_SUCCESFULLYADDEDGROUP","該集團已成功加入");//The group was succesfully added
define("_AREYOUSUREYOUWANTTODELETEGROUP","是您確定要刪除該組?");//Are you sure you want to delete the group?
define("_GROUPDELETED","該集團已刪除");//The group was deleted
define("_GROUPFILTER","組過濾器");//Group filter
define("_NOUSERSFOUND","無用戶那裡發現");//No users where found
define("_SEPARATEALTERNATIVESEXAMPLE","單獨的替代正確答案，與| ，例如：藍|黑|白");//Separate alternative correct answers with |, for example: Blue|Black|White
define("_CREATERANODOMTEST","創建隨機測試");//Create random test
define("_USING","使用");//Using
define("_EASY","容易的");//Easy
define("_HARD","硬的");//Hard
define("_LOCALESETTINGS","區域設置");//Locale settings
define("_CURRENCY","貨幣");//Currency
define("_DECIMALPOINT","小數點");//Decimal point
define("_THOUSANDSSEPARATOR","千位分隔符");//Thousands separator
define("_DATEFORMAT","日期格式");//Date format
define("_SPECIFICLOCALE","具體位置");//Specific locale
define("_LOCATION","位置");//Location
define("_TIMEZONE","時區");//Time zone
define("_INVALIDRECIPIENT","無效的收件者");//Invalid recipient
define("_NOBRANCHSELECTED","沒有科被選為");//No branch was selected
define("_AREYOUSUREYOUWANTTODELETEPROJECT","您確定您要刪除的這個項目呢?");//Are you sure that you want to delete this project?
define("_TIMESDONE","時代做");//Times done
define("_HASLEFT","左邊");//Left
define("_EMPLOYEESINGROUP","員工組");//Employees of group
define("_ERRORRESTORINGFILE","問題來了，在恢復");//A problem came up during restore
define("_DATABASEONLY","數據庫只");//Database only
define("_ALLDATABACKUP","所有的數據備份");//All data backup
define("_LESSONDIRECTORYCANNOTBCREATED","教訓目錄無法創建");//The lesson directory could not be created
define("_YOUHAVENOTCOMPLETEDTHEFOLLOWINGQUESTIONS","您尚未完成的問題");//You have not completed questions
define("_AREYOUSUREYOUWANTTOSUBMITTEST","您確定要提交測試?");//Are you sure you want to submit the test?
define("_JOBANALYTICALDESCRIPTION","詳細說明");//Detailed description
define("_INCLUDESUBBRANCHES","包括subbranches");//Include subbranches
define("_PDFFORMAT","PDF格式");//PDF format
define("_XLSFORMAT","Excel格式");//EXCEL format
define("_ATTENDING","出席");//Attending
define("_USERAVERAGESCOREFORTESTS","平均分數為教訓的測試");//Average score for lesson&#039;s tests
define("_PROJECTSCOMPRESSED","下載項目文件");//Download project files
define("_EDUCATIONALROLE","教育的作用");//Educational role
define("_ORGANIZATIONALROLE","組織的作用");//Organizational role
define("_TYPEOFUSER","用戶類型");//User type
define("_MESSAGEBODY","郵件正文");//Message body
define("_ONLYRECIPIENTSDEFINEDBELOW","受助人的界定，只有在下面的字段");//Only recipients defined in the field below
define("_NORECIPIENTSHAVEBEENSELECTED","沒有受助者已選定");//No recipients have been selected
define("_NORECIPIENTSHAVEBEENFOUND","沒有受助人已找到");//No recipients have been found
define("_CHANGELESSON","改變的教訓");//Change lesson
define("_HOME","家");//Home
define("_FFROM","自");//from
define("_CALENDARTYPE","日曆類型");//Calendar type
define("_ORGANIZATIONPROFILE","組織簡介");//Organization profile
define("_CURRENTLESSON","目前的教訓");//Current lesson
define("_SUBMITANDADDANOTHER","提交和添加另一個");//Submit and add another
define("_EDUCATIONAL","教育");//Educational
define("_PAYPALTITLE","貝寶");//Paypal
define("_PAYPALCONFIGURATIONPANEL","貝寶配置小組");//Paypal configuration panel
define("_PAYPALMYTRANSACTIONS","我的交易");//My transactions
define("_PAYPALTRANSACTION","交易");//Transaction
define("_PAYPALCONFIGURATION","配置");//Configuration
define("_PAYPALBUSINESSMAIL","貝寶公司地址");//Paypal business address
define("_PAYPALBUSINESSMAILPLZ","填補在貝寶公司地址");//Fill in the Paypal business address
define("_PAYPALMAILSTUDENTS","通知學生");//Inform students
define("_PAYPALMAILPROFESSORS","可否告知教授");//Inform professors
define("_PAYPALMAILADMINS","通知管理員");//Inform admins
define("_PAYPALORDERPREVIEW","預覽秩序");//Preview order
define("_PAYPALFINALPRICE","最終價格");//Final price
define("_PAYPALPAYNOW","現在的薪酬與貝寶");//Pay now with Paypal
define("_PAYPALNOCONFIGURATION","您不能使用這項服務，因為它的不正確配置。");//You can not use this service because its not configured properly.
define("_PAYPALORDERPROCESSING","您的訂單正在處理通過貝寶。");//Your order is being processing through Paypal.
define("_PAYPALORDERPROCESSINGERROR","有一個錯誤，與您的訂單。");//There was an error with your order.
define("_PAYPALORDERSSUCCESS","完成");//Finished
define("_PAYPALORDERSNOSUCCESS","未完成");//Not-Finished
define("_PAYPALTABLEPRICE","數量");//Amount
define("_PAYPALITEMCODE","代碼");//Code
define("_PAYPALTABLEDATESUBMIT","訂單日期");//Order date
define("_PAYPALTABLEDATEPAYPAL","付款日期");//Payment date
define("_PAYPALTRANSACTIONCODE","交易代碼");//Transaction code
define("_PAYPALTABLEUSER","用戶");//User
define("_PAYPALTABLESTATUS","付款狀態");//Payment status
define("_PAYPALTABLELESSONS","教訓");//Lessons
define("_PAYPALORDERINFO","交易詳情");//Transaction details
define("_PAYPALCUSTOMERINFO","客戶的信息");//Customer&#039;s information
define("_PAYPALITEMSINFO","項目信息");//Items information
define("_PAYPALPURCHASEORDER","採購訂單");//Purchase order
define("_PAYPALPURCHASEORDERFOR","付款");//Payment to
define("_ADDTOCART","放入購物車");//Add to cart
define("_REMOVEFROMCART","刪除購物車");//Remove from cart
define("_REMOVEALLFROMCART","刪除所有從購物車");//Remove all from cart
define("_CART","購物車");//Shopping cart
define("_NOCART","購物車是空的");//The cart is empty
define("_FREEOFCHARGE","自由的");//Free
define("_LOGINFIRST","日誌在首先進行購買");//Log in first to proceed purchase
define("_RESULTS","結果");//results
define("_RESULT","結果");//result
define("_PAYPALORDERSUCCESS","交易順利完成");//The transaction completed successfully
define("_PAYPALORDERFAILURE","有一個錯誤與交易");//There was an error with the transaction
define("_PAYPALFREEORDERSUCCESS","教訓登記順利完成");//Lessons registration finished successfully
define("_FREEREGISTRATION","免費註冊");//Free registration
define("_VIEWDIRECTORY","顯示教訓/課程目錄");//Show lesson/courses catalog
define("_VIEWDIRECTORYYESAFTERLOGIN","是（只有登錄後）");//Yes (only after login)
define("_VIEWDIRECTORYYESONLOGIN","是（對登入網頁和登錄後）");//Yes (on login page and after login)
define("_VIEWDIRECTORYNO","否");//No
define("_VIEWDIRECTORYDISABLED","該calatog是無效的這一刻");//The calatog is inactive this moment
define("_INTERFACEVIEW","選擇界面索引頁");//Select the interface of index page
define("_INTERFACEVIEWSIMPLE","簡單");//Simple
define("_INTERFACEVIEWEXTENDED","延長");//Extended
define("_PAYPALUSE","使用貝寶");//Payments through Paypal
define("_DIRECTORY","目錄");//Directory
define("_LESSONSDIRECTORY","當然目錄");//Course catalog
define("_ASSOCIATEDLESSONS","相關的經驗教訓");//Associated lessons
define("_APPLYTOALLDESCRIPTIONSWITHDESCRIPTION","適用於所有職位描述：");//Apply to all jobs with description: 
define("_AREYOUSUREYOUWANTTOREMOVETHATSKILLFROMTHISEMPLOYEE","您確定要刪除的技能，從該僱員?");//Are you sure you want to remove that skill from that employee?
define("_JOBDESCRIPTIONEXISTSALREADY","職位描述已經存在的");//Job description exists already
define("_EVENTFIELDISMANDATORY","活動領域是強制性的");//Event field is mandatory
define("_SKILLCATEGORY","技能類");//Skill category
define("_ADDSKILLCATEGORY","新增技能類");//Add skill category
define("_EDITSKILLCATEGORY","編輯技能類");//Edit skill category
define("_DELETESKILLCATEGORY","刪除技能類");//Delete skill category
define("_AREYOUSUREYOUWANTTODISMISSTHISSKILLCATEGORY","是您確定要關閉這個技能類?");//Are you sure you want to dismiss this skill category?
define("_UPDATESKILLSCATEGORY","更新技能類");//Update skill category
define("_SKILLCATEGORYDATAUPDATED","技能類的數據更新");//Skill category data updated
define("_SUCCESSFULLYCREATEDSKILLCATEGORY","技能類成功創建");//Skill category successfully created
define("_SKILLCATEGORYDELETED","技能類刪除");//Skill category deleted
define("_USERDOESNOTEXIST","該用戶不存在");//The user does not exist
define("_INVALIDSURNAME","用戶去年指定的名稱是無效的");//The user last name specified is not valid
define("_INVALIDEMAIL","用戶指定的電子郵件是無效的");//The user email specified is not valid
define("_USERALREADYEXISTS","用戶指定的登錄已經存在");//A user with the specified login already exists
define("_EMAILALREADYEXISTS","用戶指定的電子郵件已經存在");//A user with the specified email already exists
define("_COULDNOTINSERTUSER","指定的用戶無法插入到數據庫");//The user specified could not be inserted to database
define("_INVALIDUSERTYPE","指定的用戶類型是無效的");//The specified user type is not valid
define("_REMEMBERME","記得我");//Remember me
define("_INVALIDPASSWORD","密碼無效");//Invalid password
define("_INVALIDPASSWORDFORUSER","無效的使用者的密碼");//Invalid password for user
define("_PROBLEMACTIVATINGACCOUNT","有問題，在激活帳戶");//There was a problem during account activation
define("_THEUSERCOULDNOTBEDELETED","使用無法刪除");//The use could not be deleted
define("_THEUSERCOULDNOTBEDEACTIVATED","用戶不能停用");//The user could not be deactivated
define("_THEUSERCOULDNOTBEACTIVATED","用戶不能啟動");//The user could not be activated
define("_USERDIRECTORYCOULDNOTBEDELETED","用戶目錄無法刪除");//The user directory could not be deleted
define("_INVALIDLESSONID","無效的教訓，編號");//Invalid lesson id
define("_UNITDOESNOTEXIST","該單位不存在");//The unit does not exist
define("_DOWNLOADEXPORTED","下載出口的教訓");//Download exported lesson
define("_SUCCESFULLYRESTOREDSYSTEM","恢復程序順利完成");//The restoring procedure completed successfully
define("_LESSONDOESNOTEXIST","教訓指定不存在");//The lesson specified does not exist
define("_UNDOCHANGES","撤消變化");//Undo changes
define("_CONTENTTREEMANAGEMENT","內容樹的管理");//Content tree management
define("_ORDERWILLPERMANENTLYCHANGE","此操作將永久改變單位訂購和無法復原。您是否確定?");//This operation will permanently change unit ordering and cannot be undone. Are you sure?
define("_ERRORLOADINGCONTENT","錯誤載入內容的教訓");//Error loading content for lesson
define("_USERROLE","用戶角色");//User role
define("_CANNOTUPDATEUSERLESSONINFORMATION","的教訓，這方面的資料用戶無法更新");//The lesson information on this user could not be updated
define("_PROBLEMUPDATINGUSERSTOLESSON","有問題，更新用戶信息的教訓");//There was a problem updating the user lesson information
define("_INVALIDPROJECTID","無效的項目編號");//Invalid project Id
define("_PROJECTNOTFOUND","指定的項目沒有被發現");//The specified project was not found
define("_USERDOESNOTHAVETHISLESSON","用戶沒有登記這個教訓");//The user is not registered to this lesson
define("_COURSEDOESNOTEXIST","指定的當然是不存在的");//The specified course does not exist
define("_NODEDOESNOTEXIST","指定的節點不存在");//The specified node does not exist
define("_PROJECTCOULDNOTBEDELETED","該項目無法刪除");//The project could not be deleted
define("_FREELESSON","免費的教訓");//Free lesson
define("_BUYCOURSE","當然購買");//Buy course
define("_FREECOURSE","免費課程");//Free course
define("_USERDOESNOTHAVETHISPROJECT","用戶不會有這個項目");//The user does not have this project
define("_SCOREMUSTBEINTEGERBETWEEN0100","該項目評分必須是整數的範圍從0到100");//The project score must be an integer ranging from 0 to 100
define("_THEPROJECTGRADECOULDNOTBEUPDATED","該項目等級無法更新");//The project grade could not be updated
define("_INVALIDDATA","無效數據");//Invalid data
define("_UPLOADEDON","上載");//Uploaded on
define("_PROJECTDELETEDSUCCESSFULLY","該項目已成功刪除");//The project was deleted succesfully
define("_FILESCOULDNOTBEDOWNLOADED","該項目的檔案無法下載");//The project files could not be downloaded
define("_RESULTSFORPROJECT","結果項目");//Results for project
define("_VIEWPROJECT","鑑於項目");//View project
define("_REMAINING","其餘");//Remaining
define("_PROJECTEXPIRED","該項目的最後期限已經過期");//The project deadline has expired
define("_SENDPROJECT","發送項目");//Send project
define("_NEWLESSONS","新的教訓");//New lessons
define("_YOUMUSTDELETEALLLESSONSANDSUBDIRECTIONSINTHISDIRECTIONBEFOREDEACTIVATINGIT","你不能停用非空語類");//You cannot deactivate a non-empty category
define("_CANNOTUPDATEUSERCOURSEINFORMATION","課程信息關於這個用戶無法更新");//The course information on this user could not be updated
define("_CANNOTADDUSERTOCOURSE","用戶可不會被添加到課程");//The user could not be added to course
define("_CANNOTREMOVEUSERFROMCOURSE","用戶可以不被免職過程");//The user could not be removed from the course
define("_USERHASNOTDONETEST","該用戶已沒有這樣做的測試");//The user has not done this test
define("_TESTISNOTDONE","測試是沒有這樣做");//The test is not done
define("_INVALIDQUESTIONTYPE","無效的問題類型");//Invalid question type
define("_YOUCANNOTDEACTIVATEANONEMPTYDIRECTION","你不能停用非空語類");//You cannot deactivate a non-empty category
define("_YOUCANNOTDELETEANONEMPTYDIRECTION","您不能刪除一個非空語類");//You cannot delete a non-empty category
define("_MAXFILEISAFFECTEDANDIS","最高上傳文件的大小也受PHP中的INI設置。目前真正的最大文件大小是");//The maximum upload file size is also affected by PHP ini settings. Current true max file size is
define("_CAREFULNOTLOCKOUT","當設定的IP接入名單，小心，不要禁止自己出去！");//When setting ip access lists, be careful not to ban yourself out!
define("_ADMINISTRATORWILLACTIVATEYOURACCOUNT","註冊完成。您的帳戶將被激活由系統管理員");//Registration is complete. Your account will be activated by the system administrator
define("_USERPENDING","該帳戶尚未啟用，但由管理員");//The account has not been activated yet by the administrator
define("_DOWNLOADDEFAULTSTYLE","下載的預設樣式");//Download default style
define("_SETDEFAULTSTYLE","設置默認的作風，積極");//Set default style as active
define("_SUCCESFULLYUPDATEDLOGO","徽標文件已更新成功");//Logo file was updated successfully
define("_USEDEFAULTLOGO","使用預設的標誌");//Use default logo
define("_GROUPOPTIONS","組選項");//Group options
define("_GROUPUSERS","集團用戶");//Group users
define("_USETHIS","使用此");//Use this
define("_PAGESETSUCCESSFULLY","網頁設置成功");//Page set succesfully
define("_TEXTBOX","文本框");//Text box
define("_SELECTBOX","專責名單");//Select list
define("_EDITFIELD","編輯欄位");//Edit field
define("_COULDNOTADDFIELD","外地無法加入");//The field could not be added
define("_COULDNOTUPDATEFIELD","外地無法更新");//The field could not be updated
define("_FIELDALREADYEXISTS","實地已經存在具有此名稱");//A field with this name already exists
define("_INTEGER","整數");//Integer
define("_DEFAULTVALUE","默認值");//Default value
define("_VALUES","價值觀");//Values
define("_ADDVALUES","添加值");//Add values
define("_DELETEBOOKMARK","刪除書籤");//Delete bookmark
define("_SUCCESSFULLYINSERTEDBOOKMARK","該網頁的書籤");//The page was bookmarked
define("_ERRORINSERTINGBOOKMARK","網頁不能書籤");//The page could not be bookmarked
define("_LOADING","載入中...");//Loading...
define("_UNITS","單位");//Units
define("_USERCOULDNOTBECREATED","用戶無法創建");//The user could not be created
define("_PROCEEDTOTEST","進行測試");//Proceed to test
define("_OPERATIONWILLAFFECTMANYAREYOUSURE","這項行動將影響不可逆轉了大量的實體。進行?");//This operation will affect irreversibly a large number of entities. Proceed?
define("_CLICKTOTOGGLE","按一下以切換");//Click to toggle
define("_COMPRESSDOWNLOAD","壓縮和下載");//Compress and download
define("_SELECTEDENTRYTO","選定項目");//the selected entry to
define("_YOUWANTTO","您想要");//You want to
define("_UPLOADTODIGITALLIBRARY","上傳到數字圖書館");//Upload to digital library
define("_SHARE","共享");//Share
define("_OPERATIONSUCCESFULLYAPPLIEDON","運作成功的應用");//Operation successfully applied on
define("_BYUSER","由用戶");//by user
define("_VIEWSOLVEDTEST","鑑於解決測試");//View solved test
define("_VIEWQUESTION","鑑於問題");//View question
define("_COULDNOTCREATETESTSDIRECTORY","測試文件夾無法創建");//The tests folder could not be created
define("_SAVEASNEWTEST","另存為新的考驗");//Save as new test
define("_SELECTLESSONTOCOPYFROM","選擇一個教訓，複製，從");//Select a lesson to copy from
define("_VIEWCOMMENT","查看評論");//View comment
define("_SHOWEVALUATIONS","查看評價");//Show evaluations
define("_RECIPIENTS","受助人");//Recipients
define("_SHOWRECIPIENTSCATEGORIES","顯示收件人的預定義分類");//Show recipient&#039;s predefined categories
define("_HIDERECIPIENTSCATEGORIES","隱藏收件人的預定義分類");//Hide recipient&#039;s predefined categories
define("_TOYOURSUPERVISORS","您所有的上司");//All your supervisors
define("_BASICINFO","基本資料");//Basic info
define("_TRAININGCAP","訓練");//T R A I N I N G
define("_COURSESAVERAGE","平均分數在所有課程");//Average score in all courses
define("_LESSONSAVERAGE","平均分數在所有的經驗教訓");//Average score in all lessons
define("_TESTSAVERAGE","平均分數在所有測試");//Average score in all tests
define("_DONTTAKEINTOACCOUNT","不考慮");//Do not take into account
define("_CANNOTADDUSERTOLESSON","不能添加用戶，以教訓");//Cannot add user to lesson
define("_UNKNOWNUSER","未知用戶");//Unknown user
define("_DEPENDSON","要視乎");//Depends on
define("_COURSEINFORMATION","當然信息");//Course information
define("_NODATAFOUND","沒有找到數據");//No data found
define("_ERROROPENINGATTACHMENT","錯誤開放實習");//Error opening attachment
define("_USERAVERAGESCOREFORLESSON","平均分數為教訓的測試");//User&#039;s average score for lesson
define("_LESSONSINFO","教訓信息");//Lessons info
define("_USERSINGROUP","小組中的用戶");//Users in group
define("_PROFESSORSOFLESSON","教授的教訓");//Professors of lesson
define("_TOBRANCHSUPERVISORS","只有您的分行監事");//Only your branch supervisors
define("_OTHERBRANCHJOBS","職務說明，從其他科");//Job descriptions from other branches
define("_SENDMESSAGETOALLFOUNDEMPLOYEES","發送信息給所有僱員發現");//Send messages to all employees found
define("_SEARCHCOURSEUSERS","搜索為僱員[課程標準]");//Search for employee [Course criteria]
define("_COMPLETIONDATE","竣工日期");//Completion date
define("_YEAR","年");//Year
define("_NOTASSIGNED","未分配，但");//Not assigned yet 
define("_NEWSEARCHCRITERIUM","添加搜索的詳情");//Add search criterium
define("_NOSEARCHCRITERIADEFINED","沒有搜索標準界定");//No search criteria defined
define("_ERRORSAVINGTREE","錯誤節省樹");//Error saving tree
define("_MAXEXECUTIONTIME","最高執行時間");//Maximum execution time
define("_MEMORYLIMIT","內存限制");//Memory limit
define("_PHPSETTINGS","PHP的設置");//PHP settings
define("_MEGABYTES","兆字節");//megabytes
define("_LEAVEBLANKTOUSEPHPINI","離開領域的空白，以便利用php.ini的默認設置");//Leave fields blank in order to use php.ini default settings
define("_DISPLAYERRORS","顯示錯誤");//Display errors
define("_UPLOADLESSONFILE","上傳檔案的教訓");//Upload lesson file
define("_DCTITLE","標題");//Title
define("_DCCREATOR","創作者");//Creator
define("_DCSUBJECT","題目");//Subject
define("_DCDESCRIPTION","描述");//Description
define("_DCPUBLISHER","出版商");//Publisher
define("_DCCONTRIBUTOR","投稿");//Contributor
define("_DCDATE","日期");//Date
define("_DCTYPE","類型");//Type
define("_DCFORMAT","格式");//Format
define("_DCIDENTIFIER","標識符");//Identifier
define("_DCSOURCE","來源");//Source
define("_DCLANGUAGE","語言");//Language
define("_DCRELATION","關係");//Relation
define("_DCCOVERAGE","涵蓋範圍");//Coverage
define("_DCRIGHTS","權利");//Rights
define("_NOENTRYFOUNDFOR","沒有進入發現");//No entry found for
define("_FIELD","領域");//field
define("_COURSECERTIFICATES","當然證書");//Course certificates
define("_LDAPUSERMUSTCONTACTADMIN","您的帳戶是通過訪問LDAP服務器。請聯繫系統管理員在");//Your account is accessed through the LDAP server. Please contact the system administrator at 
define("_COURSEMETADATA","當然中繼");//Course metadata
define("_COURSESTATUS","當然地位");//Course status
define("_LESSONSCOMPLETED","完成的教訓");//Completed lessons
define("_COURSESCORE","當然評分");//Course score
define("_LESSONSCOMPLETED","完成的教訓");//Lessons completed and awaiting approval
define("_VIEWUSERCOURSEPROGRESS","查看用戶的進展的整個過程中");//View the user progress throughout the course
define("_COURSERULES","當然規則");//Course rules
define("_INFORMATIONFORCOURSE","信息的過程中");//Information for course
define("_CERTIFICATESFORCOURSE","證書課程");//Certificates for course
define("_FORMATCERTIFICATEFORCOURSE","格式證書課程");//Format certificate for course
define("_RULESFORCOURSE","規則當然");//Rules for course
define("_CONTENTDONE","內容做");//Content done
define("_LESSONSPROGRESS","教訓進展");//Lessons progress
define("_COMPLETECOURSE","完成課程");//Complete course
define("_PROPOSEDSCOREISAVERAGELESSONSCORE","擬議的評分是平均的教訓評分");//The proposed score is the average lessons score
define("_INTHESELECTEDLANGUAGE","鍵入描述在首選語言");//Type the description in the prefered language
define("_SUCCESSFULLYDELETEDFIELD","成功刪除領域");//Successfully deleted field
define("_COMPLETELESSON","完整的教訓");//Complete lesson
define("_AUTOCOMPLETEDCOURSE","過程是自動完成時，所有的經驗教訓已完成");//The course was automatically completed when all lessons were completed
define("_INFORMATIONFORLESSON","信息的教訓");//Information for lesson
define("_LESSONMETADATA","教訓中繼");//Lesson metadata
define("_DISPLAYINGRESULTS","結果顯示");//Displaying results
define("_LOADINGDATA","加載數據");//Loading data
define("_COURSESTATISTICS","當然報告");//Course reports
define("_CHOOSECOURSE","當然，選擇");//Choose course
define("_HISTORYRECORDDELETED","歷史記錄刪除");//History record deleted
define("_AREYOUSUREYOUWANTTODELETETHEHISOTYRECORD","您確定要刪除的歷史記錄?");//Are you sure you want to delete the history record?
define("_HIDEALL","全部隱藏");//Hide all
define("_COURSEORDER","當然，為了");//Course order
define("_ORDERFORCOURSE","為了讓課程");//Order for course
define("_DRAGITEMSTOCHANGELESSONSORDER","拖移項目，以改變顯示順序的過程中的經驗教訓");//Drag items to change the display order of the course lessons
define("_IRREVERSIBLEACTIONDELETESUBUNITSAREYOUSURE","這一行動將irreversably刪除此單位和任何亞基，它可能有。您是否確定?");//This action will irreversably delete this unit and any subunits it may have. Are you sure?
define("_CLICKOKTOACTIVATEITEM","單擊確定以啟動/關閉項目");//Click OK to activate/deactivate item
define("_ANDITSSUBNODES","和它的子節點");//and it&#039;s sub nodes
define("_ERRORDELETINGUNIT","錯誤刪去股");//Error deleting unit
define("_ERRORACTIVATINGUNIT","錯誤激活股");//Error activating unit
define("_ERRORDEACTIVATINGUNIT","錯誤失能單位");//Error deactivating unit
define("_ERRORDEPOSITIONINGUNIT","錯誤定位單元");//Error positioning unit
define("_ERRORREPAIRINGTREE","錯誤修復樹");//Error repairing tree
define("_DRAGAUNITTOCHANGEITSPOSITION","拖動一個單位，改變其立場");//Drag a unit to change its position
define("_IFUSESSLTHENPHPOPENSSL","如果你想使用SSL ，請確保PHP的OpenSSL的支持啟用");//If you want to use ssl, make sure that PHP openssl support is enabled
define("_COURSECOMPLETED","當然完成");//Course completed
define("_COURSECERTIFICATE","當然證書");//Course certificate
define("_COURSESINFO","課程信息");//Courses info
define("_DRAGTOMOVEMAILTOFOLDER","拖動以移動此電子郵件到另一個文件夾");//Drag to move this email to another folder
define("_SCORMOPTIONS","SCORM的選項");//Scorm options
define("_SCORMOPTIONSFOR","SCORM的選擇");//Scorm options for
define("_SCORMREVIEW","檢討SCORM的數據");//Review SCORM data
define("_REVIEWSCORMDATAFOR","檢討SCORM的數據");//Review SCORM data for
define("_SCORMFILEINZIPFORMAT","SCORM的zip檔案");//SCORM zip file
define("_TREEROOT","林木根");//Tree root
define("_INVALIDPAGE","無效頁");//Invalid page
define("_VALUEISSMALLERTHATPHPINI","該值是小於1所訂的php.ini");//The value is smaller than the one set by php.ini
define("_PERMISSIONS","權限");//Permissions
define("_UNSHARE","取消共享");//Cancel sharing
define("_UNSHARESELECTED","取消共享選定的文件");//Cancel sharing of selected files
define("_SHARESELECTED","分享選定的文件");//Share selected files
define("_YOUDONTHAVEPERMISSION","您不“噸的權限，執行選定的行動");//You don&quot;t have permission to perform the selected action
define("_EXPORT","出口");//Export
define("_NOMODULECLASSFOUND","沒有模塊級的發現與名稱");//No module class found with name
define("_ERRORLOADINGMODULE","錯誤加載模塊");//Error loading module
define("_VERSIONKEYTITLE","版本的關鍵");//Version Key
define("_VERSIONKEY","版本的關鍵");//Version key
define("_VERSIONALLOEDUSERS","允許用戶");//Allowed Users
define("_VERSIONTYPE","版本類型");//Version Type
define("_VERSIONSERIAL","序號");//Serial Number
define("_USERSEXCEEDED","您的版本類型不容許創造新的用戶");//Your version type does not allow the creation of new users
define("_BASICCRITERIA","基本準則");//Basic criteria
define("_BASICSEARCHOPTIONS","基本搜索選項");//Basic search options
define("_DELETEDATA","刪除數據");//Delete data
define("_ERRORDETAILS","錯誤的詳細資料");//Error Details
define("_PARTOFTHISGROUP","用戶的一部分，這個小組");//The user is part of this group
define("_SUCCESSFULLYIMPORTEDSCORMFILE","SCORM的文件被成功導入");//SCORM file was successfully imported
define("_CONVERTTOSCORMCONTENT","轉換到SCORM的內容單位");//Convert to SCORM content unit
define("_CONVERTTOSCORMTEST","轉換到SCORM的測試單元");//Convert to SCORM test unit
define("_SCORMTREE","SCORM的樹");//SCORM tree
define("_MASTERYSCORE","掌握評分");//Mastery score
define("_GZHANDLER","廣州處理");//GZ handler
define("_PROJECTPENDING","這個項目正在等待");//This project is pending
define("_USERHASNOTDONETEST","該用戶已沒有這樣做的測試");//The user has not done this test
define("_USERHASNOTTHISLESSON","用戶沒有登記這個教訓");//The user is not registered for this lesson
define("_SHIFTSCHEDULEFORNEWUSERS","附表轉移為新用戶");//Shift schedule for new users
define("_CURRENTSCHEDULE","目前附表");//Current schedule
define("_NOSCHEDULESET","沒有時間表");//No schedule set
define("_DELETESCHEDULE","刪除附表");//Delete schedule
define("_SCHEDULINGFORCOURSE","調度過程");//Scheduling for course
define("_ADDSCHEDULE","新增附表");//Add schedule
define("_COURSESCHEDULE","當然附表");//Course schedule
define("_AVAILABLEUNTIL","可直到");//Available until
define("_FILETYPE","文件類型");//File type
define("_FULLPATH","完整路徑");//Full path
define("_MIMETYPE","MIME類型");//MIME type
define("_CANNOTSHAREFILE","不能共享文件");//Cannot share file
define("_SHAREDFILES","共享文件");//Shared files
define("_CLICKTOEXPORT","按一下按鈕出口的教訓");//Click the button to export lesson
define("_EXISTINGFILE","下列文件已經存在");//The following file already exists
define("_PROBLEMADDINGUSERSTOLESSON","用戶可不會被添加到教訓");//The user could not be added to the lesson
define("_TRANSLATEFILESYSTEM","編碼非拉丁字母的檔案名稱，以");//Encode non-latin file names to
define("_CANNOTMOVEFILE","該文件無法移動");//Cannot move file
define("_INCOMPATIBLEVERSIONS","不兼容的版本");//Incompatible versions
define("_BACKUPVERSION","備份版本");//Backup version
define("_CURRENTVERSION","目前版本");//Current Version
define("_MAXIMUMUPLOADSIZE","檔案大小上限");//Maximum file size
define("_BACKUPFAILED","備份失敗");//Backup failed
define("_PERSONALFILES","個人檔案");//Personal files
define("_MAXIMUMUSERSNUMBERREACHED","最高的用戶數量達到");//The maximum number of users is reached
define("_UPLOADING","上傳");//Uploading
define("_SELECTEDFILESTO","選定的文件，以");//selected files to
define("_CATEGORYDOESNOTEXIST","一類是不存在的");//The category does not exist
define("_CATEGORIES","類別");//Categories
define("_NEWCATEGORY","新的類別");//New category
define("_EDITCATEGORY","編輯類別");//Edit category
define("_CATEGORYSETTINGS","類別設置");//Category settings
define("_YOUWANTTOBEDONE","您想要");//You want to
define("_OVERWRITE","覆蓋");//Overwrite
define("_USERSPROGRESS","僱員的地位");//Users progress
define("_LESSONUSERS","教訓用戶");//Lesson users
define("_ASSOCIATEDCOURSES","相關課程");//Associated courses
define("_OUTPUT","輸出");//Output
define("_TOKEN","令牌");//Token
define("_PERMITTEDROLESMODULEERROR","一個或多個模塊允許的角色是錯誤的");//One or more module permitted roles are wrong
define("_SMARTYTEMPLATEDOESNOTEXIST","該smarty模板文件不存在");//The smarty template file does not exist
define("_FOLDERWITHMODULENAMEEXISTSIN","文件夾中與模塊名稱已存在在");//Folder with module name already exists in 
define("_SITENAME","網站名稱");//Site name
define("_SITEMOTO","網站摩托");//Site moto
define("_UNKNOWNSEPARATOR","未知分離");//Unknown separator
define("_LDAPUSER","此用戶驗證通過LDAP服務器");//This user authenticates through the LDAP server
define("_EXECUTE","執行");//Execute
define("_RECREATE","再現");//Recreate
define("_CLICKHERETOREINDEX","點擊這裡重新搜索表");//Click here to recreate the search table
define("_TRANSLATION","翻譯");//Translation
define("_ENGLISHNAME","名稱在英語");//Name in english
define("_SUCCESSFULLYADDEDLANGUAGE","語言已成功創建");//The language was successfully created
define("_SUCCESSFULLYUPDATEDLANGUAGE","語言已成功更新");//The language was successfully updated
define("_LANGUAGES","語文");//Languages
define("_SERIALRULE","用戶必須看到的內容在一個串行秩序");//Users must see content in a serial order
define("_TREERULE","用戶必須完成的一個分支的“ S節點，然後再轉到下一個");//Users must complete a branch&quot;s nodes before moving to the next one
define("_ADDCUSTOMRULE","新增自訂規則");//Add custom rule
define("_ADDREADYRULE","添加準備規則");//Add ready rule
define("_THEFOLLOWINGUSERSCOULDNOTBEIMPORTED","以下用戶無法導入");//The following users could not be imported
define("_STARTHERE","從這裡開始");//Start here
define("_COPYSELECTED","複製選定");//Copy selected
define("_USERACCESSESINLESSON","用戶訪問在教訓");//User access in lesson
define("_NUMBEROFFIELDSMUSTBE","有多少領域必須");//The number of fields must be
define("_BUTFOUND","但被發現");//but there was found
define("_APPLYAVATARCHANGES","適用於阿梵達的變化");//Apply avatar changes
define("_TERMFIELDISMANDATORY","任期領域是強制性的");//Term field is mandatory
define("_DEFINITIONFIELDISMANDATORY","定義領域是強制性的");//Definition field is mandatory
define("_TOPLEFTCORNER","左上角");//Top left corner
define("_TOPRIGHTCORNER","右上角");//Top right corner
define("_BOTTOMLEFTCORNER","左下角");//Bottom left corner
define("_BOTTOMRIGHTCORNER","右下角");//Bottom right corner
define("_LOGOPOSITION","徽標的立場");//Logo position
define("_LOGOFILE","Logo文件");//Logo file
define("_LESSONSKILLSSELECTION","的教訓，所提供的技能選擇");//Lesson offered skills selection
define("_TOPCENTER","頂端中心");//Top center
define("_BOTTOMCENTER","底部的中心");//Bottom center
define("_HIDECOMPLETEUNITICON","隱藏完成股圖標");//Hide complete unit icon
define("_HIDENAVIGATION","隱藏導航處理");//Hide navigation handles
define("_AUTOCOMPLETEDAT","自動完成");//Auto completed at
define("_SECOND","第二");//second
define("_NOACCESSDATA","沒有訪問數據");//No access data
define("_USERAVATAR","用戶化身");//User avatar
define("_MOSTACTIVELESSONS","最活躍的教訓");//Most active lessons
define("_LESSONSACTIVITY","教訓活動");//Lessons activity
define("_USERSACTIVITY","用戶活動");//Users activity
define("_USERHASNOTTHELESSON","用戶不會有這個教訓");//The user doesn&#039;t have this lesson
define("_USERHASTHELESSON","該用戶已這個教訓");//The user has this lesson
define("_TESTSINFORMATION","測試信息");//Tests information
define("_QUESTIONSINFORMATION","問題信息");//Questions information
define("_PROJECTSINFORMATION","項目信息");//Projects Information
define("_MCEXPLANATION","*管委會=多種選擇-單一的答案");//* MC = Multiple choices - Single Answers
define("_MCMAEXPLANATION","* mcma =多種選擇-多個答案");//* MCMA = Multiple choices - Multiple Answers
define("_MAEXPLANATION","*馬=匹配");//* MA = Matching
define("_FBEXPLANATION","*庫務局=填補空白");//* FB = Fill the blank
define("_OAEXPLANATION","*辦公自動化=開放的答案");//* OA = Open answer
define("_YNEXPLANATION","*被=是/否");//* YN = Yes/No
define("_PROJECTNAME","項目名稱");//Project name
define("_STATISTICSFORCOURSE","統計過程中");//Statistics for course
define("_YOUARENOTAUTHORISEDTOSEETHISTEST","未授權您看到這個測試");//You are not authorized to see this test
define("_YOUCANNOTREDOTHISTEST","你不能重做此測試");//You cannot redo this test
define("_ACCESSEDLESSON","訪問教訓");//Accessed lesson
define("_ACCESSEDCONTENT","訪問內容單位");//Accessed content unit
define("_ACCESSEDTEST","進入測試");//Accessed test
define("_BEGUNTEST","開始測試");//Begun test
define("_NAVIGATEDSYSTEM","通過導航系統");//Navigated through the system
define("_PROJECTDESCRIPTION","項目說明");//Project description
define("_CONTENTTRAVERSINGRULES","內容遍歷規則");//Content traversing rules
define("_FILEUPLOADEDON","該文件上載");//The file was uploaded on
define("_DIRECTIONOPTIONSFOR","選擇類別");//Options for category
define("_NEWDIRECTIONOPTIONS","新的類別選項");//New category options
define("_COURSELESSONS","當然，教訓");//Course lessons
define("_RELATEDTO","有關");//Related to
define("_SUCCESSFULLYEXPORTEDSCORMFILE","教訓是出口到SCORM的格式成功");//The lesson was exported to SCORM format succesfully
define("_LDAPEXTENSIONNOTLOADED","警告： LDAP的擴展不加載");//Warning: LDAP Extension  not loaded
define("_PERCENTAGEMUSTBEBETWEEN1100","百分比必須介於1和100");//Percentage must be between 1 and 100
define("_MUSTSEECONTENTSERIALSOMUSTFIRSTREADUNIT","你必須看到的內容在一個串行秩序，所以您必須先閱讀單位");//You must see content in a serial order, so you must first read unit
define("_YOUDONTHAVEANYLESSONS","您沒有任何的教訓或課程");//You don&#039;t have any lessons or courses
define("_THEADMINISTRATORWILLASSIGNYOULESSONS","系統管理員會發放給您的教訓，或課程");//The system administrator will assign you lessons or courses
define("_BACKTOINDEX","回到索引頁");//Back to index page
define("_LESSONAVAILABLE","教訓是可用");//Lesson is available
define("_DIRECTLY","直接");//Directly
define("_ADDFILE","新增檔案");//Add file
define("_DOWNLOADSCORMEXPORTEDFILE","下載出口SCORM的檔案");//Download exported SCORM file
define("_EMPTYUNIT","空單位");//Empty unit
define("_YOUMUSTPROVIDELOGINLINK","您必須提供登錄的鏈接，否則，你將不能夠直接連接。登錄表單是可以通過鏈接： ". G_SERVERNAME ."index.php?index_eFront");//You must provide a login link, otherwise you will not be able to connect directly. Login form is available through the link: ".G_SERVERNAME."index.php?index_efront
define("_NOFILEUPLOADED","沒有文件被上傳");//No file was uploaded
define("_FONTSIZE","字體大小");//Font size
define("_FONTSTYLE","字體樣式");//Font style
define("_PROBLEMINSERTINGPARSEDXMLVALUESORMODULEEXISTS","問題插入解析XML的值到數據庫。請檢查您的說明文件，或是否該模塊已經安裝");//Problem inserting the parsed XML values to the database. Please check your description file or whether the module is already installed
define("_NOMODULEPERMITTEDROLESDEFINED","沒有模塊允許的角色定義。檢查功能getpermittedroles （ ）");//No module permitted roles defined. Check function getPermittedRoles()
define("_MODULECLASSNOTEXISTSIN","模塊級中沒有界定");//module class is not defined in
define("_MODULEDBERRORONINSTALL","數據庫錯誤的執行過程中的功能oninstall為模塊");//Database error during the execution of function onInstall for the module
define("_MODULEISALREADYINSTALLED","該模塊已經安裝");//The module is already installed
define("_LOGOUTREDIRECT","重定向後，登出來");//Redirect after logout to
define("_INFORMATIONFORFILE","資料檔案");//Information for file
define("_METADATA","中繼");//Metadata
define("_FILEMETADATA","檔案元數據");//File metadata
define("_NOENTRYFOUNDFORTHEFIELD","沒有進入發現為外地");//No entry found for the field
define("_CONTENTMETADATA","內容元數據");//Content Metadata
define("_METADATAFORUNIT","元數據為單位");//Metadata for unit
define("_RESOURCEREQUESTEDREQUIRESLOGIN","資源，您要求您必須先登錄");//The resource that you requested requires that you login first
define("_DATABASEERROR","數據庫錯誤");//Database error
define("_CANNOTACCESSRESOURCE","您沒有權限訪問此資源");//You don&#039;t have permission to access this resource
define("_RESOURCEISNOTACCESSIBLEFROMOUTSIDE","這個資源是沒有直接訪問");//This resource is not directly accessible
define("_RESOURCEISNOTAVAILABLE","這個資源是不是可用");//This resource is not available
define("_DIRECTLYACCESSIBLE","方便與直接網址");//Accessible with a direct URL
define("_DIRECTLACCESSIBLEEXPLANATION","這意味著，該單位可以訪問使用以下直接網址：");//This means that the unit can be accessed using the following direct url:
define("_HIDE","隱藏");//Hide
define("_LESSONOPTIONSET","教訓選項設置");//Lesson option set
define("_BACKUPRESTORE","備份/還原");//Backup/restore
define("_CONFIGURATIONOPTIONS","配置選項");//Configuration options
define("_UNAUTHORIZEDACCESS","您沒有權限訪問此節");//You do not have permission to access this section
define("_LESSONUSER","教訓用戶");//Lesson user
define("_PROGRESSFORUSER","進展，為用戶");//Progress for user
define("_LESSONSORDER","為了教訓");//Lessons order
define("_COURSEUSER","當然用戶");//Course user
define("_COURSELESSON","當然，教訓");//Course lesson
define("_CANNOTDELETEOWNTYPE","您可能無法刪除您自己的類型");//You may not delete your own type
define("_GROUPUSER","集團用戶");//Group user
define("_EXPLICITIFRAMESIZE","明確iFrame大小");//Explicit iframe size
define("_EXPLICITSIZEEXPLANATION","這是大小的SCORM的內容包含框架。請將它留為空白，以有，它會自動計算");//This is the size of the SCORM content containing frame. Leave it blank to have it automatically calculated
define("_USERROLEINLESSON","用戶角色在教訓");//User role in lesson
define("_LESSONROLE","的作用，教訓");//Role in lesson
define("_COURSEROLE","在過程中的作用");//Role in course
define("_PAYPAL","貝寶");//Paypal
define("_DOWNLOADEXAMPLE","下載的例子");//Download example
define("_CONTENTTREEFIRSTPAGE","內容樹在第一頁");//Content tree in first page
define("_LAYOUT","佈局");//Layout
define("_CONNECTIONERROR","連接錯誤");//Connection error
define("_ONLYEFRONTNOTSCORM","使用此上傳的教訓，在eFront格式只。為SCORM的上載，使用SCORM的選項，在教授的控制面板");//Use this to upload lessons in eFront format only. For SCORM uploads, use the SCORM option at the professor's control panel
define("_TESTSMATRIX","測試矩陣");//Tests matrix (New)
define("_PROJECTSMATRIX","項目矩陣");//Projects matrix (New)
define("_MODULEDBERRORONUPGRADECHECKUPGRADEFUNCTION","數據庫錯誤的執行過程中的功能onUpgrade模塊");//Database error during the execution of function onUpgrade for the module (New)
define("_MODULENOTUPGRADEDFOLDERNOTDELETEDCLOSEALLOPENFILES","模塊升級失敗，因為現有目錄無法刪除。關閉所有打開的文件在此目錄，然後再試一次");//Module upgrade failed, because existing directory could not be deleted. Close all open files in that directory and try again (New)
define("_MODULESUCCESFULLYUPGRADED","模塊成功升級");//Module successfully upgraded (New)
define("_USERRESULTS","用戶結果");//User results (New)
define("_SKILLSCORES","得分技巧");//Skill scores (New)
define("_PROPOSEDASSIGNMENTS","擬議轉讓");//Proposed assignments (New)
define("_THRESHOLD","開始");//Threshold (New)
define("_SKILLGAPANALYSISFORUSER","技能差距分析用戶");//Skill gap analysis for user (New)
define("_ACCORDINGTOTEST","據測試");//according to test (New)
define("_NOLESSONSPROPOSEDACCORDINGTOANALYSIS","沒有經驗教訓，提出根據技能差距分析");//No lessons are proposed according to the skill gap analysis (New)
define("_NOCOURSESPROPOSEDACCORDINGTOANALYSIS","沒有課程的建議根據技能差距分析");//No courses are proposed according to the skill gap analysis (New)
define("_CERTIFICATETEMPLATE","證書模板（ RTF格式）");//Certificate template (rtf format) (New)
define("_COMMANDS","命令");//Commands (New)
define("_SEARCHRESULTSCOMMANDS","搜索結果中的命令");//Search results in commands (New)
define("_TOGGLEHTMLEDITORMODE","切換編輯/ HTML模式");//Toggle editor/html mode (New)
define("_UPLOADFILEFROMURL","上傳文件從以下網址");//Upload file from url (New)
define("_OPENCLOSEFILEMANAGER","打開/關閉文件管理器");//Open/close file manager (New)
define("_INSERTEDITOR","插入編輯");//Insert to editor (New)
define("_AUTOMATICALLYASSIGNTOALLNEWSTUDENTS","自動分配給所有的新學生");//Automatically assign to all new students (New)
define("_SKILLGAPTESTSTOBECOMPLETED","技能差距試驗完成");//Skill gap tests to be completed (New)
define("_SKILLGAPTESTCOMPLETEDSUCCESSFULLY","技能差距試驗順利完成");//Skill gap test completed successfully (New)
define("_RELEVANCE","關聯");//Relevance (New)
define("_KNOWLEDGEOFLESSON" , "Knowledge of lesson");
define("_KNOWLEDGEOFCOURSE","當然知識");//Knowledge of course (New)
define("_NOSKILLSCORRELATEDWITHTHETESTSQUESTIONS","沒有相關的技能測試的問題");//No skills correlated with the test&#039;s questions (New)
define("_OPENFILEMANAGER","打開文件管理器");//Open file manager (New)
define("_CLOSEFILEMANAGER","關閉文件管理器");//Close file manager (New)
define("_CLICKFORHELP","點擊幫助");//Click for help (New)
define("_NOSKILLGAPTESTSASSIGNEDTOYOU","沒有技能差距試驗分配給您");//No skill gap tests assigned to you (New)
define("_TESTSOLVEDVIEWTOSEESKILLGAPANALYSIS" , "Test solved: View skill gap analysis");
define("_GENERALTHRESHOLD","一般閾值");//General Threshold (New)
define("_UPLOADPDFFORCONTENT","切換PDF格式/自定義內容");//Toggle pdf/custom content (New)
define("_PDFFILE","上傳新pdf檔案");//Upload new pdf file (New)
define("_ASSOCIATEDSKILLS","相關技能");//Associated skills (New)
define("_SKILLGAPTESTS","技能差距試驗");//Skill gap tests (New)
define("_ASSOCIATEDWITH","合併");//Associated with (New)
define("_NEWSKILLGAPTESTS","新技能差距試驗");//New skill gap tests (New)
define("_CORRELATESKILLSTOQUESTION","相關技能問題");//Correlate skills to question (New)
define("_EDITSKILLGAPTEST","編輯技能差距測試");//Edit skill gap test (New)
define("_ADDSKILLGAPTEST","新增技能差距測試");//Add skill gap test (New)
define("_YOUMUSTUPLOADAPDFFILE","您必須上傳pdf檔案");//You must upload a pdf file (New)
define("_RECENTLYCOMPLETEDSKILLGAP","最近完成的測試skillgap");//Recently completed skillgap tests (New)
define("_NOCOMPLETEDSKILLGAP","沒有完成測試發現skillgap");//No completed skillgap tests found (New)
define("_SHOWALLSOLVEDSKILLGAPTESTS","顯示所有的測試解決skillgap");//Show all solved skillgap tests (New)
define("_DELETESKILLGAPTESTRECORD","刪除技能差距測試記錄");//Delete skill gap test record (New)
define("_ASSIGNTOALLNEWSTUDENTS","分配給所有的新學生");//Assign to all new students (New)
define("_AUTOMATICALLYASSIGNLESSONS","自動分配的教訓");//Automatically assign lessons (New)
define("_AUTOMATICASSIGNMENTINFO","在完成測試的學生，將被自動分配與所有<br>經驗教訓和課程符合他或她的教育需求");//After completing the test, a student will be automatically assigned with all<br> lessons and courses matching his or her educational needs (New)
define("_SKILLGAPTESTCOMPLETEDSUCCESSFULLYANDTHECORRESPONDING","技能差距試驗順利完成和相應的");//Skill gap test completed successfully and the corresponding (New)
define("_HAVEBEENASSIGNED","已分配給您");//have been assigned to you (New)
define("_SKILLGAPTESTRESULTS","技能差距的測試結果");//Skill gap test results (New)
define("_CURRENTPDFFILE","當前pdf檔案");//Current pdf file (New)
define("_SEARCHTEXTWASINSCRIPT","搜索文本被發現倒斃在一個腳本");//Search text was found inside a script (New)
define("_NUMBERFROM000TO9999REQUIRED","數從0.00到99.99要求");//Number from 0.00 to 99.99 required (New)
define("_COMPLETETHESKILLGAPTESTSBELOWSOTHATWECANASSIGNLESSONS","完成技能差距下面的測試，以便我們可以指定課程最適合您的neeeds 。");//Complete the skill gap tests below so that we can assign courses most suitable to your neeeds. (New)
define("_YOUHAVECOMPLETEDALLSKILLGAPSTESTSASSIGNEDTOYOUWAITTOBEASSIGNEDLESSONS","您已完成了所有試驗技能差距分配給您。 <br>請等待，直到你的教授指派給您最合適的課程，根據您的需要。");//You have completed all skill gap tests assigned to you. <br>Please wait until your professors assign to you the most suitable courses according to your needs. (New)
define("_YOURRESULTSHAVEBEENSENTTOYOURPROFESSORSWHOWILLASSIGNLESSONSACCORDINGTOYOURNEEDS","您的結果已發送到您的教授誰不久將指定課程，您根據您的需要確定從這個測試");//Your results have been sent to your professors who will soon assign courses to your according to your needs as identified from this test (New)
define("_JOBPLACEMENTS","就業安置");//Job placements (New)
define("_NEWJOBPLACEMENT","新安排就業");//New job placements (New)
define("_UPGRADEMODULE","升級模塊");//Upgrade module (New)
define("_NEWUNITOPTIONS","新單位的選擇");//New unit options (New)
define("_UNITOPTIONSFOR","選擇單位");//Options for unit (New)
define("_OPTIONSFORSKILLGAPTEST","選擇技能差距測試");//Options for skill gap test (New)
define("_OPTIONSFORTEST","選擇測試");//Options for test (New)
define("_REPORTSFORCOURSE","當然報告");//Reports for course (New)
define("_REPORTSFORTEST","測試報告");//Reports for test (New)
define("_USERISNOTVALIDORYOUCANNOTSEEUSER","指定的用戶是無效的，或者你無法訪問該用戶的數據");//The user specified is not valid, or you cannot access this user&#039;s data (New)
define("_SELECTGROUP","選擇組");//Select group (New)
define("_BLANKFORNOLIMIT","留空為沒有時間限制");//Leave blank for no time limit (New)
define("_HARDPLURAL","硬的");//Hard (New)
define("_MEDIUMPLURAL","中等");//Medium (New)
define("_EASYPLURAL","容易的");//Easy (New)
define("_UNLIMITED","Unilimited");//Unilimited (New)
define("_INCORRECTQUESTION","現在的問題是不正確");//The question is incorrect (New)
define("_QUESTIONISCORRECT","現在的問題是正確的");//The question is correct (New)
define("_PARTIALLYCORRECTQUESTION","現在的問題是部分正確的");//The question is partially correct (New)
define("_FAILED","失敗");//Failed (New)
define("_PASSED","通過");//Passed (New)
define("_TESTOPTIONS","試驗選擇");//Test options (New)
define("_TESTQUESTIONS","測試的問題");//Test questions (New)
define("_SAVETESTANDADDQUESTIONS","保存和選擇的問題");//Save and select questions (New)
define("_RANDOMPOOLTEST","隨機試驗池");//Random pool test (New)
define("_SUBMITANDCONTINUEEDITING","提出並繼續編輯");//Submit and continue editing (New)
define("_SUBMITANDRETURN","提交並返回");//Submit and return (New)
define("_SUBMITASNEWANDCONTINUEEDITING","提出新的和繼續編輯");//Submit as new and continue editing (New)
define("_SUBMITASNEWANDRETURN","提出新的和返回");//Submit as new and return (New)
define("_QUESTIONSINPOOL","在池的問題");//Questions in pool (New)
define("_SELECTRANDOMQUESTIONS","隨機問題");//Randomize questions (New)
define("_RANDOMIZE","隨機");//Randomize (New)
define("_PAUSETEST","暫停測試");//Pause test (New)
define("_ALLFORUMS","所有論壇");//All forums (New)
define("_USERCANDOTEST","用戶可以做的測試");//The user can do the test (New)
define("_ANDUSERDIDITIN","這是完成");//It was completed in (New)
define("_TESTSCOREIS","測試評分");//Test score is (New)
define("_USERREDOTEST","重做試驗");//Redo test (New)
define("_SOLVEDTEST","解決測試");//Solved test (New)
define("_CHANGESCORE","更改評分");//Change score (New)
define("_ADDFEEDBACK","購買反饋");//Add feedback (New)
define("_EDITFEEDBACK","編輯反饋");//Edit feedback (New)
define("_RESETTESTSTATUS","重置這個測試執行");//Reset this test execution (New)
define("_THETESTISDONE","測試完成");//The test is done (New)
define("_ANDCANBEDONE","並可以做到的");//and can be done (New)
define("_TESTCANBEPAUSED","試驗可以暫停");//Test can be paused (New)
define("_TESTSTARTEDAT","測試開始");//The test started at (New)
define("_ANDCOMPLETEDAT","並完成");//and completed at (New)
define("_SCOREINTEST","在測試分數");//Score in test (New)
define("_TESTRESULTS","試驗結果");//Test results (New)
define("_JUMPTOEXECUTION","跳轉到執行");//jump to execution (New)
define("_LASTEXECUTION","最後一次執行死刑");//Last execution (New)
define("_EXECUTION","執行");//execution (New)
define("_LAST","最後的");//Last (New)
define("_CORRECTIONPENDING","待修正");//Correction pending (New)
define("_FULLNAME","全名");//Full name (New)
define("_PARTIALLYCORRECT","部分正確");//Partially correct (New)
define("_CORRECT","正確的");//Correct (New)
define("_NOUNIT","任何單位");//No unit (New)
define("_TESTANALYSIS","測試分析");//Test analysis (New)
define("_THISLEVEL","這個級別");//This level (New)
define("_BELOWLEVELS","以下各級");//Below levels (New)
define("_SUCCESSRATES","成功率");//Success rates (New)
define("_NOPARENT","沒有父母");//Without parent (New)
define("_THEUSERUNDERGOINGTESTSTARTEDAT","用戶現在正在進行試驗，開始在");//The user is right now undergoing the test, started at (New)
define("_NONEXISTENTTEST","這不是一個完成測試");//This is not a completed test (New)
define("_FORTEST","測試");//for test (New)
define("_ANDUSER","和用戶");//and user (New)
define("_TESTANALYSISFORTEST","試驗分析測試");//Test analysis for test (New)
define("_RESETALLTESTSSTATUS","重置所有的執行狀況");//Reset all execution status (New)
define("_ADDANOTHERFILE","添加其他文件");//Add another file (New)
define("_YOUPAUSEDTHISTESTON","您暫停這一試驗");//You paused this test on (New)
define("_RESUMETEST","恢復測試");//Resume test (New)
define("_DISPLAYQUESTIONWEIGHTS","在顯示重量測試");//Display weights during test (New)
define("_UNAVAILABLEOPTION","此選項不可用");//This option is not available (New)
define("_SKILLGAPTESTS","技能差距試驗");//Skill gap tests (New)
define("_HOURSSHORTHAND","h");//h (New)
define("_MINUTESSHORTHAND","米");//m (New)
define("_SECONDSSHORTHAND","語");//s (New)
define("_NONEUNIT","無單位");//None unit (New)
define("_NOSYSTEMANNOUNCEMENTS","沒有系統的通知");//There are no system announcements (New)
define("_NOONELOGGEDIN","沒有人是目前登入");//Noone is currently logged in (New)
define("_ENTERYOUREMAILADDRESS","請輸入您的電子郵箱地址");//Enter you email address (New)
define("_ENTERMESSAGESUBJECT","輸入郵件主題");//Enter the message subject (New)
define("_ENTERMESSAGE","輸入的信息");//Enter the message (New)
define("_ENTERANYCOMMENTS","輸入任何評論您可能");//Enter any comments you might have (New)
define("_LOGINOREMAIL","登錄或電子郵件");//Login or email (New)
define("_USETHISTORESETPASSWORD","使用此表為重置密碼");//Use this form to reset your password (New)
define("_USETHISTOREGISTERANEWACCOUNT","使用這個表格，以建立一個新的用戶帳戶");//Use this form to create a new user account (New)
define("_USETHISTOCONTACTUS","使用此表與我們聯繫任何問題");//Use this form to contact us for any issue (New)
define("_AVAILABLELESSONS","經驗和現有的課程體系");//Lessons and courses available in the system (New)
define("_SELECTLAYOUT","選擇一個版面");//Select a layout (New)
define("_ENROLL","註冊");//Enroll (New)
define("_INFORMATION","信息");//Information (New)
define("_STARTPAGE","起始網頁");//Start page (New)
define("_SIGNUP","註冊");//Sign up (New)
define("_INFOFORLESSON","信息課");//Information for lesson (New)
define("_DONTHAVEACCOUNT","我沒有一個帳戶");//I do not have an account (New)
define("_FORGOTPASSWORD","我忘記了密碼");//I forgot my password (New)
define("_LOGINFORM","登錄表單");//Login form (New)
define("_SEARCHFORM","搜索表單");//Search form (New)
define("_CARTBLOCK","購物車塊");//Shopping Cart block (New)
define("_CUSTOMBLOCK","自定義塊");//Custom block (New)
define("_LESSONSLIST","總結名單");//Lessons list (New)
define("_SYSTEMNEWS","系統新聞");//System news (New)
define("_REMOVE","刪除");//Remove (New)
define("_TWOCOLUMNSRIGHT","兩列右對齊");//Two columns right-aligned (New)
define("_TWOCOLUMNSLEFT","兩列左對齊");//Two columns left-aligned (New)
define("_THREECOLUMNS","三欄");//Three columns (New)
define("_SIMPLE","簡單");//Simple (New)
define("_SAVELAYOUT","保存佈局");//Save layout (New)
define("_ADDBLOCK","新增區塊");//Add block (New)
define("_RESTOREDEFAULTLAYOUT","還原默認佈局");//Restore default layout (New)
define("_INFOFORCOURSE","當然信息");//Information for course (New)
define("_PLEASELOGINTOCOMPLETEREGISTRATION","請登入以完成註冊");//Please login to complete registration (New)
define("_GOTOLESSONSLIST","轉到列表中的經驗教訓");//Go to lessons list (New)
define("_PUBLISHED","發布時間");//Published (New)
define("_NOTPUBLISHED","未發布");//Not published (New)
define("_OPTIONSFORPROJECT","選擇項目");//Options for project (New)
define("_SKILLGAPTESTRESULTSREMOVEDFROMUSERTHETESTCANBEREPEATED","試驗結果已成功刪除該用戶。測試現在可以完成了。");//Test results have been successfully removed for this user. The test can now be completed again. (New)
define("_HOMEOFLESSON","主頁的教訓");//Home of lesson (New)
define("_OPTIONSFORGROUP","選項組");//Options for group (New)
define("_SURVEYFAILEDTOBEDELETED","調查未能予以刪除");//Survey failed to be deleted (New)
define("_COURSESNUMBER","一些課程");//Number of courses (New)
define("_GROUPSNUMBER","一些團體");//Number of groups (New)
define("_FORUMTITLE","論壇名稱");//Forum title (New)
define("_OTHERLESSONS","其他的經驗教訓");//Other lessons (New)
define("_CONTENTREPORT","內容錯誤報告");//Content error report (New)
define("_CONTENTREPORTTOPROFS","報告內容錯誤教授");//Report content error to professors (New)
define("_TOPIC","專題");//Topic (New)
define("_LINK","鏈接");//Link (New)
define("_REPORT","報告");//Report (New)
define("_SUCCESFULLYSENDREPORT","您的報告中已成功發送");//Your report was successfully sent (New)
define("_ERRORREPORTFOR","錯誤報告內容的教訓");//Content error report for lesson (New)
define("_YOUSHOULDCHANGEHEADERLANGUAGETAG","您應該在改變_HEADERLANGUAGETAG");//You should change _HEADERLANGUAGETAG in (New)
define("_LANGUAGEFILE","語言文件");//language file (New)
define("_YOURSYSTEMSUPPORTS","您的系統支持");//Your system supports (New)
define("_LINKTOTOPIC","專題鏈接");//Link to topic (New)
define("_SCOREINEACHUNIT","分數在每個單位");//Score in each unit (New)
define("_SCOREINUNIT","分數的單位");//Score in unit (New)
define("_SHOWDETAILS","查看詳細");//Show details (New)
define("_DISPLAYORDEREDLIST","顯示命令列表");//Display ordered list (New)
define("_AVERAGESCOREON","平均分數上");//average score on (New)
define("_SCOREONLASTEXECUTION","評分上最後一次執行死刑");//score on last execution (New)
define("_EXECUTIONS","處決");//Executions (New)
define("_RECENTLYCOMPLETEDTESTS","最近完成的測試");//Recently completed tests (New)
define("_IMPORTNOTICE","警告：進口的教訓將刪除現有的所有課程資料");//Warning: importing a lesson will erase all existing lesson information (New)
define("_RESET","重置");//Reset (New)
define("_RESETGRAPH","重圖");//Reset graph (New)
define("_CANNOTAUTOMATICALLYLOGIN","你不能自動登錄");//You cannot login automatically (New)
define("_LOGINENTRANCE","註冊");//Login (New)
define("_SELECTEDLESSONS","選定的教訓");//Selected lessons (New)
define("_ADDTOLESSONS","添加到教訓");//Add to lessons (New)
define("_AVAILABLEBLOCKS","可用區塊");//Available blocks (New)
define("_ADDCUSTOMBLOCK","新增自訂區塊");//Add custom block (New)
define("_CURRENTLAYOUT","當前佈局");//Current layout (New)
define("_UNDOALLCHANGES","撤消所有的變化");//Undo all changes (New)
define("_BLOCKTITLE","座冠軍");//Block title (New)
define("_BLOCKCONTENT","座內容");//Block content (New)
define("_YOUCANNOTACCESSREQUESTEDRESOURCE","你不能獲得所要求的資源");//You cannot access the requested resource (New)
define("_TOTALUNITS","總計單位");//Total units (New)
?>
