<?php
if (is_file($GLOBALS['path']."language/custom-chinese_simplified.php.inc")) {
include($GLOBALS['path']."language/custom-chinese_simplified.php.inc");
}
define("_HEADERLANGUAGEHTMLTAG","ch");//en
define("_CURRENTLANGUAGESYMBOL","ch_si");//en
define("_HEADERLANGUAGETAG","chinese");//english
define("_CHARSET","EUC-CN");//ISO-8859-1
define("_LANGUAGE","语言");//Language
define("_PASSWORD","密码");//Password
define("_SUBMIT","提交");//Submit
define("_REGISTER","注册");//Register
define("_CONTACT","联系我们");//Contact us
define("_FROM","自");//From
define("_SENDSUCCESS","您的留言已成功发送。感谢您与我们联系!");//Your message was sent successfully. Thank you for contacting us!
define("_SENDFAILURE","错误。请再试一次。");//A problem has come up. Please try again.
define("_LOGIN","注册");//Login
define("_NAME","名字");//Name
define("_SURNAME","姓氏");//Surname
define("_ADDRESS","地址");//Address
define("_POSTCODE","邮政编码");//Post code
define("_CITY","城市");//City
define("_HOMEPHONE","电话号码");//Phone number
define("_EMAILADDRESS","电子邮件地址");//Email address
define("_COMMENTS","评论");//Comments
define("_TIME","时间");//Time
define("_BACK","&larr;&nbsp;回");//&larr;&nbsp;Back
define("_CONFIGURATIONVARIABLES","系统配置");//System configuration
define("_CHANGESITELOGO","改变网站徽标");//Change site logo
define("_ONLYONELANGUAGE","支持只有一个（默认）语言");//Support only one (the default) Language
define("_YES","是");//Yes
define("_NO","否");//No
define("_UPDATELESSONS","节更新");//Update lessons
define("_ADMINEMAIL","管理员电子邮件");//Administrator email
define("_LESSONSDELETED","节已删除");//The lesson was deleted
define("_SHOWFOOTER","显示页脚");//Show footer
define("_DEFAULTLANGUAGE","默认语言");//Default language
define("_DIGITALLIBRARY","数字文件");//Digital file library
define("_BACKUP","备份系统");//Backup system
define("_RESTORE","恢复系统");//Restore system
define("_FREE","这个节是免费提供给所有");//This lesson is free for all
define("_SUCCESSREGISTER","您已注册成功");//You have registered successfully
define("_LESSONSREGISTRATION","节登记");//Lesson registration
define("_YOUREMAIL","您的电子邮件");//Your e-mail 
define("_MESSAGESUBJECT","邮件主题");//Message subject
define("_PASSWORDLEAVEBLANK","密码（空白离开不变）");//Password (blank to leave unchanged)
define("_PERSONALDATACHANGESUCCESS","您的个人信息已成功改变");//Your personal info has been successfully altered
define("_REGISTRATIONDATE","登记日期");//Registration date
define("_SAVECHANGES","保存更改");//Save changes
define("_PERSONALDATA","个人信息");//Personal info
define("_LESSONOPTIONS","节选项");//Lesson options
define("_PERSONALOPTIONS","工具");//Tools
define("_QUESTIONWEIGHT","问题权重（ 1-10 ）");//Question weight (1-10)
define("_WEIGHT","权重");//Weight
define("_NONEWLESSONREGISTRATIONS","没有新的节登记");//No new lesson registration
define("_LESSONS","节");//Lessons
define("_RECREATESEARCHTABLE","重新搜索表");//Recreate search table
define("_LESSONSREGISTRATIONS","节登记");//Lesson registrations
define("_TOOLS","工具");//Tools
define("_ONLINEUSERS","对线路用户");//On line users
define("_DATE","日期");//Date
define("_STUDENT","学生");//Student
define("_LINE","线");//Line
define("_SOMEPROBLEMEMERGED","有些问题已经发生");//Some problem has occured
define("_CORRECTION","正确的 它");//Correct it
define("_LESSONNAME","节名称");//Lesson name
define("_DIRECTION","类别");//Categories
define("_DIRECTIONNAME","类别名称");//Category name
define("_NEWLESSON","新的节");//New lesson
define("_NEWDIRECTION","新的类别");//New category
define("_EMAILSENDAT","电子邮件被送往");//Email was sent to 
define("_CHOOSELESSON","选择的节");//Choose lesson
define("_SUBJECT","题目");//Subject
define("_RECIPIENTSSELECTION","受助人的选择");//Recipients selection
define("_EMAILBODY","电子邮件机构");//E-mail body
define("_SENDEMAIL","发送电子邮件");//Send E-mail
define("_EXIT","退出");//Exit
define("_MORE","更多");//more
define("_DELETE","删除");//Delete
define("_MESSAGES","邮件");// Messages
define("_THEORY","理论");//Theory
define("_PROJECTS","项目");//Projects
define("_TESTS","测试");//Tests
define("_PREVIOUS","&lt;向前");//&lt; Previous
define("_NEXT","下一个&gt;");//Next &gt;
define("_CANNOTACCESSTHISUNIT","您不能看到这个单元的 因为：");//You cannot see this unit because:
define("_SENDPERSONALMESSAGE","发送个人讯息");//Send personal message
define("_SEND","发送");//Send
define("_STATISTICS","报告");//Reports
define("_OPTIONS","选项");//Options
define("_THEFIELD","外地");//The field
define("_WELCOMETO","欢迎您到");//Welcome to the
define("_LESSONANNOUNCEMENT","公布的节");//Announcement for the lesson
define("_COLOR","颜色");//Color
define("_HOUR","小时");//hour
define("_HOURS","小时");//hours
define("_MINUTE","分钟");//minute
define("_MINUTES","分钟");//minutes
define("_SECONDS","秒");//seconds
define("_LASTLOGIN","最后登录在");//Last log-in
define("_MEAN","平均");//Average
define("_LOGINAT","登时时间为");//Log-in at
define("_TESTHADAT","测试完成");//Test completed at
define("_HASMAXIMUMDURATION","最长期限");//It had maximum duration
define("_YOURSCOREIS","你的分数是");//Your score is
define("_FINALSCOREWILLBEFROM","最后的评分将来自");//Final score will be from
define("_ANDYOUDIDITIN","你完成了它在");//and you completed it in
define("_TO","到");//to
define("_DEPENDSONQUESTIONS","根据您的答案，开放式回答问题。");//depending on your answers on open-answer questions.
define("_EXAMPLEANSWER","例子答案");//Example answer
define("_SCORE","评分");//Score
define("_THISQUESTIONCORRECTEDPROFESSOR","这个问题将由教师纠正。");//This question will be corrected by the professor
define("_RIGHTANSWER","正确答案");//Correct answer
define("_TESTSHOULDCOMPLETEIN","这项测试必须完成在");//This test must be completed in
define("_TIMELEFT","剩余时间");//Time remaining
define("_YOUCANNOTLOGINAS","无指定用户名的用户：");//No user exists with login name:
define("_WRONGPASSWORDTRYAGAIN","密码错误。请再试一次。");//You gave a wrong password. Please try again.
define("_NOTACTIVATEDACCOUNTTRYAGAINLATER","您的账户尚未激活。请稍后再试。");//Your account has not been activated yet. Please try again later.
define("_YOUHAVEBEENEXCLUDEDBYPROFESSOR","你被教师开除");//You are excluded by professor
define("_MUSTFIRSTREADUNIT","您必须先阅读单元");//You must first read unit
define("_MUSTFIRSTTAKEATLEAST","您必须首先完成");//You must first take at least
define("_YOURTIMEISUP","时间到");//Your time is up
define("_ATTEST","测试中");//at test
define("_WANTTOREDOTEST","我想重做这个测试");//I want to redo this test
define("_PERCENT","％");//Percent
define("_CANNOTREDOTEST","你不能重做这项测试！");//You cannot redo this test!
define("_LESSON","节");//Lesson
define("_ALL","所有内容");//All content
define("_GOTOFORUM","去论坛");//Go to forum
define("_SENDMESSAGEATFORUM","帖子");//Post message
define("_SENDMESSAGE","发送消息");//Send message
define("_ANNOUNCEMENTS","公告");//Announcements
define("_MESSAGESATFORUM","论坛讯息");//Forum messages
define("_PERSONALMESSAGES","个人信息");//Personal messages
define("_SOLVEDTESTS","处理测试");//Solved tests
define("_ATFORUM","在论坛");//At forum
define("_PRINTERFRIENDLY","打印单元");//Print unit
define("_PRINTERFRIENDLYALLCONTENT","打印所有内容");//Print all the content
define("_ADDCOMMENT","添加评论");//Add comment
define("_LESSONSELECT","选择的节");//Select lesson
define("_CURRENTCONTENT","目前的内容");//Current content
define("_COMMENTDELETED","评论已被删除");//The comment has been deleted
define("_COMMENTADD","添加评论");//Add comment
define("_ADDYOURCOMMENT","新增您的评论");//Add your comment
define("_SUCCESFULLYADDEDCOMMENT","添加评论成功");//The comment was added successfully
define("_SUCCESFULLYUPDATEDCOMMENT","评论更新成功");//The comment was updated successfully
define("_SUCCESFULLYDELETEDFILEWINDOWCLOSE5SECONDS","该文件被删除。该窗口会自动关闭在5秒内。");//The file was deleted. This window will automatically close in 5 seconds.
define("_SUCCESFULLYDELETEDFOLDERWINDOWCLOSE5SECONDS","该文件夹删除。该窗口会自动关闭在5秒内。");//The folder was deleted. This window will automatically close in 5 seconds.
define("_NOTSUCCESFULLYDELETEDFOLDERWINDOWCLOSE5SECONDS","该文件夹是不会被删除。它必须不包含任何文件或文件夹予以删除。该窗口会自动关闭在5秒内。");//The folder was not deleted. It must not contain any files or folders to be deleted. This window will automatically close in 5 seconds.
define("_SUCCESFULLYCREATEDFOLDERWINDOWCLOSE5SECONDS","该文件夹已创建。该窗口会自动关闭在5秒内。");//The folder was created. This window will automatically close in 5 seconds.
define("_FOLDERNAME","文件夹名称");//Folder name
define("_CREATE","创建");//Create
define("_LESSONNOTSET","的节，并未设定。");//The lesson was not set.
define("_COPYNAMESFROMLEFTTORIGHTTOSAVEIMAGES","复制姓名从左边向右边一栏，为了节省图像文件在您的文件。");//Copy names from the left to the right column, in order to save the image files in your document.
define("_THEFILE","文件");//The file
define("_MUSTBESMALLERTHAN","必须小于");//must be smaller than
define("_KILOBYTES","千字节.");//Kbytes.
define("_HASBEENSEND","被送往。");//was sent.
define("_SENDFILE","发送文件");//Send file
define("_CLOSEWINDOW","关闭窗口");//Close window
define("_UPDATE","更新");//Update
define("_SUCCESFULLYDELETEDANNOUNCEMENTWINDOWCLOSE5SECONDS","通知已成功删除");//The announcement was deleted successfully
define("_ANNOUNCEMENTADD","新增公告");//Add announcement
define("_ANNOUNCEMENTTITLE","公告标题");//Announcement title
define("_ANNOUNCEMENTBODY","公布机构");//Announcement body
define("_SUCCESFULLYADDEDANNOUNCEMENTWINDOWCLOSE5SECONDS","公告加入成功");//The announcement was added successfully
define("_SUCCESFULLYUPDATEDANNOUNCEMENTWINDOWCLOSE5SECONDS","公告已成功更新");//The announcement was updated successfully
define("_ENDDATEMUSTBEBEFORESTARTDATE","结束日期必须后开始日期。");//End date must be after start date.
define("_SAVE","保存");//Save
define("_SUCCESFULLYUPDATEDQUESTION","问题是，成功更新");//The question was updated successfully
define("_SUCCESFULLYADDEDQUESTION","问题是，添加成功");//The question was added successfully
define("_QUESTIONTEXT","题目文本");//Question text
define("_SAVEQUESTION","保存问题");//Save question
define("_UNIT","单元");//Unit
define("_QUESTIONTYPE","问题类型");//Type
define("_DIFFICULTY","困难");//Difficulty
define("_RATEMUSTBEBETWEEN0100","评分范围必须介于0和100之间");//The score must range between 0 and 100
define("_ALLOFTHEM","所有用户");//All users
define("_VALIDFOR","有效期为");//Valid for
define("_TOBEEXCLUDEDFROMUNIT","被排除在该单元");//to be excluded from the unit
define("_THEUNIT","单元");//the unit
define("_TESTNAME","测试名称");//Test name
define("_UNITPARENT","父单元");//Parent unit
define("_SAVETEST","储存测试");//Save test
define("_SUCCESFULLYADDEDRATE","比率插入成功");//The rate was inserted successfully
define("_STUDENTANSWER","学生的答案");//Student answer
define("_SEARCHTABLERECREATED","搜索表重建");//The search table was recreated
define("_SAVETHE","保存");//Save the
define("_OFTHELESSONATYOURCOMPUTER","的节，在您的计算机上。");//of the lesson at your computer.
define("_ATYOURCOMPUTER","在您的计算机上。");//at your computer.
define("_DATAFILE","数据文件");//Data file
define("_NOTGIVEFILENAME","您没有供应文件名称");//You did not supply a file name
define("_LESSONDATAFILE","节的数据文件");//Lesson data file
define("_INSERTDATA","导入数据");//Import data
define("_OFLESSON","的节");//Of the lesson
define("_CATEGORY","类别");//Category
define("_SEARCH","搜索");//Search
define("_DESCRIPTION","描述");//Description
define("_TYPE","类型");//Type
define("_POSITION","立场");//Position
define("_LESSONCONTENT","节内容");//Lesson content
define("_TITLE","标题");//Title
define("_TEXT","文本");//Text
define("_NORESULTSFOUNDINFORUM","在论坛中没有发现结果");//No results found in forum
define("_SEARCHRESULTSINLESSONS","在节中搜索");//Search results in lessons
define("_SEARCHRESULTSINFORUM","在论坛中搜索");//Search results in forum
define("_SEARCHRESULTSINUSERS","在论坛中搜索");//Search results in users
define("_NOSEARCHRESULTSFOUND","未找到搜索项");//No results found during the search
define("_PRINTIT","打印！");//Print it!
define("_LANGUAGEADMINISTRATION","设置语言");//Set languages
define("_INTERMEDIATESELLER","中级推销员");//Intermediate salesman
define("_PROFESSOR","教师");//Professor
define("_ADMINSTRATOR","管理员");//Administrator
define("_CONTROLCENTER","控制中心");//Control center
define("_EXAMPLES","例子");//Examples
define("_FORUM","论坛");//Forum
define("_NOCONTENT","单元没有内容");//Unit without content
define("_INACTIVE","未激活单元");//Inactive unit
define("_CONTENTMANAGEMENT","内容");//Content
define("_SCHEDULING","调度");//Scheduling
define("_OFDEVELOPMENT","发展");//development
define("_MULTIPLECHOICEONESELECTION","选择题");//Multiple choices, single correct answer
define("_MULTIPLECHOICEMULTIPLESELECTIONS","选择题");//Multiple choices, multiple correct answers
define("_OFMATCH","匹配");//matching
define("_OFEMPTYSPACES","在空白上填写");//Fill in the blanks
define("_LOW","低的");//Low
define("_MEDIUM","中等");//Medium
define("_HIGH","高的");//High
define("_PERIODSPERSTUDENT","每名学生");//Periods per student
define("_NETMEETINGSUPPORT","NetMeeting支持");//Netmeeting support
define("_IFSTUDENTHASNOTSEEN","如果学生没有看到");//If student has not seen
define("_IFSTUDENTHASNOTPASSED","如果学生尚未通过");//If student has not passed
define("_STUDENTALLWAYS","学生总是");//Student allways
define("_ACCESSRULES","节规则");//Lesson rules
define("_EMAILS","电子邮件");//Emails
define("_CHAT","聊天");//Chat
define("_OFJANUARY","一月");//January
define("_OFFEBRUARY","二月");//February
define("_OFMARCH","三月");//March
define("_OFAPRIL","四月");//April
define("_OFMAY","五月");//May
define("_OFJUNE","六月");//June
define("_OFJULY","七月");//July
define("_OFAUGUST","八月");//August
define("_OFSEPTEMBER","九月");//September
define("_OFOCTOBER","十月");//October
define("_OFNOVEMBER","十一月");//November
define("_OFDECEMBER","十二月");//December
define("_ADDLANGUAGE","新增语言");//Add language
define("_CURRENTLANGUAGES","当前语言");//Current languages
define("_CHANGE","更改");//Change
define("_RETURN","返回");//Return
define("_UPDATESUCCESFULLYMADE","更新成功完成");//The update was completed successfully
define("_LESSONMATERIAL","节材料");//Lesson material
define("_NOQUESTIONSSETFORTHISUNIT","无题目定义");//There are no questions defined
define("_ADDQUESTION","新增测验项目");//Add question
define("_PREVIEW","预览");//Preview
define("_NOTESTSSETFORTHISUNIT","没有测试，发现");//No tests found
define("_ADDTEST","新增测试");//Add test
define("_UNITANDSUBUNITSTESTS","单元和子单元测试");//Unit and subunits tests
define("_NORESULTSFOUND","没有结果发现！");//No results found!
define("_PAGES","页面");//pages
define("_UPLOADFILESANDIMAGES","上传文件和图像");//Upload files and images
define("_COPYFROMANOTHERLESSON","从另一个节复制");//Copy from another lesson
define("_UNITNAME","单元名称");//Unit name
define("_CONTENTTYPE","内容类型");//Content type
define("_CONTENT","内容");//Content
define("_UPDATEUNIT","更新单元");//Update unit
define("_CREATESUBUNIT","创建子单元");//Create subunit
define("_CREATETEST","创建测试");//Create test
define("_ADDPERIOD","添加期");//Add period
define("_LESSONPERIODS","节时期");//Lesson periods
define("_COPY","复制");//Copy
define("_EXCLUDECONSTRAINT","排斥约束");//Exclusion constraint
define("_EXCLUSIONUNIT","排斥单元");//Exclusion unit
define("_FUNCTIONS","职能");//Functions
define("_THETEST","测试");//the test
define("_WITHSCOREATLEAST","比率至少");//with rate at least
define("_NOQUESTIONSTOCORRECTFORTHISLESSON","此节没有待更正问题。");//No questions to correct for this lesson.
define("_QUESTIONSTOCORRECT","待修正问题");//Questions to correct
define("_DELETESELECTED","删除所选");//Delete selected
define("_REDOABLE","测验重复");//Test repetitions
define("_PROFESSORS","教师");//Professors
define("_CANNOTOPENFOLDER","文件夹无法打开");//The folder can&#039;t be opened
define("_CREATEFOLDER","创建文件夹");//Create folder
define("_OPENFOLDER","打开文件夹");//Open folder
define("_CUT","剪切");//Cut
define("_PASTE","粘贴");//Paste
define("_UNDO","撤消");//Undo
define("_REDO","重做");//Redo
define("_FIND","查找");//Find
define("_INSERTHYPERLINK","插入超链接");//Insert hyperlink
define("_INSERTIMAGE","插入图像");//Insert image
define("_NORMAL","正常");//Normal
define("_DEFAULT","默认");//Default
define("_BOLD","粗体");//Bold
define("_ITALIC","斜体");//Italics
define("_UNDERLINED","强调");//Underlined
define("_FONTCOLOR","字体颜色");//Font color
define("_DIMENSIONS","尺寸");//Dimensions
define("_CANCEL","取消");//Cancel
define("_OR","或");//or
define("_LEFT","左边");//Left
define("_RIGHT","右边");//Right
define("_UP","向上");//Up
define("_MIDDLE","中间的");//Middle
define("_DOWN","向下的");//Down
define("_FILE","文件");//File
define("_SELECTTHEONEYOUWANTASLINK","选择一个做为待插入的超链接");//Select the one you want inserted as hyperlink
define("_SELECTTHEONEYOUWANTAS","选择一个您想要插入");//Select the one you want inserted as
define("_SMALLCAPSHYPERLINK","超级链接");//hyperlink
define("_ADD","添加");//Add
define("_NOTE","注意：");//Note
define("_SELECTLESSON","选择节");//Choose lesson
define("_STUDENTS","学生");//Students
define("_ADMINISTRATORS","管理员");//Administrators
define("_LESSONSTATISTICS","节报告");//Lesson reports
define("_FILES","文件");//Files
define("_TOTALSIZE","总大小");//Total size
define("_NEWMESSAGE","新讯息");//New message
define("_PARTICIPATION","参与");//Participation
define("_AVERAGE","平凡");//unremarkable
define("_ACTIVE","激活");//Active
define("_PASSWORDLOST","忘记您的密码?");//Forgot your password?
define("_ANEMAILHASBEENSENT","操作步骤的电子已发送到您邮箱。");//An email with instructions was sent to you.
define("_PASSWORDRECOVERY","恢复您的密码");//Recover your password
define("_THENEWPASSWORDIS","您的新密码是：");//Your new password is: 
define("_EMAILWITHPASSWORDSENT","新密码已通过邮件发送给您。");//An email with your new password was sent to you.
define("_LINEARCONTENT","内容顺序");//Content order
define("_ONEBYONE","显示的问题，一个一个地");//Show questions one by one
define("_NEXTQUESTION","下一个问题");//Next question
define("_IDONOTWANTTODOTHETEST","返回。");//I changed my mind. Please take me back
define("_YOUHAVE","你有");//You have
define("_SENDFILEASANSWER","上传一个文件作为一个答案");//Upload a file as an answer
define("_FILEUPLOADED","上传的文件");//File uploaded
define("_PREVIOUSQUESTION","先前的问题");//Previous question
define("_RESTARTLESSON","节初始化");//Lesson initialization
define("_RESTARTLESSONCOMPLETED","节已经初始化");//The lesson has been initialized
define("_UPLOADFILE","上传文件");//Upload file
define("_PROBLEMUPLOADINGFILE","上传时出现问题。");//There was a problem while uploading file
define("_SHOW","显示");//Show
define("_URL","网址");//URL
define("_TARGET","目标");//Target
define("_NONE","无");//None
define("_OTHER","其它");//Other
define("_TEXTTOP","texttop");//Texttop
define("_ABSMIDDLE","absmiddle");//Absmiddle
define("_ABSBOTTOM","absbottom");//Absbottom
define("_BASELINE","基线");//Baseline
define("_CELLSPACING","单元格间距");//Cell spacing
define("_CELLPADDING","单元格填充");//Cell padding
define("_EM","Em");//Em
define("_WIDTH","宽度");//Width
define("_ALIGN","对齐");//Align
define("_BORDER","边框");//Border
define("_BOTTOM","底部");//Bottom
define("_CSS","CSS");//CSS
define("_CAPTION","标题");//Caption
define("_CENTER","居中");//Center
define("_CHAR","字符");//Char
define("_HEIGHT","高度");//Height
define("_JUSTIFY","理由");//Justify
define("_MARGIN","边距");//Margin
define("_PADDING","填充");//Padding
define("_RULES","规则");//Rules
define("_SUMMARY","摘要");//Summary
define("_TEXTALIGN","文本对齐");//Text align
define("_TOP","顶端");//Top
define("_ENTER","注册");//Login
define("_HASBEENLOGGEDOUT","已注销");//has been logged out
define("_LOGOUT","注销");//Log out
define("_EACHFILESIZEMUSTBESMALLERTHAN","每个文件必须小于");//Each file must be smaller than
define("_DONE","完成");//Done
define("_UPLOADTHESCORMFILEINZIPFORMAT","上传SCORM的文件在ZIP格式");//Upload SCORM file in ZIP format
define("_SCORMEXPORT","导出节为SCORM");//Export lesson to SCORM
define("_SCORMIMPORT","导入SCORM的内容");//Import SCORM content
define("_FORUMPOSTS","论坛讯息");//Forum messages
define("_TOTAL","总");//Total
define("_ALLLESSONS","所有节");//All lessons
define("_STUDENTSOFLESSON","学生节");//Students of lesson
define("_REVIEWSCORMDATA","查看SCORM的数据");//Review SCORM data
define("_IMPORTOFUNIT","导入单元");//Import of unit
define("_SELECTFILE","选择一个文件");//Select a file
define("_THESYSTEMSUGGESTSTHEFILES","该系统的建议文件");//The systems suggests the files
define("_CHECKIFITISASINGLESCO","检查如果是一个单一的上海合作组织");//Check if it is a single SCO
define("_CHOOSESTUDENT","选择一个学生");//Select a student
define("_NOSCORMDATAFOUNDFORTHISSTUDENT","没有SCORM的数据，发现这名学生");//No SCORM data found for this student
define("_ENTRY","进入");//Entry
define("_TOTALTIME","总时间");//Total time
define("_MINSCORE","最低分数");//Minimum score
define("_MAXSCORE","最高评分");//Maximum score
define("_FINALSCORE","最后评分");//Final score
define("_TOCAPITAL","至");//To
define("_NOTEPUBLICROOMSARESTOREDANDACCESSED","注意：公共聊天室的内容将被记录，并且所有用户均可看到");//Note: Conversations in public rooms are recorded and made available to all users
define("_PRIVATEROOM","私人房间");//Private room
define("_ENTEREDROOM","进入房间");//entered the room
define("_LEFTTHEROOM","离开房间");//left the room
define("_WRONGROOMID","错误的房间编号");//Wrong room id
define("_EXITCHAT","退出聊天");//Exit chat
define("_ADJUSTTOPAGE","调整页");//Adjust to page
define("_CREATEPUBLICROOM","创造公共空间");//Create public room
define("_CREATEPRIVATEROOM","创建私人房间");//Create private room
define("_OPENROOMS","开放室");//Open rooms
define("_NEWPUBLICROOM","新的公共空间");//New public room
define("_NEWPRIVATEROOM","新的私人房间");//New private room
define("_SHOWPASTCOVERSATIONS","查看过去的谈话");//Show past conversations
define("_PUBLICROOMS","公共聊天室");//Public rooms
define("_PRIVATEROOMS","单人房");//Private rooms
define("_PARTICIPANTS","与会者");//participants
define("_NOROOMSFOUND","没有客房发现");//No rooms found
define("_DEACTIVATE","停用");//Deactivate
define("_ACTIVATE","激活");//Activate
define("_SYSTEMMESSAGE","系统讯息");//System message
define("_ROOMALREADYEXISTS","同名房间已存在");//A room with this name already exists
define("_ROOMNAME","客房名称");//Room name
define("_ACTIVENEUTRAL","激活");//Active
define("_SHOWCONVERSATIONSFORROOM","显示会话为室");//Show conversations for the room
define("_NOMESSAGESFOUNDFORTHISINTERVAL","无会话，发现在这个房间为指定的时间间隔");//No conversations found in this room for the specified interval
define("_MESSAGE","讯息");//Message
define("_FILESIZE","文件大小");//File size
define("_ILLEGALFILENAME","非法文件名");//Illegal file name
define("_IRREVERSIBLEACTIONAREYOUSURE","此操作是不可逆转的！您是否确定?");//This operation is irreversible! Are you sure?
define("_FILENAME","文件名称");//File name
define("_SUCCESFULLYDELETEDFILE","成功删除文件");//Successfully deleted file
define("_TAKEBACKUP","备份！");//Backup!
define("_SUCCESFULLYBACKEDUP","备份成功地完成了");//Backup successfully completed
define("_NONEXISTINGMAIL","此电子邮件，并不属于任何用户");//This email/login does not belong to any user
define("_PORT","服务器端口");//Server port
define("_DATABASE","数据库名称");//Database name
define("_ACTIVATELDAP","启动LDAP支持");//Activate LDAP support
define("_LDAPSERVER","LDAP服务器");//LDAP server
define("_LDAPBINDDN","LDAP的绑定的DN");//LDAP bind DN
define("_LDAPPASSWORD","LDAP的绑定密码");//LDAP bind password
define("_SUPPORTONLYLDAP","只支持LDAP的注册");//Support only LDAP registration
define("_LOGINATTRIBUTE","登入名称属性");//Login name attribute
define("_LDAPCOMMONNAME","全称属性");//Full name attribute
define("_LDAPADDRESS","地址属性");//Address attribute
define("_LDAPLOCALITY","城市属性");//City attribute
define("_LDAPTELEPHONENUMBER","电话号码属性");//Phone number attribute
define("_LDAPMAIL","电子邮件属性");//Email attribute
define("_LDAPLANGUAGE","语言属性");//Language attribute
define("_CHECKSETTINGS","检查设置");//Check settings
define("_LDAPPORT","LDAP服务器港口");//LDAP server port
define("_USESSL","使用SSL联机");//Use SSL connection
define("_CANNOTCONNECTLDAPSERVER","该系统是无法连接到LDAP服务器");//The system was unable to connect to LDAP server
define("_CANNOTBINDLDAPSERVER","系统无法绑定到LDAP服务器");//The system was unable to bind to LDAP server
define("_LDAPCONFIGURATION","LDAP的配置");//LDAP configuration
define("_LDAPBASEDN","LDAP的基本DN");//LDAP Base DN
define("_YOUHAVEALREADYCORRECTEDTHISQUESTION","你已经纠正了这一问题");//You have already corrected this question
define("_SHOWALL","显示所有");//Show all
define("_TOTALLOGINS","总系统登录");//Total system logins
define("_ALLOWEDIPS","允许的IPS");//Allowed IPs
define("_COMMASEPARATEDLISTASTERISKEXAMPLE","以逗号分隔的列表中。星号*是不允许的。例如： 192.168.0 .* ， 192.168.1.1 ， 192.168.1.100");//Comma separated list. The asterisk * is allowed. Example: 192.168.0.*, 192.168.1.1, 192.168.1.100
define("_DISALLOWEDIPS","不允许的IPS");//Disallowed IPs
define("_ALLOWEDEXTENSIONS","允许文件扩展名");//Allowed file extensions
define("_DISALLOWEDEXTENSIONS","不允许的文件扩展名");//Disallowed file extensions
define("_COMMASEPARATEDLISTASTERISKEXTENSIONEXAMPLE","以逗号分隔的列表中。例如： PHP中， js ，压缩EXE的CGI");//Comma separated list. Example: php, js, exe, cgi
define("_DENIALTAKESPRECEDENCE","拒绝的先导许可。如果这两个领域都留空，然后一切都让");//Denial precedes permission. If both fields are left blank, then everything is allowed
define("_EFRONT","eFront");//eFront
define("_CONTACTUS","联系我们");//Contact us
define("_EFRONTLOGIN","登录到eFront");//Login to eFront
define("_LDAPPROTOCOLVERSION","LDAP协议版本");//LDAP Protocol Version
define("_GOTOINBOX","去收件箱");//Go to inbox
define("_RECENTCOMMENTS","最新评论");//Last comments
define("_CONTROLPANEL","控制面板");//Control panel
define("_YOUCANNOTCREATETHISFOLDER","你不能建立这样一个文件夹");//You cannot create such a folder
define("_INVALIDID","无效的编号");//Invalid id
define("_UNPRIVILEGEDATTEMPT","你没有权限执行这个动作");//You do not have the priviledges to perform this action
define("_INVALIDLOGIN","无效的登录名");//Invalid login name
define("_DOWNLOADLANGUAGEFILE","下载语言文件");//Download language file
define("_SOMEPROBLEMOCCURED","出错");//Some problem occured
define("_ALTERNATIVELYCOPYANDPASTEBROWSER","另外，您也可以链接复制并粘贴在您的浏览器的地址栏");//Alternatively, you may copy the link and paste it in your browser&#039;s address field
define("_YOUCANNOTACCESSTHISFOLDER","您没有访问此文件夹");//You do not have access to this folder
define("_YOUCANNOTDELETETHISFILE","您不能删除此文件");//You cannot delete this file
define("_TRIEDTODELETE","试图删除文件");//Tried to delete file
define("_ACTION","行动");//Action
define("_NOTES","债券");//Notes
define("_SENDFILES","传送文件");//Send files
define("_YOUCANNOTUPLOADFILESWITHTHISEXTENSION","你不能上传文件与此扩展");//You cannot upload files with this extension
define("_YOUMAYONLYUPLOADFILESWITHEXTENSION","你只可以上传文件与扩展");//You may only upload files with extension
define("_COULDNOTCREATEFOLDER","无法创建文件夹。请检查文件夹名称和该文件夹不存在");//Could not create folder. Please check the folder name and that the folder does not already exist
define("_REGISTERANEWACCOUNT","新的用户账户");//New user account
define("_REC","建议");//rec
define("_SUCESSFULLYCONNECTEDTOLDAPSERVER","成功连接到LDAP服务器");//Successfully connected to LDAP server
define("_DIRECTIONDELETED","类别删除");//Category deleted
define("_NOANNOUNCEMENTSPOSTED","没有张贴公告，为这个节");//No announcements posted for this lesson
define("_NONEWFORUMMESSAGES","没有论坛的邮件就这个节");//No forum messages regarding this lesson
define("_NONEWPERSONALMESSAGES","没有新的个人信息在您的收件箱");//No new personal messages in your inbox
define("_NONEWCOMMENTS","没有新的评论");//No new comments
define("_NOMATERIALINTHISLESSON","的节，目前是空的");//The lesson is currently empty
define("_NOSOLVEDTESTSFOUND","没有解决测试");//No solved tests
define("_NORELATEDPOSTSFOUND","没有职位，与此有关的单元。");//No posts relevant to this unit.
define("_SUCCESSFULLYCREATEDLESSON","节是成功创建");//The lesson was created successfully
define("_SORRYNEEDIFRAME","对不起，您需要iframe支持使用聊天室");//Sorry, you need iframe support to use the Chat
define("_TOPICSUBJECT","主题的主旨");//Topic subject
define("_SEARCHRESULTS","搜索结果");//Search results
define("_NORESULTSFOUNDINPERSONALMESSAGES","在个人信息中未找到结果");//No results found in personal messages
define("_SEARCHRESULTSINPERSONALMESSAGES","在个人信息在检索");//Search results in personal messages
define("_SEARCHRESULTSINCOURSES","搜索结果在课程");//Search results in courses
define("_MESSAGEFOLDER","消息文件夹");//Message folder
define("_EMAIL","电子邮件");//e-mail
define("_RESETPASSWORD","重设密码");//Reset password
define("_JOINED","加入");//Joined
define("_MOREINFO","更多信息");//More info
define("_AVERAGESCORE","平均分数");//Average score
define("_CHATMESSAGES","聊天讯息");//Chat messages
define("_MONTHLOGINS","上个月登录");//Logins last month
define("_WEEKLOGINS","上周登录");//Logins last week
define("_MEANDURATION","意味着会议时间");//Mean session duration
define("_MONTHMEANDURATION","意味着会议的时间上个月");//Mean session duration last month
define("_WEEKMEANDURATION","意味着会议的时间上星期");//Mean session duration last week
define("_MONTH","一个月");//Month
define("_WEEK","周");//Week
define("_PRICE","价格");//Price
define("_DURATION","会议时间");//Session duration
define("_MAINTENANCE","维修");//Maintenance
define("_FORUMLASTMESSAGE","最近一则留言，在论坛");//Last message in forum
define("_MESSAGESFOLDERS","个人邮件文件夹");//Personal messages folders
define("_FOLDERS","文件夹");//Folders
define("_CHATLASTMESSAGE","最近一则留言，在聊天室");//Last message in chat
define("_INFO","信息");//Information
define("_LASTPOST","最后发表的帖子");//Last post
define("_TOTALQUESTIONS","总的问题");//Total questions
define("_DEVELOPMENT","发展");//Development
define("_MULTIPLEONE","多种选择-单一的正确答案");//Multiple choices - Single correct answer
define("_MULTIPLEMANY","多种选择-许多正确的答案");//Multiple choices - Many correct answers
define("_MATCH","比赛");//Match
define("_EMPTYSPACES","空白");//Empty spaces
define("_LOWDIFFICULTY","低难度");//Low difficulty
define("_MEDIUMDIFFICULTY","中等难度");//Medium difficulty
define("_HIGHDIFFICULTY","高困难");//High difficulty
define("_CATEGORIES","类别");//Categories
define("_OVERALL","全部的");//Overall
define("_BACKTOTOP","回到顶部");//Back to top
define("_STATISTICSFORLESSON","节报告");//Reports for lesson
define("_GENERALLESSONINFO","一般的节信息");//General lesson information
define("_LESSONPARTICIPATIONINFO","的节，参与信息");//Lesson participation information
define("_LESSONCONTENTINFO","课的内容信息");//Lesson content information
define("_TESTINFO","测试信息");//Test information
define("_QUESTIONINFO","问题信息");//Question information
define("_VIEWTEST","查看测试");//View test
define("_SYSTEMSTATISTICS","系统报告");//System reports
define("_ORDER","命令");//Order
define("_TEST","测试");//Test
define("_TOPICSUCCESFULLYCREATED","成功创建");//The topic was created successfully
define("_SUCCESFULLYPOSTEDMESSAGE","您的留言已发布成功");//Your message was posted successfully
define("_SUCCESFULLYUPDATEDTOPIC","该专题已成功更新");//The topic was updated successfully
define("_SUCCESFULLYUPDATEDMESSAGE","您的留言已成功更新");//Your message was updated successfully
define("_INVISIBLE","隐藏");//Invisible
define("_LOCKED","锁定");//Locked
define("_PUBLIC","市民");//Public
define("_PREVIEWMESSAGE","预览邮件");//Preview message
define("_BODY","身体");//Body
define("_ATTACHMENT","附件");//Attachment
define("_RECENTMESSAGESATFORUM","最近一则留言");//Last messages at Forum
define("_RECENTUNREADPERSONALMESSAGES","最近未读个人信息");//Recent unread personal messages
define("_NOCONTENTAVAILABLE","本单元的内容类型目前无法使用");//No units of this content-type currently available
define("_THEREWASAPROBLEMDELETETINGFILEWINDOWCLOSE5SECONDS","删除文件出错。该窗口会自动关闭在5秒内");//A problem occured during the file deletion. This window will close automatically in 5 seconds
define("_TRIEDTOCREATEFOLDER","试图创建文件夹：");//Tried to create folder:
define("_COULDNOTCREATEFOLDERWINDOWCLOSE5SECONDS","文件夹无法建立。该窗口会自动关闭在5秒内");//The folder could not be created. This window will close automatically in 5 seconds
define("_INVALIDNAME","无效的名称");//Invalid name
define("_THISFOLDERCONTAINS","此文件夹包含");//This folder contains
define("_TOPICS","话题");//Topics
define("_FILEDOESNOTEXIST","文件不存在");//File does not exist
define("_ADDLINK","添加链接");//Add link
define("_CONTENTUNITS","内容单元");//Content units
define("_MAINPAGE","主页");//Main page
define("_PLEASEGIVEYOURLOGINOREMAIL","请您给您的登录名或电子邮件");//Please give your login or email
define("_LESSONSETTINGS","节设置");//Administration
define("_ADMINISTRATOR","管理员");//Administrator
define("_PROGRESS","教师");//Progress
define("_IMAGEFILE","图像文件");//Image file
define("_SETAVATAR","化身");//Set avatar
define("_CURRENTAVATAR","目前的化身");//Current avatar
define("_DELETECURRENTAVATAR","删除当前的化身");//Delete current avatar
define("_ONLYIMAGEFILESAREVALID","只有图片文件都是有效的。请选择一个图像文件。");//Only image files are valid. Please select an image file.
define("_VIEWLIST","检视清单");//View list
define("_SUCCESFULLYSETAVATAR","新化身设置成功");//New avatar is successfully set
define("_TOPICDELETEDSUCCESSFULLY","话题已成功删除");//Topic deleted successfully
define("_MESSAGEDELETEDSUCCESSFULLY","信息已成功删除");//Message deleted successfully
define("_POSTS","post");//Posts
define("_BY","通过");//by
define("_NEWCATEGORY","新的类别");//New category
define("_FORUMCONFIGURATIONPANEL","论坛配置小组");//Forum configuration panel
define("_VIEWS","意见");//Views
define("_STICKY","手杖");//Sticky
define("_NOTOPICSFOUND","没有主题发现");//No topics found
define("_NEWTOPIC","新话题");//New topic
define("_POSTEDBY","张贴");//Posted by
define("_ON","在");//on
define("_INREPLYTO","在答复");//in reply to
define("_REPLYWITHQUOTE","引帖回复");//Reply with quote
define("_QUOTE","引用");//quote
define("_REPLY","回复");//Reply
define("_AREYOUSUREYOUWNATTODELETEMESSAGE","您确定要删除邮件");//Are you sure you want to delete message
define("_EDIT","编辑");//Edit
define("_STATUS","身份");//Status
define("_NOMESSAGESFOUND","没有邮件");//No messages found
define("_GOTOCHATROOMSLIST","去聊天室名单");//Go to chat rooms list
define("_ROOM","房间");//Room
define("_INVITE","邀请");//Invite
define("_INVITESYOUCLICKLINK","约请您去会谈，请点击链接转到聊天室。");//invites you to a chat session. Click the link below to be taken to the chat room.
define("_GOTOCHATROOM","去聊天室");//Go to chat room
define("_CHATINVITATION","聊天邀请");//Chat invitation
define("_NEWCONTENT","新的内容");//New content
define("_NONEWCONTENT","没有新的内容");//No new content
define("_TEMPLATE","范本");//Template
define("_APPLY","应用");//Apply
define("_PRIVATECONVERSATIONWITH","私人谈话");//Private conversation with
define("_TORESPOND","回应...");//to respond...
define("_TOAPRIVATECONVERSATION","以私人谈话");//to a private conversation
define("_INVITESYOUTOPRIVATECONVERSATION","邀请您私人密谈");//is inviting you to a private conversation
define("_DOYOU","你");//Do you
define("_QUESTIONMARK","?");//?
define("_CONVERSATIONINVITATIONACCEPTED","您的请求被接受");//The conversation invitation was accepted
define("_CONVERSATIONINVITATIONDENIED","该会话的邀请被拒绝");//The conversation invitation was denied
define("_YOUACCEPT","接受");//accept
define("_YOUDENY","拒绝");//deny
define("_THEMAILCOULDNOTBESENDTRYLATER","该电子邮件无法传送。请稍后再试，或联系系统管理员");//The email could not be send. Please try again later or contact the system administrator
define("_AUTOMATEDEMAILSENTFROM","自动电子邮件发送地址：");//Automated email sent from address:
define("_CLIKCINGONTHELINKWILLCONFIRM","点击链接，将确认您的电子邮件地址是有效的，所以一个新的密码，可以发送给您。");//Clicking on the link will confirm that your email address is valid so a new password can be sent to you.
define("_FORFURTHERCONTACTADMINAT","如需进一步数据，您可以联络系统管理员，在");//For further information, you may contact the system administrator, at
define("_KINDREGARDSEFRONT","的亲切问候， eFront系统");//Kind regards, eFront system
define("_THISISANAUTOMATEDEMAILSENTFROM","这是一个自动发送的电子邮件从");//This is an automated email sent from
define("_BECAUSEYOUASKEDTORECOVERPASSWORD","因为你问到要恢复您的密码。");//because you asked to recover your password.
define("_PLEASECLICKTHECONFIRMATIONLINKBELOW","请确认下面的链接：");//Please click the confirmation link below:
define("_WITHTHENEWPASSWORD","与您的新eFront账户密码。");//with your new eFront account password.
define("_REGISTRATIONEMAIL","注册电子邮件");//Registration email
define("_CURRENCYSYMBOL","&euro;");//&euro;
define("_ELEARNINGPLATFORM","网络学习平台");//eLearning platform
define("_ACCOUNTACTIVATEDWITHPERSONALINFORMATION","您的账户已成功创建与以下个人资料：");//Your account was successfully created with the following personal information:
define("_YOUHAVEAPPLIEDFORTHELESSONS","您已申请参加以下节：");//You have applied to attend the following lessons:
define("_YOUMAYSTARTUSINGFREEIMMEDIATELYBUTNOTNONFREE","您可以直接加入免费的节。如果您的选择的节中含有收费内容");//You may start attending lessons that are free immediately. If your selection includes lessons that are not free, the administrator must apply your selection before using them.
define("_YOUMAYALTERPERSONALINFORMATIONFROMSETTINGS","所有您的个人信息，包括节选择，已经提交，以后您可在个人设置页面中修改这些内容。");//All the personal info you have submitted, as well as your lessons selection, may be altered at any time from your personal settings page.
define("_YOUMAYLOGINIMMEDIATELY","您可以登录并开始使用该系统");//You may login and start using the system immediately
define("_YOUMAYLOGINWHENADMINACTIVATESYOU","你可以开始使用该系统尽快管理员激活您的账户");//You may start using the system as soon as the administrator activates your account
define("_EMAILSENTFROM","发送的电子邮件从");//Email sent from
define("_STUDENTSOFLESSONSMALL","学生的节");//students of lesson
define("_DIRECTIONDEACTIVATED","类别停用");//Category deactivated
define("_DIRECTIONACTIVATED","类激活");//Category activated
define("_LESSONUPDATED","节更新");//Lesson updated
define("_LESSONDEACTIVATED","节停用");//Lesson deactivated
define("_LESSONACTIVATED","节启动");//Lesson activated
define("_VIEWALL","查看所有");//View all
define("_FILESANDSUBFOLDERS","文件和子文件夹");//files and subfolders
define("_ATTACHMENTS","附加的");//Attachments
define("_PROBLEMQUERYINGDATABASE","问题查询数据库");//Problem querying database
define("_FIRSTNAME","名字");//First name
define("_LASTNAME","姓氏");//Last name
define("_LESSONSTATUS","节地位");//Lesson status
define("_SPACEUSAGE","空间使用");//Space usage
define("_NEWFOLDER","新文件夹");//New folder
define("_VIEWFOLDERSTATISTICS","查看文件夹统计");//View folder statistics
define("_VIEWMESSAGE","检视邮件");//View message
define("_OFTOTAL","总");//of total
define("_KBYTESUSED","Kbyte的使用");//Kbytes used
define("_MARK","标记");//Mark
define("_WITHSELECTED","与选定");//With selected
define("_MARKASREAD","标记&nbsp;as&nbsp;阅读");//Mark&nbsp;as&nbsp;read
define("_MARKASUNREAD","标记&nbsp;as&nbsp;未读");//Mark&nbsp;as&nbsp;unread
define("_MOVETOFOLDER","移至文件夹");//Move to folder
define("_MOVE","移动");//Move
define("_PERSONALMESSAGE","个人讯息");//Personal message
define("_FROM2","来自：");//From:
define("_TO2","到：");//To:
define("_SUBJECT2","主题：");//Subject:
define("_BECAUSEYOURMESSAGEBOXISFULL","因为您的消息空间已满");//because your message box is full
define("_YOURMESSAGETO","您的邮件");//Your message to
define("_COULDNOTBEDELIVERED","无法交付");//could not be delivered
define("_BECAUSEHISMESSAGEBOXISFULL","因为他的消息已满");//because his message box is full
define("_THEMESSAGE","讯息");//Message
define("_MESSAGEWASSENT","发送邮件");//Message was sent 
define("_INVALIDFOLDERNAME","无效文件夹名称");//Invalid folder name
define("_SORRYYOUCANNOTCREATEANYMOREFOLDERS","抱歉，你不能创造任何其它文件夹");//Sorry but you cannot create any other folders
define("_FOLDERWITHSAMENAMEALREADYEXISTS","一个文件夹具有相同名称已经存在");//A folder with the same name already exists
define("_FOLDERCREATED","建立的数据夹");//Folder created
define("_FOLDERUPDATED","文件夹更新");//Folder updated
define("_FOLDERDELETED","文件夹删除");//Folder deleted
define("_NEWFOLDERNAME","新的数据夹名称");//New folder name
define("_THISFOLDERDOESNOTEXIT","这个文件夹不存在");//This folder does not exist
define("_MODIFY","更改");//Modify
define("_FOLDER","文件夹");//Folder
define("_SIZE","大小");//Size
define("_YOUMUSTSPECIFYANACTION","您必须指定一个行动");//You must specify an action
define("_ALLOWHTMLFPM","允许的HTML在论坛和个人信息");//Allow HTML in Forum and Personal messages
define("_ACTIVATEPOLLS","激活调查");//Activate polls
define("_ALLOWATTACHMENTSINF","允许附件在论坛");//Allow attachments in forum
define("_PMQUOTA","个人信息配额");//Personal messages quota
define("_PMATTACHMENTSQUOTA","个人邮件的附件配额");//Personal messages attachments quota
define("_YOUMUSTSELECTMESSAGESTODELETE","您必须选择要删除的邮件");//You must select messages to delete
define("_YOUMUSTSELECTMESSAGESTOMOVE","您必须选择邮件动议");//You must select messages to move
define("_YOUMUSTSELECTMESSAGESTOMARK","您必须选择讯息给标记");//You must select messages to mark
define("_SUCCESSFULLYDELETEDMESSAGES","邮件被成功删除");//Messages were successfully deleted
define("_AREYOUSURETODELETEFOLDER","您确定要删除的文件夹");//Are you sure you want to delete folder
define("_ANDALLCONTENTS","和所有其组成部分?");//and all its components?
define("_APPROACHINGMESSAGEQUOTA","您已接近您的邮件配额。");//You are approaching your message quota.
define("_DELETEOLDMESSAGES","请删除所有旧邮件，以节省空间。");//Please delete any old messages to save space.
define("_MESSAGEBOXSIZECRITICAL","您的邮件空间大小是至关重要的。");//Your messages box size is critical.
define("_ERASEMESSAGESNOTRECEIVENEW","如果您不清除任何讯息，您将无法获得新讯息。");//If you don&#039;t erase any messages, you will not be able to receive new ones.
define("_NOMESSAGESINFOLDER","没有邮件在此文件夹中");//No messages in this folder
define("_AREYOUSURETODELETEMESSAGE","您确定要删除此讯息?");//Are you sure you want to delete this message?
define("_TRIEDACCESSMESSAGEMALFORMEDID","试图访问的讯息，畸形编号");//Tried to access messages with malformed id
define("_THISMESSAGEDOESNOTEXIST","此消息是不存在的");//This message does not exist
define("_RETURNFOLDERSLIST","返回到文件夹列表");//Return to folders list
define("_TOFORUM","至");//To
define("_RE","关于");//Re
define("_INCOMING","传入");//Incoming
define("_SENT","已发送");//Sent
define("_DRAFTS","草稿");//Drafts
define("_CALENDAR","日历");//Calendar
define("_JANUARY","一月");//January
define("_FEBRUARY","二月");//February
define("_MARCH","三月");//March
define("_APRIL","四月");//April
define("_MAY","可能");//May
define("_JUNE","六月");//June
define("_JULY","七月");//July
define("_AUGUST","八月");//August
define("_SEPTEMBER","九月");//September
define("_OCTOBER","十月");//October
define("_NOVEMBER","十一月");//November
define("_DECEMBER","十二月");//December
define("_MON","米");//M
define("_TUE","吨");//T
define("_WED","瓦特");//W
define("_THU","吨");//T
define("_FRI","f");//F
define("_SAT","s");//S
define("_SUN","s");//S
define("_VALUE","价值");//Value
define("_PERSONALDATACHANGESUCCESSADMIN","个人信息已成功变更");//User&#039;s personal info have been successfully altered
define("_CONTINUE","继续");//Continue
define("_WEB","个人网页");//Personal page
define("_DATA","数据");//Data
define("_USERNAMEERROR","请输入显示名称！");//Please enter the a display name!
define("_CVERROR","请填写在一些关于您的信息！");//Please fill in some information about you!
define("_NUM","单元票数量");//Ticker number
define("_SCORM","SCORM的");//SCORM
define("_MYSETTINGS","我的设置");//my Settings
define("_MYLESSONS","我的节");//my Lessons
define("_MYOPTIONS","我的选择");//my Options
define("_YOUHAVENOBOOKMARKS","你有没有书签");//You have no bookmarks
define("_ADDCONTENT","新增内容");//Add content
define("_NEWMESSAGES","新邮件");//New messages
define("_DOYOUWANTTOADDTHISPAGETOYOURBOOKMARKS","你要添加此页到您的书签吗?");//Do you want to add this page to your bookmarks?
define("_BOOKMARKS","书签");//Bookmarks
define("_SHOWBOOKMARKS","显示书签");//Show bookmarks
define("_ADDTHISPAGETOYOURBOOKMARKS","将此网页添加到您的书签");//Add this page to your bookmarks
define("_YOUCANDOTEST","你可以做的测试");//You can do test
define("_TIMESMORE","额外");//times more
define("_FIELDNAME","字段名称");//Field name
define("_FIELDDESCRIPTION","实地描述");//Field description
define("_DBTYPE","数据库类型");//Database type
define("_ADDFIELD","添加字段");//Add field
define("_TREESAVEDSUCCESSFULLY","树保存succefully");//Tree saved succefully
define("_ERROROCCURED","发生一个错误。请再试一次。");//An error occured. Please try again.
define("_EXPORTSTATS","导出报告：");//Export reports:
define("_MATHTYPEHELP1","您可以插入数学表达式在编辑器中使用特殊代码，其中tranlates一个ASCII的数学符号，以数学表达式。 eFront已建成编辑这个特别的代码。因此，用户可以方便地添加数学类型。您可以从下面的表格了解此代码，或从<a target=\"_blank\" href=\"http://www1.chapman.edu/~jipsen/mathml/asciimath.html\">这个网页</a>");//You can insert math expressions in the editor by using a special code which tranlates an ASCII math notation to mathematic expressions. eFront has built into editor this special code. So users can easily add math types. You can learn about this code from the table below or from <a target=\"_blank\" href=\"http://www1.chapman.edu/~jipsen/mathml/asciimath.html\">this page</a>
define("_MATHTYPEHELP2","<p>你应该避免使用 \ 象征，因为它代表着特殊字符为编码。在情况下，您要使用它");//<p>You should  avoid to use symbol \` because it represents a special character for the encoding. In case you want to use it, use escape character \ before it, e.g. \\\`</p>
define("_PERCENTCORRECT","％正确的");//percent correct
define("_GLOSSARY","词汇");//Glossary
define("_ADDDEFINITION","新增的定义");//Add definition
define("_SUCCESFULLYADDEDDEFINITION","的定义是添加成功");//The definition was added successfully
define("_DEFINITION","定义");//Definition
define("_NODEFINITIONSFOUNDFORTHISLESSON","没有定义，发现这个节");//No definitions found for this lesson
define("_CHOOSEWHATTOEXPORT","选择什么导出（除内容）");//Choose what to export (apart from content)
define("_CREATED","创建");//Created
define("_CANCELTEST","取消测试");//Cancel test
define("_DELETEEXISTINGDATAFROM","删除现有的数据：");//Delete existing data from:
define("_CLOSE","关闭");//Close
define("_SHOWHIDE","显示/隐藏");//Show/Hide
define("_EFRONTLOGO","eFront标志");//eFront logo
define("_READ","阅读");//Read
define("_UNREAD","未读");//Unread
define("_SUCCESFULLYADDEDROOM","成功加入室");//Succesfully added room
define("_AND","和");//and
define("_TRUEFALSE","真/假");//True/False
define("_DROPDOWN","从列表中选择");//Select from list
define("_TRUE","正确的");//True
define("_FALSE","虚假");//False
define("_QUESTIONNUMBER","问题数目");//Question number
define("_QUESTIONTITLE","问题标题");//Question title
define("_NUMBEROFOPTIONS","多项选择");//Number of options
define("_YOUHAVELOGGEDOUTBECAUSEYOURSESSIONHASTIMEDOUT","您已注销，因为您的会话已超时");//You have logged out because your session has timed out
define("_ORSELECTONEFROMLIST","或选择其中一个，从名单");//Or select one from list
define("_EXPLANATION","解释");//Explanation
define("_QUESTION","问题");//Question
define("_CHANGESTYLE","改变主题");//Change theme
define("_PREDEFINED","预定义");//Predefined
define("_SELECTNEWSTYLE","选择新的主题");//Select new theme
define("_SETSTYLE","设定主题");//Set theme
define("_NOPREVIEWIMAGEFOUND","预览图像没有发现");//Preview image not found
define("_EDITOR_BOLD_DESC","粗体（按Ctrl +B）");//Bold (Ctrl+B)
define("_EDITOR_ITALIC_DESC","斜体（按Ctrl +I）");//Italic (Ctrl+I)
define("_EDITOR_UNDERLINE_DESC","下划线（ Ctrl + U）");//Underline (Ctrl+U)
define("_EDITOR_STRIKETROUGH_DESC","删除线");//Strikethrough
define("_EDITOR_JUSTIFYLEFT_DESC","左对齐");//Align left
define("_EDITOR_JUSTIFYCENTER_DESC","居中对齐");//Align center
define("_EDITOR_JUSTIFYRIGHT_DESC","右对齐");//Align right
define("_EDITOR_JUSTIFYFULL_DESC","对齐");//Align full
define("_EDITOR_BULLIST_DESC","无序清单");//Unordered list
define("_EDITOR_NUMLIST_DESC","下令名单");//Ordered list
define("_EDITOR_OUTDENT_DESC","outdent");//Outdent
define("_EDITOR_INDENT_DESC","缩进");//Indent
define("_EDITOR_UNDO_DESC","撤消（按Ctrl + Z ）的");//Undo (Ctrl+Z)
define("_EDITOR_REDO_DESC","重做（按Ctrl + y ）的");//Redo (Ctrl+Y)
define("_EDITOR_LINK_DESC","插入/编辑链接");//Insert/edit link
define("_EDITOR_UNLINK_DESC","断开");//Unlink
define("_EDITOR_IMAGE_DESC","插入/编辑图像");//Insert/edit image
define("_EDITOR_CLEANUP_DESC","清理混乱的代码");//Cleanup messy code
define("_EDITOR_FOCUS_ALERT","1编辑器，例如必须集中，才能使用此命令。");//A editor instance must be focused before using this command.
define("_EDITOR_EDIT_CONFIRM","你是否想使用所见即所得的模式，这个文本?");//Do you want to use the WYSIWYG mode for this textarea?
define("_EDITOR_INSERT_LINK_TITLE","插入/编辑链接");//Insert/edit link
define("_EDITOR_INSERT","插入");//Insert
define("_EDITOR_UPDATE","更新");//Update
define("_EDITOR_CANCEL","取消");//Cancel
define("_EDITOR_INSERT_LINK_URL","链接网址");//Link URL
define("_EDITOR_INSERT_LINK_TARGET","目标");//Target
define("_EDITOR_INSERT_LINK_TARGET_SAME","打开链接在同一个窗口");//Open link in the same window
define("_EDITOR_INSERT_LINK_TARGET_BLANK","打开链接在一个新窗口");//Open link in a new window
define("_EDITOR_INSERT_IMAGE_TITLE","插入/编辑图像");//Insert/edit image
define("_EDITOR_INSERT_IMAGE_SRC","图片URL");//Image URL
define("_EDITOR_INSERT_IMAGE_ALT","图片说明");//Image description
define("_EDITOR_HELP_DESC","帮助");//Help
define("_EDITOR_BOLD_IMG","bold.gif");//bold.gif
define("_EDITOR_ITALIC_IMG","italic.gif");//italic.gif
define("_EDITOR_UNDERLINE_IMG","underline.gif");//underline.gif
define("_EDITOR_CLIPBOARD_MSG","复制/削减/粘贴是不具备的Mozilla和Firefox 。你想了解更多信息有关此问题的呢?");//Copy/Cut/Paste is not available in Mozilla and Firefox.Do you want more information about this issue?
define("_EDITOR_POPUP_BLOCKED","很抱歉，您的浏览器禁止弱出窗口 ");//Sorry, but we have noticed that your popup-blocker has disabled a window that provides application functionality. You will need to disable popup blocking on this site in order to fully utilize this tool.
define("_EDITOR_JAVA_TITLE","插入/编辑的Java");//Insert / edit Java
define("_EDITOR_JAVA_DESC","插入/编辑的Java");//Insert / edit Java
define("_EDITOR_JAVA_FILE","Java的文件（ 。阶级）");//Java-File (.class)
define("_EDITOR_JAVA_SIZE","大小");//Size
define("_EDITOR_JAVA_LIST","java文件");//Java files
define("_EDITOR_JAVA_PROPS","Java的性能");//Java properties
define("_EDITOR_JAVA_GENERAL","一般");//General
define("_EDITOR_JAVA_CODEBASE","的CODEBASE");//Codebase
define("_EDITOR_ADVHR_INSERT_ADVHR_DESC","horizontale规则");//Horizontale rule
define("_EDITOR_ADVHR_INSERT_ADVHR_WIDTH","宽度");//Width
define("_EDITOR_ADVHR_INSERT_ADVHR_SIZE","高度");//Height
define("_EDITOR_ADVHR_INSERT_ADVHR_NOSHADE","没有影子");//No shadow
define("_EDITOR_ADVIMAGE_TAB_GENERAL","一般");//General
define("_EDITOR_ADVIMAGE_TAB_APPEARANCE","外观");//Appearance
define("_EDITOR_ADVIMAGE_TAB_ADVANCED","先进");//Advanced
define("_EDITOR_ADVIMAGE_GENERAL","一般");//General
define("_EDITOR_ADVIMAGE_TITLE","标题");//Title
define("_EDITOR_ADVIMAGE_PREVIEW","预览");//Preview
define("_EDITOR_ADVIMAGE_CONSTRAIN_PROPORTIONS","制约比例");//Constrain proportions
define("_EDITOR_ADVIMAGE_LANGDIR","语言方向");//Language direction
define("_EDITOR_ADVIMAGE_LANGCODE","语言代码");//Language code
define("_EDITOR_ADVIMAGE_LONG_DESC","长期描述链接");//Long description link
define("_EDITOR_ADVIMAGE_STYLE","作风");//Style
define("_EDITOR_ADVIMAGE_CLASSES","班");//Classes
define("_EDITOR_ADVIMAGE_LTR","左向右");//Left to right
define("_EDITOR_ADVIMAGE_RTL","从右至左");//Right to left
define("_EDITOR_ADVIMAGE_ID","编号");//Id
define("_EDITOR_ADVIMAGE_IMAGE_MAP","影像地图");//Image map
define("_EDITOR_ADVIMAGE_SWAP_IMAGE","掉期的形象");//Swap image
define("_EDITOR_ADVIMAGE_ALT_IMAGE","另类形象");//Alternative image
define("_EDITOR_ADVIMAGE_MOUSEOVER","鼠标移过");//for mouse over
define("_EDITOR_ADVIMAGE_MOUSEOUT","鼠标移出");//for mouse out
define("_EDITOR_ADVIMAGE_MISC","杂项");//Miscellaneous
define("_EDITOR_ADVIMAGE_EXAMPLE_IMG","外观预览图像");//Appearance&nbsp;preview&nbsp;image
define("_EDITOR_ADVIMAGE_MISSING_ALT","您确定要继续操作而不包括图像描述? ");//Are you sure you want to continue without including an Image description? Without  it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.
define("_EDITOR_ADVLINK_GENERAL_TAB","一般");//General
define("_EDITOR_ADVLINK_POPUP_TAB","弹出");//Popup
define("_EDITOR_ADVLINK_ADVANCED_TAB","先进");//Advanced
define("_EDITOR_ADVLINK_GENERAL_PROPS","一般性质");//General properties
define("_EDITOR_ADVLINK_POPUP_PROPS","弹出属性");//Popup properties
define("_EDITOR_ADVLINK_EVENT_PROPS","事件");//Events
define("_EDITOR_ADVLINK_ADVANCED_PROPS","先进的性能");//Advanced properties
define("_EDITOR_ADVLINK_POPUP_OPTS","选项");//Options
define("_EDITOR_ADVLINK_ANCHOR_NAMES","主播");//Anchors
define("_EDITOR_ADVLINK_TARGET_SAME","开放，在此窗口/帧");//Open in this window / frame
define("_EDITOR_ADVLINK_TARGET_PARENT","开放在父窗口/帧");//Open in parent window / frame
define("_EDITOR_ADVLINK_TARGET_TOP","开放的顶面框架（取代所有帧）");//Open in top frame (replaces all frames)
define("_EDITOR_ADVLINK_TARGET_BLANK","在新窗口中打开");//Open in new window
define("_EDITOR_ADVLINK_POPUP","JavaScript的弹出");//Javascript popup
define("_EDITOR_ADVLINK_POPUP_URL","弹出网址");//Popup URL
define("_EDITOR_ADVLINK_POPUP_NAME","窗口名称");//Window name
define("_EDITOR_ADVLINK_POPUP_RETURN","插入  返回FALSE ");//Insert \\\"return false\\\"
define("_EDITOR_ADVLINK_POPUP_SCROLLBARS","显示滚动条");//Show scrollbars
define("_EDITOR_ADVLINK_POPUP_STATUSBAR","显示状态区");//Show status bar
define("_EDITOR_ADVLINK_POPUP_TOOLBAR","显示工具栏");//Show toolbars
define("_EDITOR_ADVLINK_POPUP_MENUBAR","显示菜单栏");//Show menu bar
define("_EDITOR_ADVLINK_POPUP_LOCATION","显示位置酒吧");//Show location bar
define("_EDITOR_ADVLINK_POPUP_RESIZABLE","使窗口大小可调整");//Make window resizable
define("_EDITOR_ADVLINK_POPUP_DEPENDENT","依赖（ Mozilla基金会/ Firefox的只有）");//Dependent (Mozilla/Firefox only)
define("_EDITOR_ADVLINK_POPUP_SIZE","大小");//Size
define("_EDITOR_ADVLINK_POPUP_POSITION","位置（的X / Y ）");//Position (X/Y)
define("_EDITOR_ADVLINK_ID","编号");//Id
define("_EDITOR_ADVLINK_STYLE","作风");//Style
define("_EDITOR_ADVLINK_CLASSES","班");//Classes
define("_EDITOR_ADVLINK_TARGET_NAME","目标名称");//Target name
define("_EDITOR_ADVLINK_LANGDIR","语言方向");//Language direction
define("_EDITOR_ADVLINK_TARGET_LANGCODE","目标语言");//Target language
define("_EDITOR_ADVLINK_LANGCODE","语言代码");//Language code
define("_EDITOR_ADVLINK_ENCODING","目标字符编码");//Target character encoding
define("_EDITOR_ADVLINK_MIME","目标MIME类型");//Target MIME type
define("_EDITOR_ADVLINK_REL","关系转到目标");//Relationship page to target
define("_EDITOR_ADVLINK_REV","关系的目标页");//Relationship target to page
define("_EDITOR_ADVLINK_TABINDEX","tabindex");//Tabindex
define("_EDITOR_ADVLINK_ACCESSKEY","快速");//Accesskey
define("_EDITOR_ADVLINK_LTR","左向右");//Left to right
define("_EDITOR_ADVLINK_RTL","从右至左");//Right to left
define("_EDITOR_EMOTIONS_TITLE","插入情感");//Insert emotion
define("_EDITOR_EMOTIONS_DESC","情绪");//Emotions
define("_EDITOR_EMOTIONS_COOL","凉爽的");//Cool
define("_EDITOR_EMOTIONS_CRY","哭");//Cry
define("_EDITOR_EMOTIONS_EMBARASSED","尴尬");//Embarassed
define("_EDITOR_EMOTIONS_FOOT_IN_MOUTH","足部在口");//Foot in mouth
define("_EDITOR_EMOTIONS_FROWN","皱眉");//Frown
define("_EDITOR_EMOTIONS_INNOCENT","无辜");//Innocent
define("_EDITOR_EMOTIONS_KISS","亲吻");//Kiss
define("_EDITOR_EMOTIONS_LAUGHING","开怀大笑");//Laughing
define("_EDITOR_EMOTIONS_MONEY_MOUTH","钱口");//Money mouth
define("_EDITOR_EMOTIONS_SEALED","密封");//Sealed
define("_EDITOR_EMOTIONS_SMILE","微笑");//Smile
define("_EDITOR_EMOTIONS_SURPRISED","惊讶");//Surprised
define("_EDITOR_EMOTIONS_TONGUE_OUT","舌出");//Tongue out
define("_EDITOR_EMOTIONS_UNDECIDED","未定");//Undecided
define("_EDITOR_EMOTIONS_WINK","眨眼");//Wink
define("_EDITOR_EMOTIONS_YELL","大声喝斥");//Yell
define("_EDITOR_IESPELL_IESPELL_DESC","运行拼写检查");//Run spell checking
define("_EDITOR_IESPELL_IESPELL_DOWNLOAD","ieSpell未检出。单击确定去下载网页。");//ieSpell not detected. Click OK to go to download page.
define("_EDITOR_INSERTDATETIME_INSERTDATE_DEF_FMT","％ Y型％米- ％ d个");//%Y-%m-%d
define("_EDITOR_INSERTDATETIME_INSERTTIME_DEF_FMT","％ H ：已％米： ％ s的");//%H:%M:%S
define("_EDITOR_INSERTDATETIME_INSERTDATE_DESC","插入日期");//Insert date
define("_EDITOR_INSERTDATETIME_INSERTTIME_DESC","插入时间");//Insert time
define("_EDITOR_INSERTDATETIME_INSERTTIME_MONTHS_LONG","新的数组（ &#39;一月&#39; ， &#39;二月&#39; ， &#39;三月&#39; ， &#39;四月&#39; ， &#39;可能&#39; ， &#39;六月&#39; ， &#39;七月&#39; ， &#39;八月&#39; ， &#39;九月&#39; ， &#39; 10月&#39; ， &#39;十一月&#39; ， &#39; 12月&#39; ）");//new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December')
define("_EDITOR_INSERTDATETIME_INSERTTIME_MONTHS_SHORT","新的数组（ &#39;一月&#39; ， &#39;二月&#39; ， &#39;三月&#39; ， &#39;四月&#39; ， &#39;可能&#39; ， &#39;军&#39; ， &#39;七月&#39; ， &#39;八月&#39; ， &#39; 9 &#39; ， &#39; 10月&#39; ， &#39; 11月&#39; ， &#39; 12月&#39; ）");//new Array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')
define("_EDITOR_INSERTDATETIME_INSERTTIME_DAY_LONG","新的数组（ &#39;周日&#39; ， &#39;星期一&#39; ， &#39;星期二&#39; ， &#39;星期三&#39; ， &#39;星期四&#39; ， &#39;星期五&#39; ， &#39;星期六&#39; ， &#39;星期日&#39; ）");//new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')
define("_EDITOR_INSERTDATETIME_INSERTTIME_DAY_SHORT","新的数组（ &#39;孙&#39; ， &#39;星期一&#39; ， &#39;星期二&#39; ， &#39;星期三&#39; ， &#39;星期四&#39; ， &#39;五&#39; ， &#39;星期六&#39; ， &#39;孙&#39; ）");//new Array('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun')
define("_EDITOR_MATHTYPE_INSERT_MATHTYPE_TITLE","插入mathtype");//Insert mathtype
define("_EDITOR_MATHTYPE_TITLE","插入mathtype");//Insert mathtype
define("_EDITOR_MATHTYPE_MATHTYPE_DESC","mathtype");//Mathtype
define("_EDITOR_MATHTYPE_DESC","mathtype");//Mathtype
define("_EDITOR_MEDIA_TITLE","插入/编辑嵌入式媒体");//Insert / edit embedded media
define("_EDITOR_MEDIA_DESC","插入/编辑嵌入式媒体");//Insert / edit embedded media
define("_EDITOR_MEDIA_GENERAL","一般");//General
define("_EDITOR_MEDIA_ADVANCED","先进");//Advanced
define("_EDITOR_MEDIA_FILE","文件");//File
define("_EDITOR_MEDIA_LIST","名单");//List
define("_EDITOR_MEDIA_SIZE","尺寸");//Dimensions
define("_EDITOR_MEDIA_PREVIEW","预览");//Preview
define("_EDITOR_MEDIA_CONSTRAIN_PROPORTIONS","制约比例");//Constrain proportions
define("_EDITOR_MEDIA_TYPE","类型");//Type
define("_EDITOR_MEDIA_ID","编号");//Id
define("_EDITOR_MEDIA_NAME","名字");//Name
define("_EDITOR_MEDIA_CLASS_NAME","工人阶级");//Class
define("_EDITOR_MEDIA_VSPACE","V型空间");//V-Space
define("_EDITOR_MEDIA_HSPACE","H -空间");//H-Space
define("_EDITOR_MEDIA_PLAY","自动播放");//Auto play
define("_EDITOR_MEDIA_LOOP","死循环");//Loop
define("_EDITOR_MEDIA_MENU","显示菜单");//Show menu
define("_EDITOR_MEDIA_QUALITY","质量");//Quality
define("_EDITOR_MEDIA_SCALE","规模");//Scale
define("_EDITOR_MEDIA_ALIGN","对齐");//Align
define("_EDITOR_MEDIA_SALIGN","salign");//SAlign
define("_EDITOR_MEDIA_WMODE","wmode");//WMode
define("_EDITOR_MEDIA_BGCOLOR","背景");//Background
define("_EDITOR_MEDIA_BASE","基地");//Base
define("_EDITOR_MEDIA_FLASHVARS","flashvars");//Flashvars
define("_EDITOR_MEDIA_LIVECONNECT","swliveconnect");//SWLiveConnect
define("_EDITOR_MEDIA_AUTOHREF","autohref");//AutoHREF
define("_EDITOR_MEDIA_CACHE","缓存");//Cache
define("_EDITOR_MEDIA_HIDDEN","隐藏");//Hidden
define("_EDITOR_MEDIA_CONTROLLER","控制器");//Controller
define("_EDITOR_MEDIA_KIOSKMODE","Kiosk模式");//Kiosk mode
define("_EDITOR_MEDIA_PLAYEVERYFRAME","发挥每一个框架");//Play every frame
define("_EDITOR_MEDIA_TARGETCACHE","目标高速缓存");//Target cache
define("_EDITOR_MEDIA_CORRECTION","没有校正");//No correction
define("_EDITOR_MEDIA_ENABLEJAVASCRIPT","启用JavaScript");//Enable JavaScript
define("_EDITOR_MEDIA_STARTTIME","开始时间");//Start time
define("_EDITOR_MEDIA_ENDTIME","结束时间");//End time
define("_EDITOR_MEDIA_HREF","href");//Href
define("_EDITOR_MEDIA_QTSRCCHOKESPEED","窒息的速度");//Choke speed
define("_EDITOR_MEDIA_TARGET","目标");//Target
define("_EDITOR_MEDIA_VOLUME","数量");//Volume
define("_EDITOR_MEDIA_AUTOSTART","自动启动");//Auto start
define("_EDITOR_MEDIA_ENABLED","启用");//Enabled
define("_EDITOR_MEDIA_FULLSCREEN","全屏");//Fullscreen
define("_EDITOR_MEDIA_INVOKEURLS","引用网址");//Invoke URLs
define("_EDITOR_MEDIA_MUTE","静音");//Mute
define("_EDITOR_MEDIA_STRETCHTOFIT","舒展，以适应");//Stretch to fit
define("_EDITOR_MEDIA_WINDOWLESSVIDEO","没有窗户的视频");//Windowless video
define("_EDITOR_MEDIA_BALANCE","平衡");//Balance
define("_EDITOR_MEDIA_BASEURL","基地网址");//Base URL
define("_EDITOR_MEDIA_CAPTIONINGID","字幕编号");//Captioning id
define("_EDITOR_MEDIA_CURRENTMARKER","当前标记");//Current marker
define("_EDITOR_MEDIA_CURRENTPOSITION","当前位置");//Current position
define("_EDITOR_MEDIA_DEFAULTFRAME","预设框架");//Default frame
define("_EDITOR_MEDIA_PLAYCOUNT","发挥计数");//Play count
define("_EDITOR_MEDIA_RATE","比率");//Rate
define("_EDITOR_MEDIA_UIMODE","UI模式");//UI Mode
define("_EDITOR_MEDIA_FLASH_OPTIONS","闪光选项");//Flash options
define("_EDITOR_MEDIA_QT_OPTIONS","的QuickTime选项");//Quicktime options
define("_EDITOR_MEDIA_WMP_OPTIONS","Windows Media Player的选项");//Windows media player options
define("_EDITOR_MEDIA_RMP_OPTIONS","真正的媒体播放器的选项");//Real media player options
define("_EDITOR_MEDIA_SHOCKWAVE_OPTIONS","冲击波选项");//Shockwave options
define("_EDITOR_MEDIA_AUTOGOTOURL","汽车后藤网址");//Auto goto URL
define("_EDITOR_MEDIA_CENTER","中心");//Center
define("_EDITOR_MEDIA_IMAGESTATUS","形象地位");//Image status
define("_EDITOR_MEDIA_MAINTAINASPECT","保持方面");//Maintain aspect
define("_EDITOR_MEDIA_NOJAVA","没有的Java");//No java
define("_EDITOR_MEDIA_PREFETCH","预取");//Prefetch
define("_EDITOR_MEDIA_SHUFFLE","shuffle的");//Shuffle
define("_EDITOR_MEDIA_CONSOLE","控制台");//Console
define("_EDITOR_MEDIA_NUMLOOP","NUM个循环");//Num loops
define("_EDITOR_MEDIA_CONTROLS","管制");//Controls
define("_EDITOR_MEDIA_SCRIPTCALLBACKS","脚本回调");//Script callbacks
define("_EDITOR_MEDIA_SWSTRETCHSTYLE","舒展的作风");//Stretch style
define("_EDITOR_MEDIA_SWSTRETCHHALIGN","舒展的H -对齐");//Stretch H-Align
define("_EDITOR_MEDIA_SWSTRETCHVALIGN","拉伸V型对齐");//Stretch V-Align
define("_EDITOR_MEDIA_SOUND","健全");//Sound
define("_EDITOR_MEDIA_PROGRESS","教师");//Progress
define("_EDITOR_MEDIA_QTSRC","Qt的钢骨混凝土");//QT Src
define("_EDITOR_MEDIA_QT_STREAM_WARN","RTSP应当被添加到高级选项卡的QT的src属性中");//Streamed rtsp resources should be added to the QT Src field under the advanced tab.You should also add a non streamed version to the Src field..
define("_EDITOR_PREVIEW_PREVIEW_DESC","预览");//Preview
define("_EDITOR_PRINT_PRINT_DESC","打印");//Print
define("_EDITOR_SAVE_SAVE_DESC","保存");//Save
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_SEARCH_DESC","查找");//Find
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_SEARCHNEXT_DESC","再次找到");//Find again
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACE_DESC","查找/替换");//Find/Replace
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_NOTFOUND","搜寻工作已经完成。搜寻字符串无法找到。");//The search has been completed. The search string could not be found.
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_SEARCH_TITLE","查找");//Find
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACE_TITLE","查找/替换");//Find/Replace
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_ALLREPLACED","所有发生的搜寻字符串的取代。");//All occurrences of the search string were replaced.
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_FINDWHAT","寻找什么");//Find what
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACEWITH","替换");//Replace with
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_DIRECTION","方向");//Direction
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_UP","向上");//Up
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_DOWN","向下的");//Down
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_CASE","匹配大小写");//Match case
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_FINDNEXT","寻找下一个");//Find&nbsp;next
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACE","取代");//Replace
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_REPLACEALL","全部替换");//Replace&nbsp;all
define("_EDITOR_SEARCHREPLACE_SEARCHREPLACE_CANCEL","取消");//Cancel
define("_EDITOR_TABLE_GENERAL_TAB","一般");//General
define("_EDITOR_TABLE_ADVANCED_TAB","先进");//Advanced
define("_EDITOR_TABLE_GENERAL_PROPS","一般性质");//General properties
define("_EDITOR_TABLE_ADVANCED_PROPS","先进的性能");//Advanced properties
define("_EDITOR_TABLE_DESC","插入一个新表");//Inserts a new table
define("_EDITOR_TABLE_ROW_BEFORE_DESC","插入行之前");//Insert row before
define("_EDITOR_TABLE_ROW_AFTER_DESC","插入行后，");//Insert row after
define("_EDITOR_TABLE_DELETE_ROW_DESC","删除行");//Delete row
define("_EDITOR_TABLE_COL_BEFORE_DESC","插入列前");//Insert column before
define("_EDITOR_TABLE_COL_AFTER_DESC","插入列后");//Insert column after
define("_EDITOR_TABLE_DELETE_COL_DESC","删除栏");//Remove column
define("_EDITOR_TABLE_ROWTYPE","列在表中的一部分");//Row in table part
define("_EDITOR_TABLE_TITLE","插入/修改表");//Insert/Modify table
define("_EDITOR_TABLE_WIDTH","宽度");//Width
define("_EDITOR_TABLE_HEIGHT","高度");//Height
define("_EDITOR_TABLE_COLS","专栏");//Columns
define("_EDITOR_TABLE_ROWS","行");//Rows
define("_EDITOR_TABLE_CELLSPACING","cellspacing");//Cellspacing
define("_EDITOR_TABLE_CELLPADDING","cellpadding");//Cellpadding
define("_EDITOR_TABLE_BORDER","边境");//Border
define("_EDITOR_TABLE_ALIGN","对齐");//Alignment
define("_EDITOR_TABLE_ALIGN_DEFAULT","默认");//Default
define("_EDITOR_TABLE_ALIGN_LEFT","左边");//Left
define("_EDITOR_TABLE_ALIGN_RIGHT","右边");//Right
define("_EDITOR_TABLE_ALIGN_MIDDLE","中心");//Center
define("_EDITOR_TABLE_ROW_TITLE","表行属性");//Table row properties
define("_EDITOR_TABLE_CELL_TITLE","表格单元格属性");//Table cell properties
define("_EDITOR_TABLE_CELL_TYPE","单元格类型");//Cell type
define("_EDITOR_TABLE_ROW_DESC","表行属性");//Table row properties
define("_EDITOR_TABLE_CELL_DESC","表格单元格属性");//Table cell properties
define("_EDITOR_TABLE_VALIGN","垂直对齐");//Vertical alignment
define("_EDITOR_TABLE_ALIGN_TOP","顶端");//Top
define("_EDITOR_TABLE_ALIGN_BOTTOM","底部");//Bottom
define("_EDITOR_TABLE_PROPS_DESC","表属性");//Table properties
define("_EDITOR_TABLE_BORDERCOLOR","边框颜色");//Border color
define("_EDITOR_TABLE_BGCOLOR","背景颜色");//Background color
define("_EDITOR_TABLE_MERGE_CELLS_TITLE","合并表单元格");//Merge table cells
define("_EDITOR_TABLE_SPLIT_CELLS_DESC","单元格分裂表");//Split table cells
define("_EDITOR_TABLE_MERGE_CELLS_DESC","合并表单元格");//Merge table cells
define("_EDITOR_TABLE_CUT_ROW_DESC","削减表行");//Cut table row
define("_EDITOR_TABLE_COPY_ROW_DESC","复制表行");//Copy table row
define("_EDITOR_TABLE_PASTE_ROW_BEFORE_DESC","粘贴表行前");//Paste table row before
define("_EDITOR_TABLE_PASTE_ROW_AFTER_DESC","粘贴表行后，");//Paste table row after
define("_EDITOR_TABLE_ID","编号");//Id
define("_EDITOR_TABLE_STYLE","作风");//Style
define("_EDITOR_TABLE_LANGDIR","语言方向");//Language direction
define("_EDITOR_TABLE_LANGCODE","语言代码");//Language code
define("_EDITOR_TABLE_MIME","目标MIME类型");//Target MIME type
define("_EDITOR_TABLE_LTR","左向右");//Left to right
define("_EDITOR_TABLE_RTL","从右至左");//Right to left
define("_EDITOR_TABLE_BGIMAGE","背景图像");//Background image
define("_EDITOR_TABLE_SUMMARY","摘要");//Summary
define("_EDITOR_TABLE_TD","数据");//Data
define("_EDITOR_TABLE_TH","标题");//Header
define("_EDITOR_TABLE_CELL_CELL","更新目前的单元格");//Update current cell
define("_EDITOR_TABLE_CELL_ROW","更新所有单元格在连续");//Update all cells in row
define("_EDITOR_TABLE_CELL_ALL","更新所有单元格的表");//Update all cells in table
define("_EDITOR_TABLE_ROW_ROW","更新当前行");//Update current row
define("_EDITOR_TABLE_ROW_ODD","更新奇的行表");//Update odd rows in table
define("_EDITOR_TABLE_ROW_EVEN","更新，甚至排在表");//Update even rows in table
define("_EDITOR_TABLE_ROW_ALL","更新所有的行表");//Update all rows in table
define("_EDITOR_TABLE_THEAD","表fead");//Table fead
define("_EDITOR_TABLE_TBODY","表机构");//Table body
define("_EDITOR_TABLE_TFOOT","表脚");//Table foot
define("_EDITOR_TABLE_DEL","删除表");//Delete table
define("_EDITOR_TABLE_SCOPE","范围");//Scope
define("_EDITOR_TABLE_ROW","行");//Row
define("_EDITOR_TABLE_COL","中校");//Col
define("_EDITOR_TABLE_ROWGROUP","连续组");//Row group
define("_EDITOR_TABLE_COLGROUP","中校组");//Col group
define("_EDITOR_TABLE_COL_LIMIT","您已经超过了最高的列数。");//You have exceeded the maximum number of columns.
define("_EDITOR_TABLE_ROW_LIMIT","您已经超过了最高的行数。");//You have exceeded the maximum number of rows.
define("_EDITOR_TABLE_CELL_LIMIT","您已超出最多的单元格。");//You have exceeded the maximum number of cells.
define("_EDITOR_TABLE_MISSING_SCOPE","您确定要继续操作而不指定的范围，这表头单元格。没有它，它可能很难为一些残疾人用户了解的内容或数据，显示该表。");//Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.
define("_EDITOR_AUTOSAVE_AUTOSAVE_UNLOAD_MSG","的变化，你将会失去，如果你浏览远离这一页。");//The changes you made will be lost if you navigate away from this page.
define("_EDITOR_DIRECTIONALITY_DIRECTIONALITY_LTR_DESC","方向左向右");//Direction left to right
define("_EDITOR_DIRECTIONALITY_DIRECTIONALITY_RTL_DESC","方向从右至左");//Direction right to left
define("_EDITOR_LAYER_INSERTLAYER_DESC","插入新层");//Insert new layer
define("_EDITOR_LAYER_FORWARD_DESC","向前迈进");//Move forward
define("_EDITOR_LAYER_BACKWARD_DESC","动议落后");//Move backward
define("_EDITOR_LAYER_ABSOLUTE_DESC","切换绝对寻址");//Toggle absolute positioning
define("_EDITOR_LAYER_CONTENT","新的层...");//New layer...
define("_EDITOR_NONBREAKING_DESC","插入非打破空间的性质");//Insert non-breaking space character
define("_EDITOR_THEME_THEME_STYLE_SELECT","-风格-");//-- Styles --
define("_EDITOR_THEME_THEME_CODE_DESC","编辑HTML源代码");//Edit HTML Source
define("_EDITOR_THEME_THEME_CODE_TITLE","HTML源代码编辑器");//HTML Source Editor
define("_EDITOR_THEME_THEME_CODE_WORDWRAP","自动换行");//Word wrap
define("_EDITOR_THEME_THEME_SUB_DESC","标");//Subscript
define("_EDITOR_THEME_THEME_SUP_DESC","标");//Superscript
define("_EDITOR_THEME_THEME_HR_DESC","插入水平尺");//Insert horizontal ruler
define("_EDITOR_THEME_THEME_REMOVEFORMAT_DESC","删除格式");//Remove formatting
define("_EDITOR_THEME_THEME_CUSTOM1_DESC","您的自定义描述在这里");//Your custom description here
define("_EDITOR_THEME_INSERT_IMAGE_BORDER","边境");//Border
define("_EDITOR_THEME_INSERT_IMAGE_DIMENSIONS","尺寸");//Dimensions
define("_EDITOR_THEME_INSERT_IMAGE_VSPACE","垂直空间");//Vertical space
define("_EDITOR_THEME_INSERT_IMAGE_HSPACE","横向空间");//Horizontal space
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN","对齐");//Alignment
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_DEFAULT","-未设置-");//-- Not set --
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_BASELINE","基线");//Baseline
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_TOP","顶端");//Top
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_MIDDLE","中间的");//Middle
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_BOTTOM","底部");//Bottom
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_TEXTTOP","texttop");//TextTop
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_ABSMIDDLE","绝对中间的");//Absolute middle
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_ABSBOTTOM","绝对底部");//Absolute bottom
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_LEFT","左边");//Left
define("_EDITOR_THEME_INSERT_IMAGE_ALIGN_RIGHT","右边");//Right
define("_EDITOR_THEME_THEME_FONT_SIZE","-字体大小-");//-- Font size --
define("_EDITOR_THEME_THEME_FONTDEFAULT","-字体的家庭-");//-- Font family --
define("_EDITOR_THEME_THEME_BLOCK","-格式-");//-- Format --
define("_EDITOR_THEME_THEME_PARAGRAPH","段");//Paragraph
define("_EDITOR_THEME_THEME_DIV","除法");//Div
define("_EDITOR_THEME_THEME_ADDRESS","地址");//Address
define("_EDITOR_THEME_THEME_PRE","预");//Preformatted
define("_EDITOR_THEME_THEME_H1","标题 1");//Heading 1
define("_EDITOR_THEME_THEME_H2","标题 2");//Heading 2
define("_EDITOR_THEME_THEME_H3","标题 3");//Heading 3
define("_EDITOR_THEME_THEME_H4","标题 4");//Heading 4
define("_EDITOR_THEME_THEME_H5","标题 5");//Heading 5
define("_EDITOR_THEME_THEME_H6","标题 6");//Heading 6
define("_EDITOR_THEME_THEME_BLOCKQUOTE","引用");//Blockquote
define("_EDITOR_THEME_THEME_CODE","代码");//Code
define("_EDITOR_THEME_THEME_SAMP","代码示例");//Code sample
define("_EDITOR_THEME_THEME_DT","定义任期");//Definition term 
define("_EDITOR_THEME_THEME_DD","定义说明");//Definition description
define("_EDITOR_THEME_THEME_COLORPICKER_TITLE","选择一种颜色");//Select a color
define("_EDITOR_THEME_THEME_COLORPICKER_APPLY","应用");//Apply
define("_EDITOR_THEME_THEME_FORECOLOR_DESC","选择文字颜色");//Select text color
define("_EDITOR_THEME_THEME_BACKCOLOR_DESC","选择背景颜色");//Select background color
define("_EDITOR_THEME_THEME_CHARMAP_TITLE","选择自定义字符");//Select custom character
define("_EDITOR_THEME_THEME_CHARMAP_DESC","插入自定义字符");//Insert custom character
define("_EDITOR_THEME_THEME_VISUALAID_DESC","切换指引/隐藏要素");//Toggle guidelines/invisible elements
define("_EDITOR_THEME_INSERT_ANCHOR_TITLE","插入/编辑锚");//Insert/edit anchor
define("_EDITOR_THEME_INSERT_ANCHOR_NAME","锚点名称");//Anchor name
define("_EDITOR_THEME_THEME_ANCHOR_DESC","插入/编辑锚");//Insert/edit anchor
define("_EDITOR_THEME_THEME_INSERT_LINK_TITLEFIELD","标题");//Title
define("_EDITOR_THEME_THEME_CLIPBOARD_MSG","复制/削减/粘贴是不具备的Mozilla和Firefox 。你想了解更多信息有关此问题的呢?");//Copy/Cut/Paste is not available in Mozilla and Firefox.Do you want more information about this issue?
define("_EDITOR_THEME_THEME_PATH","路径");//Path
define("_EDITOR_THEME_CUT_DESC","剪切");//Cut
define("_EDITOR_THEME_COPY_DESC","复制");//Copy
define("_EDITOR_THEME_PASTE_DESC","粘贴");//Paste
define("_EDITOR_THEME_LINK_LIST","链接列表");//Link list
define("_EDITOR_THEME_IMAGE_LIST","图像列表");//Image list
define("_EDITOR_THEME_BROWSE","浏览");//Browse
define("_EDITOR_THEME_IMAGE_PROPS_DESC","图像属性");//Image properties
define("_EDITOR_THEME_NEWDOCUMENT_DESC","新文件");//New document
define("_EDITOR_THEME_CLASS_NAME","工人阶级");//Class
define("_EDITOR_THEME_NEWDOCUMENT","您确定要清除所有的内容?");//Are you sure you want clear all contents?
define("_EDITOR_THEME_ABOUT_TITLE","关于tinymce");//About TinyMCE
define("_EDITOR_THEME_ABOUT","大约");//About
define("_EDITOR_THEME_LICENSE","许可");//License
define("_EDITOR_THEME_PLUGINS","插件");//Plugins
define("_EDITOR_THEME_PLUGIN","插件");//Plugin
define("_EDITOR_THEME_AUTHOR","作者");//Author
define("_EDITOR_THEME_VERSION","版本");//Version
define("_EDITOR_THEME_LOADED_PLUGINS","加载插件");//Loaded plugins
define("_EDITOR_THEME_HELP","帮助");//Help
define("_EDITOR_THEME_NOT_SET","-未设置-");//-- Not set --
define("_EDITOR_THEME_CLOSE","关闭");//Close
define("_EDITOR_THEME_TOOLBAR_FOCUS","跳转到工具按钮-按A lt+的Q跳转到编辑器-按A l t-Z型，跳转到元素的路径-按Al t -X的");//Jump to tool buttons - Alt+Q, Jump to editor - Alt-Z, Jump to element path - Alt-X
define("_EDITOR_THEME_INVALID_DATA","错误：无效的价值观进入，这些都是以红色标示。");//Error: Invalid values entered, these are marked in red.
define("_EDITOR_PASTE_PASTE_TEXT_DESC","粘贴为纯文本");//Paste as plain text
define("_EDITOR_PASTE_PASTE_TEXT_TITLE","使用CTRL + V对您的键盘，文本粘贴到窗口。");//Use CTRL+V on your keyboard to paste the text into the window.
define("_EDITOR_PASTE_PASTE_TEXT_LINEBREAKS","保持linebreaks");//Keep linebreaks
define("_EDITOR_PASTE_PASTE_WORD_DESC","粘贴从Word");//Paste from Word
define("_EDITOR_PASTE_PASTE_WORD_TITLE","使用CTRL + V对您的键盘，文本粘贴到窗口。");//Use CTRL+V on your keyboard to paste the text into the window.
define("_EDITOR_PASTE_SELECTALL_DESC","选择所有");//Select all
define("_EDITOR_FULLSCREEN_FULLSCREEN_DESC","切换全屏模式");//Toggle fullscreen mode (New)
define("_EDITOR_LESSONSINFO_LANG_LESSONS_INFO_LINKDESCRIPTION","转到：吸取信息");//Go to: lessons info (New)
define("_EDITOR_LESSONSINFO_LANG_LESSONS_INFO_DESC","总结信息链接");//Lessons info link (New)
define("_EDITOR_INDEXLINK_LANG_INDEX_LINK_LINKDESCRIPTION","注册");//Login (New)
define("_EDITOR_INDEXLINK_LANG_INDEX_LINK_DESC","登录连结");//Login link (New)
define("_CHOOSELANGUGETOSYNC","选择语言同步");//Choose language to synchronize
define("_INSERTJAVA","插入的Java文件");//Insert java file
define("_INSERTMEDIA","插入媒体文件");//Insert media file
define("_CHANGEORDER","修改订单");//Change order
define("_DRAGITEMSTOCHANGEQUESTIONSORDER","拖移项目，以改变显示顺序的问题");//Drag items to change the display order of the questions
define("_TERM","任期");//Term
define("_OPERATIONS","行动");//Operations
define("_AREYOUSUREYOUWANTTODELETELESSON","您确定要删除的节呢?");//Are you sure you want to delete lesson?
define("_EDITLESSON","节设置");//Edit lesson
define("_DIRECTIONS","类别");//Categories
define("_UPDATEDIRECTIONS","编辑类别");//Edit categories
define("_PARENTDIRECTIONS","家长类");//Parent category
define("_AREYOUSUREYOUWANTTODELETEDIRECTION","您确定要删除类别?");//Are you sure you want to delete the category?
define("_YOUMUSTDELETEALLLESSONSANDSUBDIRECTIONSINTHISDIRECTIONBEFOREDELETINGIT","您必须删除所有的节和所有子属于这一类删除之前");//You must delete all lessons and all subcategories that belong to this category before deleting it
define("_ROOTDIRECTION","----热门分类----");//----Root category----
define("_CHECK","检查");//Check
define("_REQUIREDNOTE","*必填");//*Mandatory fields
define("_BEFOREJAVASCRIPTERROR","以下错误发生：");//The following errors occured:
define("_AFTERJAVASCRIPTERROR","请更正上述错误");//Please correct the above errors
define("_ISMANDATORY","是强制性的");//is mandatory
define("_HASINVALIDCHARACTERS","无效字符");//has invalid characters
define("_ONLYALLOWEDCHARACTERSLOGIN","只能使用字母和字符<strong>。 -_ @允</strong>许");//Only letters and the characters <strong>. - _ @</strong> are allowed
define("_ALREADYEXISTS","已经存在");//already exists
define("_PASSWORDSDONOTMATCH","该密码不匹配");//The passwords do not match
define("_ONLYALLOWEDCHARACTERSTEXT","请不要使用报价和其它特殊字符。");//Please do not use quotes and other special characters.
define("_REPEATPASSWORD","重复密码");//Repeat password
define("_TERMS","服务条款");//Terms of Service
define("_REGISTRATIONFAILEDCONTACTADMIN","注册失败。请联系系统管理员。");//Registration failed. Please contact the system administrator.
define("_THELOGIN","用户名");//The user name
define("_THEEMAIL","电子邮件");//The email
define("_PASSWORDMUSTBE6CHARACTERS","密码必须至少6个字符");//Password must be at least 6 characters
define("_DEFAULTCONTACTMESSAGE","我想被告知的内容和规格，您的经验节，以及对任何课程的参与要求");//I would like to be informed on the content and specifications of your lessons, as well as on any course participation requirements
define("_DEFAULTTERMSOFUSAGE","eFront平台使用条款，所有注册用户必须阅读并同意下列条款： 1 。禁止把本平台应用于非学习过程；");//\teFront platform terms of usage\n\nEvery user registering to the present e-learning system must read and comply with the following terms of proper usage.\n\n1. It is forbidden to use the system for reasons other than performing a learning procedure, as for example: Promotion of products or services or any combination of these, personal or other person promotional practices, affront to other person, either registered system users or not
define("_YOUMUSTAGREEWITHTERMSOFUSAGETOCONTINUE","继续前您必须同意这些条款");//You must agree with the terms of usage in order to continue
define("_INVALIDFIELDDATA","无效数据");//Invalid field data
define("_SUCCESFULLYINSERTEDNEWUNIT","成功地插入新的单元");//Succesfully inserted new unit
define("_ACCEPTTERMS","同意条款");//Accept terms
define("_SUCCESFULLYUPDATEDUNIT","成功更新单元");//Succesfully updated unit
define("_ACTIVE2","激活");//Active
define("_ACTIVEFEM","激活");//Active
define("_LESSONSNUMBER","节数目");//Number of lessons
define("_PARENTDIRECTION","家长类");//Parent category
define("_EXPANDCOLLAPSE","展开/折迭");//Expand/Collapse
define("_RAWTEXT","原始文本");//Raw text
define("_SUCCESFULLYADDEDTEST","测试添加成功");//Succesfully added test
define("_SUCESSFULLYDELETEDTEST","测试成功删除");//Succesfully deleted test
define("_SUCCESFULLYMODIFIEDTEST","成功修改测试");//Succesfully modified test
define("_USEQUESTION","使用问题");//Use question
define("_SHUFFLEANSWERS","shuffle的答案");//Shuffle answers
define("_SHUFFLEQUESTIONS","shuffle的问题");//Shuffle questions
define("_QUESTIONS","问题");//Questions
define("_INSERTMULTIPLEQUESTIONS","插入多种选择");//Insert the multiple choices
define("_INSERTEXPLANATION","插入解释");//Insert explanation
define("_THISQUESTIONIS","这个问题是");//This question is
define("_CREATEEMPTYSPACES","创建空白");//Create empty spaces
define("_EMPTYSPACESEXPLANATION","在需要填空处插入###");//Write the question text and wherever you need to insert a blank space, insert ###. When you are done, click on the &quot;Create empty spaces&quot; button below
define("_INSERTMATCHCOUPLES","插入匹配对");//Insert matching pairs
define("_ADDOPTION","添加选项");//Add option
define("_GOTOCALENDAR","转到日历");//Go to calendar
define("_EXPANDALL","全部展开");//Expand all
define("_COLLAPSEALL","全部折迭");//Collapse all
define("_SURVEY","调查");//Survey
define("_SURVEYADDEDSUCCESSFULLY","调查添加成功");//Survey added successfully
define("_SURVEYFAILEDTOBEADDED","调查无法加入");//Survey failed to be added
define("_SURVEYDELETEDSUCCESSFULLY","调查成功删除");//Survey deleted successfully
define("_QUESTIONADDEDSUCCESSFULLY","问题补充成功");//Question added successfully
define("_QUESTIONFAILEDTOBEADDED","没有添加问题");//Failed to add question
define("_CREATESURVEYQUESTION","创造问题的调查");//Create question for survey
define("_CREATESURVEY","建立调查");//Create survey
define("_EDITSURVEY","编辑调查");//Edit survey
define("_NOSURVEYFORLESSON","有没有调查的节");//There is no survey for the lesson
define("_NOQUESTIONSFORSURVEY","有没有问题，以供调查");//There are no questions for the survey
define("_SURVEYCODE","代码");//Code
define("_SURVEYNAME","名字");//Name
define("_SURVEYSTATUS","身份");//Status
define("_SURVEYNUMBEROFQUESTIONS","问题基数");//Question cardinality
define("_SURVEYAVALIABLEFROM","可从");//Availiable from
define("_SURVEYUNTIL","直到");//Until
define("_PUBLISH","发布");//Publish
define("_SURVEYSELECTION","选择");//Select
define("_SELECTALL","选择所有");//Select all
define("_SURVEYINFO","副标题为调查");//Subtitle for the survey
define("_SURVEYINTROTEXT","调查的介绍性文字");//Survey introductory text
define("_SURVEYENDTEXT","调查结束文本");//Survey ending text
define("_YES_NO","是/否");//Yes/No
define("_SURVEYQUESTIONMULTIPLEONE","多种选择-一个答案");//Multiple choices-one answer
define("_SURVEYQUESTIONMULTIPLEMANY","多种选择-多个答案");//Multiple choices-multiple answers
define("_ENTERMAILMESSAGE","讯息");//Message
define("_PLEASESELECTAVALIDTYPEOFQUESTION","请选择一个有效的类型的问题在前面的步骤。");//Please select a valid type of question in the previous step.
define("_SURVEYDATAUPDATEDSUCCESSFULLY","调查数据更新成功");//Survey data updated successfully
define("_SURVEYDATAFAILEDTOBEUPDATED","调查数据没有更新");//Survey data failed to be updated
define("_QUESTIONDELETEDSUCCESSFULLY","问题已成功删除");//Question deleted successfully
define("_THEQUESTIONWASSUCCESSFULLYMOVED","问题的动议成功");//The question moved successfully
define("_THEQUESTIONFAILEDTOBEMOVED","问题没有被提出");//The question failed to be moved
define("_NOSUCHOPERATION","没有这样的运作");//No such operation
define("_SHOWDATAFORUNIT","数据显示单元");//Show data for unit
define("_ALLUNITS","各单元");//All units
define("_YOUMUSTUPLOADFILE","您必须表明要上传的文件");//You must indicate a file to upload
define("_TOTALINSERTED","完全插入");//Totally inserted
define("_PERSONALOPTIONSFOR","个人选择用户");//Personal options for user
define("_LESSONOPTIONSFOR","选择的节");//Options for lesson
define("_NEWLESSONOPTIONS","新的节，选择");//New lesson options
define("_ROLES","用户类型");//User types
define("_TYPENAME","类型名称");//Type name
define("_UPDATEUSERTYPEFOR","更新雇员类型");//Update user type for
define("_SYSTEMANNOUNCEMENTS","系统公告");//System announcements
define("_CREATEUNIT","创建单元");//Create unit
define("_DONETIMES","时代完成");//Times completed
define("_QUESTIONSTATISTICS","问题统计");//Question statistics
define("_ADDQUESTIONOFTYPE","添加的问题类型");//Add question of type
define("_NOSYSTEMANNOUNCEMENTSPOSTED","没有系统的公告张贴");//No system announcements posted
define("_DURATIONINMINUTES","在几分钟的时间");//Duration in minutes
define("_ADDCALENDAR","新增日历事件");//Add calendar event
define("_EVENTS","事件");//events
define("_NOEVENTSPLANNED","有没有活动计划");//There are no events planned
define("_UNITOPERATIONS","单元操作");//Unit operations
define("_LESSONINFORMATION","节信息");//Lesson information
define("_GENERALDESCRIPTION","一般说明");//General description
define("_OBJECTIVES","目标");//Objectives
define("_OTHERINFO","其它信息");//Other information
define("_ASSESSMENT","估价");//Assessment
define("_RESOURCES","资源");//Resources
define("_LESSONTOPICS","节话题");//Lesson topics
define("_NODESCRIPTIONSET","有没有说明订定这个节");//There is no description set for this lesson
define("_HASINVALIDEMAILADDRESS","已无效的电子邮件地址");//has invalid email address
define("_SUCCESFULLYADDEDDIRECTION","成功添加类");//Succesfully added category
define("_SUCCESFULLYUPDATEDDIRECTION","成功更新类别");//Succesfully updated category
define("_LESSONRULES","节规则");//Lesson rules
define("_BASEDONTERM","基于对任期");//Based on term
define("_HASNOTSEENTHEUNIT","有没有看到单元");//Has not seen the unit
define("_HASNOTPASSEDTHETEST","未完成测试");//Has not completed the test
define("_ALWAYS","总是");//Always
define("_WITHNAME","与名称");//With name
define("_ANDSCOREGREATEROREQUAL","和评分大于或等于");//And score greater or equal to
define("_INVALIDRULE","无效的规则类型");//Invalid rule type
define("_INVALIDSCORE","无效的评分");//Invalid score
define("_SUCCESFULLYUPDATEDRULE","succefully更新规则");//Succefully updated rule
define("_SUCCESFULLYINSERTEDRULE","succefully插入规则");//Succefully inserted rule
define("_ADDRULE","添加规则");//Add rule
define("_RULEDELETED","法治的成功删除");//Rule deleted successfully
define("_NEWSURVEYPUBLISHED","调查报告：");//Survey:
define("_DOSURVEY","这样做的调查");//Do the survey
define("_THANKYOU","谢谢您");//Thank you
define("_THISEMAIL","此电子邮件");//This email
define("_CONTAINSINFORMATIONABOUTYOURACCOUNTINTHEPLATFORM","包含有关您的账户在该平台");//contains information about your account in the platform
define("_SURVEYPUBLISHEDSUCCESSFULLY","发表的调查成功");//Survey published sucessfully
define("_STARTSURVEY","开始调查");//Start survey
define("_SURVEYSUBMISSIONSUCCESSFUL","调查提交成功");//Survey submitted successfully
define("_YOUCANNOTACCESSTHISPAGE","你不能进入此页");//You cannot access this page
define("_NOCONTENTFOUND","没有内容");//No content
define("_EDITLESSONSDIRECTION","类的节");//Category lessons
define("_EXTERNALLYSIGNUP","对外注册");//External signup
define("_EVENT","事件");//Event
define("_EDITEVENT","编辑活动");//Edit event
define("_DELETEEVENT","删除活动");//Delete event
define("_ADDEVENT","添加活动");//Add event
define("_SUCCESFULLYADDEDEVENT","成功添加事件");//Succesfully added event
define("_SUCCESFULLYUPDATEDEDEVENT","成功更新事件");//Succesfully updated event
define("_SUCCESFULLYDELETEDEVENT","成功删除事件");//Succesfully deleted event
define("_SHOWALLEVENTS","显示所有活动");//Show all events
define("_NOEVENTSPLANNEDTHISWEEK","有没有活动计划在本星期");//There are no events planned this week
define("_NOEVENTSPLANNEDTHISMONTH","有没有活动计划在本月");//There are no events planned this month
define("_NOEVENTSPLANNEDTODAY","有没有活动计划这一天");//There are no events planned this day
define("_SHOWDAYEVENTS","显示这一天的活动");//Show this day&#039;s events
define("_SHOWWEEKEVENTS","显示这周的活动");//Show this week&#039;s events
define("_SHOWMONTHEVENTS","显示这一个月的活动");//Show this month&#039;s events
define("_SUBTITLE","副标题");//Subtitle
define("_SURVEYSTATISTICS","调查报告");//Survey reports
define("_PROJECT","项目");//Project
define("_DEADLINE","截止日期");//Deadline
define("_ADDPROJECT","添加项目");//Add project
define("_PROJECTCREATEDSUCCESSFULLY","项目的成功创建");//Project created successfully
define("_PROJECTUPDATEDSUCCESSFULLY","项目已成功更新");//Project updated successfully
define("_CREATOR","创作者");//Creator
define("_EDITPROJECT","编辑项目");//Edit project
define("_NOPROJECTS","有没有项目，这个节");//There are no projects for this lesson
define("_SURVEYDONE","调查");//Survey done
define("_DONESURVEYUSERS","调查参与者");//Survey participants
define("_SURVEYPREVIEWFORUSER","调查预览用户：");//Survey preview for user:
define("_QUESTIONSKIND","种问题");//Questions types
define("_QUESTIONUPDATEDSUCCESSFULLY","问题的成功更新");//Question updated successfully
define("_QUESTIONFAILEDTOBEUPDATED","问题未能得到更新");//Question failed to be update
define("_INVALIDPERCENTAGE","无效的百分比");//Invalid percentage
define("_PASSEDALLUNITS","看到各单元");//Seen all units
define("_PERCENTAGEUNITS","看到的一小部分单元");//Seen a fraction of units
define("_SPECIFICUNIT","看到一个具体单元");//Seen a specific unit
define("_PASSEDALLTESTS","通过所有测试");//Passed all tests
define("_SPECIFICTEST","通过一个具体的测试");//Passed a specific test
define("_INVALIDCONDITION","无效的条件");//Invalid condition
define("_THEUSERMUSTHAVE","学生必须有");//The student must have
define("_UNITSPERCENTAGE","百分比");//Percentage
define("_SUCCESFULLYADDEDCONDITION","成功的附加条件");//Succesfully added condition
define("_SUCCESFULLYUPDATEDCONDITION","成功更新条件");//Succesfully updated condition
define("_SUCCESFULLYDELETEDCONDITION","成功删除条件");//Succesfully deleted condition
define("_LESSONCONDITIONS","节完成条件");//Lesson completion conditions
define("_ADDCONDITION","添加条件");//Add condition
define("_CONDITION","条件");//Condition
define("_CONDITIONTYPE","条件类型");//Condition type
define("_RELATIONTOOTHERS","与他人的关系");//Relation to others
define("_SCROLLTOTOPOFPAGE","翻阅到返回页首");//Scroll to top of page
define("_SCROLLTOBOTTOMOFPAGE","滚动到页面底部");//Scroll to bottom of page
define("_NOUSERHAVEDONETHISSURVEYYET","没有雇员所做的这项调查，但");//No employee has done this survey yet
define("_SYSTEM","系统");//System
define("_EMAILCONFIGURATIONS","电子邮件服务器配置");//E-mail server configuration
define("_SAWUNIT","设置单元为完成");//Set the unit as completed
define("_NOTSAWUNIT","设置单元未完成");//Set the unit as not completed
define("_CONDITIONSCOMPLETED","条件完成");//Conditions completed
define("_OUTOF","出于");//out of
define("_LESSONPROGRESS","节教师");//Lesson progress
define("_YOUMUSTSEEUNIT","你必须看到单元");//You must see unit
define("_YOUMUSTSEEALLUNITS","你必须看到，各单元");//You must see all units
define("_OFLESSONUNITS","课单元");//of lesson units
define("_YOUMUSTSEE","您必须见");//You must see
define("_YOUMUSTCOMPLETEALLTESTSWITHSCORE","您必须完成所有测试，平均得分");//You must complete all tests with mean score
define("_YOUMUSTCOMPLETETEST","您必须完成测试");//You must complete test
define("_WITHSCORE","与评分");//with score
define("_NOCONDITIONSSET","有没有条件，订定这个节");//There are no conditions set for this lesson
define("_CONDITIONS","条件");//conditions
define("_RESUMELESSON","恢复的节");//Resume lesson
define("_STARTLESSON","开始的节");//Start lesson
define("_TRACKING","跟踪");//Tracking
define("_FORMATCERTIFICATE","格式证书");//Format certificate
define("_TRAFFIC","交通");//Traffic
define("_LESSONTRAFFIC","节交通");//Lesson traffic
define("_EDITTEST","编辑测试");//Edit test
define("_EDITQUESTION","编辑问题");//Edit question
define("_CERTIFICATE","证书");//Certificate
define("_SUCCESFULLYUPDATEDCERTIFICATE","成功更新证书");//Succesfully updated certificate
define("_EDITCONDITION","编辑条件");//Edit condition
define("_SMTPSERVERCONFIGURATIONS","SMTP服务器配置");//SMTP server Configuration
define("_SMTPSERVER","SMTP服务器");//SMTP server
define("_SMTPPASSWORD","的SMTP密码");//SMTP password
define("_SMTPPORT","服务器SMTP端口");//Server SMTP port
define("_TOTALACCESS","总数通道");//Total number of accesses
define("_ACCESSNUMBER","有多少通道");//Number of accesses
define("_LESSONTRAFFICANALYSIS","分析节的交通");//Analysis of Lesson&#039;s Traffic
define("_SETTINGS","设置");//Settings
define("_LESSONACCESS","一些节&#39;通道");//Number of lessons&#039; accesses
define("_ACCESSPERLESSON","有多少通道，每节");//Number of Accesses per Lesson
define("_NOFILESFOUNDDIGITALLIBRARY","有没有任何文件在数字图书馆");//There aren&#039;t any files in the digital library
define("_BLANKFORUNLIMITED","留空无限");//Leave blank for unlimited
define("_CERTIFICATES","证书");//Certificates
define("_NOUSERDATAFOUND","没有雇员的教师数据发现");//No employee progress data found
define("_ISSUECERTIFICATE","问题证书");//Issue certificate
define("_LESSONFILES","节文件");//Lesson files
define("_TOTALACCESSTIME","总存取时间");//Total access time
define("_DEFAULTPAGE","默认页");//Default page
define("_NEWPAGE","新的一页");//New page
define("_UPDATEPAGES","更新页面");//Update pages
define("_PAGECONTENT","网页内容");//Page content
define("_UPDATEPAGE","更新网页");//Update page
define("_TOTALSTATISTICS","总统计");//Total statistics
define("_LOGINS","登录");//Logins
define("_USENONE","使用无");//Use none
define("_PAGEDELETED","网页已删除");//Page deleted
define("_AREYOUSUREYOUWANTTODELETEPAGE","您确定要删除的网页?");//Are you sure you want to delete page?
define("_SUCCESFULLYADDEDPAGE","网页添加成功");//Page added successfully
define("_LESSONMAINPAGE","节主要页");//Lesson main page
define("_GOTOPROJECTS","去项目");//Go to projects
define("_ACCESSSTATISTICS","访问统计");//Access statistics
define("_ANALYTICLOG","解析日志");//Analytic log
define("_SHOWANALYTICLOG","查看解析日志");//Show analytic log
define("_SHOWALLLESSONS","显示所有的经验节");//Show all lessons
define("_CHATROOMDEACTIVATEDBYADMIN","聊天室停用，由管理员");//Chat room deactivated by administrator
define("_IPADDRESS","IP地址");//IP address
define("_YOUHAVEALREADYUPLOADEDAFILE","您已上传的文件");//You have uploaded a file
define("_FILEDELETEDSUCCESSFULLY","文件已成功删除");//File deleted successfully
define("_GRADE","职系");//Grade
define("_PROFESSORCOMMENTS","教师的评论");//Professor comments
define("_DEADLINEPASSEDYOUCANNOLONGERUPLOADFILES","截止日期已经过去了。您可以不再上传文件。");//The deadline has passed. You can no longer upload files.
define("_UPLOADEDFILE","上传的文件");//Uploaded file
define("_CMS","外部网页");//External pages
define("_YOUMAYNOTSIGNUPCONTACTADMINISTRATOR","您可能没有注册;联系系统管理员");//You may not sign up; contact the system administrator
define("_OPERATIONCOMPLETEDSUCCESFULLY","操作成功完成");//Operation completed successfully
define("_REMOVECHOICE","删除选择");//Remove choice
define("_SURVEYDISABLEDSUCCESSFULLY","调查残疾人士成功");//Survey disabled successfully
define("_SURVEYENABLEDSUCCESSFULLY","调查成功启用");//Survey enabled successfully
define("_SURVEYSUBMIT","提交调查");//Submit survey
define("_ROWSPERPAGE","每页上的行数");//Rows per page
define("_FILTER","过滤器");//Filter
define("_OF","出于");//of
define("_SENDALSOVIAEMAIL","发送邀请通过电子邮件");//Send invitation via e-mail
define("_STYLE","作风");//Style
define("_MENU","菜单");//Menu
define("_SELECTION","选择");//Selection
define("_SMTPCONFIGURATIONARECORRECT","该配置的SMTP服务器是正确的");//The configurations of the Smtp server are correct
define("_SMTPCONFIGURATIONERROR","有一个错误的配置，请联络SMTP服务器管理员");//There is an error with the configurations please contact Smtp server administrator
define("_ADDNEWFIELD","添加的新领域");//Add new field
define("_FIELDCREATED","外地的创造");//The field was created
define("_FIELDUPDATED","外地已更新");//The field was updated
define("_LESSONSCORE","节评分");//Lesson score
define("_COMPLETED","完成");//Completed
define("_NOTCOMPLETED","未完成");//Not completed
define("_CONDITIONSMET","条件符合并等待批准");//Conditions met and awaiting approval
define("_STUDENTSTATUSCHANGED","学生的节，成功地改变现状");//Student lesson status changed successfully
define("_MUSTBENUMERIC","必须数字");//Must be numeric
define("_DEFAULTCERTIFICATE","eFront网络学习平台的组织，证明用户名＃ ＃ ＃ ＃ user_surname已成功地完成＃ course_name ＃级＃级＃这证书签发对＃日期＃");//eFront elearning platform organization certifies that \n\n #user_name# #user_surname# \n\n has successfully completed \n #course_name# \n with grade \n\n #grade# \n\nThis certificate was issued on #date#
define("_NOQUESTIONSTOCORRECT","有没有问题，以正确的");//There are no questions to correct
define("_RESTTESTSCORE","评分在其余的测试");//Score at the remaining of the test
define("_CORRECTQUESTION","正确的问题");//Correct question
define("_FILEMANAGER","文件管理员");//File manager
define("_NOFILESFOUND","没有找到文件");//No files found
define("_LASTMODIFIED","最后修改");//Last modified
define("_KB","千字节.");//KB
define("_UPONELEVEL","一水平");//Up one level
define("_DOWNLOADFILE","下载文件");//Download file
define("_ZIPANDDOWNLOAD","压缩文件和下载");//Compress file and download
define("_COMPRESSTOZIP","压缩邮编");//Compress to zip
define("_SELECT","选择");//Select
define("_WITHSELECTEDFILES","与选定的文件");//With selected files
define("_UNCOMPRESS","解压缩");//Uncompress
define("_UNZIPFILE","解压缩文件");//Unzip file
define("_OVERWRITEFILESWITHSAMENAME","覆盖文件具有相同名称");//Overwrite files with the same name
define("_UPLOAD","上传");//Upload
define("_SUCCESFULLYCREATEDFOLDER","文件夹已成功创建");//Folder created successfully
define("_CANNOTDELETEFILE","无法删除文件");//Cannot delete file
define("_FILEWILLUNZIPINFOLDERWITHSAMENAME","该文件将被解压缩在一个文件夹中具有相同名称");//The file will be uncompressed in a folder with the same name
define("_FILEALREADYEXISTS","文件已经存在");//File already exists
define("_ROOTDIR","根文件夹中");//Root folder
define("_GOTOCORRECTQUESTIONS","去的问题，正确的网页");//Go to questions correct page
define("_THEREARE","有");//There are
define("_YOUCANNOTACCESSTHISLESSONORITDOESNOTEXIST","无论您可能无法访问此节，这个节，或不存在");//Either you may not access this lesson, or this lesson does not exist
define("_SHOWSIDEBAR","显示侧栏");//Show sidebar
define("_HIDESIDEBAR","隐藏侧栏");//Hide sidebar
define("_YOURPROJECTSCOREIS","您的评分");//Your score
define("_USERSEXPORTUSINGCSVFORMATCOMMA","导出雇员使用的数据格式（分离“ ， ” ）");//Export employees data using csv format (separated with &quot;,&quot;)
define("_USERSEXPORTUSINGCSVFORMATQM","导出雇员使用的数据格式（分开“ ; ” ）");//Export employees data using csv format (separated with &quot;;&quot;)
define("_SHOWGIVENANSWERS","显示给予的答案");//Show given answers
define("_SHOWRIGHTANSWERS","查看正确答案");//Show correct answers
define("_COULDNOTBESEND","无法寄出");//Could not be sent
define("_ENVIRONMENTALCHECK","环境检查");//Environmental check
define("_REPAIRTREE","还原树");//Restore tree
define("_RULEPROPERTIES","法治的属性");//Rule properties
define("_CONDITIONPROPERTIES","条件属性");//Condition properties
define("_ORPHANLESSONFOLDERSCHECK","孤儿的节，文件夹的所有内容");//Orphan lesson folders check
define("_LESSONSWITHOUTFOLDERSCHECK","节，没有文件夹检查");//Lessons without folders check
define("_FOLDERSWITHOUTALESSONASSOCIATED","下列文件夹中没有一个相关的节");//The following folders do not have a lesson associated
define("_LESSONSWITHOUTAFOLDER","以下节，没有一个文件夹");//The following lessons do not have a folder
define("_PROBLEM","问题");//Problem
define("_CLEANUP","清理");//Clean up
define("_OK","好的");//OK
define("_PEMANENTLYDELETEFOLLOWINGFOLDERS","这一行动将永久地删除下列文件夹");//This action will permanently delete the following folders
define("_PEMANENTLYDELETEFOLLOWINGLESSONS","这一行动将永久删除以下节");//This action will permanently delete the following lessons
define("_CREATEFOLLOWINGLESSONFOLDERS","这一行动将创建文件夹为以下的经验节");//This action will create folders for the following lessons
define("_AREYOUSURE","您是否确定?");//Are you sure?
define("_CHECKAGAIN","再次检查");//Check again
define("_GENERICQUERIES","通用查询");//Generic queries
define("_SENDINFOVIAEMAIL","发送登录信息在电子邮件账户");//Send login information in email account
define("_NOONEHASBEENASSIGNEDTHISPROJECT","这个项目还没有被分配到任何学生");//This project has not been assigned to any student
define("_PROJECTINFO","项目信息");//Project information
define("_ANNOUNCEMENTGO","去公告页");//Go to announcements page
define("_PROJECTAVERAGESCOREFORLESSON","平均分数为节的项目");//Average score for lesson&#039;s projects
define("_NEWPOLL","新的民意调查");//New poll
define("_NOBOOKMARKSFOUND","没有书签发现");//No bookmarks found
define("_FOLDERSTATISTICS","文件夹统计");//Folder statistics
define("_DROPAUNITTOCOPY","下降一个单元，将它复制到指定位置");//Drop a unit to copy it to the designated position
define("_DRAGAUNITTOCOPY","拖曳单元将它复制");//Drag the unit to copy it
define("_ERROR","错误");//Error
define("_ERRORUPLOADINGFILE","错误上传文件");//Error uploading file
define("_EDITANNOUNCEMENT","编辑公告");//Edit announcement
define("_ANNOUNCEMENT","公告");//Announcement
define("_THEFOLLOWINGFOLDERSCOULDNOTBEDELETED","下列文件夹无法删除");//The following folders could not be deleted
define("_SUCCESFULLYCLEANEDUPFOLDERS","成功清理文件夹");//Succesfully cleaned up folders
define("_THEFOLLOWINGLESSONSCOULDNOTBEDELETED","以下的经验节无法删除");//The following lessons could not be deleted
define("_SUCCESFULLYCLEANEDUPLESSONS","成功清理了节");//Succesfully cleaned up lessons
define("_SUCCESFULLYCREATEDLESSONFOLDERS","成功创建文件夹的节");//Succesfully created lesson folders
define("_THEFOLLOWINGLESSONFOLDERSCOULDNOTBECREATED","文件夹以下的节，无法建立");//The folders for the following lessons could not be created
define("_EDITCONTENT","编辑内容");//Edit content
define("_NORMALSTATUS","正常状态");//Normal status
define("_APPLICATIONPENDING","未决申请。按下“送出” ，以核实");//Application pending. Press &quot;Submit&quot to verify
define("_SUCCESS","成功");//Success
define("_WARNING","警告");//Warning
define("_DEFINITIONCOULDNOTBEINSERTED","的定义，无法插入");//Definition could not be inserted
define("_SUCCESFULLYUPDATEDDEFINITION","成功更新的定义");//Succesfully updated definition
define("_SUCCESFULLYDELETEDDEFINITION","成功删除的定义");//Succesfully deleted definition
define("_DEFINITIONCOULDNOTBEUPDATED","deinition无法更新");//Deinition could not be updated
define("_SUBMITTERM","提交任期");//Submit term
define("_EDITDEFINITION","编辑的定义");//Edit definition
define("_NOFOLDERSFOUNDTOCOPYTO","有没有文件夹复制/移动到");//There are no folders to copy/move to
define("_SCORMFILE","SCORM的文件");//SCORM file
define("_SMILIES","笑脸");//Smilies
define("_SURVEYS","调查");//Surveys
define("_MODULES","模块");//Modules
define("_INSTALLMODULE","安装模块");//Install module
define("_COULDNOTOPENZIPFILE","ZIP文件无法打开");//The ZIP file could not be opened
define("_MODULEINFORMATION","模块信息");//Module information
define("_MODULESUCCESFULLYINSTALLED","该模块已成功安装");//The module was successfully installed
define("_DESCRIPTIONFILECOULDNOTBEFOUND","该模块无法安装，因为说明文件， module.xml ，没有被发现。");//The module could not be installed because the description file, module.xml, was not found.
define("_SUCCESFULLYDELETEDMODULE","该模块已成功删除");//The module was successfully deleted
define("_AUTHOR","作者");//Author
define("_VERSION","版本");//Version
define("_THEFIELDSINYOURCSVFILEMUSTCONTAINTHEFOLLOWINGFIELDS","该领域在您的CSV文件必须包含下列领域");//The fields in your csv file must contain the following fields
define("_IFEMPTYNEWPASSWORD","红色领域是强制性的。如果没有密码，给出初始密码将被设置相同的登录。");//Fields in red are mandatory. If there is no password given, the initial password will be set the same as the login.
define("_PLEASECHECKYOURCSVFILEFORMAT","请检查格式的CSV文件");//Please check the format of your CSV file
define("_CERTIFICATEINSTRUCTIONS","使用用户名＃ ＃为使用者的名称，编号user_surname ＃为用户的姓， ＃ course_name ＃课程的名称，编号＃级，一级和＃日期＃日期。");//In the template, use #organization# for organization&#039;s name, #user_name# for user&#039;s name, #user_surname# for user&#039;s surname, #course_name# for course&#039;s name, #grade# for grade and #date# for date.
define("_VOTES","票");//Votes
define("_PERCENTAGE","百分比");//Percentage
define("_CERTIFICATEISSUED","颁发证书");//Certificate issued
define("_ISSUE","问题");//Issue
define("_PROBLEMISSUINGCERTIFICATE","该证书无法发出");//The certificate could not be issued
define("_REVOKECERTIFICATE","撤销证书");//Revoke certificate
define("_VIEWCERTIFICATE","查看证书");//View certificate
define("_CERTIFICATEREVOKED","该证书被撤销成功");//The certificate was revoked successfully
define("_PROBLEMREVOKINGCERTIFICATE","证书不能被撤销");//The certificate could not be revoked
define("_CHECKFORUPDATES","检查更新");//Check for updates
define("_MODULEUPDATE","更新模块");//Update module
define("_PENDING","紧迫的");//Pending
define("_DEADLINEPASSED","限期已通过");//The deadline has passed
define("_PROJECTFINISHED","该项目完成");//The project is finished
define("_FILEUPLOADEDAWAITINGGRADE","该文件上传，但该项目尚未分级。");//The file was uploaded, but the project has not been graded yet.
define("_LOCKDOWN","锁定");//Lock down
define("_LOCKDOWNFROM","锁定系统，从");//Lock down system from
define("_LOCKDOWNTO","锁定系统");//Lock down system to
define("_DISPLAYINDEXMESSAGE","显示通知讯息系统的第一页");//Display notification message to system first page
define("_SETANNOUNCEMENT","设定一个系统公布");//Set a system announcement
define("_NOLESSONSFOUND","没有的经验节，发现");//No lessons found
define("_SUCCESFULLYSETORDER","经验节，以便在课程设置成功");//The lessons order in course was set successfully 
define("_PROBLEMSETTINGORDER","经验节，以便在这个过程中无法定");//The lessons order in the course could not be set
define("_ENABLEDAPI","启用XML的空气污染指数");//Enabled XML API
define("_OLDUPGRADEBACKUPS","旧升级备份");//Old upgrade backups
define("_CLEANUPALL","清理所有");//Clean up all
define("_THISOPERATIONALTERSYSTEM","此操作将永久地删除数据和文件从系统。你绝对肯定?");//This operation will permanently delete data and files from the system. Are you absolutely sure?
define("_SMTPAUTH","SMTP验证");//SMTP authentication
define("_FLAG","国旗");//Flag
define("_SETNORMALPRIORITY","设置优先正常");//Set priority to normal
define("_SETHIGHPRIORITY","设定优先次序，以高");//Set priority to high
define("_YOUMUSTSELECTMESSAGESTOFLAG","您必须选择讯息给国旗");//You must select messages to flag
define("_SYSTEMEMAIL","电子邮件系统");//System email
define("_MAXFILESIZE","文件大小上限");//Maximum file size
define("_SUCCESFULLYUPDATECONFIGURATION","成功更新配置变量");//Succesfully updated configuration variables
define("_COULDNOTUPDATE","无法更新");//Could not update
define("_WITHVALUE","与价值");//with value
define("_INVALIDFIELDDATAFORFIELD","无效的数据为外地");//Invalid data for field
define("_LDAPVARIABLES","LDAP服务器配置");//LDAP server configuration
define("_EMAILCOULDNOTBESENDBECAUSE","该电子邮件无法寄出");//The email could not be sent
define("_EMAILSENDTOYOURADDRESS","电子邮件被发送到您的电子邮件地址");//The email was send to your email address
define("_YOUMUSTFIRSTCREATEDIRECTION","以创造一个节，您必须先建立一个类别");//In order to create a lesson, you must first create a category
define("_SAVEQUESTIONANDCREATENEW","保存问题，并创建另一个");//Save question and create another
define("_SAVEASNEWQUESTION","另存为新问题");//Save as new question
define("_SUCCESFULLYUPDATEDPOLL","这项调查是在成功更新");//The poll was updated successfully
define("_YOUHAVESEENALLCONTENT","您已经完成了所有内容");//You have completed all content
define("_CONDITIONMET","条件满足");//Condition met
define("_CONDITIONNOTMET","条件不符合");//Condition not met
define("_OLDMODULES","旧模块");//Old modules
define("_PHPLDAPEXTENSIONISNOTLOADED","PHP的LDAP的扩展是不加载");//The PHP LDAP extension is not loaded
define("_LESSONCONDITIONSCOMPLETED","你满足节的完全条件。这个节，需要设置完成所教师");//You meet the lesson's complete conditions. This lesson needs to be set as completed by the professor
define("_LESSONCOMPLETE","节完成");//Lesson completed
define("_CERTIFICATEISSUEDSUCCESFULLY","签发的证书成功");//Certificate issued successfully
define("_NOTITLE","无标题");//No title
define("_AUTOMATICCERTIFICATES","自动证书");//Automatic certificates
define("_OFF","远的");//off
define("_POLLDELETEDSUCCESSFULLY","这项调查是在已成功删除");//The poll was deleted successfully
define("_POLLS","调查");//Polls
define("_TWOOPTIONSATMINIMUMREQUIRED","最低的两个不同的方案，都需要调查");//At minimum two different options are required for the poll
define("_POLL","民意调查");//Poll
define("_VOTE","投票");//Vote
define("_YOUHAVEALREADYVOTED","你已经投了票，为这次调查");//You have already voted for this poll
define("_SUCCESFULLYVOTED","您的投票已submited");//Your vote has been submited
define("_VIEWRESULTS","查看结果");//View results
define("_TOTALVOTES","总票数");//Total votes
define("_SUBMITTEST","提交测试");//Submit test
define("_RATEMUSTBEBETWEEN1100","分数必须范围1到100之间");//The score must range between 1 and 100
define("_NUMOFQUESTIONS","若干问题");//Number of questions
define("_TESTDURATION","测试持续时间");//Test duration
define("_QUESTIONSARESHOWN","问题显示");//Questions are shown
define("_YOUCANDOTHETEST","你可以做的测试");//You can do the test
define("_DONETIMESSOFAR","到目前为止，你做了这个测试");//So far you have done this test
define("_ALLTOGETHER","所有一起");//All together
define("_ONEBYONEQUESTIONS","一个又一个");//One by one
define("_TIMES","时代");//times
define("_LDAPACCOUNTPASSWORD","LDAP的账户密码");//LDAP account password
define("_USELDAPACCOUNT","使用您的LDAP账户凭据，以便使用该系统");//Use your LDAP account credentials in order to use the system
define("_ONLYLDAPREGISTRATIONPERMITTED","只有注册使用有效的LDAP账户允许");//Only registration using a valid LDAP account is permitted
define("_GENERALLYAVAILABLE","一般可用");//is generally available
define("_DELETECONDITION","删除条件");//Delete condition
define("_ADDFORUMPOSTONTHISUNIT","论坛会议后的信息，这个单元的");//Post forum message for this unit
define("_AUTOCOMPLETE","自动完成");//Auto complete
define("_DUPLICATESARENOTALLOWED","您不能使用两次同样的节，在一个法治");//You can&#039;t use twice the same lesson in a rule
define("_TIMEINLESSON","时间在一课");//Time in lesson
define("_ACCOUNTACTIVATIONMAILSUBJECT","激活账户的电子邮件");//Account activation email
define("_YOUWILLRECEIVEMAILFORACCOUNTACTIVATION","您会收到一封电子邮件来启动您的账户");//You will receive an email to activate your account
define("_ACCOUNTACTIVATIONMAILBODY","欢迎eFront eLearning的平台。按照下面的链接，以激活您的账户：");//Welcome to eFront eLearning platform. Follow link below to activate your account:
define("_ACCOUNTSUCCESSFULLYACTIVATED","您的账户已成功启动");//Your account was successfully activated
define("_SUCCESSFULLYINSERTEDVALUES","成功插入的价值观");//Successfully inserted values
define("_NEWFORUM","新论坛");//New forum
define("_FORUMS","论坛");//Forums
define("_FORUMADDEDSUCCESSFULLY","论坛的成功添加");//Forum added succesfully
define("_FORUMUPDATEDSUCCESSFULLY","论坛已成功更新");//Forum updated succesfully
define("_ACCESSIBLEBYUSERSOFLESSON","为节");//For lesson
define("_FORUMDELETEDSUCCESSFULLY","论坛已成功删除");//Forum deleted succesfully
define("_ACCESSIBLEBY","到达");//Accessible by
define("_NEWFORUM","新论坛");//New forum
define("_ROOTUNIT","---热门单元----");//---Root unit----
define("_GENERICLESSONINFO","通用节信息");//Generic lesson info
define("_LOGRECORD","日志记录");//Log record
define("_NOFORUMPOSTSYET","有没有职位，在这个论坛上，但");//There are no posts in this forum yet
define("_NOTOPICSFOUNDINTHISFORUM","有没有主题在这个论坛");//There are no topics in this forum
define("_NOMESSAGESFOUNDINTHISTOPIC","有没有讯息在这个主题");//There are no messages in this topic
define("_AVAILABLEFROM","可从");//Available from
define("_SUCCESSFULLYADDEDPOLL","成功将加入调查");//Successfully added poll
define("_RECIPIENT","受赠人");//Recipient
define("_SENDASEMAILALSO","发送电子邮件，也作为");//Send also as email
define("_NOSUBJECT","无主题");//No subject
define("_THEMESSAGEWASNOTSENTASEMAIL","邮件无法通过电子邮件发送");//The message could not be emailed
define("_TOTALLOGINTIME","总时间在系统");//Total time in system
if (defined('MODULE_HCD_INTERFACE') && MODULE_HCD_INTERFACE == 1) {
define("_THENEWFORMOFADDITIVELEARNING","网络学习和人力资本发展");//eLearning and Human Capital Development
define("_AUTOMATICUSERACTIVATION","雇员自动激活");//Automatic employee activation
define("_USERSEXPORT","导出雇员");//Export employees
define("_USERSIMPORT","导入雇员");//Import employees
define("_NEWUSERS","新员工");//New employees
define("_USER","雇员");//Employee
define("_CHOOSEUSER","选择雇员");//Select employee
define("_USERS","雇员");//Employees
define("_ALLSYSTEMUSERS","所有系统雇员");//All system employees
define("_USERSCONNECTEDTOSPECIFICCOURSE","所涉及的雇员与课程");//Employees involved with course
define("_USERSCONNECTEDTOSPECIFICLESSON","所涉及的雇员与节");//Employees involved with lesson
define("_SPECIFICTYPEUSERS","特定类型的员工");//Specific type of employees
define("_USERTYPE","学习者的基本类型");//Basic learner type
define("_ACTIVEUSER","积极雇员");//Active employee
define("_USERDELETED","雇员已删除。");//Employee was deleted.
define("_THEUSER","雇员");//The employee
define("_CHOOSEUSERTODISCONNECT","选择一个雇员断开");//Select a employee to disconnect
define("_LOGOUTUSER","注销雇员");//Log out employee
define("_THEREARENOOTHERUSERSRIGHTNOWINTHISROOM","没有雇员，目前在这聊天室");//No employee currently in this chat room
define("_USERSONLINE","雇员在线");//Employees online
define("_ANDTHEMESSAGESOFUSER","和邮件的员工");//And the messages of employee
define("_ALLUSERS","所有雇员");//All employees
define("_INVALIDUSER","无效的雇员名称");//Invalid employee name
define("_REPLACEEXISTINGUSERS","取代重复的雇员");//Replace duplicate employees
define("_KEEPEXISTINGUSERS","不断重复的雇员");//Keep duplicate employees
define("_NOOTHERUSERSONLINE","没有其它的雇员目前在线");//No other employees currently online
define("_USERNAME","雇员姓名");//Employee name
define("_STATISTICSFORUSER","报告为雇员");//Reports for employee
define("_GENERALUSERINFO","一般员工信息");//General employee information
define("_USERCOMMUNICATIONINFO","雇员的信息沟通");//Employee information on communication
define("_USERUSAGEINFO","雇员的信息系统的使用情况");//Employee information on system usage
define("_THEUSERHASNOTDONEANYTESTSINTHISLESSON","雇员的还没有完成任何测试，在这方面的节");//The employee has not completed any tests in this lesson
define("_USERSTATISTICS","雇员报告");//Employee reports
define("_REPORTSFORUSER","报告的员工");//Reports for employee (New)
define("_OTHERUSERSINROOM","其它雇员在房间内");//Other employees in the room
define("_NOMESSAGESFOUNDFORTHISINTERVALANDUSER","没有邮件，发现为指定的时间间隔，房间和雇员");//No messages found for the specified interval, room and employee
define("_INVITEUSERS","邀请雇员");//Invite employees
define("_SPECIFICUSER","具体的雇员");//Specific employee
define("_ALLACTIVESYSTEMUSERS","所有激活的雇员制度");//All active system employees
define("_WAITINGFORUSER","等待雇员");//Waiting for employee
define("_YOUHAVEINVITEDUSER","您邀请的雇员");//You have invited employee
define("_DEARUSER","亲爱的雇员");//Dear employee
define("_ISVISIBLEFROMOTHERUSERS","可见，从任何雇员?");//Visible from any employee?
define("_CUSTOMIZEUSERSPROFILE","自定义雇员的个人数据");//Customize employee profile
define("_USERAVERAGESCOREFORLESSON","平均分数为节的测试");//Average score for lesson&#039;s tests
define("_USERISONLINE","该雇员是在线");//The employee is online
define("_USERJUSTLOGGEDIN","雇员在刚刚登入");//The employee just logged in
define("_UPDATEUSERSTOLESSONS","指派雇员的节");//Assign employees to lesson
define("_EDITUSERSLESSON","节用户");//Lesson users
define("_NEWUSER","新雇员");//New employee
define("_UPDATEUSERS","更新雇员");//Update employees
define("_EDITUSER","雇员设置");//Employee settings
define("_EDITUSEREDIT","编辑雇员");//Edit employee (New)
define("_ADDUSERSTOSURVEY","新增雇员的调查");//Add employees to the survey
define("_UPDATEUSERTYPES","更新雇员类型");//Update employee types
define("_EDITUSERTYPE","编辑雇员类型");//Edit employee type (New)
define("_OPTIONSUSERTYPEFOR","选择雇员类型");//Options for employee type (New)
define("_NEWUSERTYPE","新雇员类型");//New employee type
define("_BASICUSERTYPE","雇员的基本类型");//Basic employee type
define("_AREYOUSUREYOUWANTTODELETEUSERTYPE","您确定要删除雇员的类型?");//Are you sure you want to delete employee type?
define("_SUCCESFULLYUPDATEDUSERTYPE","雇员型成功更新");//Employee type was updated successfully
define("_SUCCESFULLYADDEDUSERTYPE","雇员类型是添加成功");//Employee type was added successfully
define("_USERSMANAGEMENT","雇员管理");//Employees management
define("_AREYOUSUREYOUWANTTODELETEUSER","您确定要删除的雇员呢?");//Are you sure you want to delete employee?
define("_USERTYPEDELETED","雇员类型删除");//Employee type deleted
define("_EDITUSERSCOURSE","课程雇员");//Course employees
define("_USERDEACTIVATED","雇员停用");//Employee deactivated
define("_USERACTIVATED","雇员激活");//Employee activated
define("_USERSKIND","雇员类型");//Employee types
define("_USERTYPES","雇员类型");//Employee types
define("_SMTPUSER","的SMTP登录");//SMTP login
define("_USERCREATED","雇员创造");//Employee created
define("_USERTRAFFIC","雇员的交通");//Employee&#039;s traffic
define("_USERSPROGRESS","雇员的地位");//Employees status
define("_THEUSERHASNOTCOMPLETEDTHELESSON","雇员的还没有完成，但这个节");//The employee has not completed this lesson yet
define("_MOSTACTIVEUSERS","最激活的雇员");//Most active employees
define("_5MOSTACTIVEUSERS","5最激活的雇员");//5 most active employees
define("_NOUSERFORTHISSURVEYYET","没有雇员，但本次调查.");//No employees for this survey yet.
define("_SHOWALLUSERS","显示所有雇员");//Show all employees
define("_THEREARENOLESSONSDEFINEDFORTHEUSERLANGUAGE","有没有经验节的定义为雇员的语言");//There are no lessons defined for the employees&#39;s language
define("_VIEWUSERLESSONPROGRESS","鉴于学生的教师，整个的节");//View the student progress throughout the lesson
define("_USERCAPITAL","雇员");//Employee
define("_USERSDATA","汇入/汇出雇员");//Import/Export employees
define("_ORPHANUSERFOLDERSCHECK","孤儿雇员文件夹检查");//Orphan employee folders check
define("_USERSWITHOUTFOLDERSCHECK","雇员没有文件夹检查");//Employees without folders check
define("_FOLDERSWITHOUTAUSERASSOCIATED","下列文件夹中没有一个相关的雇员");//The following folders do not have a employee associated
define("_USERSWITHOUTAFOLDER","以下的雇员没有一个文件夹");//The following employees do not have a folder
define("_PEMANENTLYDELETEFOLLOWINGUSERS","这一行动将永久删除以下雇员");//This action will permanently delete the following employees
define("_CREATEFOLLOWINGUSERFOLDERS","这一行动将创建文件夹为以下雇员");//This action will create folders for the following employees
define("_USERPROGRESS","雇员教师");//Employee progress
define("_LOGOUTUSERS","注销雇员在线");//Log out employees online
define("_USERTRACKINGINFORMATION","雇员跟踪信息");//Employee tracking information
define("_MAILUSERACTIVATION","雇员激活通过电子邮件");//Employee activation by email
define("_USERSMAYADDFORUMS","雇员可添加论坛");//Employees may add forums
define("_NONEWAPPLICATIONS","没有申请新雇员");//No application from new employees
define("_EXPORTUSERSDATA","导出雇员数据");//Export employees data
define("_IMPORTUSERSDATA","导入雇员资料");//Import employees data
define("_THEUSERHASNOTBEENASSIGNEDANYPROJECT","没有项目已分配给这名雇员");//No project has been assigned to this employee
define("_SUCCESFULLYCLEANEDUPUSERS","成功清理雇员");//Succesfully cleaned up employees
define("_SUCCESFULLYCREATEDUSERFOLDERS","成功地建立了雇员的文件夹");//Succesfully created employee folders
define("_THEFOLLOWINGUSERFOLDERSCOULDNOTBECREATED","以下雇员的文件夹无法创建");//The following employee folders could not be created
define("_GROUP","雇员组");//Employee group
define("_USERSINFO","雇员信息");//Employees info
define("_PROFESSORSINFO","教师信息");//Professors info
define("_EMPLOYEEWASASSIGNEDGROUP","雇员被分配到组");//Employee was assigned to group
define("_EMPLOYEEWASRELEASEDFROMGROUP","雇员被释放，从组");//Employee was released from group
define("_PROFESSORCAPITAL","教师");//Professor
define("_STUDENTROLE","雇员的作用");//Employee role
define("_PROFESSORROLE","教师的作用");//Professor role
} else {
define("_THENEWFORMOFADDITIVELEARNING","网络学习和人力资本发展");//Refreshing eLearning
define("_AUTOMATICUSERACTIVATION","雇员自动激活");//Automatic user activation
define("_USERSEXPORT","导出雇员");//Export users
define("_USERSIMPORT","导入雇员");//Import users
define("_NEWUSERS","新员工");//New users
define("_USER","雇员");//User
define("_CHOOSEUSER","选择雇员");//Select user
define("_USERS","雇员");//Users
define("_ALLSYSTEMUSERS","所有系统雇员");//All system users
define("_USERSCONNECTEDTOSPECIFICCOURSE","所涉及的雇员与课程");//Users involved with specific course
define("_USERSCONNECTEDTOSPECIFICLESSON","所涉及的雇员与节");//Users involved with specific lesson
define("_SPECIFICTYPEUSERS","特定类型的员工");//Specific type of users
define("_USERTYPE","学习者的基本类型");//User type
define("_ACTIVEUSER","积极雇员");//Active user
define("_USERDELETED","雇员已删除。");//User deleted.
define("_THEUSER","雇员");//The user
define("_CHOOSEUSERTODISCONNECT","选择一个雇员断开");//Select a user to disconnect
define("_LOGOUTUSER","注销雇员");//Log out user
define("_THEREARENOOTHERUSERSRIGHTNOWINTHISROOM","没有雇员，目前在这聊天室");//No user currently in this chat room
define("_USERSONLINE","雇员在线");//Users online
define("_ANDTHEMESSAGESOFUSER","和邮件的员工");//And the messages of user
define("_ALLUSERS","所有雇员");//All users
define("_INVALIDUSER","无效的雇员名称");//Invalid user name
define("_REPLACEEXISTINGUSERS","取代重复的雇员");//Replace duplicate users
define("_KEEPEXISTINGUSERS","不断重复的雇员");//Keep duplicate users
define("_NOOTHERUSERSONLINE","没有其它的雇员目前在线");//No other users currently online
define("_USERNAME","雇员姓名");//User name
define("_STATISTICSFORUSER","报告为雇员");//Reports for user
define("_GENERALUSERINFO","一般员工信息");//General user information
define("_USERCOMMUNICATIONINFO","雇员的信息沟通");//User information on communication
define("_USERUSAGEINFO","雇员的信息系统的使用情况");//User information on system usage
define("_THEUSERHASNOTDONEANYTESTSINTHISLESSON","雇员的还没有完成任何测试，在这方面的节");//The user has not completed any tests in this lesson
define("_USERSTATISTICS","雇员报告");//User reports
define("_REPORTSFORUSER","用户报告");//Reports for user (New)
define("_OTHERUSERSINROOM","其它雇员在房间内");//Other users in the room
define("_NOMESSAGESFOUNDFORTHISINTERVALANDUSER","没有邮件，发现为指定的时间间隔，房间和雇员");//No messages found for the specified interval, room and user
define("_INVITEUSERS","邀请雇员");//Invite users
define("_SPECIFICUSER","具体的雇员");//Specific user
define("_ALLACTIVESYSTEMUSERS","所有激活的雇员制度");//All active system users
define("_WAITINGFORUSER","等待雇员");//Waiting for user
define("_YOUHAVEINVITEDUSER","您邀请的雇员");//You have invited user
define("_DEARUSER","亲爱的雇员");//Dear user
define("_ISVISIBLEFROMOTHERUSERS","可见，从任何雇员?");//Visible from any user?
define("_CUSTOMIZEUSERSPROFILE","自定义雇员的个人数据");//Customize user profile
define("_USERISONLINE","该雇员是在线");//The user is online
define("_USERJUSTLOGGEDIN","雇员在刚刚登入");//The user just logged in
define("_UPDATEUSERSTOLESSONS","指派雇员的节");//Select lesson users
define("_EDITUSERSLESSON","节用户");//Lesson users
define("_NEWUSER","新雇员");//New user
define("_UPDATEUSERS","更新雇员");//Update users
define("_EDITUSER","雇员设置");//User settings
define("_EDITUSEREDIT","编辑用户");//Edit user (New)
define("_ADDUSERSTOSURVEY","新增雇员的调查");//Add users to the survey
define("_UPDATEUSERTYPES","更新雇员类型");//Update user types
define("_EDITUSERTYPE","编辑用户类型");//Edit user type (New)
define("_OPTIONSUSERTYPEFOR","选择用户类型");//Options for user type (New)
define("_NEWUSERTYPE","新雇员类型");//New user type
define("_BASICUSERTYPE","雇员的基本类型");//Basic user type
define("_AREYOUSUREYOUWANTTODELETEUSERTYPE","您确定要删除雇员的类型?");//Are you sure you want to delete user type?
define("_SUCCESFULLYUPDATEDUSERTYPE","雇员型成功更新");//User type was updated successfully
define("_SUCCESFULLYADDEDUSERTYPE","雇员类型是添加成功");//User type was added successfully
define("_USERSMANAGEMENT","雇员管理");//Users management
define("_AREYOUSUREYOUWANTTODELETEUSER","您确定要删除的雇员呢?");//Are you sure you want to delete user?
define("_USERTYPEDELETED","雇员类型删除");//User type deleted
define("_EDITUSERSCOURSE","课程雇员");//Course users
define("_USERDEACTIVATED","雇员停用");//User deactivated
define("_USERACTIVATED","雇员激活");//User activated
define("_USERSKIND","雇员类型");//User types
define("_USERTYPES","雇员类型");//User types
define("_SMTPUSER","的SMTP登录");//SMTP user
define("_USERCREATED","雇员创造");//User created
define("_USERTRAFFIC","雇员的交通");//User&#039;s traffic
define("_USERSPROGRESS","雇员的地位");//Users status
define("_THEUSERHASNOTCOMPLETEDTHELESSON","雇员的还没有完成，但这个节");//The user has not completed this lesson yet
define("_MOSTACTIVEUSERS","最激活的雇员");//Most active users
define("_5MOSTACTIVEUSERS","5最激活的雇员");//5 most active users
define("_NOUSERFORTHISSURVEYYET","没有雇员，但本次调查.");//No users for this survey yet.
define("_SHOWALLUSERS","显示所有雇员");//Show all users
define("_THEREARENOLESSONSDEFINEDFORTHEUSERLANGUAGE","有没有经验节的定义为雇员的语言");//There are no lessons defined for the users&#39;s language
define("_VIEWUSERLESSONPROGRESS","鉴于学生的教师，整个的节");//View the student progress throughout the lesson
define("_USERCAPITAL","雇员");//User
define("_USERSDATA","汇入/汇出雇员");//Import/Export users
define("_ORPHANUSERFOLDERSCHECK","孤儿雇员文件夹检查");//Orphan user folders check
define("_USERSWITHOUTFOLDERSCHECK","雇员没有文件夹检查");//Users without folders check
define("_FOLDERSWITHOUTAUSERASSOCIATED","下列文件夹中没有一个相关的雇员");//The following folders do not have a user associated
define("_USERSWITHOUTAFOLDER","以下的雇员没有一个文件夹");//The following users do not have a folder
define("_PEMANENTLYDELETEFOLLOWINGUSERS","这一行动将永久删除以下雇员");//This action will permanently delete the following users
define("_CREATEFOLLOWINGUSERFOLDERS","这一行动将创建文件夹为以下雇员");//This action will create folders for the following users
define("_USERPROGRESS","雇员教师");//User progress
define("_LOGOUTUSERS","注销雇员在线");//Log out users online
define("_USERTRACKINGINFORMATION","雇员跟踪信息");//User tracking information
define("_MAILUSERACTIVATION","雇员激活通过电子邮件");//User activation by email
define("_USERSMAYADDFORUMS","雇员可添加论坛");//Users may add forums
define("_NONEWAPPLICATIONS","没有申请新雇员");//No application from new users
define("_EXPORTUSERSDATA","导出雇员数据");//Export users data
define("_IMPORTUSERSDATA","导入雇员资料");//Import users data
define("_THEUSERHASNOTBEENASSIGNEDANYPROJECT","没有项目已分配给这名雇员");//No project has been assigned to this user
define("_SUCCESFULLYCLEANEDUPUSERS","成功清理雇员");//Succesfully cleaned up users
define("_SUCCESFULLYCREATEDUSERFOLDERS","成功地建立了雇员的文件夹");//Succesfully created user folders
define("_THEFOLLOWINGUSERFOLDERSCOULDNOTBECREATED","以下雇员的文件夹无法创建");//The following user folders could not be created
define("_GROUP","雇员组");//User group
define("_USERSINFO","雇员信息");//Users info
define("_PROFESSORSINFO","教师信息");//Professors info
define("_EMPLOYEEWASASSIGNEDGROUP","雇员被分配到组");//User was assigned to group
define("_EMPLOYEEWASRELEASEDFROMGROUP","雇员被释放，从组");//User was released from group
define("_PROFESSORCAPITAL","教师");//Professor
define("_STUDENTROLE","雇员的作用");//Student role
define("_PROFESSORROLE","教师的作用");//Professor role
}
define("_COURSES","课程");//Courses
define("_COURSEDELETED","课程删除");//Course deleted
define("_COURSEDEACTIVATED","课程停用");//Course deactivated
define("_COURSEACTIVATED","课程激活");//Course activated
define("_COURSENAME","课程名称");//Course name
define("_COURSEUPDATED","课程更新");//Course updated
define("_SUCCESFULLYCREATEDCOURSE","课程，成功创建");//Course was created successfully
define("_COURSEOPTIONSFOR","课程选择");//Options for course
define("_NEWCOURSEOPTIONS","新课程的选择");//New course options
define("_EDITCOURSE","编辑过程中");//Edit course
define("_EDITLESSONSCOURSE","课程，节");//Course lessons
define("_NEWCOURSE","新课程");//New course
define("_UPDATECOURSES","更新课程");//Update courses
define("_COURSE","课程");//Course
define("_COURSEONLY","课程，仅通过");//Exclusively through course
define("_AREYOUSUREYOUWANTTODELETECOURSE","您确定要删除课程?");//Are you sure you want to delete course?
define("_NOCOURSESFOUND","没有课程的定义");//No courses defined
define("_UPDATEEMPLOYEES","更新雇员");//Update employees
define("_NEWJOB","指派新的就业");//Assign new job
define("_AREYOUSUREYOUWANTTOCANCELJOB","您确定要取消这名雇员从这个工作。");//Are you sure you want to cancel this employee from this job.
define("_AREYOUSUREYOUWANTTOFIREEMPLOYEE","您确定要小心防火这名雇员从该公司?");//Are you sure you want to fire this employee from the company?
define("_FIRE","火");//Fire
define("_WAGE","工资");//Wage
define("_VATREGNUMBER","增值税reg.no.");//VAT Reg.No.
define("_HIREDON","雇用的");//Hired on
define("_SUPERVISOR","监");//Supervisor
define("_JOBDESCRIPTIONS","职务说明");//Job descriptions
define("_EMPLOYEERELEASEDFROMJOB","雇员发表的求职者");//Employee released from job
define("_SKILLS","技能");//Skills
define("_SKILL","技能");//Skill
define("_SPECIFICATION","规格");//Specification
define("_DETAILS","详情");//Details
define("_PLACEMENTS","位置");//Placements
define("_JOBALREADYASSIGNED","选定的位置是已经分配给这名雇员");//Selected placement is already assigned to this employee
define("_BRANCHNAME","分公司名称");//Branch name
define("_EMPLOYEEPOSITION","雇员的立场");//Employee position
define("_JOBDESCRIPTION","职位描述");//Job description
define("_UPDATEBRANCHES","更新党支部");//Update branches
define("_NEWBRANCH","新科");//New branch
define("_FATHERBRANCHNAME","父亲科");//Father branch
define("_BRANCHES","党支部");//Branches
define("_BRANCHDELETED","科删除");//Branch deleted
define("_AREYOUSUREYOUWANTTODISMISSTHEBRANCH","您确定要取消该分公司?");//Are you sure you want to dismiss that branch?
define("_COUNTRY","国籍");//Country
define("_TELEPHONE","电话");//Telephone
define("_BRANCHRECORD","科创纪录");//Branch record
define("_BRANCHDATAUPDATED","分行的数据更新");//Branch data updated
define("_FATHERBRANCH","父亲科");//Father branch
define("_HCD","人力资本开发");//Human Capital Development
define("_ORGANISATIONCHART","组织架构图");//Organisation chart
define("_CANDIDATES","候选人");//Candidates
define("_SUCCSSFULLYCREATEDBRANCH","科已成功创建");//Branch was successfully created
define("_ATBRANCH","在科");// at branch 
define("_FATHERBRANCHCOULDNOTBESET","目标父亲分行不能成立，因为它是劣，这科在层次结构");//Target father branch could not be set, because it is inferior to this branch in the hierarchy
define("_JOBSASSIGNED","工作分配");//Jobs assigned
define("_AREYOUSUREYOUWANTTOREMOVETHATSKILL","您确定要删除的技能从名单中?");//Are you sure you want to remove that skill from the list?
define("_SKILLDATA","技巧数据");//Skill data
define("_NEWSKILL","新技能");//New skill
define("_SKILLDESCRIPTION","技能描述");//Skill description
define("_HAVINGSKILL","有技巧");// having the skill 
define("_EMPLOYEESWITHTHATSKILL","雇员技能");//Employees with skill
define("_UPDATESKILLS","更新技能");//Update skills
define("_THISSKILLSELEMENTSCOULDNOTBEDELETED","此技能无法删除");//This skill could not be deleted
define("_SKILLDATAUPDATED","技能说明更新");//Skill description updated
define("_SKILLCOULDNOTBECREATED","技能无法建立");//Skill could not be created
define("_SUCCESSFULLYCREATEDSKILL","技能创造成功");//Skill created successfully
define("_SKILLDELETED","技能删除");//Skill deleted
define("_NOEMPLOYEESPOSSESSSKILL","没有雇员拥有这种技巧");//No employees possess this skill
define("_NOEMPLOYEESWORKATBRANCH","没有工作的雇员目前在这个科");//No employees currently work at this branch
define("_UPDATEJOBDESCRIPTIONS","更新的职务说明");//Update job descriptions
define("_NEWJOBDESCRIPTION","新的职务说明");//New job description
define("_CURRENTLYEMPLOYEED","目前受聘");//Currently employed
define("_VACANCIES","可配售");//Available placements
define("_AREYOUSUREYOUWANTTOREMOVETHATJOBDESCRIPTION","您确定要删除的就业说明?");//Are you sure you want to remove that job description?
define("_JOBDESCRIPTIONDATA","职位描述数据");//Job description data
define("_HAVINGJOBDESCRIPTION","有职位描述");// having the job description 
define("_NOEMPLOYEESPOSSESSJOBDESCRIPTION" , "No employees are currently assigned to this job description");
define("_SUCCESSFULLYCREATEDJOBDESCRIPTION","成功地建立了职位描述");//Successfully created job description
define("_JOBDESCRIPTIONCOULDNOTBECREATED","职位描述无法创建");//Job description could not be created
define("_JOBDESCRIPTIONDATAUPDATED","职位描述数据已成功更新");//Job description data were successfully updated
define("_JOBDESCRIPTIONDELETED","职位描述删除");//Job description deleted
define("_THISJOBDESCRIPTIONSELEMENTSCOULDNOTBEDELETED","该职位描述的元素无法删除");//The job description&#039;s elements could not be deleted
define("_EDITJOBDESCRIPTION","编辑职位描述");//Edit job description
define("_SKILLSREQUIRED","所需技能");//Skills desired
define("_EMPLOYEESOFBRANCH","雇员科");//Employees of branch
define("_EMPLOYEESWITHSKILL","雇员技能");//Employees with skill
define("_FILERECORD","文件记录");//File record
define("_VIEW","查看");//View
define("_SORRYYOUDONOTHAVEPERMISSIONTOPERFORMTHISACTION","对不起，您没有权限执行此操作");//Sorry you do not have the permission to perform this action
define("_MOBILEPHONE","移动电话");//Mobile phone
define("_EMPLOYEESDATASUCCESSFULLYUPDATED","雇员数据成功更新");//Employee data successfully updated
define("_EMPLOYEESRECORDCOULDNOTBEUPDATED","雇员的记录无法更新");//Employee record could not be updated
define("_NOPLACEMENTSASSIGNEDYET","没有位置的分配，但");//No placements assigned yet
define("_BRANCHCOULDNOTBECREATED","科无法建立");//Branch could not be created
define("_NOSKILLSHAVEBEENREGISTERED","没有技能，已登记");//No skills have been registered
define("_NOJOBDESCRIPTIONSHAVEBEENREGISTERED","没有工作，说明已登记");//No job descriptions have been registered
define("_PLACEMENTCOULDNOTBEASSIGNED","就业不能被指派");//Placement could not be assigned
define("_NOSKILLSASSIGNED","没有技能分配");//No skills assigned
define("_NOSKILLSREGISTEREDASPREREQUISITES","没有技能，登记为先决条件");//No skills registered as prerequisites
define("_SATISFYANYCRITERIA","满足任何准则");//Satisfy any criteria
define("_SATISFYALLCRITERIA","满足所有的准则");//Satisfy all criteria
define("_WORKINGATBRANCH","工作在科");//Working at branch
define("_WITHJOBDESCRIPTION" ,"With job description");
define("_FINDEMPLOYEES","寻找员工");//Find employees (New)
define("_WITHSKILL","与技巧");//With skill
define("_EMPLOYEESFULFILLINGCRITERIA","雇员履行的准则");//Employees fulfilling the criteria
define("_NOEMPLOYEESFULFILLTHESPECIFIEDCRITERIA","没有雇员，完成指定的标准");//No employees fulfill the specified criteria
define("_ORGANIZATIONCHARTTREE","组织结构图树");//Organization chart tree
define("_ANYBRANCH","任何分行");//Any branch
define("_ANYJOBDESCRIPTION","任何职位描述");//Any job description
define("_EXPORTVACANCIES","导出空缺");//Export vacancies
define("_NATIONALSERVICECOMPLETED","国民服务");//National service
define("_DRIVINGLICENSE","驾驶执照");//Driver license
define("_BANKACCOUNT","账户");//Account
define("_BANK","银行");//Bank
define("_TAXOFFICE","国税厅");//Tax office
define("_POLICEIDNUMBER","警方编号");//Police id
define("_WORKPERMISSIONDATA","工作许可数据");//Work permission data
define("_WAYOFWORKING","工作");//Working as
define("_EMPLOYMENTTYPE","就业类别");//Employement type
define("_MARRIED","已婚");//Married
define("_SINGLE","单个");//Single
define("_MARITALSTATUS","婚姻状况");//Marital status
define("_FEMALE","女性");//Female
define("_MALE","男性");//Male
define("_GENDER","性别");//Gender
define("_FATHERNAME","父亲姓名");//Father name
define("_MOTHERTONGUE","母语");//Mother tongue
define("_NATIONALITY","国籍");//Nationality
define("_PARTTIME","部份时间");//Part time
define("_FULLTIME","全职");//Full time
define("_BIRTHDAY","生日");//Birthday
define("_BIRTHPLACE","出生的城市");//City of birth
define("_BIRTHCOUNTRY","出生国家");//Country of birth
define("_EMPLOYEES","雇员");//Employees
define("_NEWEMPLOYEE","新雇员");//New employee
define("_OFFICE","办公室");//Office
define("_COMPANYINTERNALPHONE","公司内部电话");//Company internal phone
define("_EMPLOYEECREATED","雇员已成功创建");//Employee created successfully
define("_EMPLOYEEDELETED","雇员删除");//Employee deleted
define("_SKILLSOFFERED","技能提供");//Skills offered
define("_NOSKILLSOFFERED","没有技能提供");//No skills offered
define("_NOJOBDESCRIPTIONSSHAVEBEENREGISTERED","没有工作，说明已登记");//No job descriptions have been registered
define("_INSERTEDINTOTHESYSTEM","插入到系统");//Inserted into the system
define("_HIRED","聘请");//Hired
define("_RAISEOF","提高");//Raise of
define("_EMPLOYEESNEWWAGEIS","雇员的新的工资是");//The employee&#039;s new wage is
define("_DECREASEOF","减少");//Decrease of
define("_EMPLOYEEWASASSIGNEDJOB","雇员被指派的工作");//Employee was assigned job
define("_EMPLOYEEWASRELEASEDFROMDJOB","雇员被释放，从就业");//Employee was released from job
define("_EMPLOYEEWASASSIGNEDSKILL","雇员被指派的技巧");//Employee was assigned skill
define("_WASRELEASEDFROMEMPLOYEE","被释放的雇员");//was released from employee
define("_EMPLOYEESSKILLSPECIFICATIONSFORSKILL","雇员的技能，技巧的规格");//Employee&#039;s skill specifications for skill
define("_WERECHANGEDTO","改为");//were changed to
define("_FIRED","发射");//Fired
define("_NOHISTORYREGARDINGTHISEMPLOYEE","历史上没有关于这名雇员记录");//No history regarding this employee recorded
define("_HISTORYOFEMPLOYEE","历史雇员");//History of employee
define("_HISTORY","历史");//History
define("_NOANNOUNCEMENTSPOSTEDADMIN","没有张贴公告");//No announcements posted
define("_SEPARATEMULTIPLEUSERS","分隔多个受助人;");//Separate multiple recipients with ;
define("_STARTTYPINGFORRELEVENTMATCHES","开始输入，以获取有关比赛（键入％ ，为所有）");//Start typing to get relevant matches (Type % for all)
define("_ADVANCEDSEARCH","高级搜索选项");//Advanced search options
define("_REGISTERADVANCEDSEARCHFIELDS","注册进阶搜寻字段");//Register advanced search fields
define("_EDITBRANCH","编辑科");//Edit branch
define("_ASSIGNEMPLOYEES","指派员工");//Assign employees
define("_ASSIGNEMPLOYEESTOBRANCH","指派员工分行");//Assign employees to branch 
define("_EDITSKILL","编辑技巧");//Edit skill
define("_ASSIGNSKILL","转让的技术");//Assign skill
define("_ASSIGNEMPLOYEESTHESKILL","指派员工技能");//Assign employees the skill 
define("_NOBRANCHESHAVEBEENREGISTERED","没有分行已登记");//No branches have been registered
define("_ORGANIZATION","组织");//Organization
define("_SEARCHFOREMPLOYEE","搜索为雇员[组织准则]");//Search for employee [Organization criteria]
define("_SUBFORUMS","subforums");//Subforums
define("_NOSUBFORUMSFOUND","有没有subforums界定在这个论坛");//There are no subforums defined in this forum
define("_NONEWMESSAGELOCKED","您无法张贴任何新的讯息，因为这个题目或论坛被锁定");//You cannot post any new messages because this topic or forum is locked
define("_ACTIVITY","活动");//Activity
define("_ISVALID","有效");//Valid
define("_LEFTON","左对");//Left on
define("_ADVANCED","先进标准");//Advanced criteria
define("_MYSTUDENTS","我的学生");//My students
define("_EMPLOYEE","雇员");//Employee
define("_NOBRANCHJOBSERROR","没有工作，说明已登记为这个分支");//No job descriptions have been registered for this branch
define("_TESTSTATISTICS","测试报告");//Tests reports
define("_CHOOSETEST","选择测试");//Choose test
define("_USERPROFILE","用户配置文件");//User profile
define("_VIEWBRANCHES","鉴于党支部");//View branches
define("_NOEMPLOYEESFOUND","没有雇员被发现");//No employees were found
define("_SEARCHEMPLOYEE","搜索雇员");//Search employee
define("_ALLBRANCHES","所有分行");//All branches
define("_ANSWERS","答案");//Answers
define("_GROUPDOESNOTEXIST","该组不存在");//The group doesn&#039;t exist
define("_SUBBRANCHES","分理处");//Sub-branches
define("_OFBRANCH","分行");// of branch 
define("_NEWSUBBRANCH","新的分支行");//New sub-branch
define("_SMTPTIMEOUT","的SMTP超时");//SMTP timeout
define("_ILLEGALPATH","非法路径");//Illegal path
define("_FILEWASPARTIALLYUPLOADED","上传的文件只有部分上传");//The uploaded file was only partially uploaded
define("_NOFILEUPLOADED","没有文件被上传");//No file was uploaded
define("_NOTMPDIR","失踪系统上传临时文件夹中。请更新php.ini中设置相应的");//Missing a system upload temporary folder. Please update php.ini settings accordingly
define("_UPLOADCANTWRITE","无法写入文件到磁盘");//Failed to write file to disk
define("_UPLOADERREXTENSION","文件上传停止扩建");//File upload stopped by extension
define("_CANNOTCOPYFILE","该文件不能被复制");//The file cannot be copied
define("_CANNOTMOVEFILE","该文件无法移动");//The file cannot be moved
define("_DIRECTORYDOESNOTEXIST","目录不存在");//The directory does not exist
define("_COULDNOTCREATEDIRECTORY","目录无法创建");//The directory could not be created
define("_CANNOTCOPYDIRECTORY","目录无法复制");//The directory cannot be copied
define("_DIRECTORYALREADYEXISTS","目录已经存在");//The directory already exists
define("_AUTOASSIGNTONEWUSERS","自动分配给新用户");//Automatically assign to new users
define("_CANNOTOPENCOMPRESSEDFILE","压缩文件无法打开");//The compressed file cannot be opened
define("_CHOOSEWHATTODELETE","选择要删除系统初始化期间");//Choose what to delete during system initialization
define("_PERIODS","期");//Periods
define("_IMPORTLESSON","导入的节");//Import lesson
define("_EXPORTLESSON","导出的节");//Export lesson
define("_LESSONEXPORTEDSUCCESFULLY","的节，成功地导出");//Lesson succesfully exported
define("_LESSONIMPORTEDSUCCESFULLY","的节，成功导入");//Lesson succesfully imported
define("_FILESIZEMUSTBESMALLERTHAN","该文件必须小于");//The file must be smaller than
define("_PROBLEMIMPORTINGFILE","问题的导入文件");//Problem importing file
define("_PAGE","页");//Page
define("_ACTIVE_PROJECTS","激活");//Active
define("_INACTIVE_PROJECTS","未激活");//Inactive
define("_TIMEREMAIN","保持");//Remain
define("_WEEKS","周");//weeks
define("_WEEKs","周");//week
define("_DAYS","天");//days
define("_DAY","白天");//Day
define("_EVALUATIONDATAUPDATED","评价数据更新成功");//Evaluation data updated successfully
define("_EVALUATION","评价");//Evaluation
define("_EVALUATIONOFEMPLOYEE","评价雇员");//Evaluation of employee
define("_NEWEVALUATION","新的评价");//New evaluation
define("_EVALUATIONCOMMENT","评价评论");//Evaluation comment
define("_EVALUATIONDELETED","评价删除");//Evaluation deleted
define("_THEEVALUATIONCOULDNOTBEDELETED","评价无法删除");//The evaluation could not be deleted
define("_SUCCESSFULLYCREATEDEVALUATION","成功地建立了评价");//Successfully created evaluation
define("_EVALUATIONCOULDNOTBECREATED","评价无法建立");//Evaluation could not be created
define("_AREYOUSUREYOUWANTTODELETEEVALUATION","您确定要删除评价?");//Are you sure you want to delete the evaluation?
define("_NOEVALUATIONSASSIGNEDYET","没有书面评价，但");//No evaluation written yet
define("_BRANCH","分支");//Branch
define("_PLACEMENT","安置");//Placement
define("_EVALUATIONS","评价");//Evaluations
define("_TRANSPORTMEANS","运输途径");//Means of transport
define("_YOUCANNOTDELETESOMEELSESEVALUATION","您不能删除评价的书面交由另一名用户");//You cannot delete an evaluation written by another user
define("_YOUCANNOTEDITSOMEELSESEVALUATION","您不能编辑评价书面交由另一名用户");//You cannot edit an evaluation written by another user
define("_EMPLOYEEFORM","雇员的形式");//Employee form
define("_EMPLOYEEFORMPRINTPREVIEW","雇员的形式打印预览");//Employee form print preview
define("_PRINTPREVIEW","打印预览");//Print preview
define("_PRINTEMPLOYEEFORM","打印雇员的形式");//Print employee form
define("_PRINT","打印");//Print
define("_NOSPECIFICJOB","没有具体的职位描述");//No specific job description
define("_GROUPS","用户群体");//User groups
define("_NEWGROUP","新组");//New group
define("_NOGROUPSDEFINED","没有团体的定义");//No groups defined
define("_UPDATEGROUPS","更新团体");//Update groups
define("_GROUPDEACTIVATED","该组已停用");//The group was deactivated
define("_GROUPACTIVATED","该组被激活");//The group was activated
define("_EDITGROUP","编辑组");//Edit group
define("_UPDATEGROUP","更新组");//Update group
define("_SUCCESFULLYADDEDGROUP","该组已成功加入");//The group was succesfully added
define("_AREYOUSUREYOUWANTTODELETEGROUP","是您确定要删除该组?");//Are you sure you want to delete the group?
define("_GROUPDELETED","该组已删除");//The group was deleted
define("_GROUPFILTER","组过滤器");//Group filter
define("_NOUSERSFOUND","无用户那里发现");//No users where found
define("_SEPARATEALTERNATIVESEXAMPLE","单独的替代正确答案，与| ，例如：蓝|黑|白");//Separate alternative correct answers with |, for example: Blue|Black|White
define("_CREATERANODOMTEST","创建随机测试");//Create random test
define("_USING","使用");//Using
define("_EASY","容易的");//Easy
define("_HARD","硬的");//Hard
define("_LOCALESETTINGS","区域设置");//Locale settings
define("_CURRENCY","货币");//Currency
define("_DECIMALPOINT","小数点");//Decimal point
define("_THOUSANDSSEPARATOR","千位分隔符");//Thousands separator
define("_DATEFORMAT","日期格式");//Date format
define("_SPECIFICLOCALE","具体位置");//Specific locale
define("_LOCATION","位置");//Location
define("_TIMEZONE","时区");//Time zone
define("_INVALIDRECIPIENT","无效的收件者");//Invalid recipient
define("_NOBRANCHSELECTED","没有科被选为");//No branch was selected
define("_AREYOUSUREYOUWANTTODELETEPROJECT","您确定您要删除的这个项目呢?");//Are you sure that you want to delete this project?
define("_TIMESDONE","时代做");//Times done
define("_HASLEFT","左边");//Left
define("_EMPLOYEESINGROUP","员工组");//Employees of group
define("_ERRORRESTORINGFILE","问题来了，在恢复");//A problem came up during restore
define("_DATABASEONLY","数据库只");//Database only
define("_ALLDATABACKUP","所有的数据备份");//All data backup
define("_LESSONDIRECTORYCANNOTBCREATED","节目录无法创建");//The lesson directory could not be created
define("_YOUHAVENOTCOMPLETEDTHEFOLLOWINGQUESTIONS","您尚未完成的问题");//You have not completed questions
define("_AREYOUSUREYOUWANTTOSUBMITTEST","您确定要提交测试?");//Are you sure you want to submit the test?
define("_JOBANALYTICALDESCRIPTION","详细说明");//Detailed description
define("_INCLUDESUBBRANCHES","包括subbranches");//Include subbranches
define("_PDFFORMAT","PDF格式");//PDF format
define("_XLSFORMAT","Excel格式");//EXCEL format
define("_ATTENDING","出席");//Attending
define("_USERAVERAGESCOREFORTESTS","平均分数为节的测试");//Average score for lesson&#039;s tests
define("_PROJECTSCOMPRESSED","下载项目文件");//Download project files
define("_EDUCATIONALROLE","教育的作用");//Educational role
define("_ORGANIZATIONALROLE","组织的作用");//Organizational role
define("_TYPEOFUSER","用户类型");//User type
define("_MESSAGEBODY","邮件正文");//Message body
define("_ONLYRECIPIENTSDEFINEDBELOW","受助人的界定，只有在下面的字段");//Only recipients defined in the field below
define("_NORECIPIENTSHAVEBEENSELECTED","没有受助者已选定");//No recipients have been selected
define("_NORECIPIENTSHAVEBEENFOUND","没有受助人已找到");//No recipients have been found
define("_CHANGELESSON","改变的节");//Change lesson
define("_HOME","家");//Home
define("_FFROM","自");//from
define("_CALENDARTYPE","日历类型");//Calendar type
define("_ORGANIZATIONPROFILE","组织简介");//Organization profile
define("_CURRENTLESSON","目前的节");//Current lesson
define("_SUBMITANDADDANOTHER","提交和添加另一个");//Submit and add another
define("_EDUCATIONAL","教育");//Educational
define("_PAYPALTITLE","贝宝");//Paypal
define("_PAYPALCONFIGURATIONPANEL","贝宝配置小组");//Paypal configuration panel
define("_PAYPALMYTRANSACTIONS","我的交易");//My transactions
define("_PAYPALTRANSACTION","交易");//Transaction
define("_PAYPALCONFIGURATION","配置");//Configuration
define("_PAYPALBUSINESSMAIL","贝宝公司地址");//Paypal business address
define("_PAYPALBUSINESSMAILPLZ","填补在贝宝公司地址");//Fill in the Paypal business address
define("_PAYPALMAILSTUDENTS","通知学生");//Inform students
define("_PAYPALMAILPROFESSORS","可否告知教师");//Inform professors
define("_PAYPALMAILADMINS","通知管理员");//Inform admins
define("_PAYPALORDERPREVIEW","预览顺序");//Preview order
define("_PAYPALFINALPRICE","最终价格");//Final price
define("_PAYPALPAYNOW","现在的薪酬与贝宝");//Pay now with Paypal
define("_PAYPALNOCONFIGURATION","您不能使用这项服务，因为它的不正确配置。");//You can not use this service because its not configured properly.
define("_PAYPALORDERPROCESSING","您的订单正在处理通过贝宝。");//Your order is being processing through Paypal.
define("_PAYPALORDERPROCESSINGERROR","有一个错误，与您的订单。");//There was an error with your order.
define("_PAYPALORDERSSUCCESS","完成");//Finished
define("_PAYPALORDERSNOSUCCESS","未完成");//Not-Finished
define("_PAYPALTABLEPRICE","数量");//Amount
define("_PAYPALITEMCODE","代码");//Code
define("_PAYPALTABLEDATESUBMIT","订单日期");//Order date
define("_PAYPALTABLEDATEPAYPAL","付款日期");//Payment date
define("_PAYPALTRANSACTIONCODE","交易代码");//Transaction code
define("_PAYPALTABLEUSER","用户");//User
define("_PAYPALTABLESTATUS","付款状态");//Payment status
define("_PAYPALTABLELESSONS","节");//Lessons
define("_PAYPALORDERINFO","交易详情");//Transaction details
define("_PAYPALCUSTOMERINFO","客户的信息");//Customer&#039;s information
define("_PAYPALITEMSINFO","项目信息");//Items information
define("_PAYPALPURCHASEORDER","采购订单");//Purchase order
define("_PAYPALPURCHASEORDERFOR","付款");//Payment to
define("_ADDTOCART","放入购物车");//Add to cart
define("_REMOVEFROMCART","删除购物车");//Remove from cart
define("_REMOVEALLFROMCART","删除所有从购物车");//Remove all from cart
define("_CART","购物车");//Shopping cart
define("_NOCART","购物车是空的");//The cart is empty
define("_FREEOFCHARGE","自由的");//Free
define("_LOGINFIRST","日志在首先进行购买");//Log in first to proceed purchase
define("_RESULTS","结果");//results
define("_RESULT","结果");//result
define("_PAYPALORDERSUCCESS","交易顺利完成");//The transaction completed successfully
define("_PAYPALORDERFAILURE","有一个错误与交易");//There was an error with the transaction
define("_PAYPALFREEORDERSUCCESS","节登记顺利完成");//Lessons registration finished successfully
define("_FREEREGISTRATION","免费注册");//Free registration
define("_VIEWDIRECTORY","显示节/课程目录");//Show lesson/courses catalog
define("_VIEWDIRECTORYYESAFTERLOGIN","是（只有登录后）");//Yes (only after login)
define("_VIEWDIRECTORYYESONLOGIN","是（对登入网页和登录后）");//Yes (on login page and after login)
define("_VIEWDIRECTORYNO","否");//No
define("_VIEWDIRECTORYDISABLED","该calatog是无效的这一刻");//The calatog is inactive this moment
define("_INTERFACEVIEW","选择界面索引页");//Select the interface of index page
define("_INTERFACEVIEWSIMPLE","简单");//Simple
define("_INTERFACEVIEWEXTENDED","延长");//Extended
define("_PAYPALUSE","使用贝宝");//Payments through Paypal
define("_DIRECTORY","目录");//Directory
define("_LESSONSDIRECTORY","课程目录");//Course catalog
define("_ASSOCIATEDLESSONS","相关的经验节");//Associated lessons
define("_APPLYTOALLDESCRIPTIONSWITHDESCRIPTION","适用于所有职位描述：");//Apply to all jobs with description: 
define("_AREYOUSUREYOUWANTTOREMOVETHATSKILLFROMTHISEMPLOYEE","您确定要删除的技能，从该雇员?");//Are you sure you want to remove that skill from that employee?
define("_JOBDESCRIPTIONEXISTSALREADY","职位描述已经存在的");//Job description exists already
define("_EVENTFIELDISMANDATORY","活动领域是强制性的");//Event field is mandatory
define("_SKILLCATEGORY","技能类");//Skill category
define("_ADDSKILLCATEGORY","新增技能类");//Add skill category
define("_EDITSKILLCATEGORY","编辑技能类");//Edit skill category
define("_DELETESKILLCATEGORY","删除技能类");//Delete skill category
define("_AREYOUSUREYOUWANTTODISMISSTHISSKILLCATEGORY","是您确定要关闭这个技能类?");//Are you sure you want to dismiss this skill category?
define("_UPDATESKILLSCATEGORY","更新技能类");//Update skill category
define("_SKILLCATEGORYDATAUPDATED","技能类的数据更新");//Skill category data updated
define("_SUCCESSFULLYCREATEDSKILLCATEGORY","技能类成功创建");//Skill category successfully created
define("_SKILLCATEGORYDELETED","技能类删除");//Skill category deleted
define("_USERDOESNOTEXIST","该用户不存在");//The user does not exist
define("_INVALIDSURNAME","用户去年指定的名称是无效的");//The user last name specified is not valid
define("_INVALIDEMAIL","用户指定的电子邮件是无效的");//The user email specified is not valid
define("_USERALREADYEXISTS","用户指定的登录已经存在");//A user with the specified login already exists
define("_EMAILALREADYEXISTS","用户指定的电子邮件已经存在");//A user with the specified email already exists
define("_COULDNOTINSERTUSER","指定的用户无法插入到数据库");//The user specified could not be inserted to database
define("_INVALIDUSERTYPE","指定的用户类型是无效的");//The specified user type is not valid
define("_REMEMBERME","记得我");//Remember me
define("_INVALIDPASSWORD","密码无效");//Invalid password
define("_INVALIDPASSWORDFORUSER","无效的使用者的密码");//Invalid password for user
define("_PROBLEMACTIVATINGACCOUNT","有问题，在激活账户");//There was a problem during account activation
define("_THEUSERCOULDNOTBEDELETED","使用无法删除");//The use could not be deleted
define("_THEUSERCOULDNOTBEDEACTIVATED","用户不能停用");//The user could not be deactivated
define("_THEUSERCOULDNOTBEACTIVATED","用户不能启动");//The user could not be activated
define("_USERDIRECTORYCOULDNOTBEDELETED","用户目录无法删除");//The user directory could not be deleted
define("_INVALIDLESSONID","无效的节，编号");//Invalid lesson id
define("_UNITDOESNOTEXIST","该单元不存在");//The unit does not exist
define("_DOWNLOADEXPORTED","下载导出的节");//Download exported lesson
define("_SUCCESFULLYRESTOREDSYSTEM","恢复程序顺利完成");//The restoring procedure completed successfully
define("_LESSONDOESNOTEXIST","节指定不存在");//The lesson specified does not exist
define("_UNDOCHANGES","撤消变化");//Undo changes
define("_CONTENTTREEMANAGEMENT","内容树的管理");//Content tree management
define("_ORDERWILLPERMANENTLYCHANGE","此操作将永久改变单元订购和无法复原。您是否确定?");//This operation will permanently change unit ordering and cannot be undone. Are you sure?
define("_ERRORLOADINGCONTENT","错误加载内容的节");//Error loading content for lesson
define("_USERROLE","用户角色");//User role
define("_CANNOTUPDATEUSERLESSONINFORMATION","的节，这方面的数据用户无法更新");//The lesson information on this user could not be updated
define("_PROBLEMUPDATINGUSERSTOLESSON","有问题，更新用户信息的节");//There was a problem updating the user lesson information
define("_INVALIDPROJECTID","无效的项目编号");//Invalid project Id
define("_PROJECTNOTFOUND","指定的项目没有被发现");//The specified project was not found
define("_USERDOESNOTHAVETHISLESSON","用户没有登记这个节");//The user is not registered to this lesson
define("_COURSEDOESNOTEXIST","指定的课程是不存在的");//The specified course does not exist
define("_NODEDOESNOTEXIST","指定的节点不存在");//The specified node does not exist
define("_PROJECTCOULDNOTBEDELETED","该项目无法删除");//The project could not be deleted
define("_FREELESSON","免费的节");//Free lesson
define("_BUYCOURSE","课程购买");//Buy course
define("_FREECOURSE","免费课程");//Free course
define("_USERDOESNOTHAVETHISPROJECT","用户不会有这个项目");//The user does not have this project
define("_SCOREMUSTBEINTEGERBETWEEN0100","该项目评分必须是整数的范围从0到100");//The project score must be an integer ranging from 0 to 100
define("_THEPROJECTGRADECOULDNOTBEUPDATED","该项目等级无法更新");//The project grade could not be updated
define("_INVALIDDATA","无效数据");//Invalid data
define("_UPLOADEDON","上传");//Uploaded on
define("_PROJECTDELETEDSUCCESSFULLY","该项目已成功删除");//The project was deleted succesfully
define("_FILESCOULDNOTBEDOWNLOADED","该项目的文件无法下载");//The project files could not be downloaded
define("_RESULTSFORPROJECT","结果项目");//Results for project
define("_VIEWPROJECT","鉴于项目");//View project
define("_REMAINING","其余");//Remaining
define("_PROJECTEXPIRED","该项目的最后期限已经过期");//The project deadline has expired
define("_SENDPROJECT","发送项目");//Send project
define("_NEWLESSONS","新的节");//New lessons
define("_YOUMUSTDELETEALLLESSONSANDSUBDIRECTIONSINTHISDIRECTIONBEFOREDEACTIVATINGIT","你不能停用非空语类");//You cannot deactivate a non-empty category
define("_CANNOTUPDATEUSERCOURSEINFORMATION","课程信息关于这个用户无法更新");//The course information on this user could not be updated
define("_CANNOTADDUSERTOCOURSE","用户可不会被添加到课程");//The user could not be added to course
define("_CANNOTREMOVEUSERFROMCOURSE","用户可以不被免职过程");//The user could not be removed from the course
define("_USERHASNOTDONETEST","该用户已没有这样做的测试");//The user has not done this test
define("_TESTISNOTDONE","测试是没有这样做");//The test is not done
define("_INVALIDQUESTIONTYPE","无效的问题类型");//Invalid question type
define("_YOUCANNOTDEACTIVATEANONEMPTYDIRECTION","你不能停用非空语类");//You cannot deactivate a non-empty category
define("_YOUCANNOTDELETEANONEMPTYDIRECTION","您不能删除一个非空语类");//You cannot delete a non-empty category
define("_MAXFILEISAFFECTEDANDIS","最高上传文件的大小也受PHP中的INI设置。目前真正的最大文件大小是");//The maximum upload file size is also affected by PHP ini settings. Current true max file size is
define("_CAREFULNOTLOCKOUT","当设定的IP接入名单，小心，不要禁止自己出去！");//When setting ip access lists, be careful not to ban yourself out!
define("_ADMINISTRATORWILLACTIVATEYOURACCOUNT","注册完成。您的账户将被激活由系统管理员");//Registration is complete. Your account will be activated by the system administrator
define("_USERPENDING","该账户尚未启用，但由管理员");//The account has not been activated yet by the administrator
define("_DOWNLOADDEFAULTSTYLE","下载的预设样式");//Download default style
define("_SETDEFAULTSTYLE","设置默认的作风，积极");//Set default style as active
define("_SUCCESFULLYUPDATEDLOGO","徽标文件已更新成功");//Logo file was updated successfully
define("_USEDEFAULTLOGO","使用预设的标志");//Use default logo
define("_GROUPOPTIONS","组选项");//Group options
define("_GROUPUSERS","组用户");//Group users
define("_USETHIS","使用此");//Use this
define("_PAGESETSUCCESSFULLY","网页设置成功");//Page set succesfully
define("_TEXTBOX","文本框");//Text box
define("_SELECTBOX","专责名单");//Select list
define("_EDITFIELD","编辑字段");//Edit field
define("_COULDNOTADDFIELD","外地无法加入");//The field could not be added
define("_COULDNOTUPDATEFIELD","外地无法更新");//The field could not be updated
define("_FIELDALREADYEXISTS","实地已经存在具有此名称");//A field with this name already exists
define("_INTEGER","整数");//Integer
define("_DEFAULTVALUE","默认值");//Default value
define("_VALUES","价值观");//Values
define("_ADDVALUES","添加值");//Add values
define("_DELETEBOOKMARK","删除书签");//Delete bookmark
define("_SUCCESSFULLYINSERTEDBOOKMARK","该网页的书签");//The page was bookmarked
define("_ERRORINSERTINGBOOKMARK","网页不能书签");//The page could not be bookmarked
define("_LOADING","载入中...");//Loading...
define("_UNITS","单元");//Units
define("_USERCOULDNOTBECREATED","用户无法创建");//The user could not be created
define("_PROCEEDTOTEST","进行测试");//Proceed to test
define("_OPERATIONWILLAFFECTMANYAREYOUSURE","这项行动将影响不可逆转了大量的实体。进行?");//This operation will affect irreversibly a large number of entities. Proceed?
define("_CLICKTOTOGGLE","按一下以切换");//Click to toggle
define("_COMPRESSDOWNLOAD","压缩和下载");//Compress and download
define("_SELECTEDENTRYTO","选定项目");//the selected entry to
define("_YOUWANTTO","您想要");//You want to
define("_UPLOADTODIGITALLIBRARY","上传到数字图书馆");//Upload to digital library
define("_SHARE","共享");//Share
define("_OPERATIONSUCCESFULLYAPPLIEDON","运作成功的应用");//Operation successfully applied on
define("_BYUSER","由用户");//by user
define("_VIEWSOLVEDTEST","鉴于解决测试");//View solved test
define("_VIEWQUESTION","鉴于问题");//View question
define("_COULDNOTCREATETESTSDIRECTORY","测试文件夹无法创建");//The tests folder could not be created
define("_SAVEASNEWTEST","另存为新的考验");//Save as new test
define("_SELECTLESSONTOCOPYFROM","选择一个节，复制，从");//Select a lesson to copy from
define("_VIEWCOMMENT","查看评论");//View comment
define("_SHOWEVALUATIONS","查看评价");//Show evaluations
define("_RECIPIENTS","受助人");//Recipients
define("_SHOWRECIPIENTSCATEGORIES","显示收件人的预定义分类");//Show recipient&#039;s predefined categories
define("_HIDERECIPIENTSCATEGORIES","隐藏收件人的预定义分类");//Hide recipient&#039;s predefined categories
define("_TOYOURSUPERVISORS","您所有的上司");//All your supervisors
define("_BASICINFO","基本数据");//Basic info
define("_TRAININGCAP","训练");//T R A I N I N G
define("_COURSESAVERAGE","平均分数在所有课程");//Average score in all courses
define("_LESSONSAVERAGE","平均分数在所有的经验节");//Average score in all lessons
define("_TESTSAVERAGE","平均分数在所有测试");//Average score in all tests
define("_DONTTAKEINTOACCOUNT","不考虑");//Do not take into account
define("_CANNOTADDUSERTOLESSON","不能添加用户，以节");//Cannot add user to lesson
define("_UNKNOWNUSER","未知用户");//Unknown user
define("_DEPENDSON","要视乎");//Depends on
define("_COURSEINFORMATION","课程信息");//Course information
define("_NODATAFOUND","没有找到数据");//No data found
define("_ERROROPENINGATTACHMENT","错误开放实习");//Error opening attachment
define("_USERAVERAGESCOREFORLESSON","平均分数为节的测试");//User&#039;s average score for lesson
define("_LESSONSINFO","节信息");//Lessons info
define("_USERSINGROUP","小组中的用户");//Users in group
define("_PROFESSORSOFLESSON","教师的节");//Professors of lesson
define("_TOBRANCHSUPERVISORS","只有您的分行监事");//Only your branch supervisors
define("_OTHERBRANCHJOBS","职务说明，从其它科");//Job descriptions from other branches
define("_SENDMESSAGETOALLFOUNDEMPLOYEES","发送信息给所有雇员发现");//Send messages to all employees found
define("_SEARCHCOURSEUSERS","搜索为雇员[课程标准]");//Search for employee [Course criteria]
define("_COMPLETIONDATE","竣工日期");//Completion date
define("_YEAR","年");//Year
define("_NOTASSIGNED","未分配，但");//Not assigned yet 
define("_NEWSEARCHCRITERIUM","添加搜索的详情");//Add search criterium
define("_NOSEARCHCRITERIADEFINED","没有搜索标准界定");//No search criteria defined
define("_ERRORSAVINGTREE","错误节省树");//Error saving tree
define("_MAXEXECUTIONTIME","最高执行时间");//Maximum execution time
define("_MEMORYLIMIT","内存限制");//Memory limit
define("_PHPSETTINGS","PHP的设置");//PHP settings
define("_MEGABYTES","兆字节");//megabytes
define("_LEAVEBLANKTOUSEPHPINI","离开领域的空白，以便利用php.ini的默认设置");//Leave fields blank in order to use php.ini default settings
define("_DISPLAYERRORS","显示错误");//Display errors
define("_UPLOADLESSONFILE","上传文件的节");//Upload lesson file
define("_DCTITLE","标题");//Title
define("_DCCREATOR","创作者");//Creator
define("_DCSUBJECT","题目");//Subject
define("_DCDESCRIPTION","描述");//Description
define("_DCPUBLISHER","出版商");//Publisher
define("_DCCONTRIBUTOR","投稿");//Contributor
define("_DCDATE","日期");//Date
define("_DCTYPE","类型");//Type
define("_DCFORMAT","格式");//Format
define("_DCIDENTIFIER","标识符");//Identifier
define("_DCSOURCE","来源");//Source
define("_DCLANGUAGE","语言");//Language
define("_DCRELATION","关系");//Relation
define("_DCCOVERAGE","涵盖范围");//Coverage
define("_DCRIGHTS","权利");//Rights
define("_NOENTRYFOUNDFOR","没有进入发现");//No entry found for
define("_FIELD","领域");//field
define("_COURSECERTIFICATES","课程证书");//Course certificates
define("_LDAPUSERMUSTCONTACTADMIN","您的账户是通过访问LDAP服务器。请联系系统管理员在");//Your account is accessed through the LDAP server. Please contact the system administrator at 
define("_COURSEMETADATA","课程中继");//Course metadata
define("_COURSESTATUS","课程地位");//Course status
define("_LESSONSCOMPLETED","完成的节");//Completed lessons
define("_COURSESCORE","课程评分");//Course score
define("_LESSONSCOMPLETED","完成的节");//Lessons completed and awaiting approval
define("_VIEWUSERCOURSEPROGRESS","查看用户的教师的整个过程中");//View the user progress throughout the course
define("_COURSERULES","课程规则");//Course rules
define("_INFORMATIONFORCOURSE","信息的过程中");//Information for course
define("_CERTIFICATESFORCOURSE","证书课程");//Certificates for course
define("_FORMATCERTIFICATEFORCOURSE","格式证书课程");//Format certificate for course
define("_RULESFORCOURSE","规则课程");//Rules for course
define("_CONTENTDONE","内容做");//Content done
define("_LESSONSPROGRESS","节教师");//Lessons progress
define("_COMPLETECOURSE","完成课程");//Complete course
define("_PROPOSEDSCOREISAVERAGELESSONSCORE","拟议的评分是平均的节评分");//The proposed score is the average lessons score
define("_INTHESELECTEDLANGUAGE","键入描述在首选语言");//Type the description in the prefered language
define("_SUCCESSFULLYDELETEDFIELD","成功删除领域");//Successfully deleted field
define("_COMPLETELESSON","完整的节");//Complete lesson
define("_AUTOCOMPLETEDCOURSE","过程是自动完成时，所有的经验节已完成");//The course was automatically completed when all lessons were completed
define("_INFORMATIONFORLESSON","信息的节");//Information for lesson
define("_LESSONMETADATA","节中继");//Lesson metadata
define("_DISPLAYINGRESULTS","结果显示");//Displaying results
define("_LOADINGDATA","加载数据");//Loading data
define("_COURSESTATISTICS","课程报告");//Course reports
define("_CHOOSECOURSE","课程，选择");//Choose course
define("_HISTORYRECORDDELETED","历史记录删除");//History record deleted
define("_AREYOUSUREYOUWANTTODELETETHEHISOTYRECORD","您确定要删除的历史记录?");//Are you sure you want to delete the history record?
define("_HIDEALL","全部隐藏");//Hide all
define("_COURSEORDER","课程，为了");//Course order
define("_ORDERFORCOURSE","为了让课程");//Order for course
define("_DRAGITEMSTOCHANGELESSONSORDER","拖移项目，以改变显示顺序的过程中的经验节");//Drag items to change the display order of the course lessons
define("_IRREVERSIBLEACTIONDELETESUBUNITSAREYOUSURE","这一行动将irreversably删除此单元和任何子单元，它可能有。您是否确定?");//This action will irreversably delete this unit and any subunits it may have. Are you sure?
define("_CLICKOKTOACTIVATEITEM","单击确定以启动/关闭项目");//Click OK to activate/deactivate item
define("_ANDITSSUBNODES","和它的子节点");//and it&#039;s sub nodes
define("_ERRORDELETINGUNIT","错误删去单元");//Error deleting unit
define("_ERRORACTIVATINGUNIT","错误激活单元");//Error activating unit
define("_ERRORDEACTIVATINGUNIT","错误失能单元");//Error deactivating unit
define("_ERRORDEPOSITIONINGUNIT","错误定位单元");//Error positioning unit
define("_ERRORREPAIRINGTREE","错误修复树");//Error repairing tree
define("_DRAGAUNITTOCHANGEITSPOSITION","拖动一个单元，改变其立场");//Drag a unit to change its position
define("_IFUSESSLTHENPHPOPENSSL","如果你想使用SSL ，请确保PHP的OpenSSL的支持启用");//If you want to use ssl, make sure that PHP openssl support is enabled
define("_COURSECOMPLETED","课程完成");//Course completed
define("_COURSECERTIFICATE","课程证书");//Course certificate
define("_COURSESINFO","课程信息");//Courses info
define("_DRAGTOMOVEMAILTOFOLDER","拖动以移动此电子邮件到另一个文件夹");//Drag to move this email to another folder
define("_SCORMOPTIONS","SCORM的选项");//Scorm options
define("_SCORMOPTIONSFOR","SCORM的选择");//Scorm options for
define("_SCORMREVIEW","查看SCORM的数据");//Review SCORM data
define("_REVIEWSCORMDATAFOR","查看SCORM的数据");//Review SCORM data for
define("_SCORMFILEINZIPFORMAT","SCORM的zip文件");//SCORM zip file
define("_TREEROOT","林木根");//Tree root
define("_INVALIDPAGE","无效页");//Invalid page
define("_VALUEISSMALLERTHATPHPINI","该值是小于1所订的php.ini");//The value is smaller than the one set by php.ini
define("_PERMISSIONS","权限");//Permissions
define("_UNSHARE","取消共享");//Cancel sharing
define("_UNSHARESELECTED","取消共享选定的文件");//Cancel sharing of selected files
define("_SHARESELECTED","分享选定的文件");//Share selected files
define("_YOUDONTHAVEPERMISSION","您不“吨的权限，执行选定的行动");//You don&quot;t have permission to perform the selected action
define("_EXPORT","导出");//Export
define("_NOMODULECLASSFOUND","没有模块级的发现与名称");//No module class found with name
define("_ERRORLOADINGMODULE","错误加载模块");//Error loading module
define("_VERSIONKEYTITLE","版本的关键");//Version Key
define("_VERSIONKEY","版本的关键");//Version key
define("_VERSIONALLOEDUSERS","允许用户");//Allowed Users
define("_VERSIONTYPE","版本类型");//Version Type
define("_VERSIONSERIAL","序号");//Serial Number
define("_USERSEXCEEDED","您的版本类型不容许创造新的用户");//Your version type does not allow the creation of new users
define("_BASICCRITERIA","基本准则");//Basic criteria
define("_BASICSEARCHOPTIONS","基本搜索选项");//Basic search options
define("_DELETEDATA","删除数据");//Delete data
define("_ERRORDETAILS","错误的详细数据");//Error Details
define("_PARTOFTHISGROUP","用户的一部分，这个小组");//The user is part of this group
define("_SUCCESSFULLYIMPORTEDSCORMFILE","SCORM的文件被成功导入");//SCORM file was successfully imported
define("_CONVERTTOSCORMCONTENT","转换到SCORM的内容单元");//Convert to SCORM content unit
define("_CONVERTTOSCORMTEST","转换到SCORM的测试单元");//Convert to SCORM test unit
define("_SCORMTREE","SCORM的树");//SCORM tree
define("_MASTERYSCORE","掌握评分");//Mastery score
define("_GZHANDLER","广州处理");//GZ handler
define("_PROJECTPENDING","这个项目正在等待");//This project is pending
define("_USERHASNOTDONETEST","该用户已没有这样做的测试");//The user has not done this test
define("_USERHASNOTTHISLESSON","用户没有登记这个节");//The user is not registered for this lesson
define("_SHIFTSCHEDULEFORNEWUSERS","附表转移为新用户");//Shift schedule for new users
define("_CURRENTSCHEDULE","目前附表");//Current schedule
define("_NOSCHEDULESET","没有时间表");//No schedule set
define("_DELETESCHEDULE","删除附表");//Delete schedule
define("_SCHEDULINGFORCOURSE","调度过程");//Scheduling for course
define("_ADDSCHEDULE","新增附表");//Add schedule
define("_COURSESCHEDULE","课程附表");//Course schedule
define("_AVAILABLEUNTIL","可直到");//Available until
define("_FILETYPE","文件类型");//File type
define("_FULLPATH","完整路径");//Full path
define("_MIMETYPE","MIME类型");//MIME type
define("_CANNOTSHAREFILE","不能共享文件");//Cannot share file
define("_SHAREDFILES","共享文件");//Shared files
define("_CLICKTOEXPORT","按一下按钮导出的节");//Click the button to export lesson
define("_EXISTINGFILE","下列文件已经存在");//The following file already exists
define("_PROBLEMADDINGUSERSTOLESSON","用户可不会被添加到节");//The user could not be added to the lesson
define("_TRANSLATEFILESYSTEM","编码非拉丁字母的文件名称，以");//Encode non-latin file names to
define("_CANNOTMOVEFILE","该文件无法移动");//Cannot move file
define("_INCOMPATIBLEVERSIONS","不兼容的版本");//Incompatible versions
define("_BACKUPVERSION","备份版本");//Backup version
define("_CURRENTVERSION","目前版本");//Current Version
define("_MAXIMUMUPLOADSIZE","文件大小上限");//Maximum file size
define("_BACKUPFAILED","备份失败");//Backup failed
define("_PERSONALFILES","个人文件");//Personal files
define("_MAXIMUMUSERSNUMBERREACHED","最高的用户数量达到");//The maximum number of users is reached
define("_UPLOADING","上传");//Uploading
define("_SELECTEDFILESTO","选定的文件，以");//selected files to
define("_CATEGORYDOESNOTEXIST","一类是不存在的");//The category does not exist
define("_CATEGORIES","类别");//Categories
define("_NEWCATEGORY","新的类别");//New category
define("_EDITCATEGORY","编辑类别");//Edit category
define("_CATEGORYSETTINGS","类别设置");//Category settings
define("_YOUWANTTOBEDONE","您想要");//You want to
define("_OVERWRITE","覆盖");//Overwrite
define("_USERSPROGRESS","雇员的地位");//Users progress
define("_LESSONUSERS","节用户");//Lesson users
define("_ASSOCIATEDCOURSES","相关课程");//Associated courses
define("_OUTPUT","输出");//Output
define("_TOKEN","令牌");//Token
define("_PERMITTEDROLESMODULEERROR","一个或多个模块允许的角色是错误的");//One or more module permitted roles are wrong
define("_SMARTYTEMPLATEDOESNOTEXIST","该smarty模板文件不存在");//The smarty template file does not exist
define("_FOLDERWITHMODULENAMEEXISTSIN","文件夹中与模块名称已存在在");//Folder with module name already exists in 
define("_SITENAME","网站名称");//Site name
define("_SITEMOTO","网站摩托");//Site moto
define("_UNKNOWNSEPARATOR","未知分离");//Unknown separator
define("_LDAPUSER","此用户验证通过LDAP服务器");//This user authenticates through the LDAP server
define("_EXECUTE","执行");//Execute
define("_RECREATE","再现");//Recreate
define("_CLICKHERETOREINDEX","点击这里重新搜索表");//Click here to recreate the search table
define("_TRANSLATION","翻译");//Translation
define("_ENGLISHNAME","名称在英语");//Name in english
define("_SUCCESSFULLYADDEDLANGUAGE","语言已成功创建");//The language was successfully created
define("_SUCCESSFULLYUPDATEDLANGUAGE","语言已成功更新");//The language was successfully updated
define("_LANGUAGES","语言");//Languages
define("_SERIALRULE","用户必须看到的内容在一个串行顺序");//Users must see content in a serial order
define("_TREERULE","转到下一个前，用户必须完成的一个分支");//Users must complete a branch&quot;s nodes before moving to the next one
define("_ADDCUSTOMRULE","新增自订规则");//Add custom rule
define("_ADDREADYRULE","添加准备规则");//Add ready rule
define("_THEFOLLOWINGUSERSCOULDNOTBEIMPORTED","以下用户无法导入");//The following users could not be imported
define("_STARTHERE","从这里开始");//Start here
define("_COPYSELECTED","复制选定");//Copy selected
define("_USERACCESSESINLESSON","用户访问在节");//User access in lesson
define("_NUMBEROFFIELDSMUSTBE","有多少领域必须");//The number of fields must be
define("_BUTFOUND","但被发现");//but there was found
define("_APPLYAVATARCHANGES","适用于阿梵达的变化");//Apply avatar changes
define("_TERMFIELDISMANDATORY","任期领域是强制性的");//Term field is mandatory
define("_DEFINITIONFIELDISMANDATORY","定义领域是强制性的");//Definition field is mandatory
define("_TOPLEFTCORNER","左上角");//Top left corner
define("_TOPRIGHTCORNER","右上角");//Top right corner
define("_BOTTOMLEFTCORNER","左下角");//Bottom left corner
define("_BOTTOMRIGHTCORNER","右下角");//Bottom right corner
define("_LOGOPOSITION","徽标的立场");//Logo position
define("_LOGOFILE","Logo文件");//Logo file
define("_LESSONSKILLSSELECTION","的节，所提供的技能选择");//Lesson offered skills selection
define("_TOPCENTER","顶端中心");//Top center
define("_BOTTOMCENTER","底部的中心");//Bottom center
define("_HIDECOMPLETEUNITICON","隐藏完成单元图标");//Hide complete unit icon
define("_HIDENAVIGATION","隐藏导航处理");//Hide navigation handles
define("_AUTOCOMPLETEDAT","自动完成");//Auto completed at
define("_SECOND","第二");//second
define("_NOACCESSDATA","没有访问数据");//No access data
define("_USERAVATAR","用户化身");//User avatar
define("_MOSTACTIVELESSONS","最激活的节");//Most active lessons
define("_LESSONSACTIVITY","节活动");//Lessons activity
define("_USERSACTIVITY","用户活动");//Users activity
define("_USERHASNOTTHELESSON","用户没有这个节");//The user doesn&#039;t have this lesson
define("_USERHASTHELESSON","该用户已这个节");//The user has this lesson
define("_TESTSINFORMATION","测试信息");//Tests information
define("_QUESTIONSINFORMATION","问题信息");//Questions information
define("_PROJECTSINFORMATION","项目信息");//Projects Information
define("_MCEXPLANATION","*MC=多个选项-单一答案");//* MC = Multiple choices - Single Answers
define("_MCMAEXPLANATION","* MCMA =多种选择-多个答案");//* MCMA = Multiple choices - Multiple Answers
define("_MAEXPLANATION","*MA=匹配");//* MA = Matching
define("_FBEXPLANATION","*FB=填补空白");//* FB = Fill the blank
define("_OAEXPLANATION","*OA=开放答案");//* OA = Open answer
define("_YNEXPLANATION","*Y/N=是/否");//* YN = Yes/No
define("_PROJECTNAME","项目名称");//Project name
define("_STATISTICSFORCOURSE","统计过程中");//Statistics for course
define("_YOUARENOTAUTHORISEDTOSEETHISTEST","未授权您看到这个测试");//You are not authorized to see this test
define("_YOUCANNOTREDOTHISTEST","你不能重做此测试");//You cannot redo this test
define("_ACCESSEDLESSON","访问节");//Accessed lesson
define("_ACCESSEDCONTENT","访问内容单元");//Accessed content unit
define("_ACCESSEDTEST","进入测试");//Accessed test
define("_BEGUNTEST","开始测试");//Begun test
define("_NAVIGATEDSYSTEM","通过导航系统");//Navigated through the system
define("_PROJECTDESCRIPTION","项目说明");//Project description
define("_CONTENTTRAVERSINGRULES","内容遍历规则");//Content traversing rules
define("_FILEUPLOADEDON","该文件上传");//The file was uploaded on
define("_DIRECTIONOPTIONSFOR","选择类别");//Options for category
define("_NEWDIRECTIONOPTIONS","新的类别选项");//New category options
define("_COURSELESSONS","课程，节");//Course lessons
define("_RELATEDTO","有关");//Related to
define("_SUCCESSFULLYEXPORTEDSCORMFILE","节是导出到SCORM的格式成功");//The lesson was exported to SCORM format succesfully
define("_LDAPEXTENSIONNOTLOADED","警告： LDAP的扩展不加载");//Warning: LDAP Extension  not loaded
define("_PERCENTAGEMUSTBEBETWEEN1100","百分比必须介于1和100");//Percentage must be between 1 and 100
define("_MUSTSEECONTENTSERIALSOMUSTFIRSTREADUNIT","你必须看到的内容在一个串行顺序，所以您必须先阅读单元");//You must see content in a serial order, so you must first read unit
define("_YOUDONTHAVEANYLESSONS","您没有任何的节或课程");//You don&#039;t have any lessons or courses
define("_THEADMINISTRATORWILLASSIGNYOULESSONS","系统管理员会发放给您的节，或课程");//The system administrator will assign you lessons or courses
define("_BACKTOINDEX","回到索引页");//Back to index page
define("_LESSONAVAILABLE","节是可用");//Lesson is available
define("_DIRECTLY","直接");//Directly
define("_ADDFILE","新增文件");//Add file
define("_DOWNLOADSCORMEXPORTEDFILE","下载导出SCORM的文件");//Download exported SCORM file
define("_EMPTYUNIT","空单元");//Empty unit
define("_YOUMUSTPROVIDELOGINLINK","您必须提供登录的链接，否则，你将不能够直接连接。登录窗体链接： ". G_SERVERNAME ."index.php?index_eFront");//You must provide a login link, otherwise you will not be able to connect directly. Login form is available through the link: ".G_SERVERNAME."index.php?index_efront
define("_NOFILEUPLOADED","没有文件被上传");//No file was uploaded
define("_FONTSIZE","字体大小");//Font size
define("_FONTSTYLE","字体样式");//Font style
define("_PROBLEMINSERTINGPARSEDXMLVALUESORMODULEEXISTS","问题插入解析XML的值到数据库。请检查您的说明文件，或是否该模块已经安装");//Problem inserting the parsed XML values to the database. Please check your description file or whether the module is already installed
define("_NOMODULEPERMITTEDROLESDEFINED","没有模块允许的角色定义。检查功能getpermittedroles （ ）");//No module permitted roles defined. Check function getPermittedRoles()
define("_MODULECLASSNOTEXISTSIN","模块级中没有界定");//module class is not defined in
define("_MODULEDBERRORONINSTALL","数据库错误的执行过程中的功能oninstall为模块");//Database error during the execution of function onInstall for the module
define("_MODULEISALREADYINSTALLED","该模块已经安装");//The module is already installed
define("_LOGOUTREDIRECT","复位向后，注销来");//Redirect after logout to
define("_INFORMATIONFORFILE","数据文件");//Information for file
define("_METADATA","中继");//Metadata
define("_FILEMETADATA","文件元数据");//File metadata
define("_NOENTRYFOUNDFORTHEFIELD","没有进入发现为外地");//No entry found for the field
define("_CONTENTMETADATA","内容元数据");//Content Metadata
define("_METADATAFORUNIT","元数据为单元");//Metadata for unit
define("_RESOURCEREQUESTEDREQUIRESLOGIN","资源，您要求您必须先登录");//The resource that you requested requires that you login first
define("_DATABASEERROR","数据库错误");//Database error
define("_CANNOTACCESSRESOURCE","您没有权限访问此资源");//You don&#039;t have permission to access this resource
define("_RESOURCEISNOTACCESSIBLEFROMOUTSIDE","这个资源是没有直接访问");//This resource is not directly accessible
define("_RESOURCEISNOTAVAILABLE","这个资源是不是可用");//This resource is not available
define("_DIRECTLYACCESSIBLE","方便与直接网址");//Accessible with a direct URL
define("_DIRECTLACCESSIBLEEXPLANATION","这意味着，使用以下网址可访问此单元：");//This means that the unit can be accessed using the following direct url:
define("_HIDE","隐藏");//Hide
define("_LESSONOPTIONSET","节选项设置");//Lesson option set
define("_BACKUPRESTORE","备份/还原");//Backup/restore
define("_CONFIGURATIONOPTIONS","配置选项");//Configuration options
define("_UNAUTHORIZEDACCESS","您没有权限访问此节");//You do not have permission to access this section
define("_LESSONUSER","节用户");//Lesson user
define("_PROGRESSFORUSER"," Progress for user ");//Progress for user
define("_LESSONSORDER","节顺序");//Lessons order
define("_COURSEUSER","课程用户");//Course user
define("_COURSELESSON","课程，节");//Course lesson
define("_CANNOTDELETEOWNTYPE","您可能无法删除您自己的类型");//You may not delete your own type
define("_GROUPUSER","组用户");//Group user
define("_EXPLICITIFRAMESIZE","明确iFrame大小");//Explicit iframe size
define("_EXPLICITSIZEEXPLANATION","这是大小的SCORM的内容包含框架。请将它留为空白，以有，它会自动计算");//This is the size of the SCORM content containing frame. Leave it blank to have it automatically calculated
define("_USERROLEINLESSON","用户角色在节");//User role in lesson
define("_LESSONROLE","节中的角色");//Role in lesson
define("_COURSEROLE","课程角色");//Role in course
define("_PAYPAL","贝宝");//Paypal
define("_DOWNLOADEXAMPLE","下载的例子");//Download example
define("_CONTENTTREEFIRSTPAGE","内容树在第一页");//Content tree in first page
define("_LAYOUT","布局");//Layout
define("_CONNECTIONERROR","连接错误");//Connection error
define("_ONLYEFRONTNOTSCORM","使用eFront自有格式上传");//Use this to upload lessons in eFront format only. For SCORM uploads, use the SCORM option at the professor's control panel
define("_TESTSMATRIX","测试矩阵");//Tests matrix (New)
define("_PROJECTSMATRIX","项目矩阵");//Projects matrix (New)
define("_MODULEDBERRORONUPGRADECHECKUPGRADEFUNCTION","数据库错误的执行过程中的功能onUpgrade模块");//Database error during the execution of function onUpgrade for the module (New)
define("_MODULENOTUPGRADEDFOLDERNOTDELETEDCLOSEALLOPENFILES","模块升级失败，因为现有目录无法删除。关闭所有打开的文件在此目录，然后再试一次");//Module upgrade failed, because existing directory could not be deleted. Close all open files in that directory and try again (New)
define("_MODULESUCCESFULLYUPGRADED","模块成功升级");//Module successfully upgraded (New)
define("_USERRESULTS","用户结果");//User results (New)
define("_SKILLSCORES","得分技巧");//Skill scores (New)
define("_PROPOSEDASSIGNMENTS","拟议转让");//Proposed assignments (New)
define("_THRESHOLD","开始");//Threshold (New)
define("_SKILLGAPANALYSISFORUSER","技能差距分析用户");//Skill gap analysis for user (New)
define("_ACCORDINGTOTEST","据测试");//according to test (New)
define("_NOLESSONSPROPOSEDACCORDINGTOANALYSIS","没有经验教训，提出根据技能差距分析");//No lessons are proposed according to the skill gap analysis (New)
define("_NOCOURSESPROPOSEDACCORDINGTOANALYSIS","没有课程的建议根据技能差距分析");//No courses are proposed according to the skill gap analysis (New)
define("_CERTIFICATETEMPLATE","证书模板（ RTF格式）");//Certificate template (rtf format) (New)
define("_COMMANDS","命令");//Commands (New)
define("_SEARCHRESULTSCOMMANDS","搜索结果中的命令");//Search results in commands (New)
define("_TOGGLEHTMLEDITORMODE","切换编辑/ HTML模式");//Toggle editor/html mode (New)
define("_UPLOADFILEFROMURL","上传文件从以下网址");//Upload file from url (New)
define("_OPENCLOSEFILEMANAGER","打开/关闭文件管理器");//Open/close file manager (New)
define("_INSERTEDITOR","插入编辑");//Insert to editor (New)
define("_AUTOMATICALLYASSIGNTOALLNEWSTUDENTS","自动分配给所有的新学生");//Automatically assign to all new students (New)
define("_SKILLGAPTESTSTOBECOMPLETED","技能差距试验完成");//Skill gap tests to be completed (New)
define("_SKILLGAPTESTCOMPLETEDSUCCESSFULLY","技能差距试验顺利完成");//Skill gap test completed successfully (New)
define("_RELEVANCE","关联");//Relevance (New)
define("_KNOWLEDGEOFLESSON" , "Knowledge of lesson");
define("_KNOWLEDGEOFCOURSE","当然知识");//Knowledge of course (New)
define("_NOSKILLSCORRELATEDWITHTHETESTSQUESTIONS","没有相关的技能测试的问题");//No skills correlated with the test&#039;s questions (New)
define("_OPENFILEMANAGER","打开文件管理器");//Open file manager (New)
define("_CLOSEFILEMANAGER","关闭文件管理器");//Close file manager (New)
define("_CLICKFORHELP","点击帮助");//Click for help (New)
define("_NOSKILLGAPTESTSASSIGNEDTOYOU","没有技能差距试验分配给您");//No skill gap tests assigned to you (New)
define("_TESTSOLVEDVIEWTOSEESKILLGAPANALYSIS" , "Test solved: View skill gap analysis");
define("_GENERALTHRESHOLD","一般阈值");//General Threshold (New)
define("_UPLOADPDFFORCONTENT","切换PDF格式/自定义内容");//Toggle pdf/custom content (New)
define("_PDFFILE","上传新pdf档案");//Upload new pdf file (New)
define("_ASSOCIATEDSKILLS","相关技能");//Associated skills (New)
define("_SKILLGAPTESTS","技能差距试验");//Skill gap tests (New)
define("_ASSOCIATEDWITH","合并");//Associated with (New)
define("_NEWSKILLGAPTESTS","新技能差距试验");//New skill gap tests (New)
define("_CORRELATESKILLSTOQUESTION","相关技能问题");//Correlate skills to question (New)
define("_EDITSKILLGAPTEST","编辑技能差距测试");//Edit skill gap test (New)
define("_ADDSKILLGAPTEST","新增技能差距测试");//Add skill gap test (New)
define("_YOUMUSTUPLOADAPDFFILE","您必须上传pdf档案");//You must upload a pdf file (New)
define("_RECENTLYCOMPLETEDSKILLGAP","最近完成的测试skillgap");//Recently completed skillgap tests (New)
define("_NOCOMPLETEDSKILLGAP","没有完成测试发现skillgap");//No completed skillgap tests found (New)
define("_SHOWALLSOLVEDSKILLGAPTESTS","显示所有的测试解决skillgap");//Show all solved skillgap tests (New)
define("_DELETESKILLGAPTESTRECORD","删除技能差距测试记录");//Delete skill gap test record (New)
define("_ASSIGNTOALLNEWSTUDENTS","分配给所有的新学生");//Assign to all new students (New)
define("_AUTOMATICALLYASSIGNLESSONS","自动分配的教训");//Automatically assign lessons (New)
define("_AUTOMATICASSIGNMENTINFO","在完成测试的学生，将被自动分配与所有<br>经验教训和课程符合他或她的教育需求");//After completing the test, a student will be automatically assigned with all<br> lessons and courses matching his or her educational needs (New)
define("_SKILLGAPTESTCOMPLETEDSUCCESSFULLYANDTHECORRESPONDING","技能差距试验顺利完成和相应的");//Skill gap test completed successfully and the corresponding (New)
define("_HAVEBEENASSIGNED","已分配给您");//have been assigned to you (New)
define("_SKILLGAPTESTRESULTS","技能差距的测试结果");//Skill gap test results (New)
define("_CURRENTPDFFILE","当前pdf档案");//Current pdf file (New)
define("_SEARCHTEXTWASINSCRIPT","搜索文本被发现倒毙在一个脚本");//Search text was found inside a script (New)
define("_NUMBERFROM000TO9999REQUIRED","数从0.00到99.99要求");//Number from 0.00 to 99.99 required (New)
define("_COMPLETETHESKILLGAPTESTSBELOWSOTHATWECANASSIGNLESSONS","完成技能差距下面的测试，以便我们可以指定课程最适合您的neeeds 。");//Complete the skill gap tests below so that we can assign courses most suitable to your neeeds. (New)
define("_YOUHAVECOMPLETEDALLSKILLGAPSTESTSASSIGNEDTOYOUWAITTOBEASSIGNEDLESSONS","您已完成了所有试验技能差距分配给您。 <br>请等待，直到你的教授指派给您最合适的课程，根据您的需要。");//You have completed all skill gap tests assigned to you. <br>Please wait until your professors assign to you the most suitable courses according to your needs. (New)
define("_YOURRESULTSHAVEBEENSENTTOYOURPROFESSORSWHOWILLASSIGNLESSONSACCORDINGTOYOURNEEDS","您的结果已发送到您的教授谁不久将指定课程，您根据您的需要确定从这个测试");//Your results have been sent to your professors who will soon assign courses to your according to your needs as identified from this test (New)
define("_JOBPLACEMENTS","就业安置");//Job placements (New)
define("_NEWJOBPLACEMENT","新安排就业");//New job placements (New)
define("_UPGRADEMODULE","升级模块");//Upgrade module (New)
define("_NEWUNITOPTIONS","新单位的选择");//New unit options (New)
define("_UNITOPTIONSFOR","选择单位");//Options for unit (New)
define("_OPTIONSFORSKILLGAPTEST","选择技能差距测试");//Options for skill gap test (New)
define("_OPTIONSFORTEST","选择测试");//Options for test (New)
define("_REPORTSFORCOURSE","当然报告");//Reports for course (New)
define("_REPORTSFORTEST","测试报告");//Reports for test (New)
define("_USERISNOTVALIDORYOUCANNOTSEEUSER","指定的用户是无效的，或者你无法访问该用户的数据");//The user specified is not valid, or you cannot access this user&#039;s data (New)
define("_SELECTGROUP","选择组");//Select group (New)
define("_BLANKFORNOLIMIT","留空为没有时间限制");//Leave blank for no time limit (New)
define("_HARDPLURAL","硬的");//Hard (New)
define("_MEDIUMPLURAL","中等");//Medium (New)
define("_EASYPLURAL","容易的");//Easy (New)
define("_UNLIMITED","Unilimited");//Unilimited (New)
define("_INCORRECTQUESTION","现在的问题是不正确");//The question is incorrect (New)
define("_QUESTIONISCORRECT","现在的问题是正确的");//The question is correct (New)
define("_PARTIALLYCORRECTQUESTION","现在的问题是部分正确的");//The question is partially correct (New)
define("_FAILED","失败");//Failed (New)
define("_PASSED","通过");//Passed (New)
define("_TESTOPTIONS","试验选择");//Test options (New)
define("_TESTQUESTIONS","测试的问题");//Test questions (New)
define("_SAVETESTANDADDQUESTIONS","保存和选择的问题");//Save and select questions (New)
define("_RANDOMPOOLTEST","随机试验池");//Random pool test (New)
define("_SUBMITANDCONTINUEEDITING","提出并继续编辑");//Submit and continue editing (New)
define("_SUBMITANDRETURN","提交并返回");//Submit and return (New)
define("_SUBMITASNEWANDCONTINUEEDITING","提出新的和继续编辑");//Submit as new and continue editing (New)
define("_SUBMITASNEWANDRETURN","提出新的和返回");//Submit as new and return (New)
define("_QUESTIONSINPOOL","在池的问题");//Questions in pool (New)
define("_SELECTRANDOMQUESTIONS","随机问题");//Randomize questions (New)
define("_RANDOMIZE","随机");//Randomize (New)
define("_PAUSETEST","暂停测试");//Pause test (New)
define("_ALLFORUMS","所有论坛");//All forums (New)
define("_USERCANDOTEST","用户可以做的测试");//The user can do the test (New)
define("_ANDUSERDIDITIN","这是完成");//It was completed in (New)
define("_TESTSCOREIS","测试评分");//Test score is (New)
define("_USERREDOTEST","重做试验");//Redo test (New)
define("_SOLVEDTEST","解决测试");//Solved test (New)
define("_CHANGESCORE","更改评分");//Change score (New)
define("_ADDFEEDBACK","购买反馈");//Add feedback (New)
define("_EDITFEEDBACK","编辑反馈");//Edit feedback (New)
define("_RESETTESTSTATUS","重置这个测试执行");//Reset this test execution (New)
define("_THETESTISDONE","测试完成");//The test is done (New)
define("_ANDCANBEDONE","并可以做到的");//and can be done (New)
define("_TESTCANBEPAUSED","试验可以暂停");//Test can be paused (New)
define("_TESTSTARTEDAT","测试开始");//The test started at (New)
define("_ANDCOMPLETEDAT","并完成");//and completed at (New)
define("_SCOREINTEST","在测试分数");//Score in test (New)
define("_TESTRESULTS","试验结果");//Test results (New)
define("_JUMPTOEXECUTION","跳转到执行");//jump to execution (New)
define("_LASTEXECUTION","最后一次执行死刑");//Last execution (New)
define("_EXECUTION","执行");//execution (New)
define("_LAST","最后的");//Last (New)
define("_CORRECTIONPENDING","待修正");//Correction pending (New)
define("_FULLNAME","全名");//Full name (New)
define("_PARTIALLYCORRECT","部分正确");//Partially correct (New)
define("_CORRECT","正确的");//Correct (New)
define("_NOUNIT","任何单位");//No unit (New)
define("_TESTANALYSIS","测试分析");//Test analysis (New)
define("_THISLEVEL","这个级别");//This level (New)
define("_BELOWLEVELS","以下各级");//Below levels (New)
define("_SUCCESSRATES","成功率");//Success rates (New)
define("_NOPARENT","没有父母");//Without parent (New)
define("_THEUSERUNDERGOINGTESTSTARTEDAT","用户现在正在进行试验，开始在");//The user is right now undergoing the test, started at (New)
define("_NONEXISTENTTEST","这不是一个完成测试");//This is not a completed test (New)
define("_FORTEST","测试");//for test (New)
define("_ANDUSER","和用户");//and user (New)
define("_TESTANALYSISFORTEST","试验分析测试");//Test analysis for test (New)
define("_RESETALLTESTSSTATUS","重置所有的执行状况");//Reset all execution status (New)
define("_ADDANOTHERFILE","添加其他文件");//Add another file (New)
define("_YOUPAUSEDTHISTESTON","您暂停这一试验");//You paused this test on (New)
define("_RESUMETEST","恢复测试");//Resume test (New)
define("_DISPLAYQUESTIONWEIGHTS","在显示重量测试");//Display weights during test (New)
define("_UNAVAILABLEOPTION","此选项不可用");//This option is not available (New)
define("_SKILLGAPTESTS","技能差距试验");//Skill gap tests (New)
define("_HOURSSHORTHAND","h");//h (New)
define("_MINUTESSHORTHAND","米");//m (New)
define("_SECONDSSHORTHAND","语");//s (New)
define("_NONEUNIT","无单位");//None unit (New)
define("_NOSYSTEMANNOUNCEMENTS","没有系统的通知");//There are no system announcements (New)
define("_NOONELOGGEDIN","没有人是目前登入");//Noone is currently logged in (New)
define("_ENTERYOUREMAILADDRESS","请输入您的电子邮箱地址");//Enter you email address (New)
define("_ENTERMESSAGESUBJECT","输入邮件主题");//Enter the message subject (New)
define("_ENTERMESSAGE","输入的信息");//Enter the message (New)
define("_ENTERANYCOMMENTS","输入任何评论您可能");//Enter any comments you might have (New)
define("_LOGINOREMAIL","登录或电子邮件");//Login or email (New)
define("_USETHISTORESETPASSWORD","使用此表为重置密码");//Use this form to reset your password (New)
define("_USETHISTOREGISTERANEWACCOUNT","使用这个表格，以建立一个新的用户帐户");//Use this form to create a new user account (New)
define("_USETHISTOCONTACTUS","使用此表与我们联系任何问题");//Use this form to contact us for any issue (New)
define("_AVAILABLELESSONS","经验和现有的课程体系");//Lessons and courses available in the system (New)
define("_SELECTLAYOUT","选择一个版面");//Select a layout (New)
define("_ENROLL","注册");//Enroll (New)
define("_INFORMATION","信息");//Information (New)
define("_STARTPAGE","起始网页");//Start page (New)
define("_SIGNUP","注册");//Sign up (New)
define("_INFOFORLESSON","信息课");//Information for lesson (New)
define("_DONTHAVEACCOUNT","我没有一个帐户");//I do not have an account (New)
define("_FORGOTPASSWORD","我忘记了密码");//I forgot my password (New)
define("_LOGINFORM","登录表单");//Login form (New)
define("_SEARCHFORM","搜索表单");//Search form (New)
define("_CARTBLOCK","购物车块");//Shopping Cart block (New)
define("_CUSTOMBLOCK","自定义块");//Custom block (New)
define("_LESSONSLIST","总结名单");//Lessons list (New)
define("_SYSTEMNEWS","系统新闻");//System news (New)
define("_REMOVE","删除");//Remove (New)
define("_TWOCOLUMNSRIGHT","两列右对齐");//Two columns right-aligned (New)
define("_TWOCOLUMNSLEFT","两列左对齐");//Two columns left-aligned (New)
define("_THREECOLUMNS","三栏");//Three columns (New)
define("_SIMPLE","简单");//Simple (New)
define("_SAVELAYOUT","保存布局");//Save layout (New)
define("_ADDBLOCK","新增区块");//Add block (New)
define("_RESTOREDEFAULTLAYOUT","还原默认布局");//Restore default layout (New)
define("_INFOFORCOURSE","当然信息");//Information for course (New)
define("_PLEASELOGINTOCOMPLETEREGISTRATION","请登入以完成注册");//Please login to complete registration (New)
define("_GOTOLESSONSLIST","转到列表中的经验教训");//Go to lessons list (New)
define("_PUBLISHED","发布时间");//Published (New)
define("_NOTPUBLISHED","未发布");//Not published (New)
define("_OPTIONSFORPROJECT","选择项目");//Options for project (New)
define("_SKILLGAPTESTRESULTSREMOVEDFROMUSERTHETESTCANBEREPEATED","试验结果已成功删除该用户。测试现在可以完成了。");//Test results have been successfully removed for this user. The test can now be completed again. (New)
define("_HOMEOFLESSON","主页的教训");//Home of lesson (New)
define("_OPTIONSFORGROUP","选项组");//Options for group (New)
define("_SURVEYFAILEDTOBEDELETED","调查未能予以删除");//Survey failed to be deleted (New)
define("_COURSESNUMBER","一些课程");//Number of courses (New)
define("_GROUPSNUMBER","一些团体");//Number of groups (New)
define("_FORUMTITLE","论坛名称");//Forum title (New)
define("_OTHERLESSONS","其他的经验教训");//Other lessons (New)
define("_CONTENTREPORT","内容错误报告");//Content error report (New)
define("_CONTENTREPORTTOPROFS","报告内容错误教授");//Report content error to professors (New)
define("_TOPIC","专题");//Topic (New)
define("_LINK","链接");//Link (New)
define("_REPORT","报告");//Report (New)
define("_SUCCESFULLYSENDREPORT","您的报告中已成功发送");//Your report was successfully sent (New)
define("_ERRORREPORTFOR","错误报告内容的教训");//Content error report for lesson (New)
define("_YOUSHOULDCHANGEHEADERLANGUAGETAG","您应该在改变_HEADERLANGUAGETAG");//You should change _HEADERLANGUAGETAG in (New)
define("_LANGUAGEFILE","语言文件");//language file (New)
define("_YOURSYSTEMSUPPORTS","您的系统支持");//Your system supports (New)
define("_LINKTOTOPIC","专题链接");//Link to topic (New)
define("_SCOREINEACHUNIT","分数在每个单位");//Score in each unit (New)
define("_SCOREINUNIT","分数的单位");//Score in unit (New)
define("_SHOWDETAILS","查看详细");//Show details (New)
define("_DISPLAYORDEREDLIST","显示命令列表");//Display ordered list (New)
define("_AVERAGESCOREON","平均分数上");//average score on (New)
define("_SCOREONLASTEXECUTION","评分上最后一次执行死刑");//score on last execution (New)
define("_EXECUTIONS","处决");//Executions (New)
define("_RECENTLYCOMPLETEDTESTS","最近完成的测试");//Recently completed tests (New)
define("_IMPORTNOTICE","警告：进口的教训将删除现有的所有课程资料");//Warning: importing a lesson will erase all existing lesson information (New)
define("_RESET","重置");//Reset (New)
define("_RESETGRAPH","重图");//Reset graph (New)
define("_CANNOTAUTOMATICALLYLOGIN","你不能自动登录");//You cannot login automatically (New)
define("_LOGINENTRANCE","注册");//Login (New)
define("_SELECTEDLESSONS","选定的教训");//Selected lessons (New)
define("_ADDTOLESSONS","添加到教训");//Add to lessons (New)
define("_AVAILABLEBLOCKS","可用区块");//Available blocks (New)
define("_ADDCUSTOMBLOCK","新增自订区块");//Add custom block (New)
define("_CURRENTLAYOUT","当前布局");//Current layout (New)
define("_UNDOALLCHANGES","撤消所有的变化");//Undo all changes (New)
define("_BLOCKTITLE","座冠军");//Block title (New)
define("_BLOCKCONTENT","座内容");//Block content (New)
define("_YOUCANNOTACCESSREQUESTEDRESOURCE","你不能获得所要求的资源");//You cannot access the requested resource (New)
define("_TOTALUNITS","总计单位");//Total units (New)
?>
