<?php
define("_DIMDIM","Συσκέψεις");
define("_DIMDIM_LESSONLINK", "DIMDIM μαθημάτων");
define("_DIMDIM_MODULE", "DIMDIM άρθρωμα");
define("_DIMDIM_MAIN","Κύρια σελίδα");
define("_DIMDIM_MANAGEMENT","Διαχείριση");
define("_DIMDIM_SUCCESFULLYINSERTEDDIMDIMENTRY", "Η σύσκεψη ενημερώθηκε επιτυχώς");
define("_DIMDIM_PROBLEMINSERTINGDIMDIMENTRY", "Δεν ήταν δυνατόν να δημιουργηθεί η σύσκεψη");
define("_DIMDIM_INSERTDIMDIM", "Εισαγωγή εγγραφής στις συσκέψεις");
define("_DIMDIM_GOTODIMDIMPAGE", "Μετάβαση στη σελίδα των συσκέψεων");
define("_DIMDIM_DIMDIMPAGE", "Σύσκεψη");
define("_DIMDIM_NAME", "Όνομα σύσκεψης");
define("_DIMDIM_DATE", "Ημερομηνία");
define("_DIMDIM_NODIMDIMFOUND", "Δεν έχουν προγραμματιστεί συσκέψεις");
define("_DIMDIM_QUESTIONS", "Ερωτήσεις");
define("_DIMDIM_ANSWERS", "Απαντήσεις");
define("_DIMDIM_DIMDIMLIST", "Λίστα συσκέψεων");
define("_DIMDIM_ADDDIMDIM", "Προσθήκη σύσκεψης");
define("_DIMDIM_EDITDIMDIM", "Επεξεργασία σύσκεψης");
define("_DIMDIM_DELETEDIMDIM", "Διαγραφή σύσκεψης");
define("_DIMDIM_SUCCESFULLYDELETEDDIMDIMENTRY", "Η σύσκεψη διαγράφηκε επιτυχώς");
define("_DIMDIM_SUCCESFULLYUPDATEDDIMDIMENTRY", "Η σύσκεψη ενημερώθηκε επιτυχώς");
define("_DIMDIM_PROBLEMUPDATINGDIMDIMENTRY", "Η σύσκεψη δεν ήταν δυνατόν να ενημερωθεί");
define("_DIMDIMTHEFIELDNAMEISMANDATORY","Το όνομα για τη σύσκεψη είναι υποχρεωτικό");
define("_DIMDIMNOMEETINGSCHEDULED","Δεν έχουν προγραμματιστεί συσκέψεις");
define("_DIMDIM_STATUS","Κατάσταση σύσκεψης");
define("_DIMDIMSTARTED","Άρχισε");
define("_DIMDIMFINISHED","Τέλειωσε");
define("_DIMDIMNOTSTARTED", "Δεν έχει αρχίσει");
define("_DIMDIMSTARTMEETING", "Έναρξη σύσκεψης");
define("_DIMDIM_TIME","Ώρα σύσκεψης");
define("_DIMDIMJOINMEETING","Είσοδος στη σύσκεψη");
define("_DIMDIMAREYOUSUREYOUWANTTODELETEEVENT","Είστε σίγουροι ότι θέλετε να ακυρώσετε αυτή τη σύσκεψη;");
define("_DIMDIM_DIMDIMMEETING", "Σύσκεψη DimDim");
define("_DIMDIM_SCHEDULEMEETING", "Προγραμματισμός σύσκεψης");
define("_DIMDIM_MEETINGATTENDANTS", "Συμμετέχοντες σύσκεψης");
define("_DIMDIM_DIMDIMMEETINGDATA", "Πληροφορίες για τη σύσκεψη");
define("_DIMDIM_DIMDIMSERVER", "Ρύθμιση DimDim εξυπηρετητή για συσκέψεις");
define("_DIMDIM_DIMDIMSERVERNAME", "Εξυπηρετητής");
define("_DIMDIM_SUCCESFULLYCHANGEDSERVER", "Ο εξυπηρετητής καταχωρήθηκε επιτυχώς");
define("_DIMDIM_NODIMDIMSERVERDEFINED", "Δεν έχει οριστεί εξυπηρετητής για DimDim συσκέψεις");
define("_DIMDIMDURATION","Διάρκεια");
define("_DIMDIMUSELOBBYROOM","Χρήση δωματίου αναμονής");
define("_DIMDIMAUDIOONLY","Μόνο ήχος");
define("_DIMDIMAUDIOVIDEO","Ήχος και βίντεο");
define("_DIMDIMMAXPARTICIPANTS","Μέγιστος αριθμός συμμετεχόντων");
define("_DIMDIMMAXMICS","Μέγιστος αριθμός μικροφώνων");
define("_DIMDIMPRESENTERAV","Τύπος σύσκεψης");
define("_DIMDIM_NOTIFYUSERSVIAEMAIL", "Ειδοποίησε συμμετέχοντες μέσω email");
define("_DIMDIM_MEETING", "Ειδοποίηση συνεδρίασης eFront");
define("_DIMDIM_DEAR","Αγαπητέ\ή");
define("_DIMDIM_YOUHAVEBEENINVITEDBYPROFESSOR","Λάβατε πρόσκληση από τον καθηγητή");
define("_DIMDIM_TOATTENDACONFERENCE","να παρακολουθήσετε την eFront συνεδρίαση");
define("_DIMDIM_FORLESSON","για το μάθημα");
define("_DIMDIM_SCHEDULEDFOR","που έχει προγραμματιστεί για τις");
define("_DIMDIM_SINCERELY","Με εκτίμηση");
define("_DIMDIMYOUCANJOINTHEMEETINGDIRECTLYBYCLICKINGTHEFOLLOWINGLINKAFTERITSTARTS", "Μετά την έναρξη της σύσκεψης, μπορείτε να μεταβείτε απευθείας στην αντίστοιχη σελίδα, κάνοντας κλικ στον παρακάτω σύνδεσμο");
define("_DIMDIM_EMAILSENTSUCCESFFULLY", "emails στάλθηκαν επιτυχώς");
define("_DIMDIMMEETINGHASFINISHED","Η συνεδριάση που επιλέξατε έχει ήδη ολοκληρωθεί");
define("_DIMDIM_AREYOUSUREYOUWANTTOSTARTTHECONFERENCE", "Είστε σίγουροι ότι θέλετε να ξεκινήσετε τη συνεδρίαση; (ματαίωση ή κλείσιμο της συνεδρίασης μετά από αυτό το σημείο θα οδηγήσει στην κατάργησή της)");
define("_DIMDIM_RESETDEFAULTSERVER","Επαναφορά προεπιλεγμένου εξυπηρετητή");
?>
