<?php
define("_DIMDIM","Konferans");
define("_DIMDIM_SYSTEMLINK1", "DIMDIM sistem bağlantısı-1");
define("_DIMDIM_SYSTEMLINK2", "DIMDIM sistem bağlantısı-2");
define("_DIMDIM_LESSONLINK", "DIMDIM dersi");
define("_DIMDIM_MODULE", "DimDim Konferans Bileşeni");
define("_DIMDIM_MAIN","Anasayfa");
define("_DIMDIM_MANAGEMENT","Konferansları yönet");
define("_DIMDIM_SUCCESFULLYINSERTEDDIMDIMENTRY", "Konferans başarıyla güncellendi");
define("_DIMDIM_PROBLEMINSERTINGDIMDIMENTRY", "Konferans oluşturulamadı");
define("_DIMDIM_INSERTDIMDIM", "Konferans ekle");
define("_DIMDIM_GOTODIMDIMPAGE", "Konferans sayfasına git");
define("_DIMDIM_DIMDIMPAGE", "Konferans");
define("_DIMDIM_NAME", "Konferans ismi");
define("_DIMDIM_DATE", "Tarih");
define("_DIMDIM_NODIMDIMFOUND", "Konferans girdisi bulunmamaktadır");
define("_DIMDIM_QUESTIONS", "Sorular");
define("_DIMDIM_ANSWERS", "Cevaplar");
define("_DIMDIM_DIMDIMLIST", "Konferans Listesi");
define("_DIMDIM_ADDDIMDIM", "Konferans ekle");
define("_DIMDIM_EDITDIMDIM", "Konferansı düzenle");
define("_DIMDIM_DELETEDIMDIM", "Konferansı sil");
define("_DIMDIM_CHANGEDIMDIMORDER", "Konferans sırasını değiştir");
define("_DIMDIM_SUCCESFULLYDELETEDDIMDIMENTRY", "Konferans başarıyla silindi");
define("_DIMDIM_SUCCESFULLYUPDATEDDIMDIMENTRY", "Konferans başarıyla güncellendi");
define("_DIMDIM_PROBLEMUPDATINGDIMDIMENTRY", "Konferans güncellenemedi");
define("_DIMDIMTHEFIELDNAMEISMANDATORY","Konferans buluşma odası ismi zorunludur");
define("_DIMDIMNOMEETINGSCHEDULED","Planlanmış bir konferans bulunmamaktadır");
define("_DIMDIM_STATUS","Konferans durumu");
define("_DIMDIMSTARTED","Başladı");
define("_DIMDIMFINISHED","Bitti");
define("_DIMDIMNOTSTARTED","Başlamadı");
define("_DIMDIMSTARTMEETING", "Konferansı başlat");
define("_DIMDIM_TIME","Konferansın zamanı");
define("_DIMDIMJOINMEETING","Konferansa katıl");
define("_DIMDIMAREYOUSUREYOUWANTTODELETEEVENT","Bu konferansı iptal etmek istediğinize emin misiniz?");
define("_DIMDIM_DIMDIMMEETING", "Konferans");
define("_DIMDIM_SCHEDULEMEETING", "Konferans Planlama");
define("_DIMDIM_MEETINGATTENDANTS", "Konferans katılımcıları");
define("_DIMDIM_DIMDIMMEETINGDATA", "DimDim konferans bilgisi");
define("_DIMDIM_DIMDIMSERVER", "DimDim Konferans Sunucu Ayarları");
define("_DIMDIM_DIMDIMSERVERNAME", "Barındırma sunucusu");
define("_DIMDIM_SUCCESFULLYCHANGEDSERVER", "Barındırma sunucusu başarıyla güncellendi");
define("_DIMDIM_NODIMDIMSERVERDEFINED", "DimDim konferans sunucusu tanımlanmadı");
define("_DIMDIMDURATION","Süre");
define("_DIMDIMUSELOBBYROOM","Bekleme odası kullan");
define("_DIMDIMAUDIOONLY","Sadece sesli");
define("_DIMDIMAUDIOVIDEO","Sesli ve görüntülü");
define("_DIMDIMMAXPARTICIPANTS","En fazla katılımcı sayısı");
define("_DIMDIMMAXMICS","En fazla mikrofon sayısı");
define("_DIMDIMPRESENTERAV","Konferans türü");
define("_DIMDIM_NOTIFYUSERSVIAEMAIL", "Katılımcılara e-posta ile bilgilendirme gönder");
define("_DIMDIM_MEETING", "eFront Konferans Bilgilendirme Mesajı");
define("_DIMDIM_DEAR","Sayın");
define("_DIMDIM_YOUHAVEBEENINVITEDBYPROFESSOR","Eğitmen");
define("_DIMDIM_TOATTENDACONFERENCE","tarafından ");
define("_DIMDIM_FORLESSON","dersi için ");
define("_DIMDIM_SCHEDULEDFOR","planlanan konferans davet edildiniz.");
define("_DIMDIM_SINCERELY","Saygılarımla");
define("_DIMDIMYOUCANJOINTHEMEETINGDIRECTLYBYCLICKINGTHEFOLLOWINGLINKAFTERITSTARTS", "Konferas başladığında aşağıdaki bağlantıya tıklayarak doğrudan katılabilirsiniz.");
define("_DIMDIM_EMAILSENTSUCCESFFULLY", "e-posta başarıyla gönderildi");
define("_DIMDIMMEETINGHASFINISHED","Seçtiğiniz konferans sonlanmıştır");
define("_DIMDIM_AREYOUSUREYOUWANTTOSTARTTHECONFERENCE", "Konferansı başlatmak istediğinizden emin misiniz?(bu aşamadan sonra konferansı iptal etmek yada kapatmak konferansın sonlanmasına sebep olur)");
define("_DIMDIM_RESETDEFAULTSERVER","Varsayılan sunucuyu sıfırla");
?>
