<?php
define("_DIMDIM","Conferences");
define("_DIMDIM_SYSTEMLINK1", "DIMDIM system link1");
define("_DIMDIM_SYSTEMLINK2", "DIMDIM system link2");
define("_DIMDIM_LESSONLINK", "Lesson DIMDIM");
define("_DIMDIM_MODULE", "DimDim Conference Module");
define("_DIMDIM_MAIN","Main page");
define("_DIMDIM_MANAGEMENT","Manage Conferences");
define("_DIMDIM_SUCCESFULLYINSERTEDDIMDIMENTRY", "Conference was succesfully updated");
define("_DIMDIM_PROBLEMINSERTINGDIMDIMENTRY", "Conference could not be created");
define("_DIMDIM_INSERTDIMDIM", "Insert conference");
define("_DIMDIM_GOTODIMDIMPAGE", "Go to conference page");
define("_DIMDIM_DIMDIMPAGE", "Conference");
define("_DIMDIM_NAME", "Conference name");
define("_DIMDIM_DATE", "Date");
define("_DIMDIM_NODIMDIMFOUND", "There are no conference entries");
define("_DIMDIM_QUESTIONS", "Questions");
define("_DIMDIM_ANSWERS", "Answers");
define("_DIMDIM_DIMDIMLIST", "Conferences list");
define("_DIMDIM_ADDDIMDIM", "Add conference");
define("_DIMDIM_EDITDIMDIM", "Edit conference");
define("_DIMDIM_DELETEDIMDIM", "Delete conference");
define("_DIMDIM_CHANGEDIMDIMORDER", "Change conference order");
define("_DIMDIM_SUCCESFULLYDELETEDDIMDIMENTRY", "Succesfully deleted conference");
define("_DIMDIM_SUCCESFULLYUPDATEDDIMDIMENTRY", "Succesfully updated conference");
define("_DIMDIM_PROBLEMUPDATINGDIMDIMENTRY", "The conference could not be updated");
define("_DIMDIMTHEFIELDNAMEISMANDATORY","The conference meeting room name is mandatory");
define("_DIMDIMNOMEETINGSCHEDULED","No conferences have been scheduled");
define("_DIMDIM_STATUS","Conference status");
define("_DIMDIMSTARTED","Started");
define("_DIMDIMFINISHED","Finished");
define("_DIMDIMNOTSTARTED","Not started");
define("_DIMDIMSTARTMEETING", "Start conference");
define("_DIMDIM_TIME","Time of conference");
define("_DIMDIMJOINMEETING","Join conference");
define("_DIMDIMAREYOUSUREYOUWANTTODELETEEVENT","Are you sure you want to cancel this conference?");
define("_DIMDIM_DIMDIMMEETING", "Conference");
define("_DIMDIM_SCHEDULEMEETING", "Conference schedule");
define("_DIMDIM_MEETINGATTENDANTS", "Conference attendants");
define("_DIMDIM_DIMDIMMEETINGDATA", "DimDim conference information");
define("_DIMDIM_DIMDIMSERVER", "DimDim Conference Server configuration");
define("_DIMDIM_DIMDIMSERVERNAME", "Server host");
define("_DIMDIM_SUCCESFULLYCHANGEDSERVER", "Server host has been successfully updated");
define("_DIMDIM_NODIMDIMSERVERDEFINED", "No DimDim conferences server has been defined");
define("_DIMDIMDURATION","Duration");
define("_DIMDIMUSELOBBYROOM","Use lobby waiting room");
define("_DIMDIMAUDIOONLY","Audio only");
define("_DIMDIMAUDIOVIDEO","Audio and video");
define("_DIMDIMMAXPARTICIPANTS","Maximum number of participants");
define("_DIMDIMMAXMICS","Maximum number of microphones");
define("_DIMDIMPRESENTERAV","Type of conference");
define("_DIMDIM_NOTIFYUSERSVIAEMAIL", "Send notification email to participants");
define("_DIMDIM_MEETING", "eFront Conference Notification");
define("_DIMDIM_DEAR","Dear");
define("_DIMDIM_YOUHAVEBEENINVITEDBYPROFESSOR","You have been invited by professor");
define("_DIMDIM_TOATTENDACONFERENCE","to attend the eFront conference");
define("_DIMDIM_FORLESSON","for lesson");
define("_DIMDIM_SCHEDULEDFOR","scheduled for");
define("_DIMDIM_SINCERELY","Sincerely");
define("_DIMDIMYOUCANJOINTHEMEETINGDIRECTLYBYCLICKINGTHEFOLLOWINGLINKAFTERITSTARTS", "After the meeting start, you may join it directly by clicking the following link");
define("_DIMDIM_EMAILSENTSUCCESFFULLY", "emails sent successfully");
define("_DIMDIMMEETINGHASFINISHED","The conference you have selected has finished");
define("_DIMDIM_AREYOUSUREYOUWANTTOSTARTTHECONFERENCE", "Are you sure you want to start the conference? (cancelling or closing the conference after this point will cause the termination of the conference)");
define("_DIMDIM_RESETDEFAULTSERVER","Reset default server");
?>
