<?php
define("_MODULE_ADMINISTRATOR_TOOLS","Εργαλεία διαχειριστή");
define("_MODULE_ADMINISTRATOR_TOOLS_NEWLOGIN", "Νέο αναγνωριστικό");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTUSERTOCHANGELOGINFOR", "Επιλέξτε χρήστη για να αλλάξετε το αναγνωριστικό");
define("_MODULE_ADMINISTRATOR_TOOLS_CHANGELOGIN", "Αλλαγή αναγνωριστικού");
define("_MODULE_ADMINISTRATOR_TOOLS_USERALREADYEXISTS", "Υπάρχει ήδη χρήστης με αυτό το αναγνωριστικό");
define("_MODULE_ADMINISTRATOR_TOOLS_OPERATIONCOMPLETEDSUCCESSFULLYBUTHEFOLLOWINGTABLESCOULDNOTBEUPDATED", "Η λειτουργία ολοκληρώθηκε με επιτυχία αλλά οι ακόλουθοι πίνακες δεν ενημερώθηκαν");
define("_MODULE_ADMINISTRATOR_TOOLS_GLOBALLESSONSETTINGS", "Γενική διαχείριση μαθήματος");
define("_MODULE_ADMINISTRATOR_TOOLS_SQLINTERFACE", "SQL μορφή");
define("_MODULE_ADMINISTRATOR_TOOLS_SQLCOMMAND", "SQL εντολή");
define("_MODULE_ADMINISTRATOR_TOOLS_ROWSINSET", "Γραμμές στο σύνολο");
define("_MODULE_ADMINISTRATOR_TOOLS_QUERYOK", "Ερώτημα OK");
define("_MODULE_ADMINISTRATOR_TOOLS_ROWSAFFECTED", "γραμμές επηρεάστηκαν");
define("_MODULE_ADMINISTRATOR_TOOLS_EMPTYSET", "Άδειο σύνολο");
define("_MODULE_ADMINISTRATOR_TOOLS_BULKCOMPLETECOURSES", "Μαζική ολοκλήρωση μαθημάτων και δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_SETCOURSELESSONUSERSCODE", "Ανάθεση χρηστών σε μαθήματα και δέσμες");
define("_MODULE_ADMINISTRATOR_TOOLS_UNENROLLJOBCOURSES", "Απο-ανάθεση δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_ENTITYTYPE", "Τύπος οντότητας");
define("_MODULE_ADMINISTRATOR_TOOLS_ENTITYENTRY", "Καταχώρηση οντότητας");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTANENTRY", "Επιλέξτε μια καταχώρηση");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTASSIGNMENTTYPE", "Επιλέξτε εναν τύπο ανάθεσης");
define("_MODULE_ADMINISTRATOR_TOOLS_REMOVECOURSESFROMUSERS", "Απο-ανάθεση χρηστών");
define("_MODULE_ADMINISTRATOR_TOOLS_AREYOUSUREYOUWANTTOREMOVEENTITYUSERSFROMENTITYCOURSES", "Η ενέργεια αυτή θα αφαιρέσει την εγγραφή των χρηστών της οντότητας από όλες τις δέσμες της. Είστε σίγουροι;");
define("_MODULE_ADMINISTRATOR_TOOLS_CATEGORYREPORTS", "Στατιστικά κατηγοριών");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTECATEGORY", "Επιλέξτε κατηγορία");
define("_MODULE_ADMINISTRATOR_TOOLS_SHOWINCOMPLETE", "Εμφάνιση μη ολοκληρωμένων δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_COMPLETEDFROM", "Ολοκληρωμένο από");
define("_MODULE_ADMINISTRATOR_TOOLS_COMPLETEDTO", "ολοκληρώθηκε μέχρι");
define("_MODULE_ADMINISTRATOR_TOOLS_SHOWINACTIVECOURSES", "Εμφάνιση απενεργοποιημένων δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_HISTORICENTRY", "Καταχώρηση ιστορικού");
define("_MODULE_ADMINISTRATOR_TOOLS_IDLEUSERS", "Ανενεργοί χρήστες");
define("_MODULE_ADMINISTRATOR_TOOLS_LASTACTION", "Τελευταία ενέργεια");
define("_MODULE_ADMINISTRATOR_TOOLS_SHOWINACTIVEUSERSSINCE", "Εμφάνιση ανενεργών χρηστών από");
define("_MODULE_ADMINISTRATOR_TOOLS_ARCHIVEALLUSERS", "Αρχειοθέτηση όλων των χρηστών");
define("_MODULE_ADMINISTRATOR_TOOLS_THISWILLARCHIVEALLUSERSAREYOUSURE", "Θα αρχειοθετηθουν όλοι οι χρήστες που ικανοποιούν τα επιλεγμένα κριτήρια. Είστε σίγουροι;");
define("_MODULE_ADMINISTRATOR_TOOLS_DEACTIVATEALLUSERS", "Απενεργοποίηση όλων των χρηστών");
define("_MODULE_ADMINISTRATOR_TOOLS_THISWILLDEACTIVATEALLUSERSAREYOUSURE", "Θα απενεργοποιηθούν όλοι οι χρήστες που ικανοποιούν τα επιλεγμένα κριτήρια. Είστε σίγουροι;");
define("_MODULE_ADMINISTRATOR_TOOLS_TOGGLESTATUS", "Εναλλαγή κατάστασης");
define("_MODULE_ADMINISTRATOR_TOOLS_LAST3MONTHS", "Τελευταίοι 3 μήνες");
?>
