<?php
define("_MODULE_ADMINISTRATOR_TOOLS","Εργαλεία διαχειριστή");
define("_MODULE_ADMINISTRATOR_TOOLS_NEWLOGIN", "Νέο αναγνωριστικό");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTUSERTOCHANGELOGINFOR", "Επιλέξτε χρήστη για να αλλάξετε το αναγνωριστικό");
define("_MODULE_ADMINISTRATOR_TOOLS_CHANGELOGIN", "Αλλαγή αναγνωριστικού");
define("_MODULE_ADMINISTRATOR_TOOLS_USERALREADYEXISTS", "Υπάρχει ήδη χρήστης με αυτό το αναγνωριστικό");
define("_MODULE_ADMINISTRATOR_TOOLS_OPERATIONCOMPLETEDSUCCESSFULLYBUTHEFOLLOWINGTABLESCOULDNOTBEUPDATED", "Η λειτουργία ολοκληρώθηκε με επιτυχία αλλά οι ακόλουθοι πίνακες δεν ενημερώθηκαν");
define("_MODULE_ADMINISTRATOR_TOOLS_GLOBALLESSONSETTINGS", "Γενική διαχείριση μαθήματος");
define("_MODULE_ADMINISTRATOR_TOOLS_SQLINTERFACE", "διεπαφή SQL");
define("_MODULE_ADMINISTRATOR_TOOLS_SQLCOMMAND", "Eντολή SQL");
define("_MODULE_ADMINISTRATOR_TOOLS_ROWSINSET", "Γραμμές στο σύνολο");
define("_MODULE_ADMINISTRATOR_TOOLS_QUERYOK", "Ερώτημα OK");
define("_MODULE_ADMINISTRATOR_TOOLS_ROWSAFFECTED", "γραμμές επηρεάστηκαν");
define("_MODULE_ADMINISTRATOR_TOOLS_EMPTYSET", "Άδειο σύνολο");
define("_MODULE_ADMINISTRATOR_TOOLS_BULKCOMPLETECOURSES", "Μαζική ολοκλήρωση μαθημάτων και δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_SETCOURSELESSONUSERSCODE", "Ανάθεση χρηστών σε μαθήματα δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_UNENROLLJOBCOURSES", "Απο-ανάθεση δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_ENTITYTYPE", "Τύπος οντότητας");
define("_MODULE_ADMINISTRATOR_TOOLS_ENTITYENTRY", "Καταχώρηση οντότητας");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTANENTRY", "Επιλέξτε μια καταχώρηση");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTASSIGNMENTTYPE", "Επιλέξτε εναν τύπο ανάθεσης");
define("_MODULE_ADMINISTRATOR_TOOLS_REMOVECOURSESFROMUSERS", "Απο-ανάθεση χρηστών");
define("_MODULE_ADMINISTRATOR_TOOLS_AREYOUSUREYOUWANTTOREMOVEENTITYUSERSFROMENTITYCOURSES", "Η ενέργεια αυτή θα αφαιρέσει την εγγραφή των χρηστών της οντότητας από όλες τις δέσμες της. Είστε σίγουροι;");
define("_MODULE_ADMINISTRATOR_TOOLS_CATEGORYREPORTS", "Στατιστικά κατηγοριών");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTECATEGORY", "Επιλέξτε κατηγορία");
define("_MODULE_ADMINISTRATOR_TOOLS_SHOWINCOMPLETE", "Εμφάνιση μη ολοκληρωμένων δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_COMPLETEDFROM", "Ολοκληρωμένο από");
define("_MODULE_ADMINISTRATOR_TOOLS_COMPLETEDTO", "ολοκληρώθηκε μέχρι");
define("_MODULE_ADMINISTRATOR_TOOLS_SHOWINACTIVECOURSES", "Εμφάνιση απενεργοποιημένων δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_HISTORICENTRY", "Καταχώρηση ιστορικού");
define("_MODULE_ADMINISTRATOR_TOOLS_IDLEUSERS", "Ανενεργοί χρήστες");
define("_MODULE_ADMINISTRATOR_TOOLS_LASTACTION", "Τελευταία ενέργεια");
define("_MODULE_ADMINISTRATOR_TOOLS_SHOWINACTIVEUSERSSINCE", "Εμφάνιση ανενεργών χρηστών από");
define("_MODULE_ADMINISTRATOR_TOOLS_ARCHIVEALLUSERS", "Αρχειοθέτηση όλων των χρηστών");
define("_MODULE_ADMINISTRATOR_TOOLS_THISWILLARCHIVEALLUSERSAREYOUSURE", "Θα αρχειοθετηθουν όλοι οι χρήστες που ικανοποιούν τα επιλεγμένα κριτήρια. Είστε σίγουροι;");
define("_MODULE_ADMINISTRATOR_TOOLS_DEACTIVATEALLUSERS", "Απενεργοποίηση όλων των χρηστών");
define("_MODULE_ADMINISTRATOR_TOOLS_THISWILLDEACTIVATEALLUSERSAREYOUSURE", "Θα απενεργοποιηθούν όλοι οι χρήστες που ικανοποιούν τα επιλεγμένα κριτήρια. Είστε σίγουροι;");
define("_MODULE_ADMINISTRATOR_TOOLS_TOGGLESTATUS", "Εναλλαγή κατάστασης");
define("_MODULE_ADMINISTRATOR_TOOLS_LAST3MONTHS", "Τελευταίοι 3 μήνες");
define("_MODULE_ADMINISTRATOR_TOOLS_OTHEROPTIONS", "Άλλες επιλογές");
define("_MODULE_ADMINISTRATOR_TOOLS_SYNCHRONIZECASE", "Επιδιόρθωση κεφαλαίων/μικρών");
define("_MODULE_ADMINISTRATOR_TOOLS_JOBCOURSES", "Δέσμες θέσεων εργασίας");
define("_MODULE_ADMINISTRATOR_TOOLS_COPYCOURSESELECTIONTOALLSIMILARJOBS", "Αυτή η λειτουργία θα αντιγράψει τις δέσμες της επιλεγμένης θέση εργασίας σε όλες τις θέσεις εργασίας με το ίδιο όνομα, αντικαθιστώντας τη δική τους λίστα δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_COPYCOURSESELECTION", "Αντιγραφή επιλογής");
define("_MODULE_ADMINISTRATOR_TOOLS_SUCCESSFULLYASSIGNEDCOURSESTOJOBS", "Ανατέθηκαν επιτυχώς %y δέσμες σε %x θέσεις εργασίας");
define("_MODULE_ADMINISTRATOR_TOOLS_BLOCKSORDER", "Σειρά μπλοκς");
define("_MODULE_ADMINISTRATOR_TOOLS_COPYBLOCKSORDERFROMLESSON", "Αντιγραφή σειράς των μπλοκς από το μάθημα");
define("_MODULE_ADMINISTRATOR_TOOLS_BLOCKORDERCOPIED", "Η σειρά των μπλοκς αντιγράφθηκε με επιτυχία");
define("_MODULE_ADMINISTRATOR_TOOLS_CHANGEFILESENCODING", "Αλλαγή κωδικοποίησης αρχείων");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTENCODINGFROM", "Αρχική κωδικοποίηση");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTENCODINGTO", "Επιθυμητή κωδικοποίηση");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTENCODINGCONVERSION", "Επιλέξτε μετατροπή κωδικοποίησης");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTSOURCEUSERTYPE", "Επιλέξτε αρχικό τύπο χρήστη");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTTARGETUSERTYPE", "Επιλέξτε τελικό τύπο χρήστη");
define("_MODULE_ADMINISTRATOR_TOOLS_CHANGEUSERTYPES", "Αλλαγή τύπου χρηστών");
define("_MODULE_ADMINISTRATOR_TOOLS_CHANGETYPEINCOURSESASWELL", "Αλλαγή του τύπου και σε μαθήματα/δέσμες");
define("_MODULE_ADMINISTRATOR_TOOLS_BASICTYPESMUSTMATCH", "Οι βασικοί τύποι πρέπει να ταιριάζουν");
define("_MODULE_ADMINISTRATOR_TOOLS_IMPERSONATE", "Σύνδεση ως χρήστης");
define("_MODULE_ADMINISTRATOR_TOOLS_YOUCANTIMPERSONATEADMIN", "Δεν μπορείτε να συνδεθείτε ως διαχειριστής");
define("_MODULE_ADMINISTRATOR_TOOLS_YOUCANTIMPERSONATEINACTIVEUSER", "Ο χρήστης αυτός δεν είναι ενεργός");
define("_MODULE_ADMINISTRATOR_TOOLS_YOUCANNOTACCESSTHISSECTION", "Δεν μπορείτε να προσπελάσετε αυτόν τον τομέα αν δεν είστε πλήρης διαχειριστής");
define("_MODULE_ADMINISTRATOR_TOOLS_MULTIPLEPLACEMENTS", "Πολλαπλές τοποθετήσεις");
define("_MODULE_ADMINISTRATOR_TOOLS_YOUMUSTDEFINEUSER", "Πρέπει να ορίσετε ένα νέο αναγνωριστικό");
define("_MODULE_ADMINISTRATOR_TOOLS_SYNCHRONIZECOURSELESSONS", "Συγχρονισμός αποτελεσμάτων στα μαθήματα των δεσμών");
define("_MODULE_ADMINISTRATOR_TOOLS_THISWILLPROPAGATECOMPLETIONSTATUSFROMACOURSETOITSLESSONSFORALLUSERS", "Πατώντας αποστολή, θα τεθούν ως ολοκληρωμένα όλα τα μαθήματα της δέσμης (που δεν είναι ήδη ολοκληρωμένα) για όσους χρήστες την έχουν ολοκληρώσει");
define("_MODULE_ADMINISTRATOR_TOOLS_PERFORMEDXUPDATES", "Έγιναν %x αλλαγές");
define("_MODULE_ADMINISTRATOR_TOOLS_UPDATECOMPLETEDLESSONS", "Ενημέρωση ολοκληρωμένων μαθημάτων");
define("_MODULE_ADMINISTRATOR_TOOLS_SETCOMPLETEDLESSONSTOTHESAMEDATE", "Επιλέξτε αυτό για να αλλάξετε μαθήματα που είναι ήδη ολοκληρωμένα, θέτοντας το σκορ και την ημερομηνία ολοκλήρωσής τους να είναι ίδια με της δέσμης.");
?>
