<?php
define("_MODULE_ADMINISTRATOR_TOOLS","Administrator tools");
define("_MODULE_ADMINISTRATOR_TOOLS_NEWLOGIN", "New login name");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTUSERTOCHANGELOGINFOR", "Select user to change login for");
define("_MODULE_ADMINISTRATOR_TOOLS_CHANGELOGIN", "Change login");
define("_MODULE_ADMINISTRATOR_TOOLS_USERALREADYEXISTS", "A user with this login already exists");
define("_MODULE_ADMINISTRATOR_TOOLS_OPERATIONCOMPLETEDSUCCESSFULLYBUTHEFOLLOWINGTABLESCOULDNOTBEUPDATED", "Operation completed successfully but the following tables could not be updated");
define("_MODULE_ADMINISTRATOR_TOOLS_GLOBALLESSONSETTINGS", "Global lesson settings");
define("_MODULE_ADMINISTRATOR_TOOLS_SQLINTERFACE", "SQL interface");
define("_MODULE_ADMINISTRATOR_TOOLS_SQLCOMMAND", "SQL command");
define("_MODULE_ADMINISTRATOR_TOOLS_ROWSINSET", "Rows in set");
define("_MODULE_ADMINISTRATOR_TOOLS_QUERYOK", "Query OK");
define("_MODULE_ADMINISTRATOR_TOOLS_ROWSAFFECTED", "rows affected");
define("_MODULE_ADMINISTRATOR_TOOLS_EMPTYSET", "Empty set");
define("_MODULE_ADMINISTRATOR_TOOLS_BULKCOMPLETECOURSES", "Bulk complete lessons and courses");
define("_MODULE_ADMINISTRATOR_TOOLS_SETCOURSELESSONUSERSCODE", "Set course lesson users");
define("_MODULE_ADMINISTRATOR_TOOLS_UNENROLLJOBCOURSES", "Unenroll courses");
define("_MODULE_ADMINISTRATOR_TOOLS_ENTITYTYPE", "Entity type");
define("_MODULE_ADMINISTRATOR_TOOLS_ENTITYENTRY", "Entity entry");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTANENTRY", "Select an entry");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTASSIGNMENTTYPE", "Select an assignment type");
define("_MODULE_ADMINISTRATOR_TOOLS_REMOVECOURSESFROMUSERS", "Unenroll users");
define("_MODULE_ADMINISTRATOR_TOOLS_AREYOUSUREYOUWANTTOREMOVEENTITYUSERSFROMENTITYCOURSES", "This operation will unenroll all users that are part of this entity from all of its courses. Are you sure?");
define("_MODULE_ADMINISTRATOR_TOOLS_CATEGORYREPORTS", "Category reports");
define("_MODULE_ADMINISTRATOR_TOOLS_SELECTECATEGORY", "Select category");
define("_MODULE_ADMINISTRATOR_TOOLS_SHOWINCOMPLETE", "Show Incomplete courses");
define("_MODULE_ADMINISTRATOR_TOOLS_COMPLETEDFROM", "Completed from");
define("_MODULE_ADMINISTRATOR_TOOLS_COMPLETEDTO", "completed to");
define("_MODULE_ADMINISTRATOR_TOOLS_SHOWINACTIVECOURSES", "Show inactive courses");
define("_MODULE_ADMINISTRATOR_TOOLS_HISTORICENTRY", "Historic entry");
define("_MODULE_ADMINISTRATOR_TOOLS_IDLEUSERS", "Idle users");
define("_MODULE_ADMINISTRATOR_TOOLS_LASTACTION", "Last action");
define("_MODULE_ADMINISTRATOR_TOOLS_SHOWINACTIVEUSERSSINCE", "Show users idle since");
define("_MODULE_ADMINISTRATOR_TOOLS_ARCHIVEALLUSERS", "Archive all users");
define("_MODULE_ADMINISTRATOR_TOOLS_THISWILLARCHIVEALLUSERSAREYOUSURE", "This will archive all users returned matching the selected criteria! Are you sure?");
define("_MODULE_ADMINISTRATOR_TOOLS_DEACTIVATEALLUSERS", "Deactivate all users");
define("_MODULE_ADMINISTRATOR_TOOLS_THISWILLDEACTIVATEALLUSERSAREYOUSURE", "This will deactivate all users returned matching the selected criteria! Are you sure?");
define("_MODULE_ADMINISTRATOR_TOOLS_TOGGLESTATUS", "Toggle status");
define("_MODULE_ADMINISTRATOR_TOOLS_LAST3MONTHS", "Last 3 months");
define("_MODULE_ADMINISTRATOR_TOOLS_OTHEROPTIONS", "Other options");
define("_MODULE_ADMINISTRATOR_TOOLS_SYNCHRONIZECASE", "Fix upper/lower case inconsistencies");
define("_MODULE_ADMINISTRATOR_TOOLS_JOBCOURSES", "Job courses");
define("_MODULE_ADMINISTRATOR_TOOLS_COPYCOURSESELECTIONTOALLSIMILARJOBS", "This will copy the selected job's courses to all jobs with the same name, replacing their existing selection");
define("_MODULE_ADMINISTRATOR_TOOLS_COPYCOURSESELECTION", "Copy selection");
define("_MODULE_ADMINISTRATOR_TOOLS_SUCCESSFULLYASSIGNEDCOURSESTOJOBS", "Successfully assigned %y courses to %x jobs");
?>
