<?php
define("_JOURNAL_NAME", "Journal");
define("_JOURNAL_RULES", "Rules");
define("_JOURNAL_DISPLAY_RULES", "Display Rules");
define("_JOURNAL_ENTRY", "Entry");
define("_JOURNAL_ADD_RULE", "Add journal rule");
define("_JOURNAL_ADD_RULE2", "Add rule");
define("_JOURNAL_ADD_RULE_FORM", "Add rule form");
define("_JOURNAL_EDIT_RULE_FORM", "Edit rule form");
define("_JOURNAL_EDIT_RULE", "Edit rule");
define("_JOURNAL_RULE_SUCCESSFULLY_ADDED", "Rule successfully added");
define("_JOURNAL_RULE_SUCCESSFULLY_EDITED", "Rule successfully updated");
define("_JOURNAL_RULE_ADD_PROBLEM", "Problem while adding rule");
define("_JOURNAL_RULE_EDIT_PROBLEM", "Problem while updating rule");
define("_JOURNAL_NOACCESS", "You do not have sufficient permissions for this action");
define("_JOURNAL_EMPTY_RULE_DESCRIPTION", "Rule description cannot be empty");
define("_JOURNAL_NO_RULES_FOUND", "No rules found");
define("_JOURNAL_NO_ENTRIES_FOUND", "No entries found");
define("_JOURNAL_DOWNLOAD_AS", "Download As");
define("_JOURNAL_DOWNLOAD_AS_TXT", "TXT");
define("_JOURNAL_CHANGE_DIMENSIONS", "Change journal dimensions");
define("_JOURNAL_SMALL_DIMENSION", "Small (700x495)");
define("_JOURNAL_MEDIUM_DIMENSION", "Medium (800x565)");
define("_JOURNAL_LARGE_DIMENSION", "Large (900x636)");
define("_JOURNAL_ENTRY_SUCCESSFULLY_ADDED", "Entry successfully added");
define("_JOURNAL_ENTRY_SUCCESSFULLY_EDITED", "Entry successfully updated");
define("_JOURNAL_ENTRY_ADD_PROBLEM", "Problem while adding entry");
define("_JOURNAL_ENTRY_EDIT_PROBLEM", "Problem while updating entry");
define("_JOURNAL_EMPTY_ENTRY_BODY", "Entry's body cannot be empty");
define("_JOURNAL_HIDE_PAGE", "Hide page");
define("_JOURNAL_SHOW_PAGE", "Show page");
define("_JOURNAL_SHOW_ENTRIES_FROM", "Show entries from");
define("_JOURNAL_ALL_LESSONS", "All my lessons");
define("_JOURNAL_ALLOW_PRINT_EXPORT", "Allow print/export");
define("_JOURNAL_ALLOW_PROFESSOR_PREVIEW", "Preview students' journal");
define("_JOURNAL_OPEN_POPUP", "Open journal in popup window");
define("_JOURNAL_POPUP_INFO", "How to open Journal in the workflow of the lesson material");
define("_JOURNAL_HOW_TO_OPEN_POPUP1", "In order to place a link in the logical flow of the lesson material, enabling students to open Journal without visiting the control panel of a course, just follow the instructions below.");
define("_JOURNAL_HOW_TO_OPEN_POPUP2", "At first, add the following piece of HTML code in the place where you want to have the link to Journal module.");
define("_JOURNAL_HOW_TO_OPEN_POPUP3", "As a second and final step, add the following Javascript code snippet.");
define("_JOURNAL_HOW_TO_OPEN_POPUP4", "Note that, if for any reason, you as a professor, want to place a link to Journal module, the HTML code needed is the following.");
define("_JOURNAL_COPY_TO_CLIPBOARD", "Copy to clipboard");
define("_JOURNAL_STUDENTS_JOURNAL", "Students' journal");
define("_JOURNAL_STUDENT_NAME", "Student Name");
define("_JOURNAL_NO_STUDENTS_FOUND", "No students found");
?>
