<?php
define("_JOURNAL_NAME", "Journal");
define("_JOURNAL_RULES", "Κανόνες");
define("_JOURNAL_DISPLAY_RULES", "Προβολή κανόνων");
define("_JOURNAL_ENTRY", "Εγγραφή");
define("_JOURNAL_ADD_RULE", "Προσθήκη κανόνα");
define("_JOURNAL_ADD_RULE2", "Προσθήκη κανόνα");
define("_JOURNAL_ADD_RULE_FORM", "Φόρμα προσθήκης κανόνα");
define("_JOURNAL_EDIT_RULE_FORM", "Φόρμα επεξεργασίας κανόνα");
define("_JOURNAL_EDIT_RULE", "Επεξεργασία κανόνα");
define("_JOURNAL_RULE_SUCCESSFULLY_ADDED", "Ο κανόνας προστέθηκε επιτυχώς");
define("_JOURNAL_RULE_SUCCESSFULLY_EDITED", "Ο κανόνας ανανεώθηκε επιτυχώς");
define("_JOURNAL_RULE_ADD_PROBLEM", "Ο κανόνας δεν προστέθηκε επιτυχώς");
define("_JOURNAL_RULE_EDIT_PROBLEM", "Ο κανόνας δεν ανανεώθηκε επιτυχώς");
define("_JOURNAL_NOACCESS", "Δεν μπορείτε να προσπελάσετε αυτήν τη σελίδα");
define("_JOURNAL_EMPTY_RULE_DESCRIPTION", "Η περιγραφή του κανόνα δεν μπορεί να είναι κενή");
define("_JOURNAL_NO_RULES_FOUND", "Δεν βρέθηκαν κανόνες");
define("_JOURNAL_NO_ENTRIES_FOUND", "Δεν βρέθηκαν εγγραφές");
define("_JOURNAL_DOWNLOAD_AS", "Αποθήκευση ως");
define("_JOURNAL_DOWNLOAD_AS_TXT", "TXT");
define("_JOURNAL_CHANGE_DIMENSIONS", "Αλλαγή διαστάσεων");
define("_JOURNAL_SMALL_DIMENSION", "Μικρό (700x495)");
define("_JOURNAL_MEDIUM_DIMENSION", "Μεσαίο (800x565)");
define("_JOURNAL_LARGE_DIMENSION", "Μεγάλο (900x636)");
define("_JOURNAL_ENTRY_SUCCESSFULLY_ADDED", "Η εγγραφή προστέθηκε επιτυχώς");
define("_JOURNAL_ENTRY_SUCCESSFULLY_EDITED", "Η εγγραφή ανανεώθηκε επιτυχώς");
define("_JOURNAL_ENTRY_ADD_PROBLEM", "Η εγγραφή δεν προστέθηκε επιτυχώς");
define("_JOURNAL_ENTRY_EDIT_PROBLEM", "Η εγγραφή δεν ανανεώθηκε επιτυχώς");
define("_JOURNAL_EMPTY_ENTRY_BODY", "Το κείμενο της εγγραφής δεν μπορεί να είναι κενό");
define("_JOURNAL_HIDE_PAGE", "Απόκρυψη σελίδας");
define("_JOURNAL_SHOW_PAGE", "Εμφάνιση σελίδας");
define("_JOURNAL_SHOW_ENTRIES_FROM", "Προβολή εγγραφών από");
define("_JOURNAL_ALL_LESSONS", "Όλα τα μαθήματα μου");
define("_JOURNAL_ALLOW_PRINT_EXPORT", "Δυνατότητα εκτύπωσης/αποθήκευσης");
define("_JOURNAL_ALLOW_PROFESSOR_PREVIEW", "Επισκόπηση μαθητών");
define("_JOURNAL_OPEN_POPUP", "Άνοιγμα σε pop-up");
define("_JOURNAL_POPUP_INFO", "Πως να ανοίγετε το Journal στην ροή υλικού του μαθήματος");
define("_JOURNAL_HOW_TO_OPEN_POPUP1", "Προκειμένου να τοποθετήσετε ενα link στην ροή υλικού του μαθήματος, δίνοντας την δυνατότητα στους μαθητές να ανοίγουν το Journal χωρίς να επισκέπτονται τον πίνακα ελέγχου του μαθήματος, ακολουθήστε τις παρακάτω οδηγίες.");
define("_JOURNAL_HOW_TO_OPEN_POPUP2", "Αρχικά, τοποθετήστε το παρακάτω κομμάτι HTML κώδικα στο σημείο όπου επιθυμείτε να τοποθετήσετε το link στο Journal.");
define("_JOURNAL_HOW_TO_OPEN_POPUP3", "Σαν δεύτερο και τελευταίο βήμα, τοποθετήστε το παρακάτω κομμάτι Javascript κώδικα.");
define("_JOURNAL_HOW_TO_OPEN_POPUP4", "Σημειώστε ότι, αν για κάποιο λόγο, εσείς σαν καθηγητής, επιθυμείτε να τοποθετήσετε ένα link στο Journal, ο HTML κώδικας που χρειάζεστε είναι ο ακόλουθος.");
define("_JOURNAL_COPY_TO_CLIPBOARD", "Αντιγραφή");
define("_JOURNAL_STUDENTS_JOURNAL", "Journal μαθητών");
define("_JOURNAL_STUDENT_NAME", "Μαθητής");
define("_JOURNAL_NO_STUDENTS_FOUND", "Δεν βρέθηκαν μαθητές");
?>
