<?php
define("_BLOGS_BLOG","Blogs");
define("_BLOGS_GOTOBLOGS","Go to lessons blogs");
define("_BLOGS_NOPAGESFOUND","There are no changes in blogs");
define("_BLOGS_NEWBLOG","New blog");
define("_BLOGS_TITLE","Blog title");
define("_BLOGS_DESCRIPTION","Description");
define("_BLOGS_CREATOR","Creator");
define("_BLOGS_LASTPOST","Last article");
define("_BLOGS_OPERATIONS","Operations");
define("_BLOGS_BY","by");
define("_BLOGS_EDITBLOG","Edit blog");
define("_BLOGS_NEWARTICLE","New article");
define("_BLOGS_COMMENTS","Comments");
define("_BLOGS_ADDCOMMENT","Add comment");
define("_BLOGS_ACCESSIBLE","Accessible without login");
define("_BLOGS_COMMENTEDON","commented on");
define("_BLOGS_LASTCOMMENTS","Last comments");
define("_BLOGS_COMMENTED","commented");
define("_BLOGS_NOCOMMENTSFOUND","There are no comments yet");
define("_BLOGS_COMMENTADDEDSUCCESSFULLY","Comment was added successfully");
define("_BLOGS_ARTICLEWASDELETEDSUCCESSFULLY","Article was deleted successfully");
define("_BLOGS_COMMENTWASDELETEDSUCCESSFULLY","Comment was deleted successfully");
define("_BLOGS_BLOGUPDATEDSUCCESSFULLY","Blog was updated successfully");
define("_BLOGS_BLOGADDEDSUCCESSFULLY","Blog was added successfully");
define("_BLOGS_ARTICLEUPDATEDSUCCESSFULLY","Article was updated successfully");
define("_BLOGS_ARTICLEADDEDSUCCESSFULLY","Article was added successfully");
define("_BLOGS_COMMENTUPDATEDSUCCESSFULLY","Comment was updated successfully");
define("_BLOGS_BLOGS_FORM","Blogs form");
define("_BLOGS_ARTICLESFORM","Articles form");
define("_BLOGS_EDITCOMMENT","Edit comment");
define("_BLOGS_COMMENTS_FORM","Comments form");
define("_BLOGS_NOARTICLESFOUND","There are no articles yet");
define("_BLOGS_DELETECOMMENT","Delete comment");
define("_BLOGS_NOBLOGSFOUND","There are no blogs yet");
define("_BLOGS_EDITARTICLE","Edit article");
define("_BLOGS_BLOGNOTADDED","Blog was not added");
define("_BLOGS_ARTICLENOTADDED","Article was not added");
define("_BLOGS_COMMENTNOTADDED","Comment was not added");
define("_BLOGS_BLOGNOTUPDATED","Blog was not updated");
define("_BLOGS_ARTICLENOTUPDATED","Article was not updated");
define("_BLOGS_COMMENTNOTUPDATED","Comment was not updated");
define("_BLOGS_LASTCOMMENTAT","Last comment at");
define("_BLOGS_COMMENT","Comment");
define("_BLOGS_SHOWALLARTICLES","Show all articles");
define("_BLOGS_LASTARTICLES","Last articles");
define("_BLOGS_ARCHIVE","Archive");
define("_BLOGS_CREATORS","Creators");
define("_BLOGS_BLOGSCREATORS","Blog creators");
define("_BLOGS_SELECTBLOGCREATORS","Select blog creators");
define("_BLOGS_NOACCESS","You have no access for this action");
define("_BLOGS_YOURCOMMENT","Your comment");
?>