<?php
define("_BLOGS_BLOG","Μπλογκς");
define("_BLOGS_GOTOBLOGS","Μετάβαση στα μπλογκς του μαθήματος");
define("_BLOGS_NOPAGESFOUND","Δεν υπάρχουν αλλαγές στα μπλογκς");
define("_BLOGS_NEWBLOG","Νέο μπλογκ");
define("_BLOGS_TITLE","Τίτλος μπλογκ");
define("_BLOGS_DESCRIPTION","Περιγραφή");
define("_BLOGS_CREATOR","Δημιουργός");
define("_BLOGS_LASTPOST","Τελευταίο άρθρο");
define("_BLOGS_OPERATIONS","Λειτουργίες");
define("_BLOGS_BY","από");
define("_BLOGS_EDITBLOG","Επεξεργασία μπλογκ");
define("_BLOGS_NEWARTICLE","Νέο άρθρο");
define("_BLOGS_COMMENTS","Σχόλια");
define("_BLOGS_ADDCOMMENT","Προσθήκη σχολίου");
define("_BLOGS_ACCESSIBLE","Προσβάσιμο χωρίς σύνδεση");
define("_BLOGS_COMMENTEDON","σχολιαστηκε στις");
define("_BLOGS_LASTCOMMENTS","Τελευταία σχόλια");
define("_BLOGS_COMMENTED","σχολιάστηκε");
define("_BLOGS_NOCOMMENTSFOUND","Δεν υπάρχουν ακόμα σχόλια");
define("_BLOGS_COMMENTADDEDSUCCESSFULLY","Το σχόλιο προστέθηκε επιτυχώς");
define("_BLOGS_ARTICLEWASDELETEDSUCCESSFULLY","Το άρθρο διαγράφτηκε επιτυχώς");
define("_BLOGS_COMMENTWASDELETEDSUCCESSFULLY","Το σχόλιο διαγράφτηκε επιτυχώς");
define("_BLOGS_BLOGUPDATEDSUCCESSFULLY","Το μπλογκ ενημερώθηκε επιτυχώς");
define("_BLOGS_BLOGADDEDSUCCESSFULLY","Το μπλογκ προστέθηκε επιτυχώς");
define("_BLOGS_ARTICLEUPDATEDSUCCESSFULLY","Το άρθρο ενημερώθηκε επιτυχώς");
define("_BLOGS_ARTICLEADDEDSUCCESSFULLY","Το άρθρο προστέθηκε επιτυχώς");
define("_BLOGS_COMMENTUPDATEDSUCCESSFULLY","Το σχόλιο ενημερώθηκε επιτυχώς");
define("_BLOGS_BLOGS_FORM","Φόρμα μπλογκς");
define("_BLOGS_ARTICLESFORM","Φόρμα άρθρων");
define("_BLOGS_EDITCOMMENT","Επεξεργασία σχολίου");
define("_BLOGS_COMMENTS_FORM","Φόρμα σχολίων");
define("_BLOGS_NOARTICLESFOUND","Δεν υπάρχουν ακόμα άρθρα");
define("_BLOGS_DELETECOMMENT","Διαγραφή σχολίου");
define("_BLOGS_NOBLOGSFOUND","Δεν υπάρχουν ακόμα μπλογκς");
define("_BLOGS_EDITARTICLE","Επεξεργασία άρθρου");
define("_BLOGS_BLOGNOTADDED","Το μπλογκ δεν προστέθηκε");
define("_BLOGS_ARTICLENOTADDED","Το άρθρο δεν προστέθηκε");
define("_BLOGS_COMMENTNOTADDED","Το σχόλιο δεν προστέθηκε");
define("_BLOGS_BLOGNOTUPDATED","Το μπλογκ δεν ενημερώθηκε");
define("_BLOGS_ARTICLENOTUPDATED","Το άρθρο δεν ενημερώθηκε");
define("_BLOGS_COMMENTNOTUPDATED","Το σχόλιο δεν ενημερώθηκε");
define("_BLOGS_LASTCOMMENTAT","Τελευταίο σχόλιο στις");
define("_BLOGS_COMMENT","Σχόλιο");
define("_BLOGS_SHOWALLARTICLES","Εμφάνιση όλων των άρθρων");
define("_BLOGS_LASTARTICLES","Τελευταία άρθρα");
define("_BLOGS_ARCHIVE","Αρχείο");
define("_BLOGS_CREATORS","Δημιουργοί");
define("_BLOGS_BLOGSCREATORS","Δημιουργοί μπλογκς");
define("_BLOGS_SELECTBLOGCREATORS","Επιλογή δημιουργών μπλογκς");
define("_BLOGS_NOACCESS","Δεν έχετε δικαίωμα για αυτήν την ενέργεια");
define("_BLOGS_YOURCOMMENT","Το σχόλιό σας");
?>
