<?php
define("_BLOGS_BLOG","Günlük");
define("_BLOGS_GOTOBLOGS","Dersin günlüğüne git");
define("_BLOGS_NOPAGESFOUND","Günlükte bir değişim bulunmamaktadır");
define("_BLOGS_NEWBLOG","Yeni günce");
define("_BLOGS_TITLE","Günce başlığı");
define("_BLOGS_DESCRIPTION","Açıklama");
define("_BLOGS_CREATOR","Oluşturan");
define("_BLOGS_LASTPOST","En son makale");
define("_BLOGS_OPERATIONS","İşlemler");
define("_BLOGS_BY","tarafından");
define("_BLOGS_EDITBLOG","Günceyi düzenle");
define("_BLOGS_NEWARTICLE","Yeni makale");
define("_BLOGS_COMMENTS","Yorumlar");
define("_BLOGS_ADDCOMMENT","Yorum ekle");
define("_BLOGS_ACCESSIBLE","Kullanıcı girişsiz erişim");
define("_BLOGS_COMMENTEDON","yorumla");
define("_BLOGS_LASTCOMMENTS","Son yorumlar");
define("_BLOGS_COMMENTED","yorumlandı");
define("_BLOGS_NOCOMMENTSFOUND","Henüz yorum bulunmamaktadır");
define("_BLOGS_COMMENTADDEDSUCCESSFULLY","Yorum başarıyla eklendi");
define("_BLOGS_ARTICLEWASDELETEDSUCCESSFULLY","Makale başarıyla silindi");
define("_BLOGS_COMMENTWASDELETEDSUCCESSFULLY","Yorum başarıyla silindi");
define("_BLOGS_BLOGUPDATEDSUCCESSFULLY","Günce başarıyla güncellendi");
define("_BLOGS_BLOGADDEDSUCCESSFULLY","Günce başarıyla eklendi");
define("_BLOGS_ARTICLEUPDATEDSUCCESSFULLY","Makale başarıyla güncellendi");
define("_BLOGS_ARTICLEADDEDSUCCESSFULLY","Makale başarıyla eklendi");
define("_BLOGS_COMMENTUPDATEDSUCCESSFULLY","Yorum başarıyla güncellendi");
define("_BLOGS_BLOGS_FORM","Günlüklerin Sahibi");
define("_BLOGS_ARTICLESFORM","Makalelerin Sahibi");
define("_BLOGS_EDITCOMMENT","Yorumu düzenle");
define("_BLOGS_COMMENTS_FORM","Yorumların Sahibi");
define("_BLOGS_NOARTICLESFOUND","Henüz bir makale bulunmamaktadır");
define("_BLOGS_DELETECOMMENT","Yorumu sil");
define("_BLOGS_NOBLOGSFOUND","Henüz bir günlük bulunmamaktadır");
define("_BLOGS_EDITARTICLE","Makaleyi düzenle");
define("_BLOGS_BLOGNOTADDED","Günce eklenemedi");
define("_BLOGS_ARTICLENOTADDED","Makale eklenemedi");
define("_BLOGS_COMMENTNOTADDED","Yorum eklenemedi");
define("_BLOGS_BLOGNOTUPDATED","Günce düzenlenemedi");
define("_BLOGS_ARTICLENOTUPDATED","Makale düzenlenemedi");
define("_BLOGS_COMMENTNOTUPDATED","Yorum düzenlenemedi");
define("_BLOGS_LASTCOMMENTAT","Son yorum");
define("_BLOGS_COMMENT","Yorum");
define("_BLOGS_SHOWALLARTICLES","Tüm makaleleri göster");
define("_BLOGS_LASTARTICLES","Son makaleler");
define("_BLOGS_ARCHIVE","Arşiv");
define("_BLOGS_CREATORS","Oluşturanlar");
define("_BLOGS_BLOGSCREATORS","Günlük yazarları");
define("_BLOGS_SELECTBLOGCREATORS","Günce yazarı seç");
define("_BLOGS_NOACCESS","Bu işlem için yetkiniz yok");
define("_BLOGS_YOURCOMMENT","Sizin yorumunuz");
?>
